### ISSUE TITLE
Add an ability to have theme-based chart colors

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#1001]
Currently if you change the theme to dark the whole page is dark except the chart, which is not good.

We need to provide a way to apply theme-based colors to a chart whenever a theme is changed. It should affect the displayed code as well (so displayed code should exactly the same what we render).

**Comment by SlicedSilver** [comment]
Already implemented on the documentation site.

**Comment by timocov** [comment]
@SlicedSilver looks like the milestone is outdated in this and in #1002 tickets? (I believe it should 4.0 right?)
