### ISSUE TITLE
Documentation website improves

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#1002]
- [x] ~on website deploy, instead of reading size-limit config to get a size it's better to use [bundlephobia api](https://bundlephobia.com/api/size?package=lightweight-charts@3.7.0&record=true) because ppl will use this service to check the size~ Fixed in #1009
- [ ] when a screen is small enough we hide a text from the logo, but it seems that in some cases we could display it for a bit longer
  ![image](https://user-images.githubusercontent.com/3112183/153471099-47dea8f6-999f-4baa-a8a7-f6f20c06ef63.png)
- [ ] when a screen is small the header might look strange sometimes:
  ![image](https://user-images.githubusercontent.com/3112183/154325707-83dba49c-9019-40a2-b03f-4cdeccfaa085.png)
- [ ] #1001 
- [ ] migrate to postcss from css
- [ ] introduce stylelint
- [ ] try to use client-side js-based adaptive logo rather than have 4 icons and load them as images
- tbc

**Comment by igoralves1** [comment]
The documentation needs improvement. It is not clear how to customize charts.
