### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by TaylorWenOne** [tradingview/lightweight-charts#101]
when i used in ie，it report error
object not support "find" function

**Comment by timocov** [comment]
To make it works on IE you need add polyfills to your page. For example https://github.com/zloirock/core-js.

I believe we need to place that information somewhere in the docs/readme.

**Comment by TaylorWenOne** [comment]
thank you ,but i aslo find  it doesn't work in safari，how can i used in safari?

**Comment by timocov** [comment]
What version of Safari you have? Try to add that polyfills for old Safari as well.

**Comment by domrongpon-tanpaibul** [comment]
here is polyfills that I'm using.

```javascript
import 'core-js/es6/promise';
import 'core-js/es6/array';
import 'core-js/es6/string';
import 'core-js/es6/map';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es7/array';
import 'core-js/es7/object';
```
