### ISSUE TITLE
LightweightCharts: Implementing Websockets and pagination for every 1min periodicity

### ISSUE THREAD

**Issue by RSalgaonkar** [tradingview/lightweight-charts#1011]
Hi,

I am trying plot data for every one min which i am getting from API and also trying to implement pagination when i scroll to back on chart. Is their any methods in Lightweight to this?

**Comment by abhishek-deqode** [comment]
You can `update` the chart state with new data. https://stackoverflow.com/questions/69624669/how-do-i-update-chart-with-new-data-in-tradingview-lightweight-charts

**Comment by timocov** [comment]
Duplicate of #777

**Comment by timocov** [comment]
See examples: https://jsfiddle.net/TradingView/fg7yez2s/ https://jsfiddle.net/TradingView/yozeu6k1/
