### ISSUE TITLE
Still showing price line label on price axis after removing it

### ISSUE THREAD

**Issue by shaohlalnyd** [tradingview/lightweight-charts#1020]
Hi
I have 3 price line in my chart .and update them after stream received
When new data received from socket , first I  remove the previous price line and then add new.
Every thing is okay, but when user de active the page (Like go to another tab) price line removed but the label of that price line still showing.

![WhatsApp Image 2022-02-16 at 8 04 38 PM](https://user-images.githubusercontent.com/55618167/154332414-abc91b40-d9cf-4166-882f-b42f2bf8c713.jpeg)

the above photo its what heppening.
i coding in react .

```js
if (priceLineSerie) candleSerie.removePriceLine(priceLineSerie); 
if (tp1LineSerie) candleSerie.removePriceLine(tp1LineSerie);
if (slLineSerie) candleSerie.removePriceLine(slLineSerie); 
if (candleSerie) candleSerie.setMarkers([]);
```

the above code when run a new event received and remove the price lines.

```js
    //entry price line

    const priceLine = candleSerie.createPriceLine({
      price: chartData.entryPrice,
      color: "#0000ff",
      lineWidth: 2,
      // lineStyle: 'Solid',
      axisLabelVisible: true,
      title: "Price",
    });

    setPriceLineSerie(priceLine);

    candleSerie.createPriceLine(priceLine);

    //tp1 line

    const tp1Line = candleSerie.createPriceLine({
      price: chartData.tp1,
      color: "#00ff00",
      lineWidth: 2,
      // lineStyle: 'Solid',
      axisLabelVisible: true,
      title: "TP",
    });

    setTp1LineSerie(tp1Line);

    candleSerie.createPriceLine(tp1Line);

    //sl line

    const slLine = candleSerie.createPriceLine({
      price: chartData.sl,
      color: "#ff0000",
      lineWidth: 2,
      // lineStyle: 'Solid',
      axisLabelVisible: true,
      title: "SL",
    });

    setSlLineSerie(slLine);

    candleSerie.createPriceLine(slLine);
```

above code , add price line to candle serie.

Please help me how to fix it

**Comment by shaohlalnyd** [comment]
![Uploading IMG_20220216_202551.jpg…]()

**Comment by timocov** [comment]
> Please help me how to fix it

Is there any chance to provide a repro for that? Otherwise I don't think that it is possible to help.

**Comment by shaohlalnyd** [comment]
> > Please help me how to fix it
> 
> Is there any chance to provide a repro for that? Otherwise I don't think that it is possible to help.

please open this issue

**Comment by timocov** [comment]
@shaohlalnyd thanks for you code samples, but this is not enough. What steps to reproduce the issue? Is it possible to create a jsfiddle example with your issue?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.

**Comment by nopium** [comment]
removePriceLine just doesn't work

In your official fiddle
https://jsfiddle.net/63zn2v7j/

if you add the last line:
series.createPriceLine(maxPriceLine);
series.removePriceLine(maxPriceLine);


you will see an error:

lightweight-charts.standalone.production.js:7 Uncaught TypeError: t.od is not a function
    at t.removePriceLine
