### ISSUE TITLE
PriceFormatter options not working on CandleSeries

### ISSUE THREAD

**Issue by neobie** [tradingview/lightweight-charts#1022]
https://github.com/tradingview/lightweight-charts/blob/v3.7.0/docs/series-basics.md

Priceformatter doesn't seem to work on candleSeries. Working fine on areaSeries.

series.applyOptions({
    priceFormat: {
        type: 'custom',
        minMove: 0.02,
        formatter: price => '$' + price.toFixed(2),
    },
});

Tested on 3.4 and 3.7

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
