### ISSUE TITLE
Labels on price axis might be cut if they are close bottom/top borders

### ISSUE THREAD

**Issue by neobie** [tradingview/lightweight-charts#1023]
https://jsfiddle.net/acy80teg/

1. If the last point volume is much lowest, the volume label will be truncated / overflow and hide in half.
2. Also looking for option to hide the volume label on right side.

![image](https://user-images.githubusercontent.com/4213973/154413220-10717b2b-d918-459d-bb23-80f20df66ec6.png)

**Comment by neobie** [comment]
Thanks but how to hide the volume label but showing only price label for now ?

**Comment by timocov** [comment]
Is blocked by #607

**Comment by ChristopherJohnson25** [comment]
Is this fixed? Issue is still reproducible on v4 (update lib version on fiddle above to see).
