### ISSUE TITLE
Ability to save generates chart to file or generated TradingView screenshot URL

### ISSUE THREAD

**Issue by Zidious** [tradingview/lightweight-charts#1031]
[Feature Request]

Hey All,

I was looking through the API and was wondering if there is a way to save the generated chart to file or TradingView screenshot URL. 

Take the example chart: 

```ts
import { createChart } from 'lightweight-charts';

const chart = createChart(document.body, { width: 400, height: 300 });
const lineSeries = chart.addLineSeries();
lineSeries.setData([
    { time: '2019-04-11', value: 80.01 },
    { time: '2019-04-12', value: 96.63 },
    { time: '2019-04-13', value: 76.64 },
    { time: '2019-04-14', value: 81.89 },
    { time: '2019-04-15', value: 74.43 },
    { time: '2019-04-16', value: 80.01 },
    { time: '2019-04-17', value: 96.63 },
    { time: '2019-04-18', value: 76.64 },
    { time: '2019-04-19', value: 81.89 },
    { time: '2019-04-20', value: 74.43 },
]);


// Save chart to file 
chart.toFile('somepath/chart.png');

// Save chart to TradingView generated screenshot URL
const screenshot = chart.toScreenshot();
```

**Comment by timocov** [comment]
> if there is a way to save the generated chart

You can easily do it [with the current API](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#takescreenshot) and [this approach](https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server).

> or TradingView screenshot URL.

This is open-source solution that you might use at any server, even offline. Thus it won't include anything that relies on TradingView services. You can easily upload the generated image to any image server to generate an URL.

**Comment by paololazzari** [comment]
@timocov could you please share what a full example would look like using the `takeScreenshot` method?

**Comment by timocov** [comment]
@paololazzari example of what? How to upload an image to the server?

**Comment by paololazzari** [comment]
@timocov how to take a screenshot and save it locally

**Comment by timocov** [comment]
@paololazzari you can use the result from [this method](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#takescreenshot) and use [this approach](https://www.google.com/search?q=how+to+save+image+from+canvas+site%3Astackoverflow.com&newwindow=1&hl=en&sxsrf=ALiCzsYJ_U4syiru9JhRUJUddSRvB8IN6Q%3A1652612139852&ei=K9yAYpXaM8yfgQbC_rSoCg&ved=0ahUKEwjVm7D8q-H3AhXMT8AKHUI_DaUQ4dUDCA0&uact=5&oq=how+to+save+image+from+canvas+site%3Astackoverflow.com&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6BwgAELADEEM6BggAEBYQHjoFCCEQoAE6CAghEBYQHRAeSgQIQRgASgQIRhgAUK8CWLAfYJwiaAFwAXgAgAGcAYgB8QWSAQM2LjKYAQCgAQHIAQnAAQE&sclient=gws-wiz) to save it locally.
