### ISSUE TITLE
Stacked Areas

### ISSUE THREAD

**Issue by vitruvvius** [tradingview/lightweight-charts#1041]
Stacking areas to understand - in some cases - the cumulative volume of multiple assets may be helpful :)

One would think you may be able to accomplish this by pre-calculating bottom / top margins, however, the static configuration is not dynamic. When prices/volumes move up and down, the relative base / top margin must change.

**Comment by timocov** [comment]
@vitruvvius Do you have any examples of _financial_ charts where you saw this type of charts?

**Comment by vitruvvius** [comment]
In currency/prices - of course not. In the volume of total assets traded - partitioning on network either through a stacked area or a stacked bar chart quite useful to comprehend relative flow. I hoped that may be relevant herein.

**Comment by timocov** [comment]
> In currency/prices - of course not

Maybe you saw this on any financial-related website then? I do understand all advantages of stacked areas, I just want to see examples of usage of this feature in financial world so we can decide how critical/important this feature is.

**Comment by vitruvvius** [comment]
None related to the finance components of crypto - as most consume & depend on the imagination of this library for any & all charting. 

I can go out & search for examples in classical areas - but that would be confirmation bias. 

My view is it's either unexplored (since most are bounded to the optionality of this library) or not important. For reference, I am consuming this library to breakdown sources of income ie flow of money + volume of assets.

**Comment by vitruvvius** [comment]
Eventually trying to achieve a graph similar to below

<img width="592" alt="Screen Shot 2022-03-07 at 3 43 36 AM" src="https://user-images.githubusercontent.com/98918683/157135175-c843a6cc-bf5c-4c3b-908f-e04f7e987484.png">

**Comment by timocov** [comment]
It seems that this feature might be implemented if we'll have an ability to fill an area between 2 series (see https://github.com/tradingview/lightweight-charts/issues/140), then you could create accumulative series and fill the space between each 2 "neighbour" series.

**Comment by vitruvvius** [comment]
i don't have anything significant to contribute in the implementation. i'd imagine, though, from my experience w/ other libraries that all failed to encapsulate our performance requirements, all variations of this chart will reside in the same api as you note.

stacked areas, stream graphs, area difference, & so forth are inherently all similar with the minute difference of (1) the y-intercept atop the origin (0, 0) (2) the way in which height aggregates (single direction / both directions)

**Comment by vitruvvius** [comment]
closing this - no urgency herein

**Comment by skdillon** [comment]
Wondering if anymore thought has been given to this?

**Comment by x1i4b1x2** [comment]
I was able to fix it with Highcharts

**Comment by francisashley** [comment]
This would be a useful.. not sure why this was closed.

**Comment by francisashley** [comment]
That said.. just discovered an example for stacked area charts in the plugin documentation.
- https://tradingview.github.io/lightweight-charts/plugin-examples/
- https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/stacked-area-series/example/
- https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/stacked-area-series
