### ISSUE TITLE
add Custom vertical Line not by LineSeries

### ISSUE THREAD

**Issue by zeeshan-shabbir** [tradingview/lightweight-charts#1049]
is it possible we can show vertical line on time with no value required just line from up way to down in any graph (chandle bar area)graph? like vertical line on crosshair .
if not how to show vertical line?

**Comment by zeeshan-shabbir** [comment]
waiting for response :-)

**Comment by SlicedSilver** [comment]
Duplicate of #128, #127, and #965. Please post your suggestion there.
