### ISSUE TITLE
Error in the documentation at #subscribecrosshairmove

### ISSUE THREAD

**Issue by oDYRASH** [tradingview/lightweight-charts#1054]
Should be : `chart.subscribeCrosshairMove(myCrosshairMoveHandler);`

![ErrorInDoc](https://user-images.githubusercontent.com/64509934/161763161-1bd49b30-5191-4fc8-abee-1cd1bf5338ec.png)

**Comment by rimakan** [comment]
Hey, is the issue actual? If it’s so, could I please take it?

**Comment by edew** [comment]
@rimakan Yes. Feel free to submit a PR fixing this.
