### ISSUE TITLE
Not able to get volume data in formatted number.

### ISSUE THREAD

**Issue by rushikeshkoli03** [tradingview/lightweight-charts#1067]
Hi,
I have chart with histogram data (volume data)
this is the code i use to get a particular candle:
```
chart.current.subscribeCrosshairMove((param: any) => {
      const currCandleVolume = param.seriesPrices.get(volumeSeries);
      // const currCandleVolume = null;
      if (currCandleVolume) {
        setLegendText(currCandleVolume);
      }
    });
```

In charts the volume in nicely formatted, if volume is 29000, it shows 29K, if it is 300 it shows 300 on the axis line.
I would like to get such formatted number on crosshairmove.

**Comment by SlicedSilver** [comment]
You can get the formatter used for a series like this:
```js
const price = 12345;
const formattedNumber = series.priceFormatter().format(price); // would be '12.35K' if price format is 'volume'
```

https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#priceformatter
