### ISSUE TITLE
timeframes other than 'Day'

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#107]
Are timeframes other than 'day' resolutions supported? I can't see any documentation to suggest how this may work

**Comment by timocov** [comment]
Lightweight Charts supports any resolution. The only thing you need to do - provide correct time values for your data. If it's DWM resolutions - we suggest you use [business day](https://github.com/tradingview/lightweight-charts/blob/v1.0.0/docs/time.md#business-day-object), if it's intraday - you need to use [timestamp](https://github.com/tradingview/lightweight-charts/blob/v1.0.0/docs/time.md#unix-timestamp).

**Comment by jimeney** [comment]
is there a jsfiddle example for intraday data?
my data array is as follows as per the timestamp link you provide:
timestamp: 1562655360, open: 1.24914, high: 1.24914, low: 1.24878, close: 1.24878

However this throws an error as below?

lightweight-charts.s…one.production.js:7 Uncaught TypeError: Cannot read property 'year' of undefined
    at Ri (lightweight-charts.s…one.production.js:7)
    at lightweight-charts.s…one.production.js:7
    at Array.forEach (<anonymous>)
    at t.setSeriesData (lightweight-charts.s…one.production.js:7)
    at t.applyNewData (lightweight-charts.s…one.production.js:7)
    at e.t.setData (lightweight-charts.s…one.production.js:7)
    at Object.success (HTMLPage1.html:119)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at l (jquery-3.4.1.min.js:2)

**Comment by jimeney** [comment]
please disregard, I can see whilst the const is named timestamp, the input variable is still 'time'

an intraday jsfiddle would still be of use however if you could find the time

**Comment by jimeney** [comment]
https://jsfiddle.net/TradingView/bmL0vont/
