### ISSUE TITLE
Displace series marker

### ISSUE THREAD

**Issue by doliolarzz** [tradingview/lightweight-charts#1074]
**Lightweight Charts Version:** 3.8.0

**Steps/code to reproduce:**

```js
const t = 1542186000; // UTC: 2018-11-14 9.00 AM
var markers = [{ time: t, position: 'aboveBar', color: '#f68410', shape: 'circle', text: 'D' }];
series.setMarkers(markers);
```

Note that the marker is placed on the 1542186000 timestamp which is UTC: 2018-11-14 9.00 AM.

**Actual behavior:**
The marker is displayed on 2018-11-15 bar.

**Expected behavior:**
It should be on the 2018-11-14 bar, instead.

**Screenshots:**
![image](https://user-images.githubusercontent.com/17764453/166115542-75088281-376c-4237-8a0d-809bbd6b0935.png)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/o01xa2cf/1/

**Comment by romfrancois** [comment]
Hi @doliolarzz !

I believe there's a potential conversion shift when specifying date in that format. If you were to use unix timestamp you will plot the market at the right place.

```
var data = [
{ time: 1542099600 , open: 46.042722425788355 , high: 58.476056411825695 , low: 46.042722425788355 , close: 51.2300776481609 }, // 1542099600
{ time: 1542186000 , open: 53.909068487588385 , high: 60.240990154306715 , low: 45.230741063278664 , close: 51.34529637385427 }, // 1542186000
{ time: 1542272400 , open: 53.739609857086606 , high: 53.739609857086606 , low: 44.38017019990068 , close: 47.595960698697894 }, // 1542272400
]
```
<img width="815" alt="Screenshot 2022-05-04 at 07 19 41" src="https://user-images.githubusercontent.com/3977635/166631469-8aed07fc-2013-4974-a879-d24699ebe25c.png">

**Comment by doliolarzz** [comment]
Hello @romfrancois [romfrancois](https://github.com/romfrancois),
Thank you for you help!

I've already convert all of the times to unix timestamp [https://jsfiddle.net/t0gy9n7h/4/](url).
Unfortunately, the marker's still on the 2018-11-15 bar.
I mean, the 2018-11-14 bar, should display data from 2018-11-14 00.00 to 2018-11-14 23.59 and the marker is on 2018-11-14 09.00. 

Should it be on 2018-11-14 bar? or am I misunderstand anything?

Really appreciate for you help, thank you

**Comment by doliolarzz** [comment]
Hello @edew,
I'll deal with my data instead. Thank you for your clarification.
