### ISSUE TITLE
Price axis content auto-scale issue on scattered data

### ISSUE THREAD

**Issue by s-uds** [tradingview/lightweight-charts#1079]
Hello,

**Lightweight Charts Version:** 3.8.0 - https://unpkg.com/lightweight-charts@3.8.0/dist/lightweight-charts.standalone.production.js

**Steps/code to reproduce:**

Please find an example on JSFiddle: https://jsfiddle.net/4d5mhesj/

It seems that given values being too scattered, the auto-scale fails to display all the data points.

**Screenshots:**

![image](https://user-images.githubusercontent.com/10866872/167874125-ac140ebf-ae34-4454-bf88-53eb068dc7b4.png)
 
Thanks!

**Comment by victorbrambati** [comment]
You can hover the mouse on numbers of value and drag down then you will can see all data.

**Comment by s-uds** [comment]
Yes absolutely!
I'm specifically talking about the auto-scale here which I presume, should ensure all the data points are visible?

**Comment by romfrancois** [comment]
Hi @s-uds !

Any reason you're not on the latest version available?

**Comment by s-uds** [comment]
Hello,

Actually no I just took an existing JSFiddle to use an example but I'm able to reproduce the issue using the latest production version (3.8.0 - which is the one I am using) https://jsfiddle.net/oc85kng1/

I've edited my original post accordingly, sorry for the confusion.

**Comment by romfrancois** [comment]
Try reformatting the values to numbers vs strings.

**Comment by s-uds** [comment]
Thanks! That solves the issue 🎉
Is it the expected behavior?
