### ISSUE TITLE
Lines and Annotations

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#108]
I'm trying to plot simple horizontal lines, referencing data stored externally, and via a loop.

As there are no documented drawing tools, so I'm opting to add datapoints to a line series, on demand.

Sample data:
`{xe: 1562713200, xs: 1561834800, ye: 12835.97409692, ys: 12244}`

The code is designed to add one or more line series dependent on the data returned, although in the examples with static code, I can see that the chart line does not cope with missing data for the timeframe resulting in a solid horizontal line, when the data should start and stop in the middle of the chart.

This is the code in question:
` function loadTrendLines() {

                 
                    const url = "/api/trendlines/" + symbol.replace("/", "_") + "/" + timeframe;

                    $.ajax({
                        type: 'GET',
                        url: url,
                        contentType: 'application/json',
                        dataType: 'json',
                        responseType: 'application/json',

                        success: function (jdata)
                        {
                            console.log(jdata);

                            var i;
                            for (i = 0; i < jdata.TrendLines.length; ++i) {
                                console.log(jdata.TrendLines[i]);

                                var tldata = [];

                                tldata.push({ time: jdata.TrendLines[i].xe, value: jdata.TrendLines[i].ye });
                                tldata.push({ time: jdata.TrendLines[i].xs, value: jdata.TrendLines[i].ue });

                                var lineSeries = chart.addLineSeries({
                                    lastValueVisible: false
                                });

                                lineSeries.setData(tldata);

                            }

                        }

                    });
                }`

I'm receiving the following error:

Uncaught Error: Value is undefined
    at h (lightweight-charts.standalone.production.js:7)
    at p (lightweight-charts.standalone.production.js:7)
    at t.updateSeriesData (lightweight-charts.standalone.production.js:7)
    at t.updateData (lightweight-charts.standalone.production.js:7)
    at e.t.update (lightweight-charts.standalone.production.js:7)
    at Object.success (HTMLPage1.html?symbol=BINANCE:BTC/USDT&barstoshow=100&timeframe=60&trendlines=1:252)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at l (jquery-3.4.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.min.js:2)

If I manually define the xe, xs, ye and ue values, running the same inner loop logic, but placing this outside of the loop, it is successful, however this is not referencing any live data, merely static examples.

Can you please advise on a) whether this workaround should be viable, and b) if there are drawing tools that can be leveraged?

**Comment by timocov** [comment]
Can you provide repro without requesting data from your server (just with hardcoded values), but with creating chart and adding series?

**Comment by timocov** [comment]
> As there are no documented drawing tools

Yes, we don't have any drawing tools for now and I don't remember that we have any plan to add them.

**Comment by jimeney** [comment]
With static values:

https://jsfiddle.net/jimeney/Lgtrhj52/

**Comment by timocov** [comment]
![image](https://user-images.githubusercontent.com/3112183/60968315-6d09ff80-a325-11e9-9710-18d955a6fe81.png)

Please check your data.

**Comment by timocov** [comment]
But even if I replace `ue` => `ys` it fails.

**Comment by jimeney** [comment]
I have noted the typo, and corrected to ys for completeness on the jsfiddle, but, as you have stated, this still fails

**Comment by timocov** [comment]
The minimal repro code:

```javascript
var container = document.createElement('div');
document.body.appendChild(container);

var chart = LightweightCharts.createChart(container);

var areaSeries = chart.addAreaSeries();
var volumeSeries = chart.addHistogramSeries();

volumeSeries.setData([
	{ time: '2019-05-24', value: 23714686.00, color: 'red' },
]);

areaSeries.setData([
	{ time: '2019-05-24', value: 179.66 },
]);
```

It's a bug. We'll fix it.

**Comment by timocov** [comment]
I just created issue for that - see #110.

**Comment by jimeney** [comment]
Perfect, I assume I can workaround this by setting a series level colour instead?

**Comment by timocov** [comment]
It looks like there is another issue with histogram series. I just removed setting color for each item in histogram series and it fails on painting stage...

**Comment by jimeney** [comment]
No problem. I'll sight tight

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/issues/110#issuecomment-510045762.

**Comment by timocov** [comment]
Nice catch @jimeney, thank you! This is really interesting cases 🙂

**Comment by jimeney** [comment]
No problem. To confirm, I've replaced, in the static example, the histogram with an area series and the results are perfect for my use - I will test this shortly against the dynamic data

**Comment by timocov** [comment]
The [1.0.1](https://www.npmjs.com/package/lightweight-charts/v/1.0.1) version is published just now.

https://github.com/tradingview/lightweight-charts/releases/tag/v1.0.1
