### ISSUE TITLE
Custom Single Candle Bar Color / Styling

### ISSUE THREAD

**Issue by fabriziogiordano** [tradingview/lightweight-charts#1083]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to assign to a subset of candles a custom style.
When a specific patterns is forming I'd like the candles involved in the pattern to have a different visual styling to quickly identify it.

**Describe the solution you'd like**

Here an example where the regular candles are green and red. And in blue the candles that formed a pattern.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/109390/168409730-ce8899c7-2f9e-424e-9b73-cfd07f1161a3.png">

**Comment by romfrancois** [comment]
Hi @fabriziogiordano !

Im afraid that's not possible.

**Comment by fabriziogiordano** [comment]
@edew exactly what I was looking for. Thank you. I will read the doc more in depth next time.
