### ISSUE TITLE
IPriceScaleApi width method always returns 0

### ISSUE THREAD

**Issue by alexandra-b1** [tradingview/lightweight-charts#1085]
**Lightweight Charts Version:**  3.8.0

**Actual behavior:**

IPriceScaleApi.width() seems to return 0 even if price scale is visible. You can check the jsfiddle link below for an example.

**Expected behavior:**
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPriceScaleApi#width
_Returns a width of the price scale if it's visible or 0 if invisible._

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/alexandrab1/pvxq5ryd/39/

Thanks in advance for the help!

**Comment by andreyvolfman** [comment]
Hi!

I've tried to investigate this issue by myself.

When we call `chart.priceScale()` method we instantiate new PriceScaleApi every time. Before render rightPriceAxisWidth has 0 as default value (see _adjustSizeImpl). If we call `chart.priceScale().width()` in our code immediately we will have race condition.

You can check it. Just wrap `chart.priceScale().width()` in `setTimeout(..., 0)` and see the correct value.

But I wasn't satisfied and continued investigation. I found method _drawImpl which produce forceUpdate and invalidate current state.

I added this invoke before priceScale width calculation:
`this._drawImpl(new InvalidateMask(InvalidationLevel.Full));`

Everything is fine now. Method returns expected value.

Dear TradingView team if it sounds like a truthy solution I will make PR with this fix.

Thanks a lot!

**Comment by kirchet** [comment]
I don't think that it's an acceptable solution. I would prefer just change the returned type from `number` to some observable value.

**Comment by SlicedSilver** [comment]
The `width()` method is returning the correct value once the chart has been rendered. The width value can only be determined once the chart has rendered the price scale and it is visible. 
Thus you should query this value inside a `requestAnimationFrame` if you have only just created the chart / price scale.
