### ISSUE TITLE
Add a possibility to hide all fractional zeros on a price axis marks

### ISSUE THREAD

**Issue by kirchet** [tradingview/lightweight-charts#1088]
**Is your feature request related to a problem? Please describe.**

Add a possibility to hide all fractional zeros on a price axis marks if all numbers after decimal point are zeros

**Describe the solution you'd like**

Add an option like `tryCutFractionalZeros: boolean` that is disabled by default. If this option is enabled the library should try to cut non-valuable fractional parts if possible.

**Additional context**

![image](https://user-images.githubusercontent.com/1572087/172426062-774895c2-852d-49ea-bcaa-b79dd7c0bd16.png)

**Comment by SlicedSilver** [comment]
@kirchet should we close this issue?

**Comment by kirchet** [comment]
Yes, we can close this issue
