### ISSUE TITLE
More accurate TS types for `createPriceLine` within `ISeriesApi`

### ISSUE THREAD

**Issue by SlicedSilver** [tradingview/lightweight-charts#1091]
**Lightweight Charts Version:** 3.8.0

**Actual behavior:**
When creating a new price line using the [createPriceLine](https://github.com/tradingview/lightweight-charts/blob/e45ed5b89cb9212641a7806b721f5b614d912ee6/src/api/series-api.ts#L173) method on the `ISeriesApi`, the typescript compiler expects the options parameter to be of type `PriceLineOptions` and that ALL the properties are required.

An error message such as this appears:
`Argument of type '{ price: number; }' is not assignable to parameter of type 'PriceLineOptions'.`

However, the actual implementation only requires that the `price` property be set and thus the other properties should be optional. 

https://github.com/tradingview/lightweight-charts/blob/e45ed5b89cb9212641a7806b721f5b614d912ee6/src/api/series-api.ts#L173-L179

* The `checkPriceLineOptions` function ensures that the `price` property is present and is a number. 
* Next, the user supplied options are merged with the default options
* Resulting in a fully formed options object (type `PriceLineOptions`) even if the other properties aren't included

**Expected behavior:**
A typescript error shouldn't occur when leaving out any of the properties (except `price` of course).

**Code to reproduce:**

The following shouldn't trigger a typescript error.
```ts
  // @ts-expect-error 
  const newPriceLine = line.createPriceLine({
    price: 1234,
  });
  // ^ where line is of type: ISeriesApi<"Line">
```

**Proposed Solution:**
Update the typings for the `createPriceLine` options object to something like this:
```ts
// One-liner
type CreatePriceLineOptions = Partial<PriceLineOptions> & Pick<PriceLineOptions, 'price'>;

// Or using a new utility type if required in multiple places
type PartialExcept<T, K extends keyof T> = Partial<T> & Pick<T, K>;
type CreatePriceLineOptions =  PartialExcept<PriceLineOptions, 'price'>;
```

**Comment by Jeronimotio** [comment]
In fact, even `price` is not required. Yes, it throws an exception in development mode:
```
export function checkPriceLineOptions(options: PriceLineOptions): void {
	if (process.env.NODE_ENV === 'production') {
		return;
	}

	// eslint-disable-next-line @typescript-eslint/tslint/config
	assert(typeof options.price === 'number', `the type of 'price' price line's property must be a number, got '${typeof options.price}'`);
}
```
But using the dev mode requires the aliases in the bundler and the knowledge that the mode exists.

The `price` option is set to 0 by default, so everything will work fine even without any explicitly declared options. Types can simply be updated to `Partial<PriceLineOptions>` and a strong price assertion can be turned into a warning in dev mode.

```
export const priceLineOptionsDefaults: PriceLineOptions = {
	color: '#FF0000',
	price: 0,
	lineStyle: LineStyle.Dashed,
	lineWidth: 1,
	lineVisible: true,
	axisLabelVisible: true,
	title: '',
};
```
