### ISSUE TITLE
Suggestion: сhart sets default options for scales

### ISSUE THREAD

**Issue by Jeronimotio** [tradingview/lightweight-charts#1098]
**Is your feature request related to a problem? Please describe.**

At the moment, some chart options may affect other objects:
- `ChartOptions['leftPriceScale']` overwrites left price scale options
- `ChartOptions['rightPriceScale']` overwrites right price scale options
- `ChartOptions['overlayPriceScales']` overwrites options for EACH overlay price scale
- `ChartOptions['timeScale']` overwrites time scale options

If for the left, right and time scales the overwrite options are more or less obvious, then for the overlay it is not quite so. You can have multiple overlay scales with different options. Each of them can be given some unique options, but one single `chart.setOptions({ overlayPriceScales })` call will overwrite them.

**Describe the solution you'd like**

I would like to suggest adding or renaming the current chart options. Instead of the usual options, allow you to set default options. That is, we will have the option `ChartOptions['defaultOverlayPriceScale']` and it will work a little differently. This option will never overwrite explicitly set options on the scale, i.e. it will do something like this:
```
class PriceScale {
    setOptions(options) {
        merge(this._options, this._defaultOptionsFromChart, options)
    }
}
```

**Comment by SlicedSilver** [comment]
`chart.applyOptions()` only applies the properties deeply with a merge already.

Thus something like this:
```js
chart.applyOptions({
    overlayPriceScales: {
        mode: LightweightCharts.PriceScaleMode.Normal,
    }
});
```

Would only change the `mode` option on all the overlay price scales, and leave the rest of the options as they currently are.

If you want to change the options individually for each overlay price scale then you can access the specific price scale with it's id within the `chart.priceScale()` method.

For example:
```js
chart.priceScale('my-overlay').applyOptions({ autoScale: false });
```

If you feel that I've misunderstood your issue then please could you provide an example (like a JSFiddle) of the behaviour which you would like to change, and I'll reopen the issue.

**Comment by Jeronimotio** [comment]
I don't have any issue with this behavior.

I just wanted to set default options for newly created price scales, rather than overwriting options for already created and customized ones.

**Comment by SlicedSilver** [comment]
Makes sense. We probably won't implement a new api for this. Not because it is a bad idea but rather because it is something that can be achieved from outside the library and we want to keep the library as 'lightweight' as possible.

The easiest way to achieve something like that at the moment would be to create your own defaultOptions object which you then 'extend' when creating a new price scale. You could also create your own helper (factory) function or class to achieve this if it is a common requirement in your code.

```js
const myDefaultPriceScaleOptions = {
  autoScale: true,
  invertScale: true,
};

// ...

chart.priceScale('my-overlay').applyOptions({
   ...myDefaultPriceScaleOptions, // start with your new defaults
  // then add the specific options for this price scale
  scaleMargins: {
        top: 0.8,
        bottom: 0,
    },
});
```
