### ISSUE TITLE
Multiple background colors

### ISSUE THREAD

**Issue by RaenonX** [tradingview/lightweight-charts#1109]
**Is your feature request related to a problem? Please describe.**

Futures trading hours are long, and can be separated into a few sections. Having such ability helps distinguishing the sessions.

**Describe the solution you'd like**

Similar way as we add things like `addCandlestickSeries` or `createPriceLine`.

**Additional context**

![image](https://user-images.githubusercontent.com/18443743/177422659-e4f16294-9c4f-4a4e-ad6b-0a53972d3b9d.png)

> With multiple background colors.

![image](https://user-images.githubusercontent.com/18443743/177422697-b6d3801f-d605-41ff-8c9f-3a1018d22cf5.png)

> WithOUT multiple background colors.

Yellow indicating pre-market hours/Europe trading hours; 

Blue indicating post-market hours; 

Transparent indicating regular trading hours.

Comparing the images, the upper one clearly helps the viewer to identify the current trading session.

**Comment by kirchet** [comment]
Hm, not sure. I think it would be better to create a new type of series like `BackgroundSeries`. Because in this case we can change the type of the first series without changing the background.

In any case we can disscuss it.

**Comment by Javid-Izadfar** [comment]
Any updates guys?

**Comment by VilleKokkarinen** [comment]
i'd also love to be able to set multiple background colors vertically.
or have a gradient work as in css styles where i can set it to start and end at certain percentages.

for example if i want to highlight an area from 30-70 on a chart scale of 0-100.
but have another bg color for 0-30 and 70-30;

![image](https://github.com/tradingview/lightweight-charts/assets/20614421/5b3e703b-b3c9-4cb8-9685-70de4980b60d)

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples (see above links):
- Session Highlighting
- Shaded Background Series

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.

**Comment by calculabs** [comment]
# Vertical Background Primitive for TradingView Lightweight Charts

A comprehensive solution for creating **vertical background zones** in TradingView Lightweight Charts. This addresses the feature request discussed in [GitHub Issue #1109](https://github.com/tradingview/lightweight-charts/issues/1109) for multiple background colors to highlight different time periods.

## Overview

This primitive allows you to highlight specific time ranges with colored background zones, perfect for:
- Trading sessions (pre-market, regular hours, after-hours)
- Market conditions (high volatility, low liquidity periods)
- Economic events (earnings, news releases)
- Any time-based categorization

## Implementation

### Core Primitive Code

```typescript
import type { 
  ISeriesPrimitive, 
  SeriesPrimitivePaneView, 
  Time,
  ISeriesPrimitiveAxisView 
} from 'lightweight-charts'

export interface BackgroundZoneData {
  startTime: Time
  endTime: Time
  color: string
  opacity?: number
  label?: string
  labelColor?: string
  labelBackgroundColor?: string
}

class BackgroundZonePaneView implements SeriesPrimitivePaneView {
  private _zones: BackgroundZoneData[] = []
  private _defaultColor: string = 'rgba(128, 128, 128, 0.1)'
  private _defaultOpacity: number = 0.1

  constructor(zones: BackgroundZoneData[]) {
    this._zones = zones
  }

  update(zones: BackgroundZoneData[]): void {
    this._zones = zones
  }

  renderer() {
    return {
      draw: (target: CanvasRenderingContext2D, priceConverter: any, timeConverter: any, pixelRatio: number) => {
        target.save()
        
        this._zones.forEach(zone => {
          const startX = timeConverter.timeToCoordinate(zone.startTime)
          const endX = timeConverter.timeToCoordinate(zone.endTime)
          
          if (startX === null || endX === null) return
          
          const width = Math.abs(endX - startX)
          const height = target.canvas.height / pixelRatio
          
          // Draw background zone
          target.fillStyle = zone.color || this._defaultColor
          target.globalAlpha = zone.opacity ?? this._defaultOpacity
          target.fillRect(Math.min(startX, endX), 0, width, height)
          
          // Draw label if provided and zone is wide enough
          if (zone.label && width > 60) {
            const centerX = (startX + endX) / 2
            const labelY = 20
            
            target.globalAlpha = 1
            target.font = `${12 * pixelRatio}px Arial`
            target.textAlign = 'center'
            target.textBaseline = 'middle'
            
            // Label background
            const textMetrics = target.measureText(zone.label)
            const labelWidth = textMetrics.width + 8 * pixelRatio
            const labelHeight = 16 * pixelRatio
            
            target.fillStyle = zone.labelBackgroundColor || 'rgba(0, 0, 0, 0.7)'
            target.fillRect(
              centerX - labelWidth / 2,
              labelY - labelHeight / 2,
              labelWidth,
              labelHeight
            )
            
            // Label text
            target.fillStyle = zone.labelColor || '#ffffff'
            target.fillText(zone.label, centerX, labelY)
          }
        })
        
        target.restore()
      }
    }
  }

  zOrder(): number {
    return 'bottom' as any // Draw behind other elements
  }
}

export class VerticalBackgroundPrimitive implements ISeriesPrimitive<Time> {
  private _paneView: BackgroundZonePaneView
  private _zones: BackgroundZoneData[] = []

  constructor() {
    this._paneView = new BackgroundZonePaneView([])
  }

  updateAllViews(): void {
    this._paneView.update(this._zones)
  }

  paneViews(): readonly SeriesPrimitivePaneView[] {
    return [this._paneView]
  }

  priceAxisViews(): readonly ISeriesPrimitiveAxisView[] {
    return []
  }

  timeAxisViews(): readonly ISeriesPrimitiveAxisView[] {
    return []
  }

  hitTest(): null {
    return null
  }

  // Public API methods
  setZones(zones: BackgroundZoneData[]): void {
    this._zones = zones
    this.updateAllViews()
  }

  addZone(zone: BackgroundZoneData): void {
    this._zones.push(zone)
    this.updateAllViews()
  }

  clearZones(): void {
    this._zones = []
    this.updateAllViews()
  }

  getZones(): BackgroundZoneData[] {
    return [...this._zones]
  }
}
```

## Usage Examples

### 1. Trading Sessions (Original Request)

```typescript
const sessionPrimitive = new VerticalBackgroundPrimitive()

// Add trading session backgrounds
sessionPrimitive.setZones([
  {
    startTime: '2023-01-01T04:00:00Z' as Time,
    endTime: '2023-01-01T09:30:00Z' as Time,
    color: 'rgba(255, 193, 7, 0.2)', // Yellow for pre-market
    label: 'Pre-Market'
  },
  {
    startTime: '2023-01-01T20:00:00Z' as Time,
    endTime: '2023-01-01T24:00:00Z' as Time,
    color: 'rgba(59, 130, 246, 0.2)', // Blue for after-hours
    label: 'After Hours'
  }
])

series.attachPrimitive(sessionPrimitive)
```

### 2. Market Conditions

```typescript
const conditionPrimitive = new VerticalBackgroundPrimitive()

// Highlight volatile periods
conditionPrimitive.setZones([
  {
    startTime: 1640995200 as Time, // High volatility period
    endTime: 1641081600 as Time,
    color: 'rgba(239, 68, 68, 0.15)', // Red for high volatility
    label: 'High Volatility',
    opacity: 0.15
  },
  {
    startTime: 1641168000 as Time, // Low liquidity period
    endTime: 1641254400 as Time,
    color: 'rgba(107, 114, 128, 0.1)', // Gray for low liquidity
    label: 'Low Liquidity'
  }
])
```

### 3. Economic Events

```typescript
const eventPrimitive = new VerticalBackgroundPrimitive()

// Highlight news/earnings periods
eventPrimitive.setZones([
  {
    startTime: 1641340800 as Time,
    endTime: 1641344400 as Time, // 1-hour window
    color: 'rgba(16, 185, 129, 0.2)', // Green for earnings
    label: 'EARNINGS',
    labelColor: '#ffffff',
    labelBackgroundColor: 'rgba(16, 185, 129, 0.8)'
  }
])
```

## Integration with Chart Component

### React/Vue Integration

```typescript
// In your chart composable/component
export function useVerticalBackgrounds() {
  const backgroundPrimitive = new VerticalBackgroundPrimitive()
  
  const updateBackgroundZones = (zones: BackgroundZoneData[]) => {
    backgroundPrimitive.setZones(zones)
  }
  
  const clearBackgroundZones = () => {
    backgroundPrimitive.clearZones()
  }
  
  const addBackgroundZone = (zone: BackgroundZoneData) => {
    backgroundPrimitive.addZone(zone)
  }
  
  return {
    backgroundPrimitive,
    updateBackgroundZones,
    clearBackgroundZones,
    addBackgroundZone
  }
}
```

### Basic Setup

```typescript
import { createChart } from 'lightweight-charts'
import { VerticalBackgroundPrimitive } from './VerticalBackgroundPrimitive'

// Create chart and series
const chart = createChart(container)
const candlestickSeries = chart.addCandlestickSeries()

// Create and attach primitive
const backgroundPrimitive = new VerticalBackgroundPrimitive()
candlestickSeries.attachPrimitive(backgroundPrimitive)

// Add your zones
backgroundPrimitive.setZones([
  {
    startTime: 1640995200 as Time,
    endTime: 1641081600 as Time,
    color: 'rgba(255, 193, 7, 0.2)',
    label: 'Special Period'
  }
])
```

## API Reference

### `BackgroundZoneData` Interface

| Property | Type | Required | Description |
|----------|------|----------|-------------|
| `startTime` | `Time` | ✅ | Start time of the background zone |
| `endTime` | `Time` | ✅ | End time of the background zone |
| `color` | `string` | ✅ | Background color (supports rgba) |
| `opacity` | `number` | ❌ | Override opacity (0-1) |
| `label` | `string` | ❌ | Optional label text |
| `labelColor` | `string` | ❌ | Label text color |
| `labelBackgroundColor` | `string` | ❌ | Label background color |

### `VerticalBackgroundPrimitive` Methods

| Method | Parameters | Description |
|--------|------------|-------------|
| `setZones()` | `zones: BackgroundZoneData[]` | Replace all zones |
| `addZone()` | `zone: BackgroundZoneData` | Add a single zone |
| `clearZones()` | - | Remove all zones |
| `getZones()` | - | Get current zones array |

## Features

✅ **Generic & Reusable**: Works for any time-based background highlighting  
✅ **Configurable**: Colors, opacity, labels all customizable  
✅ **Performance Optimized**: Only draws visible zones  
✅ **Label Support**: Optional labels with smart positioning  
✅ **TypeScript**: Full type safety  
✅ **Plugin Architecture**: Follows TradingView's recommended approach  

## Time Format Support

The primitive supports both timestamp formats:

```typescript
// Unix timestamp (seconds)
startTime: 1640995200 as Time

// ISO string
startTime: '2023-01-01T04:00:00Z' as Time
```

## Contributing

This primitive addresses the exact need described in [GitHub Issue #1109](https://github.com/tradingview/lightweight-charts/issues/1109). Feel free to extend it for your specific use cases and share improvements with the community!

## License

This code is provided as-is for the TradingView Lightweight Charts community. Use and modify as needed for your projects.

**Comment by reconmind** [comment]
@calculabs @SlicedSilver hey guys, sorry for tagging you. I just copied the solution suggested by calculabs into a minimal project here:
https://stackblitz.com/edit/lwc-2005-bkgbjqst-599eoibp?file=src%2Fmain.ts
…but I’m getting a white screen at the line candlestickSeries.attachPrimitive(backgroundPrimitive).

Could you please take a look and see what might be causing the issue?
I know the library’s repo includes a session-highlighting example with similar functionality, and I was able to reproduce it, but it relies on many helper .ts files. The solution from calculabs is minimalistic—exactly what I need—so I’d really appreciate your help.
Thanks a lot!

**Comment by SlicedSilver** [comment]
Seems like this code is for an older version of the library. Firstly, the type `SeriesPrimitivePaneView` should rather be `IPrimitivePaneView` and it appears that the signature of the `draw` function is incorrect. It wouldn't have access to methods like `timeConverter` passed via the parameters. Not sure how it ever worked before because even in v4.1 the renderer function didn't provide those to the draw function (see old types: https://tradingview.github.io/lightweight-charts/docs/4.1/api/interfaces/ISeriesPrimitivePaneRenderer).
