### ISSUE TITLE
Can the candlestick auto fill out the gaps between 2 timestamp?

### ISSUE THREAD

**Issue by kramerlee** [tradingview/lightweight-charts#1111]
I have faced the problem that the data for a 1-hour timeframe is not continuous. Then the chart will be unable to render these gaps.

For example
```
{
  time: "2022-07-06 09:00:00",
  open: "",
  high: "",
  low: "",
  close: ""
},
{
  time: "2022-07-06 13:00:00",
  open: "",
  high: "",
  low: "",
  close: ""
}
```
The expectation here would have 3 other candlesticks which have the same OHCL with the `2022-07-06 09:00:00` timestamp, but the Volume will be zero.

If the chart still has not been supporting this yet. It would be nice if someone gave me a few hints or examples to accomplish this, I would appreciate your help!
Thank you very much! PEACE

**Comment by romfrancois** [comment]
Hi @kramerlee !

You could try using `[Whitespace](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/WhitespaceData)` data instead if you don't have any.

**Comment by kramerlee** [comment]
Thank you very much @romfrancois for the super quick reply.

I had tried Whitespace but the chart leaves it blank instead of rendering a Dash candlestick. Is there any specific setting for the chart to display that Whitespace data?

**Comment by romfrancois** [comment]
Im not quite sure I fully understand 

If you don't have any values, what would you like the chart to display?

I've set up a quick [example](https://jsfiddle.net/romainfrancois/uxb90rk3/1/) for reference.

**Comment by kramerlee** [comment]
Thank you @romfrancois, it's clear. My problem is with the data.
