### ISSUE TITLE
Problem with call to  Date.toLocaleString  inside the library. Incorrect locale information provided at Date.toLocaleString

### ISSUE THREAD

**Issue by Acruval** [tradingview/lightweight-charts#1113]
**Lightweight Charts Version:** 
Lightweight Charts v3.8.0
but  I found it happen on Lightweight Charts v3.4.0 too. I didn't check more versions.

**Steps/code to reproduce:**

Well I try to create a graph. Probably I explained more about this in the current behavior
It is regarding 

**Actual behavior:**
Shor Errot. Incorrect locale information provided at Date.toLocaleString
Even it is working on windows server, it is a problem deployed in linux server.
The windows server it is in Irelanc 0 UTC and the linux server it is in Spain +1UTC
And in both cases, I use the same browsers, (Yes it depends from the server not the browsers)

Incorrect locale information provided at Date.toLocaleString
lightweight-charts.standalone.production.js:7 Uncaught RangeError: Incorrect locale information provided
    at Date.toLocaleString (<anonymous>)
    at lightweight-charts.standalone.production.js:7:84736
    at t.Kl (lightweight-charts.standalone.production.js:7:84756)
    at t.xo (lightweight-charts.standalone.production.js:7:83823)
    at t.lo (lightweight-charts.standalone.production.js:7:74884)
    at t.Cl (lightweight-charts.standalone.production.js:7:83854)
    at t.au (lightweight-charts.standalone.production.js:7:79943)
    at t.vt (lightweight-charts.standalone.production.js:7:129210)
    at t.Aw (lightweight-charts.standalone.production.js:7:136887)
    at lightweight-charts.standalone.production.js:7:137627

**Expected behavior:**

Be able to force local it can not be found

**Comment by edew** [comment]
Hi @Acruval 

Which version of the library are you using?

**Comment by Acruval** [comment]
Sorry for miss that
- I am using Lightweight Charts v3.8.0
but  I found it happen on Lightweight Charts v3.4.0 too. I didn't check more versions.

**Comment by Acruval** [comment]
I am investigating. I am hosting  on Diet pi and It could be a Linux issue about locale
 Debian GNU/Linux 11 (bullseye)
I do not have this issue in Windows

$> locale
root@DietPi:~# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

**Comment by Acruval** [comment]
Solution
**Asigned locale for linux.**(Diet Pi bassd in debian)
[](https://www.tecmint.com/set-system-locales-in-linux/)

As sum up.  On the shell of diet pi
`$>sudo localectl set-locale LANG=en_GB.UTF-8`

and then `$>reboot`
