### ISSUE TITLE
different width without horizontal lines and time scales

### ISSUE THREAD

**Issue by IvanDmitrachkov** [tradingview/lightweight-charts#1117]
In some cases, width without horizontal lines and time scales are different, like screen below
Can you fix this it's a big problem
example on sandbox https://codesandbox.io/s/9inkb (need to scroll to scaling)

![image](https://user-images.githubusercontent.com/77490200/178961811-632a3c3b-c075-49ca-a0c2-93136ed0773a.png)

**Comment by Biszu** [comment]
This issue also causes different months to be displayed on the timescale.

May/Aug vs May/Sept

![SCR-20220817-sth](https://user-images.githubusercontent.com/2781739/185218639-583390ee-4041-49be-ac83-bfc10d43a9ac.png)


It would be nice to have it fixed.

**Comment by IvanDmitrachkov** [comment]
And what?

**Comment by SlicedSilver** [comment]
You could use the new 'Horizontal Scale Customization' available in v4.1 to customise the placements (and selection) of tick marks to be drawn as grid lines. If that doesn't meet your requirements then it would also be possible to implement your own grid lines rendering logic by using a Plugin.

https://tradingview.github.io/lightweight-charts/docs/release-notes#410
