### ISSUE TITLE
hide moving average priceLine

### ISSUE THREAD

**Issue by BehroozDante** [tradingview/lightweight-charts#1125]
how to hide moving average priceLine ? after i searched in google, i found that i can hide candleSeries with below  code;
```
            candleSeries.applyOptions({
            priceLineVisible: false,
            lastValueVisible: false,
            });
```
but it not effect on moving average (SMA) priceLine. 

![hhhhhh](https://user-images.githubusercontent.com/37669470/179499035-5a199bf1-7a55-4f8e-b286-530f159e3b7e.png)

look , the both SMA priceLine are still visible. is there any option to hide them ?

**Comment by BehroozDante** [comment]
i found it:
chart.addLineSeries({color: '#0068ff',lineWidth: 2,priceLineVisible: false, lastValueVisible: false,});

**Comment by rashearth** [comment]
hmmm...   
I did the same thing but it seems it wont work.
https://jsfiddle.net/ktjfcpu3/13/

What am i missing...

**Comment by TH3AL3X** [comment]
> priceLineVisible: false, lastValueVisible: false

Did you found it?, i'm having same troubles
