### ISSUE TITLE
How to Hide the title in the right/left axis

### ISSUE THREAD

**Issue by jadeja-rajdeep** [tradingview/lightweight-charts#1126]
**Lightweight Charts Version:** 3.8.0

**Steps/code to reproduce:**

```
chartSeries['rs_up'] = chart.addLineSeries({
		title: 'RSUP',
		color: '#008000',
		lineWidth: 2,
		crosshairMarkerVisible: false,
		lastValueVisible: false,
		priceLineVisible: false,
		priceLineLabelVisible: false
	});
```

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**
![Screenshot 2022-07-18 at 18-20-57 Parwarvivah com - Admin Panel](https://user-images.githubusercontent.com/26649950/179515198-55adbc9a-1225-48b5-8e43-236bb2860281.png)

**Comment by jadeja-rajdeep** [comment]
yes sir

**Comment by jadeja-rajdeep** [comment]
basically i also want to keep the title for later used to generate the custom tooltip. but not want to display in the right yaxis

**Comment by edew** [comment]
If the `title` is not an empty string then the label will be displayed. So you would need to keep that information outside the library and then look it up when you want to generate your tooltip.
