### ISSUE TITLE
Chart is shifting to the right on new Bar when dragging (shiftVisibleRangeOnNewBar does not help)

### ISSUE THREAD

**Issue by Yolley** [tradingview/lightweight-charts#1127]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
1. First we create a chart with shiftVisibleRangeOnNewBar=false to prevent chart from shifting to the right when we add new data (append to existing).

```js
var time = new Date(Date.UTC(2018, 0, 1, 0, 0, 0, 0));
var data = [];
var settingData = false;

function generateData() {
    var dataLength = data.length;
    for (var i = dataLength; i < (dataLength + 500); ++i) {
        var val = {
            time: time.getTime() / 1000,
            open: 100 + i,
            high: 100 + i,
            low: 50 + i,
            close: 50 + i,
        };
        data.push(val);
        time.setUTCDate(time.getUTCDate() + 1);
    }
    return data;
}

function updateData() {
    if (settingData) {
        return false;
    }
    settingData = true;
    mainSeries.setData(generateData());
    settingData = false;
}

function handleLogicalRangeChange(range) {
    if (range) {
        if (chart.timeScale().scrollPosition() > 0) {
            updateData();
        }
    }
}
var chart = LightweightCharts.createChart(
    document.body, {
        width: 600,
        height: 300,
        layout: {
            backgroundColor: '#ffffff',
            textColor: 'rgba(33, 56, 77, 1)',
        },
        timeScale: {
            shiftVisibleRangeOnNewBar: false,
        }
    }
);
var mainSeries = chart.addCandlestickSeries();
updateData();
chart.timeScale().subscribeVisibleLogicalRangeChange(handleLogicalRangeChange);
```

2. Then we click on the chart with a mouse cursor and drag it to the right to force load of new data

**Actual behavior:**

Chart shifts to the end.

**Expected behavior:**

When shiftVisibleRangeOnNewBar is set to `false`, chart should not shift visible range.

**Screenshots:**

1. That's what happens when we drag our chart (it always shifts to the end of the data, shiftVisibleRangeOnNewBar does not work)

https://user-images.githubusercontent.com/13859030/179721593-d3b14286-a8e7-4856-8a6b-7311f1d69196.mov

2. That's what happens when we zoom our chart (shiftVisibleRangeOnNewBar options works)

https://user-images.githubusercontent.com/13859030/179720970-c7c33aaa-abcd-442a-83d1-5d8473a618d8.mov

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/ocdhpr4a/3/

**Comment by Yolley** [comment]
It seems that the issue is that with dragging `_commonTransitionStartState` in time scale is not updated right after `updateTimeScale` is called, therefore `rightOffset` is not adjusted.

**Comment by Yolley** [comment]
So, we need to update `_commonTransitionStartState` for sure, for example if were to add an optional parameter in `setRightOffset` in `time-scale.ts`

```ts
	public setRightOffset(offset: number, syncScroll?: boolean): void {
		this._visibleRangeInvalidated = true;
		this._rightOffset = offset;
		this._correctOffset();
		if (syncScroll && this._scrollStartPoint !== null) {
			this._saveCommonTransitionsStartState();
		}
		this._model.recalculateAllPanes();
		this._model.lightUpdate();
	}
```

And in `updateTimeScale` in `chart-model-ts` when we call `setRightOffset` we just pass `true` for this `syncScroll` parameter
```ts
this._timeScale.setRightOffset(this._timeScale.rightOffset() - compensationShift, true);
```

The problem will be fixed, but I am not sure if it doesn't break anything, I've tried to play with chart, dragging, scrolling, zooming, seemed to work without any issues (but we need to check for _scrollStartPoint for sure, otherwise we can lock chart from scrolling).

**Comment by SlicedSilver** [comment]
The `shiftVisibleRangeOnNewBar` option only applies when you are adding new data using the [`update()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#update) method on the series instance. 
Your updateData function is using `setData()` which replaces the entire dataset.

If you are adding new data to the end of the data set then you should use the `update()` method and add each data point one at a time (can be in a loop so that you can add many points per frame, it's just that the update method only accepts a single point at a time).

If you need to add data to the beginning of the dataset then you would need to use an approach like you already have but you could record the chart position before updating using `getVisibleLogicalRange ` and then set it back to that value after updating with `setVisibleLogicalRange ` and the chart will remain in the current position.
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#getvisiblelogicalrange

**Comment by MarvinMiles** [comment]
@SlicedSilver Hello!

As for v4.1.4 version, changing `setData()` method for `update()` having same behavior.

Updated JSFiddle: https://jsfiddle.net/ynmLrqdv/2/

Previous data shifts left side which triggers execution of  `updateData()` continuously, which cause infinity loop until mouse button released. Setting `setVisibleLogicalRange` not helping at all.

Yet adding data to the beginning via "setData()" works like a charm. Even without  `setVisibleLogicalRange` .

**Comment by VasiliyTemniy** [comment]
@SlicedSilver Hello!

I've had similiar problem. Adding data to the beginning with setData() works perfectly, while adding data to the end \ most recent part of the chart caused wild jumps. I could not prevent them with setVisibleLogicalRange: false, and neither setVisibleLogicalRange, nor setVisibleRange with correct params did not help. Some dirty hacks did not work either.

What worked for my case, however, was

```
    const scrollPosition = chart.timeScale().scrollPosition();

    for (const { data, id } of newData) {
      seriesApiMap[id].setData(data);
      if (numberBarsToLoadRight > 0) {
        chart.timeScale().scrollToPosition(scrollPosition - numberBarsToLoadRight, true);
      }
    }
```

using scrollToPosition, specifically - with "animated === true" - the second argument for scrollToPosition. It effectively stops the timeScale from moving, even if I'm still dragging the mouse while holding the LMB. To scroll it further, I have to up and down the mouse button, but it's something that I can live with.

Lightweight charts is an amazing library, blazingly fast, good docs and so on, but it seems like the maintainers think about historical data only in the left time scale direction :)
