### ISSUE TITLE
Usage of hours:minutes:seconds in graphs

### ISSUE THREAD

**Issue by alfredvdheide** [tradingview/lightweight-charts#114]
Hi,

I am having trouble making my graph display actual hour, minute, second data.
For some reason, it is perfectly creating a daily graph, but even with 
**secondsVisible: true,** still nothing shows up. I've tried messing with dateFormat, but it didn't help
my time looks as so: **2019-07-10 13:55:00**

my **dateFormat: 'yyyy-MM-dd',** I couldn't find any examples in the documentation using hours and minutes.

How would one implement this?

Thanks and Kind Regards

**Comment by timocov** [comment]
> How would one implement this?

Can you provide small repro of your problem and what do you want to have?

**Comment by alfredvdheide** [comment]
Thanks for the response,
I'm using Python Django.

I'm passing a JSON file as a dictionary named `data` to javascript with `var dataFromDjango = {{ data|safe }};`
then I use this for loop in JS to add the time and value data to the array:
`      
        var myArray = [];
        for (i in dataFromDjango) {
            myArray.push({time: (dataFromDjango[i]['timestamp']), value: (dataFromDjango[i]['overall_average'])});
        }`

`console.log(myArray[i]["time"])` and `console.log(myArray[i]["value"]);` shows that what is printed out should be correct (see screenshot) especially since what looks like the daily values is rendered correctly. 
![image](https://user-images.githubusercontent.com/11142450/61003539-7d8d9a80-a364-11e9-9634-b10fd656abe9.png)

My chart settings are as follows:
```const chart = LightweightCharts.createChart(document.getElementById("main"));
        chart.applyOptions({
            width: 800,
            height: 400,
            title: 'Graph',
            localization: {
                dateFormat: 'yyyy-MM-dd',
                locale: 'en-US',
            },
            priceScale: {
                position: 'left',
                mode: 1,
                autoScale: true,
                invertScale: false,
                alignLabels: true,
                borderVisible: true,
                borderColor: '#24273E',
                scaleMargins: {
                    top: 0.30,
                    bottom: 0.30,
                },
            },
            timeScale: {
                rightOffset: 50,
                barSpacing: 10,
                fixLeftEdge: true,
                lockVisibleTimeRangeOnResize: true,
                rightBarStaysOnScroll: true,
                borderVisible: true,
                borderColor: '#fff000',
                visible: true,
                timeVisible: true,
                secondsVisible: true,
            },
            crosshair: {
                vertLine: {
                    color: '#6A5ACD',
                    width: 1,
                    style: 1,
                    visible: true,
                    labelVisible: true,
                },
                horzLine: {
                    color: '#6A5ACD',
                    width: 0.5,
                    style: 1,
                    visible: true,
                    labelVisible: true,
                },
                mode: 0,
            },
            watermark: {
                color: 'green',
                visible: true,
                text: 'osrs-portfolio.com',
                fontSize: 12,
                horzAlign: 'left',
                vertAlign: 'bottom',
            },
        });
        const areaSeries = chart.addAreaSeries();
        areaSeries.setData(myArray);
```

I would like this graph to also display the data points by the hour, instead of just by day.
Thanks in advance!

**Comment by timocov** [comment]
But this isn't repro. How do you suggest me help you? Guessing what's going on?!

For instance, the minimal repro you can find in #110, or even https://github.com/tradingview/lightweight-charts/issues/108#issuecomment-510034295 is fine.

**Comment by alfredvdheide** [comment]
Hi,
Sorry I'm still a newbie I wasn't aware what repro meant, but now I do for future references, so thanks for that.
Anyway, in case anyone gets stuck on the same problem I got the hours:minutes:seconds to work correctly by converting the date and time into Unix time `var unixTime = Date.parse(newTime)/1000;`

**Comment by timocov** [comment]
> what repro meant

This means reproduction - a minimal set of files/configs/etc needs to reproduce the problem.

**Comment by timocov** [comment]
> Anyway, in case anyone gets stuck on the same problem I got the hours:minutes:seconds to work correctly by converting the date and time into Unix time var unixTime = Date.parse(newTime)/1000;

This is covered by https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md article:

> If your chart displays an intraday interval, you should use a UNIX Timestamp format for time point data transfer.

**Comment by i3130002** [comment]
> > Anyway, in case anyone gets stuck on the same problem I got the hours:minutes:seconds to work correctly by converting the date and time into Unix time var unixTime = Date.parse(newTime)/1000;
> 
> This is covered by https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md article:
> 
> > If your chart displays an intraday interval, you should use a UNIX Timestamp format for time point data transfer.

It seems the link is no longer exists (404)

**Comment by VadimZP** [comment]
> > Anyway, in case anyone gets stuck on the same problem I got the hours:minutes:seconds to work correctly by converting the date and time into Unix time var unixTime = Date.parse(newTime)/1000;
> 
> This is covered by https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md article:
> 
> > If your chart displays an intraday interval, you should use a UNIX Timestamp format for time point data transfer.

Sir, can you update the link, please? :)

**Comment by romfrancois** [comment]
Apologies for the broken links we now have a dedicated [website](https://tradingview.github.io/lightweight-charts/) for the documentation.

Anyway, link can be found [here](https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp).

**Comment by Funk5Thousand** [comment]
Dude, it has been 4 years, but thanks for asking this question and providing all your initial setup and then providing the answer once you had found it. It was super helpful to me. I can't thank you enough.
