### ISSUE TITLE
Show the scale but do NOT highlight the last price of the series on the same (or any other) scale

### ISSUE THREAD

**Issue by charleswidnall** [tradingview/lightweight-charts#1156]
Let's assume that we have a scale to the right. Is it possible to show the scale but NOT to show the highlighted last price of the series in any way?

Currently, the option '**rightPriceScale**: false' removes both the scale and the price. Would it be possible to have '**rightPrice**: false' and '**rightScale**: true'?

That would be an intermediate situation between showing _everything_ (scale and price) in [**https://jsfiddle.net/TradingView/tygLqpu8/**]([https://jsfiddle.net/TradingView/tygLqpu8/],) line 8, with 'rightPriceScale: true', and showing _nothing_ (no scale and no price) with 'rightPriceScale: false'.

Perhaps there is an option, now, to do that without any modification to the existing functionality, but I'm not aware of it.

Thanks

**Comment by SlicedSilver** [comment]
I believe that you are looking for these options:
* https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#lastvaluevisible
* https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#pricelinevisible

which can be applied to a series.

---

Using that JSFiddle as an example, you could add these options are follows:
```js
var areaSeries = chart.addAreaSeries({
  topColor: 'rgba(233, 16, 169, 0.35)',
  bottomColor: 'rgba(233, 16, 169, 0)',
  lineColor: 'rgba(233, 16, 169, 1)',
  lineWidth: 2,
  priceLineVisible: false,
  lastValueVisible: false,
});
```

or at a later stage (after the series is created) by using `applyOptions`:
```js
areaSeries.applyOptions({
  priceLineVisible: false,
  lastValueVisible: false,
});
```

---

**Working Example:**
The JSFiddle example adjusted to not show the last price (line and label): https://jsfiddle.net/msilverwood/nrv8dL9s/2/
