### ISSUE TITLE
lineseries not work

### ISSUE THREAD

**Issue by tiger2014** [tradingview/lightweight-charts#1159]
I use this for chart:

const getData = async () => {
  const res = await fetch("https://raw.githubusercontent.com/tiger2014/fetchTest/main/Test.csv");
  const resp = await res.text();
  //   console.log(resp);
  const cdata = resp.split("\n").map((row) => {      
      const [time, open, high, low, close] = row.split(",");     
      return {        
        time: time,
        Value: open*1
      };
  });
  // in github, there is always a black row added in the end of the file: row == ""!! 
  cdata.pop();
  return cdata;  
};
const displayChart = async () => {
  const chartProperties = {
    width: 1200,
    height: 600,
    layout: {
      backgroundColor: "#ffffff",
      textColor: "rgba(33, 56, 77, 1)",
    },
    grid: {
      vertLines: {
        color: "rgba(197, 203, 206, 0.7)",
      },
      horzLines: {
        color: "rgba(197, 203, 206, 0.7)",
      },
    },
    timeScale: {
      timeVisible: true,
      secondsVisible: true,
    },   
  };
  const domElement = document.getElementById("tvchart");
  const chart = LightweightCharts.createChart(domElement, chartProperties);
  const lineseries = chart.addLineSeries({
    color: "rgba(4, 111, 232, 1)",
    lineWidth: 2,
  });
  const linedata = await getData();
  //const linedata = [{time:"2022-08-02 11:20:20", value:1}, {time:"2022-08-10 15:30:30", value:6}];
  lineseries.setData(linedata);
};
displayChart();

but this will show nothing in the chart:

![image](https://user-images.githubusercontent.com/6703612/186804651-7658a771-ce38-46bd-8f81-1aceab771288.png)

if I setr data like this: const linedata = [{time:"2022-08-02 11:20:20", value:1}, {time:"2022-08-10 15:30:30", value:6}];
the time is not show:
![image](https://user-images.githubusercontent.com/6703612/186804853-071df910-417b-4aa1-b105-5cdf7b2d39d7.png)

anyone people can tell me why?

**Comment by SlicedSilver** [comment]
Here is a working example for your code: https://jsfiddle.net/msilverwood/mxjqgbaL/12/

Two main issues within the map function of `getData`:
- the value property is typed with a capital V. Should be: `value`, not `Value`.
- The string value for the time property isn't in a format which Lightweight charts supports. You can convert your timestamp to a valid `UTCTimestamp` by using this code: `(new Date(time)).valueOf() / 1000`. See the docs below for more information.

Docs:
https://tradingview.github.io/lightweight-charts/docs/next/api#time
https://tradingview.github.io/lightweight-charts/docs/next/api#utctimestamp
