### ISSUE TITLE
LineSeries is not displayed if starting x value is out of viewport

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#116]
![Screenshot 2019-07-10 at 22 19 36](https://user-images.githubusercontent.com/4056227/61005957-1cb09300-a361-11e9-9d43-0d8f3a0f38e4.png)

![Screenshot 2019-07-10 at 22 22 09](https://user-images.githubusercontent.com/4056227/61005990-2e923600-a361-11e9-8a41-1d5a269924c5.png)

You'll note the first line disappears as you zoom in and it goes just outside of the viewport, the second line will do the same when you zoom further.

Fiddle with full reference data: https://jsfiddle.net/jimeney/Lgtrhj52/9/

Steps to repeat: zoom out

**Comment by jimeney** [comment]
A second set of reference data, this time also causing an abnormal zoom state:

![Screenshot 2019-07-10 at 22 44 20](https://user-images.githubusercontent.com/4056227/61007262-4b7c3880-a364-11e9-8a6f-70982a263d72.png)

`{"c":[1.3006,1.30153,1.30072,1.30332,1.29998,1.30126,1.30088,1.29842,1.29579,1.29608,1.29494,1.29184,1.29053,1.29134,1.2914,1.28673,1.28421,1.28442,1.28364,1.27912,1.27975,1.27906,1.27824,1.27326,1.27188,1.27372,1.27448,1.27346,1.27231,1.27296,1.2695,1.2785,1.27056,1.27154,1.26631,1.26564,1.26613,1.26479,1.26255,1.26659,1.26585,1.26612,1.26889,1.26902,1.2713,1.27302,1.27062,1.268,1.26808,1.26731,1.2671,1.26746,1.26525,1.26585,1.26424,1.2631,1.26265,1.26273,1.2627,1.25889,1.26085,1.26124,1.2615,1.26016,1.26316,1.26544,1.26425,1.26298,1.26641,1.26678,1.26525,1.26756,1.26994,1.2704,1.27144,1.27324,1.26822,1.26879,1.26818,1.27142,1.26937,1.26948,1.27168,1.27586,1.27374,1.27232,1.26887,1.26898,1.26863,1.26836,1.27083,1.27189,1.27237,1.27166,1.27435,1.27246,1.26886,1.26918,1.26704,1.26852,1.2674,1.26737,1.26619,1.26076,1.259,1.25966,1.25884,1.25557,1.25338,1.25234,1.25331,1.25422,1.25576,1.25628,1.2569,1.26313,1.26422,1.26812,1.27116,1.27006,1.27042,1.2713,1.26758,1.26953,1.2744,1.2745,1.2755,1.2729,1.2725,1.2741,1.2746,1.27628,1.27195,1.26882,1.26864,1.2673,1.26788,1.2687,1.26845,1.26972,1.26753,1.26713,1.26712,1.26778,1.27272,1.26972,1.26984,1.2644,1.26517,1.26393,1.26408,1.26178,1.25944,1.25938,1.2591,1.2579,1.25634,1.25729,1.25788,1.25798,1.25754,1.25791,1.2582,1.25554,1.25046,1.2526,1.25222,1.25334,1.25142,1.25174,1.2509,1.24704,1.24653,1.24621,1.24544,1.24805,1.24968,1.25056,1.25069],"h":[1.3036,1.30188,1.30258,1.30475,1.30397,1.30128,1.30168,1.30408,1.2987,1.29705,1.29658,1.2964,1.29286,1.29138,1.29233,1.29188,1.28798,1.28506,1.28518,1.28432,1.28057,1.27992,1.27955,1.27828,1.27412,1.27418,1.27571,1.27554,1.27367,1.27354,1.27318,1.28142,1.27938,1.27193,1.27176,1.26777,1.26939,1.2666,1.26492,1.26711,1.26838,1.26687,1.26908,1.27181,1.27324,1.27353,1.27478,1.2709,1.26832,1.26834,1.27019,1.269,1.26789,1.26626,1.26654,1.26714,1.26327,1.26346,1.26408,1.26366,1.26201,1.26154,1.26282,1.2638,1.26448,1.26555,1.26606,1.26536,1.26742,1.26684,1.26868,1.27086,1.27147,1.2712,1.27239,1.27436,1.2733,1.26931,1.26964,1.27424,1.27248,1.27,1.27219,1.27612,1.2763,1.27428,1.27266,1.26986,1.27046,1.26931,1.2711,1.2728,1.27324,1.27274,1.2748,1.27586,1.27325,1.27006,1.26965,1.2708,1.26921,1.26818,1.26805,1.26619,1.26108,1.25981,1.2598,1.26056,1.25691,1.25442,1.2545,1.25433,1.25646,1.25696,1.25802,1.2635,1.26738,1.26873,1.2726,1.27273,1.27116,1.27246,1.27168,1.26984,1.27466,1.2745,1.27564,1.27666,1.27612,1.27464,1.2753,1.2784,1.27674,1.27256,1.26938,1.26881,1.27072,1.27009,1.2698,1.27074,1.27247,1.26848,1.26786,1.26874,1.27346,1.27306,1.27058,1.2701,1.26714,1.26539,1.26481,1.26458,1.26452,1.26166,1.26002,1.2595,1.25916,1.25824,1.25912,1.25884,1.2586,1.25876,1.25832,1.25875,1.25622,1.25308,1.2531,1.25392,1.254,1.25214,1.2523,1.25126,1.24772,1.24764,1.24688,1.2483,1.2521,1.25175,1.25092],"l":[1.30022,1.30031,1.29913,1.3005,1.29987,1.29936,1.29978,1.29838,1.29412,1.29428,1.29235,1.29086,1.29041,1.29045,1.28984,1.28264,1.28373,1.28421,1.2821,1.27879,1.27884,1.27825,1.27754,1.27318,1.27146,1.27188,1.27256,1.27217,1.27147,1.27231,1.26854,1.26856,1.26976,1.27015,1.26618,1.26244,1.26428,1.26469,1.26054,1.26228,1.2653,1.26545,1.26574,1.26476,1.26848,1.2713,1.2705,1.26674,1.26733,1.26688,1.2654,1.2655,1.26512,1.26506,1.2632,1.26265,1.26117,1.26218,1.26114,1.2581,1.25889,1.26054,1.25991,1.2559,1.25922,1.26289,1.26267,1.26106,1.26168,1.26585,1.26424,1.26504,1.26661,1.26957,1.26912,1.26961,1.26812,1.26822,1.2669,1.26767,1.26862,1.26889,1.2693,1.2702,1.27324,1.27104,1.26849,1.26532,1.26776,1.26774,1.26707,1.26924,1.27136,1.27154,1.27155,1.2716,1.26816,1.26867,1.26626,1.26654,1.26728,1.26716,1.26534,1.26014,1.25804,1.25808,1.25718,1.25544,1.25324,1.25124,1.25212,1.25062,1.25372,1.25535,1.25428,1.2567,1.26218,1.26328,1.26772,1.26718,1.26892,1.27032,1.26722,1.26428,1.26872,1.2744,1.27326,1.27232,1.27082,1.27147,1.2729,1.27404,1.27102,1.2672,1.26764,1.26628,1.26642,1.26741,1.26821,1.2669,1.26714,1.26618,1.26655,1.26654,1.26704,1.26877,1.26879,1.26402,1.26322,1.26321,1.26386,1.26126,1.25841,1.25909,1.25892,1.25572,1.25592,1.25587,1.25722,1.25689,1.25689,1.2574,1.25751,1.25498,1.24814,1.24982,1.2521,1.2512,1.25001,1.25002,1.2508,1.24582,1.24398,1.24465,1.24506,1.24438,1.24625,1.24914,1.25017],"nextTime":0,"o":[1.30194,1.3006,1.30153,1.30072,1.30332,1.29998,1.30126,1.30088,1.29842,1.29579,1.29608,1.29494,1.29184,1.29053,1.29134,1.2914,1.28673,1.28421,1.28442,1.28364,1.27912,1.27975,1.27906,1.27824,1.27326,1.27188,1.27372,1.27448,1.27346,1.27231,1.27296,1.2695,1.2785,1.27056,1.27154,1.26631,1.26564,1.26613,1.26479,1.26255,1.26659,1.26585,1.26612,1.26889,1.26902,1.2713,1.27302,1.27062,1.268,1.26808,1.26731,1.2671,1.26746,1.26525,1.26585,1.26424,1.2631,1.26265,1.26273,1.2627,1.25889,1.26085,1.26124,1.2615,1.26016,1.26316,1.26544,1.26425,1.26298,1.26641,1.26678,1.26525,1.26756,1.26994,1.2704,1.27144,1.27324,1.26822,1.26879,1.26818,1.27142,1.26937,1.26948,1.27168,1.27586,1.27374,1.27232,1.26887,1.26898,1.26863,1.26836,1.27083,1.27189,1.27237,1.27166,1.27435,1.27246,1.26886,1.26918,1.26704,1.26852,1.2674,1.26737,1.26619,1.26076,1.259,1.25966,1.25884,1.25557,1.25338,1.25234,1.25331,1.25422,1.25576,1.25628,1.2569,1.26313,1.26422,1.26812,1.27116,1.27006,1.27042,1.2713,1.26758,1.26953,1.2744,1.2745,1.2755,1.2729,1.2725,1.2741,1.2746,1.27628,1.27195,1.26882,1.26864,1.2673,1.26788,1.2687,1.26845,1.26972,1.26753,1.26713,1.26712,1.26778,1.27272,1.26972,1.26984,1.2644,1.26517,1.26393,1.26408,1.26178,1.25944,1.25938,1.2591,1.2579,1.25634,1.25729,1.25788,1.25798,1.25754,1.25791,1.2582,1.25554,1.25046,1.2526,1.25222,1.25334,1.25142,1.25174,1.2509,1.24704,1.24653,1.24621,1.24544,1.24805,1.24968,1.25056],"s":"ok","t":[1557414000,1557435600,1557457200,1557478800,1557500400,1557694800,1557716400,1557738000,1557759600,1557781200,1557802800,1557824400,1557846000,1557867600,1557889200,1557910800,1557932400,1557954000,1557975600,1557997200,1558018800,1558040400,1558062000,1558083600,1558105200,1558299600,1558321200,1558342800,1558364400,1558386000,1558407600,1558429200,1558450800,1558472400,1558494000,1558515600,1558537200,1558558800,1558580400,1558602000,1558623600,1558645200,1558666800,1558688400,1558710000,1558904400,1558926000,1558947600,1558969200,1558990800,1559012400,1559034000,1559055600,1559077200,1559098800,1559120400,1559142000,1559163600,1559185200,1559206800,1559228400,1559250000,1559271600,1559293200,1559314800,1559509200,1559530800,1559552400,1559574000,1559595600,1559617200,1559638800,1559660400,1559682000,1559703600,1559725200,1559746800,1559768400,1559790000,1559811600,1559833200,1559854800,1559876400,1559898000,1559919600,1560114000,1560135600,1560157200,1560178800,1560200400,1560222000,1560243600,1560265200,1560286800,1560308400,1560330000,1560351600,1560373200,1560394800,1560416400,1560438000,1560459600,1560481200,1560502800,1560524400,1560718800,1560740400,1560762000,1560783600,1560805200,1560826800,1560848400,1560870000,1560891600,1560913200,1560934800,1560956400,1560978000,1560999600,1561021200,1561042800,1561064400,1561086000,1561107600,1561129200,1561150800,1561323600,1561345200,1561366800,1561388400,1561410000,1561431600,1561453200,1561474800,1561496400,1561518000,1561539600,1561561200,1561582800,1561604400,1561626000,1561647600,1561669200,1561690800,1561712400,1561734000,1561928400,1561950000,1561971600,1561993200,1562014800,1562036400,1562058000,1562079600,1562101200,1562122800,1562144400,1562166000,1562187600,1562209200,1562230800,1562252400,1562274000,1562295600,1562317200,1562338800,1562533200,1562554800,1562576400,1562598000,1562619600,1562641200,1562662800,1562684400,1562706000,1562727600,1562749200,1562770800,1562792400],"v":[3695,3340,4138,5891,2735,967,2291,5584,3869,1367,2969,4877,2512,960,1887,7701,2627,906,2148,4286,2079,822,2703,5461,2756,1104,2314,3358,1589,826,2779,8886,7805,864,3683,5852,4670,1190,4209,7888,3537,1307,3123,9376,2780,767,2593,3102,691,719,5326,6226,2746,970,3126,6299,3072,772,2752,4694,2426,938,2702,8883,4037,947,3409,5840,4104,783,4004,9021,2975,908,3235,9148,3890,752,2794,11976,4341,845,2748,8557,3379,1165,2865,5648,3010,949,3382,7815,3343,1101,2849,8790,4509,1057,2991,6607,2507,723,2866,8515,3141,871,1818,3811,2655,1041,4196,6470,3710,1027,2464,4682,8336,1952,4549,9018,4198,1096,4392,6741,4482,1,2012,2199,5123,2550,1106,3245,5243,6325,1841,3276,6904,3809,1321,3130,5891,3427,2118,2326,5838,4388,1423,3427,6201,3008,902,2906,6480,3548,838,2767,5458,2021,667,1660,2532,3354,505,1925,6897,2607,581,1732,3327,1734,492,2609,4689,2583,843,2369,6634,3874,66]}`

`{"SupportsResistances":[1.27571039328939,1.26267042756154,1.26618914847223,1.25646092007209],"TrendLines":[{"xe":1562792400,"xs":1561734000,"ye":1.25108406,"ys":1.27306},{"xe":1562792400,"xs":1559293200,"ye":1.24325,"ys":1.2559}]}`

**Comment by timocov** [comment]
Hm, interesting usage of the line series (as a trend line drawing).

As quick fix we can draw 2 points outside of the viewport for a line series, but we need to be careful - it may reduce the performance (because that points might have a huge coordinates away of the viewport).

**Comment by jimeney** [comment]
From my perspective, the trendline will always be within 500 datapoints, as this is as far back as the data would be expected to show. It's a workaround to not having systematic drawing tools. 

They would only ever have a start and end, no intermediate points so performance-wise I don't expect it to have too much of an effect, I suppose I could get the lowest unixtime in the viewport, then calculate the x/y value at that point in the slope.

**Comment by jimeney** [comment]
the same also applies if the closing x value is outside of viewport when scrolling back
