### ISSUE TITLE
Price lines, show behind chart series

### ISSUE THREAD

**Issue by qwazix** [tradingview/lightweight-charts#1169]
While in the [demo page](https://www.tradingview.com/lightweight-charts/) the price lines show in front of the chart area,
![image](https://user-images.githubusercontent.com/1202892/191270520-840a32b1-1928-473a-923a-42323221d7c9.png)

actually using the code (including the actual example in the fiddle [linked](https://jsfiddle.net/TradingView/fz4v5ouq/ by the above page)
![image](https://user-images.githubusercontent.com/1202892/191270661-fd6a38aa-765d-411f-be08-1fec1baf667c.png) the lines show behind the series.

This is especially problematic when the area has a fill as the price line can be completely hidden.

![image](https://user-images.githubusercontent.com/1202892/191275445-6a7f7ab2-0f8e-44ba-a88c-42704c24f306.png)

**Comment by SlicedSilver** [comment]
Thanks for reporting this issue. 

It is a known bug which has been fixed on the master branch but has not been released yet (will be in v4.0.0). 
See this issue for more information: #1120 

If you need the fix before it is released then you can clone this repo and build the library off the master branch. You could then use the pre-release version within the dist folder.
