### ISSUE TITLE
What is wrong with the timestamps?

### ISSUE THREAD

**Issue by apaulo** [tradingview/lightweight-charts#1170]
Hi, everyone

I am going crazy with this one.
When I try to use the following data for candlestick charts 
`[`
`{time: 1663723800, open: 75.16, high: 82.84, low: 36.16, close: 45.72},`
`{time: 1663722900, open: 45.12, high: 53.90, low: 45.12, close: 48.09},`
`{time: 1663722000, open: 60.71, high: 60.71, low: 53.39, close: 59.29}`
`]`
..I get 
> Uncaught Error: Value is null

Now, if I use
`[`
`{time: 1642427876, open: 75.16, high: 82.84, low: 36.16, close: 45.72},`
`{time: 1642514276, open: 45.12, high: 53.90, low: 45.12, close: 48.09},`
`{time: 1642600676, open: 60.71, high: 60.71, low: 53.39, close: 59.29}`
`]`
...it works fine!!!

The data is exactly the same, I only replaced the timestamps with the ones from an example provided by TradingView.
The error is on the timestamps, but I do not understand why.

Many thanks on any tips on why this is happening and how to solve it.

All the best!

**Comment by SlicedSilver** [comment]
Lightweight Charts expects that the data be: `Ordered (earlier time point goes first) array of data items.`
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#parameters-4

The issue with the data you are providing is that the time values aren't increasing for each subsequent data point. If you reverse the order of the data points then it will work correctly.
