### ISSUE TITLE
Error apply scaleMargins customs

### ISSUE THREAD

**Issue by julio899** [tradingview/lightweight-charts#1188]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
# references 
https://github.com/tradingview/lightweight-charts/blob/v2.0.0/docs/customization.md#price-axis
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceScaleOptions

Error runing oficial example
```js
chart.priceScale('right').applyOptions({
    scaleMargins: {
        top: 0.8,
        bottom: 0,
    },
});
```

**Actual behavior:**

**Expected behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/2575745/198154252-53e6fed7-9966-4d97-95af-3d6d93a3bdc3.png)
![image](https://user-images.githubusercontent.com/2575745/198154409-2498002b-7743-4a18-8d41-d5e9404effa9.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
I've created a JSFiddle to test this and it appears to be working: https://jsfiddle.net/msilverwood/os7dj8u0/

Could you please see if you can modify the JSFiddle to reproduce your error?

**Comment by SlicedSilver** [comment]
The API for applying scaleMargins has changed since v3.8.

If you are using a newer release (such as 4.0 or master) then you need to apply the scaleMargins options to the priceScale returned by the series.
```js
series.priceScale().applyOptions({
  scaleMargins: {
     top: 1,
    bottom:0.8,
  },
});
```

On an earlier version of the library then you can apply apply these options to the chart options.

**Comment by julio899** [comment]
> The API for applying scaleMargins has changed since v3.8.
> 
> If you are using a newer release (such as 4.0 or master) then you need to apply the scaleMargins options to the priceScale returned by the series.
> 
> ```js
> series.priceScale().applyOptions({
>   scaleMargins: {
>      top: 1,
>     bottom:0.8,
>   },
> });
> ```
> 
> On an earlier version of the library then you can apply apply these options to the chart options.

thanks @SlicedSilver
