### ISSUE TITLE
how to handle timezone and dst?

### ISSUE THREAD

**Issue by davidxiao** [tradingview/lightweight-charts#1189]
hi, 
  I am having issue to display the data, saying:

`
data must be asc ordered by time, index=3178, time=1648951200, prev time=1648953900
`

I am using time `corrected` with my local timezone.

this seems resulted from the DST as I checked, in my case, `2022-04-03T02:00:00Z` is the saving hour, meaning `2022-04-03T02:00:00Z` will come before DST, and will come again after DST. so there will be 2 candles with the same opentime,

I was thinking we can use UTC time in data, but display the time with timezone in axis, maybe i am not right?

I checked https://github.com/tradingview/lightweight-charts/blob/v3.7.0/docs/time-zones.md

this similar ticket [184](https://github.com/tradingview/lightweight-charts/issues/184)

but not find a solution.

so, wonder what's proper way to handle this? can you pls advise @timocov ?

Thanks

**Comment by SlicedSilver** [comment]
The library requires that the each data point in a series has a unique time value. If there is a duplicate then it will throw out an error message. The best approach is to use unix timestamps for the data and ensure that there are no duplicates.. 

If you are modifying the timestamps before giving the data to the library then when the clocks go back, this will result in their being two data points with the same timestamp (for hour candles or smaller).

You can control what is displayed within the crosshair label on the time scale by specifying a custom timeFormater. Which takes the timestamp as the input and should return a string. (https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LocalizationOptions#timeformatter)

```javascript
chart.applyOptions({
  localization: {
          timeFormatter: (timestamp) => {
               return new Date(timestamp * 1000).toLocaleString('en-GB');
          }
     }
});  
```

Depending on how you would like to handle the 'duplicate' candle is up to you. You could merge the two overlapping candles, or have two candles on the chart which have the same date displayed on the time scale.

JSFiddle example: https://jsfiddle.net/msilverwood/0mjx5nac/

**Comment by davidxiao** [comment]
thanks, mate
