### ISSUE TITLE
Hide line series price and circles

### ISSUE THREAD

**Issue by Vimiso** [tradingview/lightweight-charts#1190]
<img width="245" alt="Screenshot 2022-10-27 at 21 43 55" src="https://user-images.githubusercontent.com/23698496/198394428-55e634a9-bc99-4e99-ae99-4d813357581f.png">
Take the given screenshot, I can't seem to locate in the docs a way in getting rid of the y-axis price labels for the drawn lines (using line series). Additionally, is it possible to hide the circles on each line shown when hovering?

**Comment by SlicedSilver** [comment]
- You can hide the price label for the last value of each series with this option: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#lastvaluevisible 
- and you can hide the crosshair markers for each line with this option: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LineStyleOptions#crosshairmarkervisible
- if you are creating price lines then you can hide the price labels using this option: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceLineOptions#axislabelvisible 

FYI: https://tradingview.github.io/lightweight-charts/tutorials/customization/chart-colors#applying-options

**Comment by Vimiso** [comment]
Legend, how I missed those, I don't know.
