### ISSUE TITLE
different line color depending if ascending or decending.

### ISSUE THREAD

**Issue by MPdaedalus** [tradingview/lightweight-charts#1193]
Hi 

Can you add the ability to have a different line color for the line Series depending on if the line is ascending/descending ie, if previous value less than or greater than current value.

Other chart software like metatrader has had it for ages and it would really help to signal changes graphically.

Many thanks

**Comment by SlicedSilver** [comment]
It is possible to set the line colour for any data point which overrides the series line colour for that part of the line. You can use this to achieve the effect that you are looking for.

Here is a JSFiddle example: https://jsfiddle.net/msilverwood/rnLtp1o7/

Example of how to modify existing data to achieve the line colouring.
```javascript
const data = generateSampleLineData();
for (let i = 0; i < data.length; i++) {
	if (i == 0) continue;
	const smaller = data[i].value < data[i-1].value;
	data[i].color = smaller ? 'red' : 'green';
}

lineSeries.setData(data);
```
