### ISSUE TITLE
Set The `priceFormat` option to each series, it works on the first serie only

### ISSUE THREAD

**Issue by Sakchai-Refinitiv** [tradingview/lightweight-charts#1195]
**Lightweight Charts Version:** v3.8.0

**Steps/code to reproduce:**

```js
const formatters = {
  dollar: {
    formatter: function(price) { return '$' + price  },
    type: 'custom'
  },
  baht: {
    formatter: function(price) { return '฿' + price  },
    type: 'custom'
  }
};

// Set price formatter to each series
const areaSeries = chart.addAreaSeries({
  priceFormat: formatters.dollar, // It works. ($)
});

const areaSeries2 = chart.addAreaSeries({
  priceFormat: formatters.baht, // It does not work. (฿)
});
```

**Actual behavior:**
Set The `priceFormat` option to each series, it works on the first series only

**Expected behavior:**
Set The `priceFormat` option to each series, it should work in each series individually

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/sc_lseg/v5yt1wc4/7/

**Comment by SlicedSilver** [comment]
Conceptually the library is designed such that a single price scale should only represent a single 'currency'. In a sense it wouldn't make sense for both currencies to share a price scale unless a `฿` is exactly equal to a `$`.

You can rather use a second price scale on the left to represent the second currency. Here is an example: https://jsfiddle.net/msilverwood/q08tfugs/ 

Alternatively you could put the second series on an `overlay` price scale, it will show the price correctly formatted. However, the price will only be visible for things like the last price, and the crosshair won't show the values for the overlay on the existing price scale.

**Comment by Sakchai-Refinitiv** [comment]
Thank you for your explanation.
