### ISSUE TITLE
Custom font not loading

### ISSUE THREAD

**Issue by sushanyadav** [tradingview/lightweight-charts#1197]
**Lightweight Charts Version:** ^3.8.0

**Actual behavior:**
I specified my custom font as fontFamily on LayoutOptions but font is defaulted to Times New Roman.

**Expected behavior:**
I specified the font family on LayoutOptions but font is not loading.

**Screenshots:**
![CleanShot 2022-11-07 at 7 53 27](https://user-images.githubusercontent.com/53527664/200330537-76633e90-d596-4d23-93ab-6fce116a8e3d.png)

**CodeSandbox/JSFiddle/etc link:**
https://stackblitz.com/edit/nextjs-tynysx?file=styles%2Fglobals.css,components%2FChart%2Fconfig.js

**Comment by SlicedSilver** [comment]
Here is a working example on JSFiddle: https://jsfiddle.net/msilverwood/ynm5u4kh/

It's important that you only set the `fontFamily` once the font has been loaded by the browser. If it is set before it is loaded then the chart will not be able to use the font when rendering any text. If you have disabled scrolling and scaling then there won't be any need for the library to redrawn these bits of text and they will therefore remain as the fallback font.

**Comment by sushanyadav** [comment]
> 

Sorry but how we usually do this on next JS? Can you help me with the sandbox I mentioned. thank you.
