### ISSUE TITLE
Chart with whitespaces shifts on realtime

### ISSUE THREAD

**Issue by eugene-korobko** [tradingview/lightweight-charts#1201]
**Lightweight Charts Version:** 4.0.0

**Steps/code to reproduce:**

Open attached sample, wait for 6 seconds

**Actual behavior:**

red series shifts to the left

**Expected behavior:**

res series should keep its place

Additionally:

if replace whitespaces with some values

**Comment by eugene-korobko** [comment]
[debug.zip](https://github.com/tradingview/lightweight-charts/files/10065135/debug.zip)

**Comment by pedro-lucaas** [comment]
@eugene-korobko hey, i believe that this not is a bug.

[Documentaion createChart](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#shiftvisiblerangeonnewbar)

This link you can see the chart option timeScale.
In it is possible to set this behavior to false, through the option "shiftVisibleRangeOnNewBar"

Look
![image](https://user-images.githubusercontent.com/74577150/229906638-137416d1-15d9-45cc-bf6f-9454475a8ec2.png)
