### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getContext')

### ISSUE THREAD

**Issue by valentinbegnis** [tradingview/lightweight-charts#1206]
Hello, I think I'm facing the same problem mentioned here: https://github.com/tradingview/lightweight-charts/issues/638  

**Lightweight Charts Version: 3.8.0**

I'm trying to build a trading bot using React.js with Vite.js.
My app works fine but every time I save (it doesn't matter what change I make) I get this exception:

```
Uncaught TypeError: Cannot read lightweight-charts.esm.production.js:7 properties of null (reading 'getContext')
    at Mn (lightweight-charts.esm.production.js:7:94572)
    at t.R_ (lightweight-charts.esm.production.js:7:126695)
    at t.R_ (lightweight-charts.esm.production.js:7:131833)
    at t.Aw (lightweight-charts.esm.production.js:7:134449)
    at lightweight-charts.esm.production.js:7:135004
```
 
**My code (I'm getting historical data  from my backend as well as live candlestick data using WebSockets):**

``` js
const socket = io('http://localhost:3000');

export const Chart = () => {
  const [rsiValue, setRsiValue] = useState(0);
  const chartContainer = useRef();

  useEffect(() => {
    const chart = createChart(chartContainer.current, {
      width: 600,
      height: 400,
      priceScale: {
        scaleMargins: {
          top: 0.2,
          bottom: 0.3,
        }
      },
      layout: {
        background: { color: '#222' },
        textColor: '#DDD',
      },
      grid: {
        vertLines: { color: 'rgba(68, 68, 68, .4)' },
        horzLines: { color: 'rgba(68, 68, 68, .4)' },
      },
      crosshair: {
        mode: CrosshairMode.Normal
      },
    });

    chart.priceScale().applyOptions({ borderColor: '#444' });
    chart.timeScale().applyOptions({ borderColor: '#444', timeVisible: true });

    const candlesticksSeries = chart.addCandlestickSeries({
      priceFormat: {
        type: 'price',
        minMove: 0.0001,
        precision: 4,
      },
      autoScale: false
    });

    const volumeSeries = chart.addHistogramSeries({
      color: 'rgba(168, 168, 168, .5)',
      lineWidth: 2,
      priceFormat: {
        type: 'volume',
      },
      overlay: true,
      scaleMargins: {
        top: 0.95,
        bottom: 0,
      },
    });

    fetch('http://localhost:3000/candlesticks')
      .then(res => res.json())
      .then(data => {
        candlesticksSeries.setData(data.results.map(candlestick => ({
          time: candlestick.openTime / 1000,
          open: candlestick.open,
          high: candlestick.high,
          low: candlestick.low,
          close: candlestick.close
        })));

        volumeSeries.setData(data.results.map(candlestick => ({
          time: candlestick.openTime / 1000,
          value: candlestick.volume
        })))
      });

    chart.timeScale().fitContent();

    const liveCandlestickData = candlestick => {
      candlesticksSeries.update({
        time: candlestick.startTime / 1000,
        open: candlestick.open,
        high: candlestick.high,
        low: candlestick.low,
        close: candlestick.close
      });

      volumeSeries.update({
        time: candlestick.startTime / 1000,
        value: candlestick.volume
      })
    }

    const handleRsi = rsiData => {
      setRsiValue(rsiData);
    }

    socket.on('candlestick-live-data', candlestick => liveCandlestickData(candlestick));
    socket.on('rsi-live-data', rsiData => handleRsi(rsiData));

    return () => {
      chart.remove();
      socket.off('candlestick-live-data', candlestick => liveCandlestickData(candlestick));
      socket.off('rsi-live-data', rsiData => handleRsi(rsiData));
    }
  }, []);

  return (
    <>
      <div className='relative' ref={chartContainer}>
        <span className='absolute z-10 left-2 top-1'>MATICUSDTPERP - 5m - BINANCE</span>
      </div>
      <div className='flex justify-between p-2'>
        <div>
          <span className='text-sm'>RSI: {rsiValue.toFixed(2)}</span>
        </div>
        <ClockUTC />
      </div>
    </>
  )
```

I think I might be using wrong the remove() method inside the return of the useEffect but I can't find a way to fix it yet.

**Screenshots:**  

![Captura de pantalla de 2022-11-25 10-16-38](https://user-images.githubusercontent.com/66221714/203993777-cc97c430-b385-4788-9aa5-1cea657a1df0.png)

Please, let me know if you need more info, this is my first time opening an issue on github. Thank you in advance.

**Comment by SlicedSilver** [comment]
Hi Valentín

It is correct to use `chart.remove()` when you want to clean up and prevent memory leaks.

We have a React example on our documentation page which might assist:
https://tradingview.github.io/lightweight-charts/tutorials/react/simple

and a more advanced example which has updating data:
https://tradingview.github.io/lightweight-charts/tutorials/react/advanced

Let me know if this helps you find your issue, if not then please provide another update on this GitHub issue and we will try assist you further.

**Comment by valentinbegnis** [comment]
> Hi Valentín
> 
> It is correct to use `chart.remove()` when you want to clean up and prevent memory leaks.
> 
> We have a React example on our documentation page which might assist: https://tradingview.github.io/lightweight-charts/tutorials/react/simple
> 
> and a more advanced example which has updating data: https://tradingview.github.io/lightweight-charts/tutorials/react/advanced
> 
> Let me know if this helps you find your issue, if not then please provide another update on this GitHub issue and we will try assist you further.

Thank you very much for your reply, the advanced example helped me a lot with my problem!
