### ISSUE TITLE
Suspense Boundaries when importing Chart throws "Error: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by AlexLup06** [tradingview/lightweight-charts#1215]
**Lightweight Charts Version:** 3.8.0

**Steps/code to reproduce:**
I am using nextjs 13 and all the code in the Chart Component is written in useEffect boundaries. I am just gonna include all code.

```
**##TradingPage.js**
const Chart = dynamic(() => import("./trading/TraidingChart"), {
    suspense: true,
    ssr: false,
});

export default function Test(){
     <Suspense fallback={<div>Loading...</div>}>
          <Chart />
     </Suspense>
}

**##TradingChart.js**
import { createChart, IChartApi } from 'lightweight-charts';
import { useEffect, useRef } from 'react';
import styles from './css/Chart.module.scss';

export default function Chart() {

    const chartContainer = useRef<HTMLDivElement>();
    const chart = useRef<IChartApi>()

    useEffect(() => {
        const getData = async () => {
            const data = await fetch(`/api/collection/getChartData?data=dayData`).then((res) => res.json())

            chart.current = createChart(chartContainer.current, {
                crosshair: {
                    mode: 0,
                }
            });

            const candleSeries = chart.current.addCandlestickSeries();

            candleSeries.setData(data.result);
        }
        getData()

        return () => chart.current.remove()
    }, []);
    
    return (
        <div className={styles.chart_container}>
            <div className={"h-sctn"}>
                Floor Price
            </div>
            <div ref={chartContainer} className={styles.chart + " sctn"} />
        </div>

    );
}
```

**Actual behavior:**

I get an Unhandled Runtime Error. "Error: Cannot use import statement outside a module"

### **Full Error stack:**
Uncaught Error: Cannot use import statement outside a module
    at updateDehydratedSuspenseComponent (react-dom.development.js?ac89:20662:1)
    at updateSuspenseComponent (react-dom.development.js?ac89:20362:1)
    at beginWork (react-dom.development.js?ac89:21624:1)
    at beginWork$1 (react-dom.development.js?ac89:27426:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)

**Expected behavior:**

Show the loading state and after chart loads, show chart

**Comment by SlicedSilver** [comment]
See #1240 
 Try changing the "type" of your package.json to "module" or adjust your bundler / typescript options.
