### ISSUE TITLE
Ability to adjust default zoom level as used by resetTimeScale()

### ISSUE THREAD

**Issue by tasteitslight** [tradingview/lightweight-charts#1217]
**Is your feature request related to a problem? Please describe.**

We are customizing the visible range on page load to the viewport size and device type (desktop/touch). Currently, we are unable to customize the default zoom used by resetTimeScale (when double clicking time scale).

**Describe the solution you'd like**

A new property for TimeScaleOptions: defaultZoom

**Comment by SlicedSilver** [comment]
The default zoom is determined by the [`barSpacing`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#barspacing) property of the time scale options. 

You can calculate what the barSpacing is for the current state of a chart by using the [`getVisibleLogicalRange`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#getvisiblelogicalrange) method on the time scale API and the `width` of the time scale.

For example:
```js
const visibleLogicalRange = chart.timeScale().getVisibleLogicalRange();
const currentBarSpacing = chart.timeScale().width() / (visibleLogicalRange.to - visibleLogicalRange.from);

// change the current barSpacing
chart.timeScale().applyOptions({
  barSpacing: 12, // default is 6
})
```
