### ISSUE TITLE
Market time Timezone

### ISSUE THREAD

**Issue by chrispeterson3** [tradingview/lightweight-charts#1218]
I am trying to get U.S. market times to show on a chart. I have tried both of these solutions:
[date-solution](https://github.com/tradingview/lightweight-charts/blob/7104e9a4fb399f18db7a2868a91b3246014c4324/docs/time-zones.md#date-solution)
[date-fns-tz-solution](https://github.com/tradingview/lightweight-charts/blob/7104e9a4fb399f18db7a2868a91b3246014c4324/docs/time-zones.md#date-fns-tz-solution)

My chart keeps rendering with a +7 hour time difference. Has anyone experienced this issue?

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/2593324/206374622-50e92cf0-db84-4888-9fb0-3d55b0d8a97a.png">

**Comment by SlicedSilver** [comment]
Timezones are discussed in more detail here: https://tradingview.github.io/lightweight-charts/docs/time-zones

The easiest way to change what is displayed is to adjust the data before it is given to the chart. You could manually add or subtract the 7 hours from the timestamp for each data point.

There are also formatters which you can use to customise:
- The time displayed on the time axis: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#tickmarkformatter
- The time displayed on crosshair label: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LocalizationOptions#timeformatter
