### ISSUE TITLE
Price Axis Scaling Bug

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#122]
It appears there's an intermittent, but repeatable issue with price axis scaling.

Renders correctly
https://www.chartex.pro/chartviewerstatic-debug.html?symbol=BINANCE:ALGO/USDT&trendlines=1&supports=1&timeframe=60&w=1600&h=800&barstoshow=500

![Screenshot 2019-07-12 at 00 33 03](https://user-images.githubusercontent.com/4056227/61092078-a6815e80-a43c-11e9-81d2-c6221a20b429.png)

Axis scaling fails
https://www.chartex.pro/chartviewerstatic-debug.html?symbol=OANDA:EUR/GBP&trendlines=1&supports=1&timeframe=60&w=1600&h=800&barstoshow=500

**Comment by timocov** [comment]
It's a bug, we'll fix it soon.

**Comment by jimeney** [comment]
Wonderful, thank you - other than some minor niggles, real kudos, this is a solid library, hugely useful to me (I'm a current (soon to be ex!) user of the full TradingView Javascript library)
