### ISSUE TITLE
Having issue removing multiple series

### ISSUE THREAD

**Issue by lovepareek** [tradingview/lightweight-charts#1231]
Hello, I'm using a lightweight chart to display several data points in various series. When I want to delete the series for the same time period, however, the system encounters the problem indicated in the below image. nonetheless, it worked flawlessly when I tried to delete the series over a different time period, so could you perhaps assist me to identify the problem I'm having?

1. First Image of multiple series at the same time
[Multiple series](https://imgur.com/a/Ax7ps6i)

2. Error occurring during removing at same time
[Error image](https://imgur.com/a/DjB4jRi)

How my code works:--
First, when I simultaneously add a new series to the chart, I'll construct an object with the timestamp value and push it to the array. After my process is finished, I'll eliminate many lines by comparing the amount of time I have left with some of my fundamental reasoning using the `chart.removeSeries(chart>)` function. Here is the code: —

`  socket.on(socketName, (socketData1) => {
  if (arrSome.length > 0 && typeof arrSome != "undefined") {
    for (let j = 0; j < arrSome.length; j++) {
      const element = arrSome[j].chart;
      const timeToRemove = arrSome[j].time;
      const unixTime = Math.floor(Date.now() / 1000) + 19080;
      if (unixTime == timeToRemove) {
        chart.removeSeries(element);
        socket.emit("removeInterval");
      }
    }
    if (arrSome.length > 0) {
      let newData = arrSome.shift();
      console.log("newData", newData, arrSome);
    }
  }
})`

I am using javascript for my base langauge

Thanks in advance

**Comment by LovePareek** [comment]
Any Update????

**Comment by SlicedSilver** [comment]
I'm fully certain what you are trying to achieve with your code, and how you are trying to remove the series.

I've created a working example which I think covers your use case: https://glitch.com/edit/#!/helix-dune-nigella

Could you please create a similar example reproducing your problem so we can check the code and determine the issue?
