### ISSUE TITLE
Using Lightweight-charts, how to draw session breaks

### ISSUE THREAD

**Issue by ajiratech2** [tradingview/lightweight-charts#1233]
I'm able to use lightweight charts to draw candlesticks and volume. I'm also able to use the line series. How can I add Session breaks vertical line to visually separate days ?

**Comment by SlicedSilver** [comment]
It is currently not possible to draw a vertical line with the library. Below is a list of related issues. Please add any further suggestions or use cases to those issues.

Duplicate of https://github.com/tradingview/lightweight-charts/issues/128, https://github.com/tradingview/lightweight-charts/issues/127, #693, and https://github.com/tradingview/lightweight-charts/issues/965. Please post your suggestion there.
