### ISSUE TITLE
Chart displays as blurry on Electron 22.0.2

### ISSUE THREAD

**Issue by treeoflife111** [tradingview/lightweight-charts#1244]
**Lightweight Charts Version:** latest

**Steps/code to reproduce:**

- displaying lightweight-chart in a Electron app

```jsx
useEffect(() => {
    const chart = createChart(chartContainer.current, {
      width: 700,
      height: 300,
      layout: {
        background: { type: "solid", color: "white" },
        textColor: "rgb(18, 22, 34)",
        fontFamily: "Roboto",
        fontSize: 13,
      },
      grid: {
        vertLines: {
          visible: true,
          color: "rgb(230, 230, 230)",
        },
        horzLines: {
          color: "rgb(230, 230, 230)",
        },
      },
      crosshair: {
        mode: CrosshairMode.Normal,
      },

      rightPriceScale: {
        borderColor: "white",
        visible: true,
      },
      timeScale: {
        borderColor: "white",
        timeVisible: true,
        secondsVisible: false,

        rightOffset: 30,
        barSpacing: 5,
      },
    });

return (
      div ref={chartContainer} className="chart-container" 
)
```

**Actual behavior:**

The chart displays as blurry or with a lot of aliasing, text isnt sharp compared to the rest of the page.
cf my screenshot (price and time scale mostly)
I tried multiple fonts, font sizes but nothing changes. When i try the code elsewhere like JSfiddle it seems to display normal so it's probably some interaction with electron and lightweight charts

**Expected behavior:**

Chart should display clear and sharp

**Screenshots:**

![image](https://user-images.githubusercontent.com/122037688/213243955-6e9bd6d1-221d-489d-bebc-bc1b8ed55432.png)

**Comment by SlicedSilver** [comment]
@treeoflife111 Did you manage to resolve the issue?

If so, would it be possible to share what change you needed to make so that if someone else has a similar problem in the future then there will be an answer 🙂

**Comment by treeoflife111** [comment]
Yes just resolved it, this happens when the parent div of the createChart useref is not the exact same height and width (here 700 and 300) so it's not electron related just be careful when you create the container

**Comment by SlicedSilver** [comment]
Thanks for the response :)
Our next version of the library includes an `autoSize` option which will make the chart automatically fit a parent element correctly. So hopefully this will be easier in the near future.
