### ISSUE TITLE
Getting the wrong candle color for my lightweight charts

### ISSUE THREAD

**Issue by yulz008** [tradingview/lightweight-charts#1246]
**Lightweight Charts Version:** 

Hi tradingview,

I would like to ask for your support, although overall chart displays the correct color for "up" and "down" candle,  sometimes i'm getting this wrong candle color for some coins/charts, which causes misleading information. (see attached image)

**Images**
APTUSDT
![image](https://user-images.githubusercontent.com/117939069/213948926-6f4f6d22-9963-42b5-bd8c-528ed416152d.png)

AXSUSDT
![image](https://user-images.githubusercontent.com/117939069/213949241-3be59ab0-3697-41d0-a7f9-5da98ae09def.png)

What i've tried so far:
-reset the candleseries object before loading new data.
-reset the chart scale before and after loading the data.
-i've tried to swap the open and close value for the affected candle, the chart gave me the correct color (hardcoded). This shows that the lightweight charts misread the data for some candles and swaps it (Open-> close and vv).

Any thoughts?

**Comment by SlicedSilver** [comment]
The interface for OHLCData specifies that the price values should be `number`, not `string`. Could you try changing the type of the price values? [documentation link](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/OhlcData)

Additionally, the colour of a candle can be overridden by colour properties inside the data point. This is unlikely to be your problem but worth checking anyway. Discussed here: [documentation link](https://tradingview.github.io/lightweight-charts/tutorials/customization/data-points)

If there is still an issue then would be be possible to share the data, or create a small example showing the bug on JSFiddle, or similar?
