### ISSUE TITLE
How to draw top to bottom Volume bar graph 

### ISSUE THREAD

**Issue by satyam-systango** [tradingview/lightweight-charts#1247]
<img width="614" alt="213751154-8d2a11f3-2ebf-489c-84ba-7a1960d90114" src="https://user-images.githubusercontent.com/77108993/214009106-781715b4-0284-400c-839c-12116d9489b5.png">

Like this 
Can any one please send me code sandbox ?

**Comment by romfrancois** [comment]
Hi @satyam-systango !

Have a look at this [example](https://jsfiddle.net/romainfrancois/veqpa5d8/).

Basically you would need to negate all values for volume and then use a formatter for the price on the price scale to not reflect a negative value but a positive one.
