### ISSUE TITLE
Price Line Placement

### ISSUE THREAD

**Issue by amolpatel** [tradingview/lightweight-charts#1249]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/6493663/214615647-ba8bc54d-dc18-4562-806c-1c3205596183.png">

Is there anyway to get the price line to be at the median of prices?

**Comment by amolpatel** [comment]
SOLVED:

Use `scaleMargins`

**Comment by SlicedSilver** [comment]
You can disable the visibility of the default price line using the options for that series. [Documentation link](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon)

You could then create your own price line at any value using the `createPriceLine` method on the series instance. [Documentation link](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#createpriceline)

Similar guide: https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-line
