### ISSUE TITLE
How can I set the timezone?

### ISSUE THREAD

**Issue by meadiven** [tradingview/lightweight-charts#125]
Hello!
My series data like the following json:
[{time: 1559931660, open: 154.945, close: 154.9, high: 154.955, low: 154.9},
{time: 1559931720, open: 154.89, close: 154.94, high: 154.96, low: 154.89},
{time: 1559931780, open: 154.92, close: 154.95, high: 154.96, low: 154.905},
{time: 1559931840, open: 154.94, close: 154.955, high: 154.97, low: 154.94},
{time: 1559931900, open: 154.96, close: 154.955, high: 154.97, low: 154.92}]
The charts shows UTC time on the time axis.
How can I set the timezone to Beijing time?

**Comment by timocov** [comment]
We don't support Timezones out of the box.

I would suggest you provide custom [timeFormatter](https://github.com/tradingview/lightweight-charts/blob/a460384e6df6f24d12ae52e01eddd709120b4e9e/src/model/localization-options.ts#L20-L23) (sorry, we don't have docs for that property yet, we'll add it soon) and format dates as you wish.

Also, you can try to modify dates of your dataset via adding timezone's offset for each data item.

**Comment by timocov** [comment]
I'm going to close this issue. If you'll have any updates - feel free to reopen it.

**Comment by viveksudani** [comment]
Is there any update on this?
Can I set timezone now?

**Comment by timocov** [comment]
See #643, I think it's better to share your thoughts there.
