### ISSUE TITLE
Hide right price scale but show cross hair price

### ISSUE THREAD

**Issue by amolpatel** [tradingview/lightweight-charts#1250]
Is it possible to show the cross hair with price but hide the right price scale?

<img width="567" alt="image" src="https://user-images.githubusercontent.com/6493663/214619299-11d18e21-ce7d-4fd3-9f48-73e200c0c640.png">

**Comment by SlicedSilver** [comment]
There are some examples here: https://tradingview.github.io/lightweight-charts/tutorials#how-to--examples
Might want to look at the `tooltips` example. 

[Price scale Id](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#pricescaleid) could be set to `''` if you want it to be an overlay (i.e not have a visible price scale) [more info](https://tradingview.github.io/lightweight-charts/docs/migrations/from-v2-to-v3#creating-overlay)
