### ISSUE TITLE
Vertical scaling not working when `priceScaleId` is set

### ISSUE THREAD

**Issue by jussirantala** [tradingview/lightweight-charts#1254]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

1. Add candleSeries with `priceScaleId` property
2. Try to vertically zoom in/out by dragging the y-axis 

**Actual behavior:**

Nothing happens even though you see the pointer cursor

**Expected behavior:**

Chart is scaled vertically like it is without `priceScaleId`.

**Comment by SlicedSilver** [comment]
What value are you setting for the `priceScaleId` property and which version of the library are you using?

It appears to be working when I test it.
Could you perhaps make your changes on this [jsFiddle](https://jsfiddle.net/msilverwood/mhz3urq8/) so that we can have a reproducible example of the issue?

jsFiddle link: https://jsfiddle.net/msilverwood/mhz3urq8/

**Comment by jussirantala** [comment]
> What value are you setting for the `priceScaleId` property and which version of the library are you using?
> 
> It appears to be working when I test it. Could you perhaps make your changes on this [jsFiddle](https://jsfiddle.net/msilverwood/mhz3urq8/) so that we can have a reproducible example of the issue?
> 
> jsFiddle link: https://jsfiddle.net/msilverwood/mhz3urq8/

https://jsfiddle.net/2u0njz38/

It seems you also need to add second series for it to happen in addition to what I mentioned. That also makes the axis tick labels disappear.

**Comment by SlicedSilver** [comment]
You need to have at least one series which has a `priceScaleId` of either `left` or `right`.
If you only have 'overlay' price scales (where the id is something different than `left` or `right`) then there isn't actually a price scale created.

If you have two series which should be plotted on the same scale then set the `priceScaleId` to either `left` or `right` for both series.
If you have two series which should be plotted on different scales then you probably want to set one to `left` and the other to `right`.

Overlay scales are useful for when you want to plot something but not have it use an existing scale. For example Volume bars. This can be seen on this example: https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-and-volume

Similar example for two price scales: https://tradingview.github.io/lightweight-charts/tutorials/how_to/two-price-scales

**Comment by jussirantala** [comment]
> https://jsfiddle.net/2u0njz38/

If I change `priceScaleId` to "right" the `scaleMargins` stop working.

**Comment by SlicedSilver** [comment]
Sounds like you are requesting multi panes? This is discussed in this issue: #50 

The library doesn't currently support this feature. There are a few work arounds, including doing something like on the https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-and-volume example, or create to separate charts one below the other.
