### ISSUE TITLE
Add documentation and example for using date and time

### ISSUE THREAD

**Issue by Rizhiy** [tradingview/lightweight-charts#1269]
**Is your feature request related to a problem? Please describe.**

How do I show sub-day quotes?
I tried five different formats for datetime now and none of them work.
There isn't a single example of which format the datetime should be in and docs also don't mention this.
Does this library not support sub-day quotes?

**Describe the solution you'd like**

At least one example with datetime and format of datetime specified in the docs.

**Additional context**

None

**Comment by SlicedSilver** [comment]
The `Time` type is documented here: https://tradingview.github.io/lightweight-charts/docs/api#time

You would most likely want to be using a UTC timestamp (in seconds, not milliseconds).

To have the crosshair labels and time scale tick marks display the time in hours and minutes you can set `timeVisible` to `true` in the `TimeScaleOptions`. Documentation: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#timevisible

```js
const chart = createChart(chartElement, {
  timeScale: {
    timeVisible: true,
  },
});
```

Here is an example which has multiple data points in a single day: https://jsfiddle.net/msilverwood/0vzgaL6o/

**Comment by Rizhiy** [comment]
Thank you, would be great to add this to examples page.
