### ISSUE TITLE
hoveredMarkerId for marker text within subscribeClick event

### ISSUE THREAD

**Issue by FairyWorld** [tradingview/lightweight-charts#1270]
When subscribeClick is triggered by the text in the markers, the howeredMarkerId cannot be obtained. Now I have a requirement to click both the marker and the marker text to perform the processing I need to perform

**Comment by SlicedSilver** [comment]
If you are using the latest release (v4.0) then please be aware of this breaking change: https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4#mouseeventparams-field-hoveredmarkerid-was-renamed-to-hoveredobjectid

- `MouseEventParams` field `hoveredMarkerId` was renamed to `hoveredObjectId`

If this does not resolve your issue then could you please provide the following:
- The version you are using
- Steps to reproduce
- a simple example (jsFiddle or something similar).

Related: #1267

**Comment by FairyWorld** [comment]
> 如果您使用的是最新版本 （v4.0），请注意以下重大更改：[tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4#mouseeventparams-field-hoveredmarkerid-was-renamed-to-hoveredobjectid](https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4#mouseeventparams-field-hoveredmarkerid-was-renamed-to-hoveredobjectid)
> 
> * `MouseEventParams`字段已重命名为`hoveredMarkerId``hoveredObjectId`
> 
> 如果这不能解决您的问题，那么您能否提供以下内容：
> 
> * 您正在使用的版本
> * 重现步骤
> * 一个简单的例子（jsFiddle或类似的东西）。
> 
> 相关： #1267

1. The version I am using has been upgraded to v4.0.0

2. Here are some issues I'm having
	- I want to handle something when the marker is clicked.
	- If you click on the shape of the marker, param can get the hoveredObjectId. it's appropriate.
	- But if the text of the marker is clicked, param.hoveredObjectId is undefined. In this case, I want to be able to click on the text of the marker and get param.hoveredObjectId to handle something. The text surrounded by blue cannot judge whether the click is a marker.
	
![image](https://user-images.githubusercontent.com/32956212/217887568-170acaab-d665-4611-9eeb-b5164577aca2.png)


3. my configuration
```
const markers = [
  {
    id: "mark1",
    time: candleStickData[10].time,
    position: "aboveBar",
    color: "#e91e63",
    shape: "circle",
    text: "mark1",
    size: 2,
  }
];

series.setMarkers(markers);

chart.subscribeClick((param) => {
    if (param.hoveredObjectId) {
      alert("click marker");
    }
});
```

**Comment by SlicedSilver** [comment]
When I tested this further, it looks like the hit box for the text of marker is incorrectly shifted to the right (as if the text wasn't adjusted to be centred).

<img width="334" alt="lwc-marker-bug" src="https://user-images.githubusercontent.com/3482679/218164682-6bd25bf1-be0a-4c20-8c90-7fa7b698965a.png">
