### ISSUE TITLE
Make default colours easily accessible

### ISSUE THREAD

**Issue by Rizhiy** [tradingview/lightweight-charts#1272]
**Is your feature request related to a problem? Please describe.**

I would like to add volume to my chart with colours which match the candlesticks, but I can't find which colours the candlesticks use by default.

**Describe the solution you'd like**

All the colours which are used in the default palette should be easily accessible.

**Additional context**

**Comment by SlicedSilver** [comment]
The default values are visible in the documentation: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/CandlestickStyleOptions

and within the JSDoc comments for the options within the typings included in the package: https://unpkg.com/lightweight-charts@4.0.0/dist/typings.d.ts

You can also call the `options` method to get the options for a series which will contain the colours:
```
series.options();
```
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#options
