### ISSUE TITLE
Additional property for SeriesPrices when there are multiple series

### ISSUE THREAD

**Issue by visanadrian1998** [tradingview/lightweight-charts#1275]
Hi. I'm working on implementing a chart with 2 AreaSeries, something like this:
![image](https://user-images.githubusercontent.com/63725358/218482914-b9cc1aaa-b800-4f74-a827-bb922d198647.png)
When i move the crosshair on the chart, i want to display the price for each series using the "subscribeCrosshairMove". The problem is, the object I get when moving the crosshair gives me a "seriesPrices" Map, containing the "value" of each series, but I don't know which is which
![image](https://user-images.githubusercontent.com/63725358/218483715-95a5f969-c403-4a78-985b-a22b2c53529d.png)
Is there a way to add a property to every entry in this map so i can know which one is which?Thank you!

**Comment by SlicedSilver** [comment]
The `seriesPrices` (or [`seriesData`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/MouseEventParams#seriesdata) if you are using v4.0 or later) is a map where the keys of the map are [ISeriesApi](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi) instances.

In the other words, the ISeriesApi instance that you get when you create a series can be used as the key for the Map to get the value for a specific series:
```js
const mySeries = chart.addLineSeries();
/* ... */

function myCrosshairMoveHandler(param) {
    const mySeriesPrice = param.seriesPrices.get(mySeries);

    // or for v4.0 onwards
    const mySeriesData = param.seriesData(mySeries);
    const mySeriesPrice = mySeriesData.value; // or `close` depending on the series type
}

chart.subscribeCrosshairMove(myCrosshairMoveHandler);
```

Docs: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/MouseEventParams#seriesdata
