### ISSUE TITLE
Tradingview lightweight chart showing invalid date and straight line in Safari

### ISSUE THREAD

**Issue by MichielDeRuiter** [tradingview/lightweight-charts#1276]
I'm trying to get a lightweight chart from Tradingview working in Safari, but it's only working in Chrome and Firefox browsers. In chrome it shows a moving line while in Safari it only shows a straight line and "invalid date".

You can find the JSFiddle here:
https://jsfiddle.net/mideruit/xpyrd4L2/3/

**Comment by MichielDeRuiter** [comment]
The problem seems to be the date format, Safari requires the date format to be yyyy/mm/dd HH:MM instead of yyyy-mm-dd HH:MM:SS

**Comment by SlicedSilver** [comment]
Could you please specify which version of Safari that you are using?

I viewed your example on Safari and Chrome and the plot look the same. Could you additionally provide screenshots and/or console logs?

**Comment by ChristopherJohnson25** [comment]
@SlicedSilver - I believe I have encountered the same issue on iOS 15
