### ISSUE TITLE
First render when using autosize doesn't show the latest bars

### ISSUE THREAD

**Issue by SlicedSilver** [tradingview/lightweight-charts#1282]
**Lightweight Charts Version:** 4.0.0

**Steps/code to reproduce:**
- `autoSize` chart option set to true
```js
const chartOptions = {
  autoSize: true,
};
```

**Actual behavior:**

The last two data points aren't visible (scrolled out of view)

**Expected behavior:**

The latest data points should be visible.

**Screenshots:**
Current:
<img width="502" alt="Screenshot 2023-02-23 at 18 22 13" src="https://user-images.githubusercontent.com/3482679/220997080-2cab964e-55cc-4ea0-8d03-9a151a0ad003.png">
Expected:
<img width="502" alt="Screenshot 2023-02-23 at 18 23 57" src="https://user-images.githubusercontent.com/3482679/220997074-01f07e49-8827-4206-87e8-528be847c4b4.png">

**CodeSandbox/JSFiddle/etc link:**
https://glitch.com/edit/#!/obsidian-almond-latency

**Comment by ihorml** [comment]
Some of `timeScale` methods doesn't work properly as well. 

For e.g. I tried to see `rightOffset` property but it just ignored

**Comment by SlicedSilver** [comment]
> Some of `timeScale` methods doesn't work properly as well.
> 
> For e.g. I tried to use `rightOffset` property but it just ignored

@ihorml Could you please assist us by listing the issues which you have identified and how to reproduce them?

I checked `rightOffset` and it is working but perhaps there is a specific case where it is not working correctly.

Thank you.

**Comment by ihorml** [comment]
@SlicedSilver does it work with the defined `autoSize`? 

I'll create a sandbox

**Comment by 0x33dm** [comment]
> > Some of `timeScale` methods doesn't work properly as well.
> > For e.g. I tried to use `rightOffset` property but it just ignored
> 
> @ihorml Could you please assist us by listing the issues which you have identified and how to reproduce them?
> 
> I checked `rightOffset` and it is working but perhaps there is a specific case where it is not working correctly.
> 
> Thank you.

i have found a similar issue for me.

i'll set rightOffset and then add 700 candles to the chart, several times the last candles will be "chopped" / hidden to the right side of the chart.

for that reason i have to implement some sort of setTimeout as described [in this other issue](https://github.com/tradingview/lightweight-charts/issues/1175)
