### ISSUE TITLE
Interpolation for missing candle sticks

### ISSUE THREAD

**Issue by nuel77** [tradingview/lightweight-charts#1288]
**Is your feature request related to a problem? Please describe.**
Interpolation of candlestick data

To handle empty data for candlestick data, the graph skips that value if a data point is missing. for example, consider this graph
<img width="734" alt="image" src="https://user-images.githubusercontent.com/50878033/222641734-eb55dc5d-5bfa-4abe-9ac9-2a4226e60c44.png">
Here the data for day 23 is missing, And the graph skips that time point. Is there a way I can populate the missing data with the close price of the previous day so that the time range will be consistent without any missing values? Should look something like this.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/50878033/222642679-79e45b1f-33b6-4bf0-b6f9-45b6477e8524.png">

**Comment by SlicedSilver** [comment]
If you want to leave blank spaces in the chart then you can use [WhitespaceData](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/WhitespaceData). Which is essentially a data point with a `time` but no price values.

If you want to insert a bar which has all the ohlc values equal to the previous day's close then you would need to do this yourself in the data before using the `setData` method on the series.

**Comment by Kusou1** [comment]
I would like to ask if Candlestick only supports the daily line level?

**Comment by SlicedSilver** [comment]
@Kusou1 Could you please clarify what you mean by 'daily line level'? I'm not sure what you are asking.

**Comment by Kusou1** [comment]
i mean,timeframe only support 1d,not support 1m or 1h, or 15m @SlicedSilver

**Comment by Kusou1** [comment]
but the time only expect yyyy-mm-dd,not yyy-mm-dd hh:mm:ss,how to solve
<img width="255" alt="image" src="https://user-images.githubusercontent.com/57334674/223921079-1b879a1e-7ae3-426b-a643-9da2759139d4.png">

**Comment by Kusou1** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/57334674/223923192-b0e5f8b0-9665-44f1-8740-2e366e84a752.png">
here how to set when i need use hh,mm,ss
