### ISSUE TITLE
Is there any way to get callback on if candlestick is not present on left (if moving left to right chart )

### ISSUE THREAD

**Issue by satyam-systango** [tradingview/lightweight-charts#1289]
![image](https://user-images.githubusercontent.com/77108993/222645364-c2c6802d-daad-4025-bbaa-19e0e00dda5f.png)

Here timescale is not present (which area i am taking about if timescale is not present in visible range at most left )

**Comment by SlicedSilver** [comment]
Sorry, I'm not sure what exactly the question is asking.

You might be interested in using the [subscribeVisibleTimeRangeChange](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#subscribevisibletimerangechange) or [subscribeVisibleLogicalRangeChange](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#subscribevisiblelogicalrangechange) methods to be notified when the visible range is changed and then you can check if the left most bar is visible or not.
