### ISSUE TITLE
Random baseline showing up in chart

### ISSUE THREAD

**Issue by fabbricca** [tradingview/lightweight-charts#1293]
**Lightweight Charts Version:** 4.0.0

**Steps/code to reproduce:**
In my case i had a chart and three baselines, one to simulate a trade profit, one to simulate a trade loss and the last one to follow the candlestick close. (Screenshot 1)
I think the bug will show with even fewer baselines, but i didn't test it.

**Actual behavior:**
As you can see in the screenshot (Screenshot 2) whenever I scroll to the left and I pass a baseline a random baseline appears in the chart, this doesn't happend if i pass the baseline scrolling to the right. I noticed also that if you programmatically set the visible range  and move to a baseline without stopping on any baseline before the bug won't show up.

**Screenshots:**
<img width="655" alt="Screenshot 2023-03-05 164353" src="https://user-images.githubusercontent.com/109505110/222970634-1a496943-671c-4819-a9fd-897afa9ecc1f.png">

<img width="446" alt="Screenshot 2023-03-05 160123" src="https://user-images.githubusercontent.com/109505110/222969379-7720884a-57b1-4e31-9e2c-8e9371ede245.png">

**Comment by SlicedSilver** [comment]
@fabbricca Thanks for reporting this.
If possible could you please provide a few more detailed steps on how to reproduce this bug? (A code example would be ideal)
A short video would also help to show the problem so it is easier to reproduce on our side and determine the buggy behaviour.

**Comment by fabbricca** [comment]
I have modified the example in web component tutorial, now i have a variable cdata where i store the candlestick data and an array bdata where every position contains an array of baselines data. This function initialize the baselines:

export const initializeTrades = (candlestickData) => {
  const {date, trades, timeframe, close} = candlestickData;
  for (let i=0; i<trades.length; i++) {
    if (!(tradesObjList.map(t => t.start).includes(trades[i].startDate))) {
      const chartElement = document.querySelector('lightweight-chart-container').shadowRoot.querySelector('#candlestick-chart');

      let candlestickDataIndex = (trades[i].startDate - date) / (timeframe * 60);
      let tradeTime = trades[i].startDate;
      let tpBaseline = [];
      let slBaseline = [];
      let priceFollowBaseline = [];


      while (tradeTime <= trades[i].endDate) {
        priceFollowBaseline.push({time: tradeTime, value: close[candlestickDataIndex]});
        tpBaseline.push({time: tradeTime, value: trades[i].takeProfit});
        slBaseline.push({time: tradeTime, value: trades[i].stopLoss});
        tradeTime += timeframe * 60;
        candlestickDataIndex += 1;
      }

      chartElement.bdata = tpBaseline;
      chartElement.bdata = slBaseline;
      chartElement.bdata = priceFollowBaseline;
      
      trades[i].position ? initialColorSetting.long.baseValue.price = trades[i].openPrice : initialColorSetting.short.baseValue.price = trades[i].openPrice;
      chartElement.baselines[chartElement.bdata.length - 3].applyOptions(trades[i].position ? initialColorSetting.long : initialColorSetting.short);
      chartElement.baselines[chartElement.bdata.length - 2].applyOptions(trades[i].position ? initialColorSetting.long : initialColorSetting.short);
      chartElement.baselines[chartElement.bdata.length - 1].applyOptions(trades[i].position ? initialColorSetting.long : initialColorSetting.short);
      tradesObjList.push({position: trades[i].position,
                          start: trades[i].startDate,
                          end: trades[i].endDate,
                          takeProfit: tpBaseline[0].value,
                          stopLoss: slBaseline[0].value,
                          result: trades[i].result});
    }
  }
  return tradesObjList;
}


I am quite new to javascript so there might be improvement in my code, but i can assure that with the chart library version 3.8 the same code didn't give me this kind of problem.
If you need more code just ask.

https://user-images.githubusercontent.com/109505110/222982956-fa2290b9-d5ae-48b5-9465-ca1c56009446.mp4

**Comment by SlicedSilver** [comment]
Thanks for finding this issue. I think I've manage to reproduce the bug (or at least find a very similar bug): https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-u8k12p?file=%2FREADME.md

https://user-images.githubusercontent.com/3482679/223084814-45f23ed6-2e36-47a8-a4c4-1b01e02cf4ae.mov

It appears that if a baseline series is scrolled out of the visible range (moving chart into the past until the series is no longer visible) then the baseline series will still draw on the chart right next to price scale. The speed of scroll can affect how close the bug appears to the end of the chart.

**Comment by fabbricca** [comment]
@SlicedSilver Thank you very much, I was a bit confuse when i noticed it the other day so i decided to dig in the 4.0.0 documentation but i couldn't find anything that helped me.
