### ISSUE TITLE
notarget No matching version found for @types/glob@~8.0.1.

### ISSUE THREAD

**Issue by xinmans** [tradingview/lightweight-charts#1295]
npm install lightweight-charts
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/glob@~8.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xinmans/.npm/_logs/2023-03-09T07_36_22_319Z-debug-0.log

but i can find https://www.npmjs.com/package/@types/glob/v/8.0.1

**Comment by SlicedSilver** [comment]
You may need to reset your npm cache.

```shell
npm cache clean --force
```
