### ISSUE TITLE
Chart is not displayed when the latest date of the data is a few years from now

### ISSUE THREAD

**Issue by if-interface** [tradingview/lightweight-charts#1303]
**Are there any ways to make the data, whose latest date available is a few months ~ years ago, displayed in the chart?**

We are displaying the historical performance of stocks during the past specific periods using lightweight charts.

When the end date of the period is today or close to "today", like a few months ago, the chart is displayed properly like below.
<img width="810" alt="Screen Shot 2023-03-16 at 21 39 34" src="https://user-images.githubusercontent.com/70125343/225628215-9ca1a353-2334-4ff9-81d0-db949ff6afda.png">

However, the end date of the period is NOT CLOSE TO "TODAY", like a year ago or farer, the chart can't be displayed even though the data is properly stored just like the case above.
<img width="809" alt="Screen Shot 2023-03-16 at 21 39 58" src="https://user-images.githubusercontent.com/70125343/225628241-5b4ea82d-0373-4960-b545-3364ff8e1c29.png">
I tried to zoom out or to scroll the chart or to use "Go to" button to see if it can make the charts visible, both of which failed.

**Comment by SlicedSilver** [comment]
Please post this question on our [charting-library repo](https://github.com/tradingview/charting_library/issues).
Additionally I would recommend updating to a newer version of that library.
