### ISSUE TITLE
Incorrect crosshair label text color

### ISSUE THREAD

**Issue by kirchet** [tradingview/lightweight-charts#1309]
**Lightweight Charts Version:** 4.0

**Steps/code to reproduce:**

Apply crosshair options

```js
crosshair: {
  horzLine: {
    labelBackgroundColor: 'rgb(255, 255, 255)',
},
```

**Actual behavior:**

The color of the price axis label text is the same as the background color

**Expected behavior:**

The color of the price axis label text is NOT the same as the background color

**Screenshots:**

![image](https://user-images.githubusercontent.com/1572087/226323532-9f48c5db-f1e2-401a-bbfc-e6055a4e45f1.png)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/kirchet/rd8w2qmy/1/

**Comment by SlicedSilver** [comment]
Most likely related to a similar issue that was happening with the price lines.

https://github.com/tradingview/lightweight-charts/pull/1287/commits/b2e2adca9474aeb70c3460ca9f3c86bc50ed4c13#diff-5b681105d6e4ff65f282d9bbfcf6ba6913181200caa79c32749c0b0316e2c203
