### ISSUE TITLE
Support for limiting min/max zoom/scale level

### ISSUE THREAD

**Issue by ljuborados** [tradingview/lightweight-charts#1312]
**Is your feature request related to a problem? Please describe.**

We have a somewhat basic requirement - limiting how much the chart can zoom, 
e.g. this universally looks bad and we should never allow zooming into that much detail: 

<img width="507" alt="image" src="https://user-images.githubusercontent.com/18645781/226592110-f62464a1-2b11-4d54-b44d-9f614a9adffe.png">

**Describe the solution you'd like**

Ideally a config option limiting max diff between from & to - either in logical representation or in time diff.
Less ideally, being able to return `null` or `false` from `subscribeVisibleTimeRangeChange` to prevent changing the visible time range.

**Additional context**

Tried calling `setVisibleRange` from inside `subscribeVisibleTimeRangeChange` but unfortunately UI 'jumps' to the scrolled to position first, and only after applies the range in `setVisibleRange` which comes with obvious UX issues.

Willing to lend a hand in a PR if this is something you guys would consider adding.

Thanks!

**Comment by SlicedSilver** [comment]
Linking related issue: #1279

Would it be right to summarise your request as the ability to set the following options:
- Minimum Bar Spacing
- Maximum Bar Spacing

Bar spacing is the gap between the centre points of bars. It is essentially the 'zoom' level. So Essentially, options for max and min zoom. 

Is there anything else?

**Comment by ljuborados** [comment]
Absolutely would, that would handle the use-case.

Thanks!
