### ISSUE TITLE
UI Error in PriceScale when displaying a low numerical value

### ISSUE THREAD

**Issue by x1i4b1x2** [tradingview/lightweight-charts#1315]
**Lightweight Charts™ Version:** latest

When uploading decimal numbers lower than 1, the PriceScale doesn't show the numbers.

If you upload numbers higher than 1, it is all fine:
<img width="145" alt="Screenshot 2023-03-25 at 9 59 34 PM" src="https://user-images.githubusercontent.com/100806945/227741550-6783b962-2b99-4ef8-8632-64bd0726f77e.png">

When instead the series is based on numbers lower than zero, the scale is not shown:
<img width="188" alt="Screenshot 2023-03-25 at 10 00 39 PM" src="https://user-images.githubusercontent.com/100806945/227741603-7576bedd-25c2-4bcc-bd83-40c8d29bb0c9.png">

You can see that there is a big jump in the UI between 0.07 and 0.08. It skips everything in between, where instead it could be more precise.
<img width="163" alt="Screenshot 2023-03-25 at 10 04 25 PM" src="https://user-images.githubusercontent.com/100806945/227741830-073e651d-3f25-4cbf-8c93-2576228815d8.png">

This only happens with decimal numbers lower than 1. Thoughts?

**Comment by SlicedSilver** [comment]
There is a `priceFormat` option which you can set for the series
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn

Adjusting the price format settings to a smaller `minMove` value and increasing the `precision` should resolve your issue

**Comment by x1i4b1x2** [comment]
Alright, what if instead a custom price formatter is used?

**Comment by SlicedSilver** [comment]
In this case, price format and price formatter aren't exactly the same thing.
Price format is describing to the library the characteristics of the price values and this is used for the tick marks on the scale as well as the default price formatting. It is still possible to specify a custom price formatter to use instead of the default price formatter.

**Comment by x1i4b1x2** [comment]
Wait, I have managed to "fix" it in this way.

<img width="321" alt="Screenshot 2023-03-26 at 3 48 53 PM" src="https://user-images.githubusercontent.com/100806945/227780233-b51a43d2-c2a0-4dd9-b844-061bb72ae141.png">

It's weird because the library in theory should ignore the built-in formatter config if you give a custom formatter.

<img width="160" alt="Screenshot 2023-03-26 at 3 50 19 PM" src="https://user-images.githubusercontent.com/100806945/227780297-a54a9003-e435-4590-8d54-0041aa89ac65.png">

It's like when the numbers are lower than 1, the PriceSeries uses the default precision, regardless if you give a custom formatter.
