### ISSUE TITLE
Can we add MACD in a chart now?

### ISSUE THREAD

**Issue by tiger2014** [tradingview/lightweight-charts#1321]
Hi Team, 

the old version did not allow us to add a new panel like MACD, RSI, and so on. I want to know if the new version allows us to do it.

I it allows, how to do it?

Thanks

**Comment by SlicedSilver** [comment]
You can currently have multiple plots on a single chart by using different priceScales. There are two built-in price scales (left and right) and overlay scales. Here is an example of using an overlay scale: https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-and-volume

Multi-pane is currently not supported. Please see this related issue. https://github.com/tradingview/lightweight-charts/issues/50

**Comment by panxw** [comment]
I tried to place MACD in one chart , but there were some gap in chart.
Then I placed MACD in another chart,  just worked fine, links: [demo](https://winfirm.net/pages/chart/) & [source](https://github.com/winfirm/winfirm.github.io/blob/gh-pages/pages/src/main.js)

**Comment by winfirm** [comment]
I tried to place MACD in one chart , but there were some gap in chart.
Then I placed MACD in another chart,  final looks as follow: 

<img width="233" alt="macd_pic" src="https://github.com/tradingview/lightweight-charts/assets/33377544/a0cb4042-ce73-44a6-b0a0-49ed59f58c33">

source link: [https://github.com/winfirm/winfirm.github.io/blob/gh-pages/pages/src/main.js)](https://github.com/winfirm/winfirm.github.io/blob/gh-pages/pages/src/main.js)

**Comment by panxw** [comment]
Sorry, the resouce was removed away. 

The key point to show  MACD sub chart is properly using priceScaleId and scaleMargins. Here is a example: 

```
const show_charts=(chart, datas)=>{
	const mainPriceOption = {
            scaleMargins: {
                top: 0.05,
                bottom: 0.3
            },
        };

        show_candle(chart, mainPriceOption, datas.datas, ''); //scaleMargins=''
        
	const macdPriceOption = {
            scaleMargins: {
                top: 0.7,
                bottom: 0.02
            },
        };

        show_histogram(chart, datas.macds[2], macdPriceOption, 'macd');//scaleMargins='macd'
        let macd = datas.macds[0];
        let signal = datas.macds[1];
        show_mas(chart, [macd, signal], ['#ffffff', '#ff0000'], macdPriceOption, 'macd');//scaleMargins='macd'
}

const show_candle = (chart, mainPriceOption, datas, priceScaleId) => {
        const candlestickSeries = chart.addCandlestickSeries({
            priceScaleId,
            touch: false,
            upColor: '#cc0000', downColor: '#33cc00', borderVisible: false,
            wickUpColor: '#cc0000', wickDownColor: '33cc00',
            priceFormat: {
                type: 'price',
                precision: 6
            }
        });

        candlestickSeries.priceScale().applyOptions(mainPriceOption);
        candlestickSeries.setData(datas);
}
    
const show_mas = (chart, datasma, colors, priceOption, priceScaleId) => {
        let lineSeries;
        for (let i = 0; i < datasma.length; i++) {
            lineSeries = chart.addLineSeries({
                priceScaleId,
                color: colors[i],
                lineWidth: 0.5,
                priceLineVisible: false,
                priceFormat: {
                    type: 'price',
                    precision: 6
                }
            });
            lineSeries.priceScale().applyOptions(priceOption);
            lineSeries.setData(datasma[i]);
        }
}

const show_histogram = (chart, histogram, priceOption, priceScaleId) => {
        let histogramSeries = chart.addHistogramSeries({
            priceScaleId,
            color: '#33cc00',
            priceLineVisible: false,
            priceFormat: {
                type: 'volume',
                precision: 6
            }
        });

        histogramSeries.priceScale().applyOptions(priceOption);
        histogramSeries.setData(histogram);
}
    
```

**Comment by 946629031** [comment]
It's April 2025, can the MACD subchart be supported now?

**Comment by SlicedSilver** [comment]
Yes, it is possible for you to implement MACD within LWC. LWC v5 added support multiple panes, and it has been possible for a long time to do the following:
- add histogram series for the bars (and colour the individual bars using the 'color' property on the data points)
- draw 2 line series

So all the building blocks are there and thus it would be possible to draw a MACD chart using LWC.

**Comment by grizonsky** [comment]
I tried to add a stochastic oscillator to the panel, but I always encountered a problem: either each line is in a separate panel, or the panel is not completely removed after deletion. Maybe you have a solution to this problem?

**Comment by SlicedSilver** [comment]
In this PR #1894 we made some improvements to the Pane API.
The changes are in v5.0.8 ([Release Notes](https://github.com/tradingview/lightweight-charts/releases/tag/v5.0.8))

Perhaps this setting would solve your problem: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPaneApi#setpreserveemptypane

If not then please describe your issue in more detail (and/or include screenshots) so that we can understand the issue better and suggest what to do.
