### ISSUE TITLE
Chart is not displayed when the latest date of the data is a few years ago

### ISSUE THREAD

**Issue by if-interface** [tradingview/lightweight-charts#1327]
**Lightweight Charts™ Version:** 
4.0.1 

**Steps/code to reproduce:**
2 charts of the historical performances of a stock with two different time periods were created respectively using lightweight chart.
1. 2010/01/04 ~ today
2. 2010/01/04 ~ 2020/01/04

**Actual behavior:**
The first one, the data whose latest date is today or a few months ago, the chart is displayed properly. 
<img width="1206" alt="Screenshot 2023-04-07 at 22 44 33" src="https://user-images.githubusercontent.com/70125343/230620298-e03f32fa-1e52-48b0-95fc-6658388a521b.png">

On the other hand, when the latest data is 2020/01/04, the chart is NOT displayed.
This happens not only with this date, but also when the latest data is at least a few years ago or older.
<img width="1202" alt="Screenshot 2023-04-07 at 22 44 55" src="https://user-images.githubusercontent.com/70125343/230620574-6b58bf66-d27f-414e-ab18-95edda90436f.png">

**Expected behavior:**
The chart should be displayed regardless of the latest date of the data.

My gut instinct says that this may be an issue which has been overlooked as people hadn't really looked into stocks delisted years ago, whose latest data is old,but sometimes we need that.

**Comment by SlicedSilver** [comment]
**This issue isn't for Lightweight Charts but rather for Charting Library.**
You can post issues for that project on this link: https://github.com/tradingview/charting_library/issues

I can see from your screenshots that you are using an old version of that library, so I would suggest updating to a newer version.

Additionally, our test data feed for that project only includes data up to 2018 and it still functions correctly so I suspect that your issue would be a misconfiguration of your datafeed. Specifically I would look at when you are returning the `noData: true` meta data, which means that there is no further data (even at earlier dates). https://www.tradingview.com/charting-library-docs/latest/connecting_data/Datafeed-API#getbars
