### ISSUE TITLE
Format left price scale

### ISSUE THREAD

**Issue by daniel-zero** [tradingview/lightweight-charts#1328]
I'd like to format the percentage labels of the left price scale. Currently it is not possible to format the rendered label values. I can only format the right price scale. But maybe I'm missing something.

I want to remove the last two digits of the percentage value.

```ts
      leftPriceScale: {
        visible: true,
        mode: PriceScaleMode.Percentage,
        borderVisible: false,
      },
```

```ts
    this._percentage = this._chart.addLineSeries({
      priceScaleId: 'left',
      color: 'rgba(92, 163, 239, 0)',
      baseLineVisible: false,
      priceLineVisible: false,
      lastValueVisible: false,
      priceFormat: {
        type: 'custom',
        formatter: (price: number) => {
          return `${price.toFixed(0)}%`;
        },
      },
    });
```

**Comment by SlicedSilver** [comment]
Using a custom price formatter with a percentage price scale is limited at the moment, and something that we should look into improving for the library.

Related issue: https://github.com/tradingview/lightweight-charts/issues/1291

**Comment by daniel-zero** [comment]
@SlicedSilver can you give me a time-box for the next release containing the formatting feature? I'm asking because our product release depends on this feature.
