### ISSUE TITLE
Add full support for sub-second timestamps

### ISSUE THREAD

**Issue by gerardo-contijoch** [tradingview/lightweight-charts#1342]
I noticed recently that this library doesn't have full support timestamps with a sub-second resolution.

The chart seems to work fine, but the timescale doesn't.

Here I show you how a chart looks when I load a series of 1-minute bars starting from 2021-02-19 9:30am:

![chart-proper-time](https://user-images.githubusercontent.com/74666655/233462760-e3f7e71e-f6e9-4fce-933b-31cf667cc015.png)

And here is a chart showing the same data but this time the `time` property of the data includes milliseconds:

![chart-wrong-time](https://user-images.githubusercontent.com/74666655/233463187-1cd4cfa4-8e8b-453e-9787-16e01bc91386.png)

You can reproduce this issue [here](https://jsfiddle.net/cfbeLhu1/2/). All the times include ms resolution.

I tried using a custom `tickMarkFormatter` but the problem is the argument `tickMarkType` is always wrong. It seems the algorithm that generate the tickmarks does not support sub-second resolution.

**Comment by SlicedSilver** [comment]
The times should be defined according to the following type: https://tradingview.github.io/lightweight-charts/docs/api#time

Which means if you are using timestamps then they need to be specified in **seconds**, not milliseconds
https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp

If you want to support sub-second times then you should be using decimal points on the timestamp. Therefore to fix your example, you should divide all the time values by `1000`.

**Comment by gerardo-contijoch** [comment]
I didn't know it was possible to use decimal values!

Thank you! That solved my problem!
