### ISSUE TITLE
How to realize the adaptive display of the time tick mark according to time scale ratio ? 

### ISSUE THREAD

**Issue by zaleGZL** [tradingview/lightweight-charts#1346]
**Is your feature request related to a problem? Please describe.**

How to realize the adaptive display of the time tick mark in the TradingView chart instead of the fixed type

such as tradingview:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/20339327/233844604-c4d4e3fa-5cf9-4071-9f02-592151567437.png">

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/20339327/233844753-3d2158ec-9598-485f-8842-baf5b36e3c80.png">

**Describe the solution you'd like**

Adaptive display like tradingview charts, or how to achieve it?

**Comment by zaleGZL** [comment]
It turned out to be controlled by the timeVisible attribute, sorry I didn't see it.

**Comment by SlicedSilver** [comment]
For future reference, issues related to Charting Library should be opened on the [tradingview/charting_library](https://github.com/tradingview/charting_library) repo.
