### ISSUE TITLE
SubscribeCrosshairMove does not work on H5

### ISSUE THREAD

**Issue by AnyFork** [tradingview/lightweight-charts#1350]
**Lightweight Charts™ Version:** 
"lightweight-charts": "^4.0.1"
**Steps/code to reproduce:**
When I use subscribeCrosshairMove to increase the Data Tooltip effect, it can be achieved in a web browser. If I use a mobile browser or browser simulation mode to browse, subscribeCrosshairMove does not trigger. What is the reason for this?

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
Within the [ChartOptions](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptions) there are settings for `handleScroll`. Make sure that the touch events are enabled there.
Additionally, please have at look at the [trackingMode](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptions#trackingmode) option.

When using the chart on a mobile device, the user is required to long press on the chart to activate the crosshair.

Here are some examples which are working on a mobile device: https://tradingview.github.io/lightweight-charts/tutorials/how_to/tooltips
