### ISSUE TITLE
Does the Range switch support minutes, such as 5 minutes and 10 minutes

### ISSUE THREAD

**Issue by AnyFork** [tradingview/lightweight-charts#1351]
**Lightweight Charts™ Version:** 
Does the Range switch support minutes, such as 5 minutes and 10 minutes
**Steps/code to reproduce:**
Does the Range switch support minutes, such as 5 minutes and 10 minutes. I have tested the type of time as yyyy mm dd

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
[Time](https://tradingview.github.io/lightweight-charts/docs/api#time) can be specified as a [UTCTimestamp](https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp) which will allow you to use seconds if needed.

Additionally the timeScale can be configured to show time and seconds: [TimeScaleOptions](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions)

```js
const chart = createChart('container', {
   timeScale: {
      timeVisible: true,
      secondsVisible: true,
   },
});

const lineSeries = chart.addLineSeries();
lineSeries.setData([
  {time: 1672531200, value: 100},
  {time: 1672531800, value: 120},
  // ...
]);
```
