### ISSUE TITLE
chart not showing in Vue.js

### ISSUE THREAD

**Issue by Zhu-Aemon** [tradingview/lightweight-charts#1352]
I am using vite and vue.js. I just started to learn lightweight-charts. After following the instructions in the document carefully, I am still unable to see the chart in my web page.
The code below is taken from my BasicPanel.vue:
```
...
<div ref="chartContainer"></div>
...
<script setup>
...
import { createChart } from "lightweight-charts";

let chart
const chartContainer = ref()

onMounted(() => {
  const chartOptions = { layout: { textColor: 'black', background: { type: 'solid', color: 'white' } } };
  chart = createChart(chartContainer.value, chartOptions)
  const candleSeries = chart.addCandlestickSeries({
    upColor: '#26a69a', downColor: '#ef5350', borderVisible: false,
    wickUpColor: '#26a69a', wickDownColor: '#ef5350',
  })

  candleSeries.setData([
    { time: '2018-12-22', open: 75.16, high: 82.84, low: 36.16, close: 45.72 },
    ...
  ]);

  chart.timeScale().fitContent()
})
```

I have installed the package and there is no error in the console. But after inspecting the element, I got something like this:
```
<div class="tv-lightweight-charts" style="overflow: hidden; width: 814px; height: 0px; user-select: none; -webkit-tap-highlight-color: transparent;"><table cellspacing="0" style="height: 0px; width: 814px;"><tr>...
```
The code seems to be there. However, there is just nothing shown in my web page. How do I fix this?

**Comment by SlicedSilver** [comment]
It would appear that the `div` which is used as the container for the chart does not have a height. You should either assign some css rules to that div, or set the style directly on the div such that the height of the div is what you are expecting.

We have a Vue tutorial on our documentation site which may be helpful with some further tips: https://tradingview.github.io/lightweight-charts/tutorials/vuejs/wrapper

Specifically, we are setting the containers height using the following styles:
```html
<template>
    <div class="lw-chart" ref="chartContainer"></div>
</template>
<style scoped>
    .lw-chart {
        height: 100%;
    }
</style>
```

**Comment by Zhu-Aemon** [comment]
It works! Thank you! ^_^
