### ISSUE TITLE
rightPriceScale visible:false breaks the procentage mode

### ISSUE THREAD

**Issue by henrikbergstrom** [tradingview/lightweight-charts#1359]
Hi,
I like to show two lines as procentage mode and hide the rightPriceScale.
But when I set visible to false the procentage stops working.

**Lightweight Charts™ Version:** 
v4.0.1

**Steps/code to reproduce:**
Set rightPriceScale visible to false.
The mode:2 and 3 stop working.
The lines are not starting at same value in chart.

https://jsfiddle.net/8xLqz6po/15/

**Actual behavior:**
For mode:2  (Procentage) I expect two lines to start at same value.
This works when visible: true but stop not when visible: false
 

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/8xLqz6po/15/

**Comment by SlicedSilver** [comment]
If you would like to have a chart without a [price scale](https://tradingview.github.io/lightweight-charts/docs/price-scale) then you can make use of 'overlay' price scales. 

Essentially you set the priceScaleId on the series to a string which is not either `left` or `right`. You can set global settings for the overlay price scales with the `overlayPriceScales` chart option

Overlay price scales are used in this example: https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-and-volume

Updated example: https://jsfiddle.net/msilverwood/cLg3sr7w/
