### ISSUE TITLE
candlestick no candle  displayed for minutes 15 minutes timeframe

### ISSUE THREAD

**Issue by brusand** [tradingview/lightweight-charts#1365]
**Lightweight Charts™ Version:** 
last
**Steps/code to reproduce:**
this data set error, if you delete one entry it is works

[{'time': 1684464300, 'open': 26856.08, 'high': 26900.0, 'low': 26831.61, 'close': 26884.4, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684465200, 'open': 26884.4, 'high': 26911.99, 'low': 26873.72, 'close': 26887.03, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684466100, 'open': 26887.03, 'high': 26887.03, 'low': 26820.01, 'close': 26840.01, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684467000, 'open': 26840.01, 'high': 26846.94, 'low': 26776.87, 'close': 26784.33, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684467900, 'open': 26784.33, 'high': 26810.06, 'low': 26751.12, 'close': 26810.0, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684468800, 'open': 26810.0, 'high': 26846.28, 'low': 26795.68, 'close': 26822.69, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684469700, 'open': 26822.69, 'high': 26844.65, 'low': 26813.69, 'close': 26841.66, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684469700, 'open': 26822.69, 'high': 26844.65, 'low': 26813.69, 'close': 26841.66, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684470600, 'open': 26841.66, 'high': 26850.0, 'low': 26768.55, 'close': 26775.45, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684471500, 'open': 26775.45, 'high': 26801.0, 'low': 26763.25, 'close': 26799.66, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684472400, 'open': 26799.66, 'high': 26814.16, 'low': 26767.2, 'close': 26811.43, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684473300, 'open': 26811.43, 'high': 26868.0, 'low': 26810.61, 'close': 26868.0, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684474200, 'open': 26868.0, 'high': 26876.13, 'low': 26851.52, 'close': 26856.58, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684475100, 'open': 26856.58, 'high': 26856.58, 'low': 26834.65, 'close': 26836.73, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684476000, 'open': 26836.73, 'high': 26845.98, 'low': 26825.19, 'close': 26825.19, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684476900, 'open': 26825.19, 'high': 26840.0, 'low': 26817.24, 'close': 26834.79, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684477800, 'open': 26834.79, 'high': 26861.09, 'low': 26823.29, 'close': 26861.09, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684478700, 'open': 26861.09, 'high': 26876.4, 'low': 26852.01, 'close': 26875.33, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684479600, 'open': 26875.33, 'high': 26887.87, 'low': 26843.27, 'close': 26845.95, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684480500, 'open': 26845.95, 'high': 26861.08, 'low': 26832.94, 'close': 26853.87, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684481400, 'open': 26853.87, 'high': 26884.94, 'low': 26851.99, 'close': 26880.6, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684482300, 'open': 26880.6, 'high': 26889.02, 'low': 26860.38, 'close': 26881.57, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684483200, 'open': 26881.57, 'high': 26924.38, 'low': 26867.42, 'close': 26900.56, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684484100, 'open': 26900.56, 'high': 26932.71, 'low': 26895.4, 'close': 26902.11, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684485000, 'open': 26902.11, 'high': 26916.88, 'low': 26881.1, 'close': 26906.92, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684485900, 'open': 26906.92, 'high': 26931.88, 'low': 26906.92, 'close': 26906.97, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684486800, 'open': 26906.97, 'high': 26953.82, 'low': 26886.18, 'close': 26946.31, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684487700, 'open': 26946.31, 'high': 26960.48, 'low': 26897.69, 'close': 26897.69, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684488600, 'open': 26897.69, 'high': 26912.61, 'low': 26861.09, 'close': 26873.07, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684489500, 'open': 26873.07, 'high': 26878.96, 'low': 26851.83, 'close': 26857.14, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684490400, 'open': 26857.14, 'high': 26874.76, 'low': 26841.1, 'close': 26873.01, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684491300, 'open': 26873.01, 'high': 26893.97, 'low': 26873.01, 'close': 26883.82, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684492200, 'open': 26883.82, 'high': 26926.87, 'low': 26883.82, 'close': 26901.15, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684493100, 'open': 26901.15, 'high': 26924.99, 'low': 26891.1, 'close': 26891.63, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684494000, 'open': 26891.63, 'high': 26910.39, 'low': 26862.49, 'close': 26862.5, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684494900, 'open': 26862.5, 'high': 26875.92, 'low': 26828.61, 'close': 26843.64, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684495800, 'open': 26843.64, 'high': 26849.45, 'low': 26825.0, 'close': 26836.29, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684496700, 'open': 26836.29, 'high': 26851.25, 'low': 26834.39, 'close': 26837.7, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684497600, 'open': 26837.7, 'high': 26864.76, 'low': 26837.7, 'close': 26863.82, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684498500, 'open': 26863.82, 'high': 26876.29, 'low': 26831.1, 'close': 26855.02, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684499400, 'open': 26855.02, 'high': 26858.39, 'low': 26836.02, 'close': 26847.41, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684500300, 'open': 26847.41, 'high': 26847.42, 'low': 26794.34, 'close': 26820.0, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684501200, 'open': 26820.0, 'high': 26846.83, 'low': 26801.09, 'close': 26801.6, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684502100, 'open': 26801.6, 'high': 26846.62, 'low': 26801.6, 'close': 26832.93, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684503000, 'open': 26832.93, 'high': 26848.33, 'low': 26831.16, 'close': 26833.44, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684503900, 'open': 26833.44, 'high': 26875.61, 'low': 26833.44, 'close': 26857.39, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684504800, 'open': 26857.39, 'high': 26989.1, 'low': 26857.39, 'close': 26955.18, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684505700, 'open': 26955.18, 'high': 26987.06, 'low': 26904.81, 'close': 26922.52, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684506600, 'open': 26922.52, 'high': 26945.29, 'low': 26901.81, 'close': 26926.94, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684507500, 'open': 26926.94, 'high': 26931.23, 'low': 26887.98, 'close': 26910.15, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684508400, 'open': 26910.15, 'high': 26929.2, 'low': 26910.14, 'close': 26915.19, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684509300, 'open': 26915.19, 'high': 26952.84, 'low': 26904.51, 'close': 26941.4, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684510200, 'open': 26941.4, 'high': 26946.74, 'low': 26892.87, 'close': 26910.76, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684511100, 'open': 26910.76, 'high': 26913.38, 'low': 26843.79, 'close': 26868.28, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684512000, 'open': 26868.28, 'high': 26868.28, 'low': 26763.01, 'close': 26788.07, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684512900, 'open': 26788.07, 'high': 26844.71, 'low': 26782.28, 'close': 26809.97, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684513800, 'open': 26809.97, 'high': 26838.59, 'low': 26797.47, 'close': 26803.34, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684514700, 'open': 26803.34, 'high': 26838.66, 'low': 26786.01, 'close': 26838.65, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684515600, 'open': 26838.65, 'high': 26924.96, 'low': 26717.21, 'close': 26905.39, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684516500, 'open': 26905.39, 'high': 27199.99, 'low': 26865.1, 'close': 26879.6, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684517400, 'open': 26879.6, 'high': 26987.68, 'low': 26632.01, 'close': 26947.93, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684518300, 'open': 26947.93, 'high': 26988.21, 'low': 26835.35, 'close': 26885.96, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684519200, 'open': 26885.96, 'high': 26960.48, 'low': 26850.64, 'close': 26917.03, 'color': 'rgba(38,166,154,0.9)'}, {'time': 1684520100, 'open': 26917.03, 'high': 26958.66, 'low': 26894.43, 'close': 26895.3, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684521000, 'open': 26895.3, 'high': 26895.3, 'low': 26801.51, 'close': 26884.51, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684521900, 'open': 26884.51, 'high': 26896.91, 'low': 26855.04, 'close': 26860.78, 'color': 'rgba(239,83,80,0.9)'}, {'time': 1684522800, 'open': 26840.23, 'high': 26840.24, 'low': 26840.23, 'close': 26840.24, 'color': 'rgba(38,166,154,0.9)'}]
seriesCandlestickChart = [
    {
        "type": 'Candlestick',
        "data": candles,
        "options": {
            "upColor": COLOR_BULL,
            "downColor": COLOR_BEAR,
            "borderVisible": True,
            "wickUpColor": COLOR_BULL,
            "wickDownColor": COLOR_BEAR
        }
    }
]
chartOptions = {
    "layout": {
        "textColor": 'black',
        "background": {
            "type": 'solid',
            "color": 'white'
        },
    },    
    "timeScale": {
        "timeVisible": True,
        "secondsVisible": False,
    },
    "watermark": {
        "visible": True,
        "fontSize": 48,
        "horzAlign": 'center',
        "vertAlign": 'center',
        "color": 'rgba(171, 71, 188, 0.3)',
        "text": 'BTC/USDT - 15m',
    }
}
renderLightweightCharts([
    {
        "chart": chartOptions,
        "series": seriesCandlestickChart
    }
], 'candlestick')
#

**Actual behavior:**
my data are loaded, the time are well displayed but i have a console error wich don t display the chart but i dont wich variable is not defined

lightweight-charts.production.mjs:7 Uncaught Error: Value is null
    at E (lightweight-charts.production.mjs:7:590)
    at t.Candlestick [as Ah] (lightweight-charts.production.mjs:7:43380)
    at t.value (lightweight-charts.production.mjs:7:44546)
    at n.value (lightweight-charts.production.mjs:7:29339)
    at lightweight-charts.production.mjs:7:24728
    at Array.map (<anonymous>)
    at n.value (lightweight-charts.production.mjs:7:24715)
    at n.value (lightweight-charts.production.mjs:7:22279)
    at n.value (lightweight-charts.production.mjs:7:22114)
    at t.value (lightweight-charts.production.mjs:7:105334)

it is ok for daily candlesticks

**Expected behavior:**
display the chart withoutconsole error

**Screenshots:**
<img width="651" alt="Capture d’écran 2023-05-19 à 17 35 12" src="https://github.com/tradingview/lightweight-charts/assets/1648561/7c7a43cb-b223-4858-b069-7fbac084bad3">

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
You've got multiple (3) data points for the `1684469700` timestamp. The library requires that the data doesn't contain more than one data entry per specific timestamp per series. Additionally, the data needs to be ascending order.

Here is your supplied data working on a candlestick series: https://codesandbox.io/p/sandbox/lightweight-charts-1365-uynzi2?file=%2FREADME.md%3A4%2C1

Notice, the commented out entries in the `sample-data.js` file. You had a sequence of entries with these timestamps:
- `1684467900`
- `1684468800`
- `1684469700` ← timestamp is smaller than previous entry, and the timestamp has already been defined
- `1684469700` ← timestamp has already been defined.
