### ISSUE TITLE
HoverObjectID undefined when hovering slowly or stopping over PriceLineID

### ISSUE THREAD

**Issue by FarhanSajid1** [tradingview/lightweight-charts#1371]
When working with priceLines, if you hover over the price line slowly, the hoverObjectID returns undefined. And if you stop moving the hoverObjectID is set to undefined, is there a way to handle this?

**Steps/code to reproduce:**

```js

      const handleChartHover = (param) => {
     
          console.log('hiding tooltip',param.hoveredObjectId);
      }
      // subscribe to events where the user clicks on the chart
      chart.subscribeCrosshairMove(handleChartHover);

          candleSeries.createPriceLine({

            id: `price-line`,
          });
```

**Comment by SlicedSilver** [comment]
@FarhanSajid1 Are there any other steps required to reproduce this issue?

I've created a test example and it is working correctly (even if I move the cursor very slowly).
https://glitch.com/edit/#!/full-mixolydian-marquess

**Comment by FarhanSajid1** [comment]
@SlicedSilver I'll work on making a reproducible example, I'm making use of react and it does something like the following:

Would react rendering the component have anything to do with this?

```
        console.log(param.hoveredObjectId);
    
        if (!param.hoveredObjectId || !param.hoveredObjectId.includes("-")) {
          console.log('hiding tooltip',param.hoveredObjectId);
          setShowTooltip(false); // Show the tooltip
          return;
        }
        
             setTooltipData({ level: price, explanation: explanation });
              setTooltipPosition({ x: param.point.x, y: param.point.y });
              setShowTooltip(true); // Show the tooltip
```
