### ISSUE TITLE
Specific data display exception

### ISSUE THREAD

**Issue by keene-dalveytech** [tradingview/lightweight-charts#1373]
**Lightweight Charts™ Version:** 

Zoom in a little bit and then slide back to January 2018 and it shows an anomaly

**Actual behavior:**

Height exceedance display

**Expected behavior:**

Do not exceed the display

**Screenshots:**

<img width="762" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/126315969/75d5822f-1666-4d9c-84a2-bfc2262ecb24">

**CodeSandbox/JSFiddle/etc link:**

[codesandbox](https://codesandbox.io/s/lightweight-charts-forked-h23img?file=/src/App.js)

**Comment by SlicedSilver** [comment]
The `open`, `high`, `low`, and `close` values are expected to be numbers instead of strings. (https://tradingview.github.io/lightweight-charts/docs/api/interfaces/OhlcData)

You could convert your data using a map function:
```js
const data = [ /* ... your data ... */ ].map((d) => {
    return {
      time: d.time,
      open: parseFloat(d.open),
      close: parseFloat(d.close),
      high: parseFloat(d.high),
      low: parseFloat(d.low)
    };
  })
```
