### ISSUE TITLE
Add `subscribeTouch` event or Crosshair on mobile!

### ISSUE THREAD

**Issue by n8tb1t** [tradingview/lightweight-charts#138]
I noticed that `Crosshair` is not working on mobile.

But, I need it, to update the `legend` once the user touches some candle, or a bar on the chart.
On the desktop it works flawlessly with `subscribeCrosshairMove` but on mobile there is no way to know which part of the chart the user is touching.

Can you please think about it, and add some, solution, because, somehow `crosshair` is working in `Technical Analysis Charts` library on mobile. 

Unfortunately, I don't have access to its repository, otherwise, I would've checked how it's done, and maybe push a PR. So I would like to have access to `lightweight-charts` — “big brother” as well, can you add me to the repo.?

**Comment by n8tb1t** [comment]
Well, as a quick fix, I came out with this solution, now, I only add this `event listener` on devices with touch support.
And, now if the user scroll the chart horizontally, with his finger, the `legend block` is getting updated.

```jsx
    chart.subscribeVisibleTimeRangeChange(event => {
      if (legendData.time === event.to) return
      updateLegend(candlestickData.filter(data => data.time === event.to)[0])
    })
```

**Comment by timocov** [comment]
> I noticed that Crosshair is not working on mobile.

Hey @n8tb1t, did you know about tracking mode (try to long press on mobile and then move the finger)?

**Comment by n8tb1t** [comment]
Ух ты, удивительно, как я раньше это не заметил!
Спасибо огромное!

I'm currently working on integrating `lightweight-charts` with `react`, so far it's going ok, but It seems, I'll need to write a wrapper to defer, the initial rendering of  `let chart = createChart(chartContainerRef, chartOptions)`  it interacts with DOM  right away, simple `helper` like `chart.render()` would be extremely useful.
Also, I'm going to look into `SSR` - to generate charts on the server, during the build process.
I'll let you know when it's all ready!

**Comment by timocov** [comment]
> but It seems, I'll need to write a wrapper to defer, the initial rendering of let chart = createChart(chartContainerRef, chartOptions) it interacts with DOM right away

Why you can't do this in `componentDidMount` method?

> Also, I'm going to look into SSR - to generate charts on the server, during the build process.

I'm not sure that it's even possible with canvas. But anyway, if you'll have any suggestion with that - feel free to create different issue.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by vaibhav-systango** [comment]
> Well, as a quick fix, I came out with this solution, I only add this `event listener` on devices with touch support. And, now if the user scrolls the chart horizontally, with his finger, the `legend block` is getting updated.
> 
> ```js
>     chart.subscribeVisibleTimeRangeChange(event => {
>       if (legendData.time === event.to) return
>       updateLegend(candlestickData.filter(data => data.time === event.to)[0])
>     })
> ```

@timocov @n8tb1t 
how will get the crosshair x and y intersection as, crossHairMove doesn't gets subscribed on touch devices on mobile. SO im showing a tooltip and its showing data but when I scroll graph crosshair still shows old data and doesn't shows latest data that its pointing to from x-y axis of chart, But this works fine on desktop devices
