### ISSUE TITLE
When change time level have two chart behave，one half is 1h one half is 1d

### ISSUE THREAD

**Issue by Kusou1** [tradingview/lightweight-charts#1384]
Why when I go from 1h time level to 1d time level, the watch will have two time scales, half of which are hour level and half are day level, why is this
![Kapture 2023-06-26 at 23 00 23](https://github.com/tradingview/lightweight-charts/assets/57334674/d2643bfd-dbf7-4a19-9c65-798321b85b07)

**Comment by SlicedSilver** [comment]
You should either 
- remove the old series using [`chart.removeSeries()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#removeseries), 
- or use the existing series and replace it's data with the [`setData()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#setdata) method.
