### ISSUE TITLE
TimeScale option to stop visible range changing ever on new data.

### ISSUE THREAD

**Issue by cursorial** [tradingview/lightweight-charts#1395]
**Is your feature request related to a problem? Please describe.**

I'm working on a project that loads in data incrementally while the user is using the chart. This might mean that the user would see the initial chart, scroll around, and then when new data arrives and is added to the chart, it snaps them away from whatever they were just looking at. See the videos below:

https://github.com/tradingview/lightweight-charts/assets/2265262/8b321694-8c01-4bee-ad42-9bbeb137df79

https://github.com/tradingview/lightweight-charts/assets/2265262/44ddfee9-1441-495c-a04e-e79835ca0576

What I want is a boolean option on timeScale that means when `setData` is called on a new series that has just been added to the chart, the visible range will not change under any circumstance.

**Additional context**

There is a bit of an additional issue that I'm facing here, in that I've attempted to use `timeScale.shiftVisibleRangeOnNewBar = false`, and even when the last bar is visible, the chart still snaps back when a new lineSeries is added. I can add a repro for this if needed.

**Comment by SlicedSilver** [comment]
Hi @cursorial
Would it be possible to create a small reproduction? or provide a code sample?

The default behaviour is not to adjust the visible range (the left most visible bar if new dates are added) when adding a new series.

Are you calling `setData` on both series?

**Comment by cursorial** [comment]
I think I've found my issue and it's not lightweight-charts related. It's a React problem.

Essentially I'm rendering my Chart in a component, when new data arrives, my app forces a re-render of the chart, which causes this behaviour.
