### ISSUE TITLE
Time range options for initialization and resetTimeScale

### ISSUE THREAD

**Issue by clark800** [tradingview/lightweight-charts#1397]
After creating a chart, I am setting up the time scale according to some logic, which is either based on a fixed start date or fitting the content. However, when double clicking on the time scale, `resetTimeScale` is not aware of this logic and it resets to a different range. I'd like it if double clicking the time scale reset to my custom time range.

I think the best solution would be to have some fields in `TimeScaleOptions`: `initialMin` (date), `initialMax` (date), and `fitContent` (boolean). These would control both the initial range of the chart and the reset range. If `fitContent` is set and `initialMin` and/or `initialMax` are set, the min/max could take precedence.

**Comment by SlicedSilver** [comment]
When the timescale is reset, it will apply the values for
- [barSpacing](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#barspacing)
- [rightOffset](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#rightoffset)
which are currently set in the options for the time scale.

If you have some custom logic to apply when reseting the time scale then I would suggest that you add an event listener for the click event and detect when the time scale has been doubled click. You could either try add the listener to the time scale div, or use the height property from the Timescale API to determine if the click was over the time scale. 

You could then apply your custom time scale reset within that event handler.

---

An alternative to adding those `TimeScaleOptions` would be to add an event for the time scale being reset.
