### ISSUE TITLE
Stop propagation of axis double click events if it triggers a reset

### ISSUE THREAD

**Issue by clark800** [tradingview/lightweight-charts#1398]
I want to be able to catch double click events on the chart except when double clicking the axes. I'm using an event listener on the div that contains the chart. I currently have a hack that works, but it would be nice if there was a cleaner option.

I think it might work to call `event.stopPropagation()` on double click in the axes if the corresponding `axisDoubleClickReset` setting is enabled, or if there is a reason to keep propagation, perhaps it could be an option to disable it.

**Comment by SlicedSilver** [comment]
You should be able to use the [`subscribeDblClick`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#subscribedblclick) event listener on the IChartApi and use the passed parameters ([MouseEventParams](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/MouseEventParams)) to know where on the chart the click.
