### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by ujenjt** [tradingview/lightweight-charts#14]
It's nice to have live demo on the https://codesandbox.io for example =)

**Comment by timocov** [comment]
Wow, I even didn't hear about CodeSandbox before. It looks pretty good. We have some examples internally and I believe we can provide them in that way. Thank you! 👍

**Comment by ezhukovskiy** [comment]
btw we have lots of examples on jsfiddle (click the titles)
https://www.tradingview.com/lightweight-charts/

**Comment by timocov** [comment]
Related to #875

**Comment by SlicedSilver** [comment]
We have a variety of demos hosted on this page: https://www.tradingview.com/lightweight-charts/
and on our documentation page: https://tradingview.github.io/lightweight-charts/tutorials#how-to--examples
