### ISSUE TITLE
Pricescale is not recalculated after `visibility` change

### ISSUE THREAD

**Issue by nichita-pasecinic** [tradingview/lightweight-charts#1403]
**Lightweight Charts™ Version:** 4.0.1

[Repro on CodeSandbox](https://codesandbox.io/p/sandbox/lwc-fixed-edges-issue-forked-xc32dt?file=%2Fsrc%2Fmain.ts%3A1334%2C23)

Simply after changing the visibility of the rightPriceScale the price scale itself becomes unresponsive.

Thanks

**Comment by SlicedSilver** [comment]
You will need to assign the series to the right price scale.
Since there weren't any visible price scales when the chart was created, this means that the series isn't automatically assigned to a price scale so it will need to be done by applying the option.

```js
mainSeries.applyOptions({
    priceScaleId: 'right',
  });
```

**Comment by nichita-pasecinic** [comment]
@SlicedSilver that worked, Thanks a lot!
