### ISSUE TITLE
setData unexpectedly shifts time scale when removing candle bars

### ISSUE THREAD

**Issue by louisnw01** [tradingview/lightweight-charts#1405]
**Lightweight Charts™ Version:** 4.1.0

**Steps/code to reproduce:**

https://jsfiddle.net/6t82qa5k/2/

**Actual behavior:**

When removing a bar of data, the time scale shifts.

Similar issues were raised in #584 and #549, and they were fixed for appending new data with `shiftVisibleRangeOnNewBar`, but the bug still appears when removing data.

In the JS fiddle, you can see that `shiftVisibleRangeOnNewBar` is set to `false`, which works for adding bars, but not removing them.

**Expected behavior:**

Timescale should not move. Fixing this bug would allow for dynamically loaded data which throws away the most present data.

**Comment by louisnw01** [comment]
Hey,

I just wanted to update this as I may have not been clear in my initial post as to why this would be an awesome thing to fix.

In the following JSfiddle, we are dynamically loading data from the past as we scroll backward (shown within the viewport for clarity). Upon pressing the `Dynamic Load Present Data` button, the chart begins to remove/add data to the end of `currentData`, which shifts the timescale as described above, causing a feedback loop which making this a tricky thing to integrate in the current version of the library.

https://jsfiddle.net/qfgxraom/

In a real use case scenario, the data would be loaded externally from a server, which would allow essentially limitless datasets containing as many bars as the user desires.

The current way to do this would be to only load data from the past as the user scrolls backward, without throwing away data from the present. This means that the futher the user scrolls back, the longer it takes to load the data before the chart starts freezing for seconds at a time as it has to set the entire dataset up to the present upon each change of the visible range.

Let me know if this clears things up, and what an awesome library you guys have made!

Louis

**Comment by MathsPsychopath** [comment]
Correct me if I'm wrong, but you want to emulate how TradingView loads historical chart data. 

> ...chart starts freezing for seconds at a time as it has to set the entire dataset up to the present upon each change of the visible range.

What about making API calls only when the barsBefore has reached a threshold, e.g., -20 bars? This way, you wouldn't need to fetch every thousandth of a second as the visible range changes.

I'm not entirely sure how historical data loading is implemented in the TradingView platform, so I'm not an expert.

Also, the jsfiddle seems to have some slightly odd behaviour sometimes when I scroll forward. Like it works for a bit, then all the data disappears from the chart.

**Comment by louisnw01** [comment]
Hey @MathsPsychopath, Thanks for the response!

> What about making API calls only when the barsBefore has reached a threshold, e.g., -20 bars? This way, you wouldn't need to fetch every thousandth of a second as the visible range changes.

The issue of a delay occurs due to the dataset becoming larger and larger as the user scrolls further back in time; I didn't implement a threshold for clarity in the example, but in production this would definitely be necessary.

> Also, the jsfiddle seems to have some slightly odd behaviour sometimes when I scroll forward. Like it works for a bit, then all the data disappears from the chart.

Assuming this is with dynamic load present data turned on; as the preloading buffer is set to 5, data is initially needed to be removed to match the buffer (like how data is added/removed from the end within the viewport), which shifts the time scale.

Louis

**Comment by SlicedSilver** [comment]
The [time scale api](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi) has methods for reading the current position, and methods to set the position. You should be able to read this position before adding new data, and then restore that position after the data has loaded.

There is a code example for loading historical data here: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#barsinlogicalrange

**Comment by amirzamli** [comment]
@louisnw01 Were you able to handle this? I have tried to apply the suggested solution with setting the range/position manually but it still jumps around when you add and remove data.

**Comment by louisnw01** [comment]
> @louisnw01 Were you able to handle this? I have tried to apply the suggested solution with setting the range/position manually but it still jumps around when you add and remove data.

Still haven't been able to; maybe take a look at the jsfiddle and see if you can figure it out?

Louis

**Comment by SlicedSilver** [comment]
We have an example which shows how to dynamically load older data as needed here: [Infinite History](https://tradingview.github.io/lightweight-charts/tutorials/demos/infinite-history)

If you are needing to remove data (instead of only adding) then you could potentially use the [`scrollPosition`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#scrollposition) and [`scrollToPosition`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#scrolltoposition) methods on the Time Scale API. 

The scroll position is the distance from the right edge of the time scale to the latest (last) bar of the series measured in bars. If you are removing the latest bar/s then you could read that value before removing the latest bar and then call the scrollToPosition method immediately after changing the data with an appropriate value. For example, if you delete the last 10 bars then you could adjust this scroll position by 10 bars.

**Comment by markhammond** [comment]
@louisnw01 @amirzamli 
The following patch works for me. It addresses the feedback loop induced when dynamically loading and _removing_ data. There is noticeable flicker when compositing new data, albeit very brief.

(I am not sure how to use ScrollPosition in conjunction with asynchronous data loading - it may yield a better user experience)

diff --git a/src/model/chart-model.ts b/src/model/chart-model.ts
index fb2d7d562..c2ab99d88 100644
--- a/src/model/chart-model.ts
+++ b/src/model/chart-model.ts
@@ -861,6 +861,9 @@ export class ChartModel<HorzScaleItem> implements IDestroyable, IChartModelBase
 			if (isSeriesPointsAddedToRight && !needShiftVisibleRangeOnNewBar) {
 				const compensationShift = newBaseIndex - currentBaseIndex;
 				this._timeScale.setRightOffset(this._timeScale.rightOffset() - compensationShift);
+			} else if (isLeftBarShiftToLeft && newBaseIndex != null && newBaseIndex != currentBaseIndex) {
+				const compensationShift = newBaseIndex - currentBaseIndex;
+				this._timeScale.setRightOffset(this._timeScale.rightOffset() + compensationShift);
 			}
 		}

**Comment by SlicedSilver** [comment]
Thanks @markhammond, could you please create a PR for this change? 🙏
