### ISSUE TITLE
When Changing the chart type from Area to Candle the chart is not showing Properly 

### ISSUE THREAD

**Issue by balram1996** [tradingview/lightweight-charts#1413]
**Lightweight Charts™ Version:** 
Version "3.7.0" and in latest also
**Steps/code to reproduce:**
See the video to reproduce the issue.

https://github.com/tradingview/lightweight-charts/assets/86410279/cfbeb00d-baaf-4e89-83c7-5eca38ac2b12

**Actual behavior:**
When i click on the change the chart type from Area to Candle the chart not holding(showing).

**Expected behavior:**
The chart should show the candle chart like the Area Chart.

**Screenshots:**
<img width="1440" alt="Screenshot 2023-08-23 at 3 49 46 PM" src="https://github.com/tradingview/lightweight-charts/assets/86410279/69b8e198-cf46-45c4-a038-ff5cbe255d8d">
<img width="1440" alt="Screenshot 2023-08-23 at 3 49 53 PM" src="https://github.com/tradingview/lightweight-charts/assets/86410279/97a8ba99-d55a-4f8e-adb0-d8f22817cbc7">

**Code for Reference:**
`async function onDPItemClicked(ele) {
	dayData = getApi(url, selectedSeries);
	fixforVolume();
	formattedRanges();
	volumeformattedRanges();

	selectedSeries = ele.childNodes[0].className.includes("area-chart")
		? "Area"
		: "Candle";
	if (selectedSeries) {
		localStorage.setItem("selectedSeries" + params.symbol, selectedSeries);
		chart.removeSeries(sSeries);
		chart.removeSeries(vSeries);
		Series = await callChart(selectedSeries);
		VSeries = await volumecallChart(selectedSeries);
		Series.setData(dataTobeSent);
		VSeries.setData(volumeData);
		debugger;
	}
	var candleEle = document.getElementsByClassName("candle-chart-header");
	var areaEle = document.getElementsByClassName("area-chart-header");

	if (selectedSeries == "Area") {
		areaElement[0].classList.add("chart-btn-back-color");
		candleElement[0].classList.remove("chart-btn-back-color");
		candleEle[0].classList.remove("display-none");
		areaEle[0].classList.add("display-none");
	} else {
		areaElement[0].classList.remove("chart-btn-back-color");
		candleElement[0].classList.add("chart-btn-back-color");
		candleEle[0].classList.add("display-none");
		areaEle[0].classList.remove("display-none");
	}
	// changeThemeParameters(currentSelectedTheme);
	toolTip.style.display = "none";
	//location.reload();
	//window.location.top;
	//chart.timeScale().scrollToPosition(14);
}`

Pls solve this Bug ASAP.

**Comment by SlicedSilver** [comment]
Here is a quick example showing this working: https://codesandbox.io/p/sandbox/lightweight-charts-js-starter-forked-tlqqk7?file=%2Fsrc%2Fmain.js%3A1%2C1

If you believe that there is still a bug in the library then could you please create a small bug reproduction on a site like jsFiddle / code sandbox which demonstrates the bug in an isolated test case?

**Comment by balram1996** [comment]
https://tradechart-uat.5paisa.com/index.html?source=derivative&range=D&period=1&appName=TATA&appVer=5.11.6.0&osName=TTWEB&loginId=50999693&type=future-curcom&exchange=M&exchType=D&symbol=CRUDEOIL&scripCode=258086&option_type=PE&strike_price=6300&expiry_date=15%20Sep%202023&searchFlag=true&theme=light

You can check this here.

**Comment by SlicedSilver** [comment]
I believe it is a bug on your side. Please check the developer console and note that your candlestick data is invalid. (you can switch to the development build, instead of the production build, of the library to get more helpful error messages).

It appears to correctly switch chart type and then the code tries to setData with invalid data for the candlestick series.

As mentioned above, if you think there is a bug with the library then could you please create a bug reproduction (which isn't your site).

**Comment by balram1996** [comment]
Thanks for the Quick Replies.
By using the development build i am getting this error
<img width="1440" alt="Screenshot 2023-08-23 at 7 12 37 PM" src="https://github.com/tradingview/lightweight-charts/assets/86410279/d92b50fe-0313-4d80-84da-05b392eb48b8">

But Even when i sending the data in Ascending order to library i am getting the same error. I am getting this error only for this symbol.
For this Symbol i am not getting this error 
https://tradechart-uat.5paisa.com/index.html?type=overview&period=1&exchange=nse&exchType=C&range=d&symbol=Reliance&scripCode=2885&appName=TATA&appVer=5.11.6.0&osName=Android&loginId=0&theme=Light&searchFlag=true

**Comment by SlicedSilver** [comment]
The data should be in ascending order AND without duplicate times. In this case you are providing more than one data point for a specific `time` value.

**Comment by balram1996** [comment]
Thanks @SlicedSilver. The issue have been resolved. The backend was passing the double data points.
