### ISSUE TITLE
Need fraction value types for LineWidth

### ISSUE THREAD

**Issue by Amyx000** [tradingview/lightweight-charts#1416]
In the `draw-line.ts` file I see types are defined like `export type LineWidth = 1 | 2 | 3 | 4;`

For example, I needed 0.5 width, even though width works in the UI, but I got a typescript error. Right now I am overwriting the types by extending the original, but I think this can be improved in the package itself.

**Comment by Amyx000** [comment]
Assign me this, I can solve the issue related to typescript types

**Comment by SlicedSilver** [comment]
The type is defined that way to ensure that the lines are rendered correctly across different screens with different device pixel ratios. We don't wish to adjust the type to allow decimal widths.

You are free to use a [typescript type assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) in your code to suppress the error.

**Comment by Amyx000** [comment]
Thanks for the clarification @SlicedSilver
