### ISSUE TITLE
iChartApi subscribeClick not working on mobile devices

### ISSUE THREAD

**Issue by ebadran** [tradingview/lightweight-charts#1417]
**Lightweight Charts™ Version: 4.01**

The subscribeClick method is working perfectly on desktop devices. However, it doesn't work on mobile.

**Steps/code to reproduce:**

```
const chart = createChart(chartContainerRef.current, chartOptions);

chart.subscribeClick((param) => {
    console.log(param);
});
```

**Actual behavior:**

Desktop users can see the param values logged to the console when they click on the chart. Nothing is logged when a mobile user taps (or double-taps) on the chart.

The same is true if you tap and hold to enable the crosshair - nothing is logged to the console.

I'm using an iOS device. Haven't tried it on Android.

**Comment by SlicedSilver** [comment]
I've created an (ugly) example which demonstrates that the `subscribeClick` method appears to be working correctly.
https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-wyhhxl

In the example, the chart and line colour will change when you click on the chart. And additionally, it will write the point data at the top of screen.

Here is a video running on an actual device:
https://github.com/tradingview/lightweight-charts/assets/3482679/ae3ef981-578a-4b72-8986-0e5cf29d8fcf
