### ISSUE TITLE
Scrollintoposition is not behaving correctly. Data for the range is not being shown

### ISSUE THREAD

**Issue by IAMAFIVESTARMAN** [tradingview/lightweight-charts#1422]
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
Working as expected: https://codesandbox.io/p/sandbox/lightweight-charts-js-starter-forked-g3hshf?file=%2Fsrc%2Fmain.js%3A1%2C1

```
setTimeout(() => {
  chart.timeScale().scrollToPosition(-200, true);
}, 2000);
```
