### ISSUE TITLE
ScrollToposition is not behaving correctly. Data for the range is not being shown. The chart becomes empty with very thin data visible yet data is scrollable behind the chart 

### ISSUE THREAD

**Issue by IAMAFIVESTARMAN** [tradingview/lightweight-charts#1423]
**Lightweight Charts™ Version:**  :  "^4.0.1",

**Steps/code to reproduce:**

useEffect for your reference : 

```
import React, { useEffect, useState, useRef } from "react";
import { MouseEventParams, createChart } from "lightweight-charts";
import { IChartApi } from "lightweight-charts";

import { ChartCandle } from "../types/typesAndEnums";
import { useLastCandleData } from "../hooks/useLastData";
type ChartData = {
  chartData: ChartCandle[];
  timeDuration: string;
};

const LightweightChart = ({ chartData, timeDuration }: ChartData) => {
  const chartContainerRef = useRef<HTMLDivElement>(null);
  // const [candlePrice, setCandlePrice] = useState<any>(null);

  const chart = useRef<IChartApi | null>(null);
  const candleSeries = useRef<any>(null);
  const HistogramSeries = useRef<any>(null);

  chartData.sort((a, b) => a.time - b.time);

  const { lastCandle } = useLastCandleData(timeDuration);

  // console.log("candle stick rendered");

  // console.log(lastCandle);

  useEffect(() => {
    chart.current = createChart(chartContainerRef.current!, {
      timeScale: {
        timeVisible: true,
        secondsVisible: false,
      },

      width: 1600,
      height: 500,
      autoSize: true,
      layout: {
        background: { color: "#121723" },
        textColor: "#8b969f",
      },
      crosshair: {
        mode: 0, // LightweightCharts.CrosshairMode.Normal
      },
      grid: {
        vertLines: { color: "#777", visible: false },
        horzLines: { color: "#777" },
      },
    });



    chart.current.timeScale().fitContent();



    candleSeries.current = chart.current.addCandlestickSeries({
      upColor: "#4bffb5",
      downColor: "#ff4976",
      borderDownColor: "#ff4976",
      borderUpColor: "#4bffb5",
      wickDownColor: "#ff4976",
      wickUpColor: "#4bffb5",
    });
    // HistogramSeries.current = chart.current.addHistogramSeries({
    //   priceFormat: {
    //     type: "volume",
    //   },
    //   priceScaleId: "",
    // });

    // HistogramSeries.current.priceScale().applyOptions({
    //   // set the positioning of the volume series
    //   scaleMargins: {
    //     top: 0.65, // highest point of the series will be 70% away from the top
    //     bottom: 0, // lowest point will be at the very bottom.
    //   },
    // });

    // HistogramSeries.current.setData(
    //   chartData.map((bar: ChartCandle) => {
    //     return {
    //       time: bar.time,
    //       value: bar.volume,
    //       color: `${bar.open > bar.close ? "#4bffb560" : "#ff497660"}`,
    //     };
    //   })
    // );

    candleSeries.current.setData(chartData);

    if (Object.keys(lastCandle).length !== 0) {
      console.log(lastCandle);
    }

    // chart.current.subscribeCrosshairMove((param: MouseEventParams) => {
    //   if (param.time) {
    //     setCandlePrice({ ...param.seriesData.get(candleSeries.current) });
    //   }
    // });

    return () => {
      chart.current?.remove();
    };
  }, [chartData]);

  const scrollBackInTime = () => {
    if (chart.current) {
      chart.current!.timeScale().setVisibleLogicalRange({
        from: Math.floor((Date.now() - 21600000) / 1000),
        to: Math.floor(Date.now() / 1000),
      });
    }
  };
  return (
    <>
      <div ref={chartContainerRef} className="relative">
        {/* {candlePrice && (
        <div
          className={`absolute  z-10 -top-4 left-4 ${
            candlePrice.open > candlePrice.close
              ? "text-red-700"
              : "text-green-700"
          }`}
        >{`O:${candlePrice.open} H:${candlePrice.high} L:${candlePrice.low} C:${candlePrice.close} V:$ `}</div>
      )} */}
      </div>
      <div className="flex justify-between w-1/6 py-2">
        <button onClick={scrollBackInTime}>1Y</button>
        <button onClick={scrollBackInTime}>3m</button>
        <button onClick={scrollBackInTime}>1m</button>
        <button onClick={scrollBackInTime}>7d</button>
        <button onClick={scrollBackInTime}>3d</button>
        <button onClick={scrollBackInTime}>6h</button>
        <button onClick={scrollBackInTime}>1h</button>
      </div>
    </>
  );
};

export default LightweightChart;
```

**Actual behavior:**

The initial data from API loads , once 6 hour marker is selected, last 6 hours of data should be show and spread out towards the entire chart

**Expected behavior:**

Hi, I am creating a OHLC Chart in React/Next using BitfinexAPI and wanted to have scroll position to start from from where I specify while still being able to scroll through the entire back chart. However either data isn't taking any space or it's width is not taking the entire chart but just maybe 5%.
Please help 

**Screenshots:**

Expected Behaviour:
![image](https://github.com/tradingview/lightweight-charts/assets/99925216/355d99fa-b3a5-475b-af89-8070f0984ec6)

Actual Behaviour :
![image](https://github.com/tradingview/lightweight-charts/assets/99925216/534a4c30-5ce2-49bf-9531-3917bb32d90d)

**CodeSandbox/JSFiddle/etc link:**

UI Url : https://order-book-ohlc-afmu9nat5-iamafivestarman.vercel.app/
Repo : https://github.com/IAMAFIVESTARMAN/OrderBookOHLC

**Comment by SlicedSilver** [comment]
`setVisibleLogicalRange` expects the `from` and `to` values to be index (logical) values and not time values. So if you had a plot with 500 data points and you wanted to show some data in the middle then you would use something like this:
```js
chart.timeScale().setVisibleLogicalRange({
  from: 100,
  to: 400,
})
```

If you want to use dates then you should use the [`setVisibleRange`](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/ITimeScaleApi#setvisiblerange) method instead. However it is important to note that you must supply time values which exist on the chart. 

You can use [`timeToCoordinate`](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/ITimeScaleApi#timetocoordinate) if you need to convert the time into a coordinate and then you can convert it into a logical ([`coordinateToLogical `](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/ITimeScaleApi#coordinatetological)) for use with the `setVisibleLogicalRange` method (instead of `setVisibleRange`)

**Comment by IAMAFIVESTARMAN** [comment]
Hi, so I put timestamps greater than said time duration and found the first index to satisfy and put from index as that. The number of chart entries are 10000 but for 5m data duration for one month it's not going back one month, stopping at just 10-12 days before even though the data is present

URL : https://trading-few.vercel.app/Ohlcchart , select data range as 1M=1 month and time duration as 5m = 5 minutes

![image](https://github.com/tradingview/lightweight-charts/assets/99925216/df88826b-ef79-4a87-a544-b5b4e59605e0)

RepoLink : https://github.com/IAMAFIVESTARMAN/TradingFew

**Comment by SlicedSilver** [comment]
In this case it is most likely because of the minimum bar spacing. This essentially limits the zoom level so that each point can not be smaller than one pixel wide. You can change this setting here: https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/TimeScaleOptions#minbarspacing

Make sure that the number isn't zero, but if you make it something like `0.001` then the library will be able to draw more candles on the screen.
