### ISSUE TITLE
generateCandlestickData undefined

### ISSUE THREAD

**Issue by maulidailham** [tradingview/lightweight-charts#1425]
**Steps/code to reproduce:**

just following the tutorial here:
https://tradingview.github.io/lightweight-charts/tutorials/customization/creating-a-chart

**Actual behavior:**
```
lightweight.js:7 Uncaught ReferenceError: generateCandlestickData is not defined
    at HTMLDocument.<anonymous> (lightweight.js:7:29)
```

**Expected behavior:**

boilerplate code should be working fine. alas the documentation / tutorial needs an update

**Comment by edew** [comment]
Hi.

I believe the idea is that you provide your own data in this case, but the documentation could be clearer about that.

If you want to use the same sample data that the tutorial does you can see the definition of the function here https://github.com/tradingview/lightweight-charts/blob/master/website/tutorials/customization/assets/step1.html#L30

**Comment by SlicedSilver** [comment]
There is a note at the very top of the page (which you provided as a link):
> If you haven't already, please read the [Introduction](https://tradingview.github.io/lightweight-charts/tutorials/customization/intro). At the bottom of that page, you will find a starting file containing everything you need to get up and running with this tutorial (including some sample data to display on the chart).

The complete code (https://tradingview.github.io/lightweight-charts/tutorials/customization/creating-a-chart#complete-code) includes the `generateCandlestickData()` method.
