### ISSUE TITLE
lineStyle has no effect on grid lines

### ISSUE THREAD

**Issue by ingria** [tradingview/lightweight-charts#1436]
**Lightweight Charts Version:**
4.1.0

**Steps/code to reproduce:**

Add `lineStyle` to grid options:

```js
const chart = LightweightCharts.createChart(document.body, {
  grid: {
    vertLines: {
      color: 'red',
      lineStyle: 2,
    },
    horzLines: {
      color: 'blue',
      lineStyle: 3,
    },
  },
});
```

**Actual behavior:**

Lines are solid no matter what value `lineStyle` has

**Expected behavior:**

Line style changes according to the [interface](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/GridLineOptions)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/onpd3y85/1/

**Comment by mozeryansky** [comment]
I'm not a maintainer but for grid options, it's `style` not `lineStyle`:
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/GridLineOptions#style

I verified using your JSFiddle:
<img width="1033" alt="Screen Shot 2023-10-10 at 12 12 34 AM" src="https://github.com/tradingview/lightweight-charts/assets/3287719/0b590045-3a18-4432-afec-bd63446cf96f">

`LineStyleOptions` uses `lineStyle`, but `GridLineOptions` uses `style`.

**Comment by ingria** [comment]
Thanks, seems I've got confused by similar interface names and props
