### ISSUE TITLE
Firefox freezes when resizing

### ISSUE THREAD

**Issue by mozeryansky** [tradingview/lightweight-charts#1439]
**Lightweight Charts™ Version:** 4.1.0

**Steps/code to reproduce:**

Using the React Simple example as is from: https://tradingview.github.io/lightweight-charts/tutorials/react/simple

**Actual behavior:**

I'm reproducing on the latest Firefox and I can't reproduce on Chrome, but the window will freeze and show a spinner. I have to close the tab. I've isolated this issue to calling the resize handler repeatedly. Also tradingview.com and using widgets work perfectly fine.

Do I need to use ResizeObserver instead? (how?)

**Expected behavior:**

Work fine.

**Screenshots:**

Page freezes, nothing special to see.

**CodeSandbox/JSFiddle/etc link:**

NextJS app with component copy/pasted from the example above.

**Comment by SlicedSilver** [comment]
Related: https://github.com/tradingview/lightweight-charts/issues/1429

It is most likely a bug in the specific React example. The example is just showing the minimal amount to get a chart working in React, and I'm certain there are many optimisations which can be done to improve the performance.

The library does support an autosize setting which might be a better fit for this type of behaviour. https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptionsBase#autosize

However, it is our plan to provide an updated example for React before the next release as it is within our next milestone.

**Comment by mozeryansky** [comment]
I've removed the resize listener calls and now use `autoSize: true`. This fixed my css issue, but even after disabling React Strict Mode (which simulates add/remove/add for the memory bug) I still see the issue. It's much harder to reproduce, but I was also able to reproduce on tradingview.com once. So there may be an underlying issue, but it seems to be more on Firefox's side. I've filed a bug there as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1858047

My main problem with this is the page hangs and refresh doesn't fix it, so the ux is terrible.

**Comment by patrickcook28** [comment]
I had a similar problem. Try adding the changes I made here: https://github.com/tradingview/lightweight-charts/issues/1429

**Comment by mozeryansky** [comment]
@patrickcook28 I'm not sure this bug is related to yours. I mentioned above I tried non-strict mode in reference to your memory issue and still had my browser hang issue. Also I'm using the simple example.

I tried to set the IChartAPI reference to null anyway, but I don't think it matters as the const isn't referenced outside. Here's my use: is this the changes your suggest?
```
  // note: for reference in this issue only, don't use
  useLayoutEffect(() => {
    console.log('add')
    let chart: IChartApi | null = createChart(chartContainerRef.current!, { //  <-- let, and typed to allow null
      layout: {
        background: { type: ColorType.Solid, color: backgroundColor },
        textColor,
      },
      width: chartContainerRef.current!.clientWidth,
      height,
      autoSize: true,
    })
    chart.timeScale().fitContent()

    const newSeries = chart.addAreaSeries({
      lineColor,
      topColor: areaTopColor,
      bottomColor: areaBottomColor,
    })
    newSeries.setData(data)

    return () => {
      console.log('remove')
      chart?.remove()
      chart = null //                 <-- set to null after remove
    }
  }, [
    data,
    height,
    backgroundColor,
    lineColor,
    textColor,
    areaTopColor,
    areaBottomColor,
  ])
```

With strict mode I see logged 'add'/'remove'/'add' as expected, and I don't see anymore add/removes being logged when resizing. I wouldn't expect the chart to be removed on resize anyway.

My issue comes from resizing back and forth a few times and then the page hangs, I'll then see this in Firefox:
<img width="560" alt="Screen Shot 2023-10-11 at 7 19 39 PM" src="https://github.com/tradingview/lightweight-charts/assets/3287719/a5f61705-bf12-4049-a943-30378ba25d86">

I'm not sure if there's an underlying issue within the library causing this.

**Comment by SlicedSilver** [comment]
Ideally, you would only want to create the chart once (`createChart`) and then make any further changes via the `applyOptions()` methods on the chart, series,... instances.

Is your code creating the chart more than once?

And if you've set `autosize` then you can remove the need to specify the `height` property in the chart options. It can be used as a fallback, but I doubt you actually want it to be in the array of the useEffect. (there is a method to check if autosize is active and working: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#autosizeactive)
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptionsBase#autosize

**Comment by mozeryansky** [comment]
@SlicedSilver Sorry for the confusion, I was responding to @patrickcook28's suggestion. I'll delete my comment as it was just a response to his suggestion, and I am only creating the chart once and it appears patrick was creating it many times, and the the height property is unused.

I do believe the issue you linked is unrelated.

**Comment by mozeryansky** [comment]
To update on this, Firefox confirmed the bug and has made a fix. The latest version is v119 and is still affected, but the fix will be in v120 and currently is in the Nightly release.
