### ISSUE TITLE
The chart can't start from the left 

### ISSUE THREAD

**Issue by ReshmaDotin** [tradingview/lightweight-charts#144]
Hi, lightweight-charts team
I am facing an issue with lightweight-charts. I want to display my chart from left edge, I used
`fixLeftEdge: true`,  but it won't make the chart start on the left.

**Comment by timocov** [comment]
Can you provide link to jsfiddle/minimal repro of your problem?

**Comment by dotintechno** [comment]
[https://jsfiddle.net/t7rahbxn/](https://jsfiddle.net/t7rahbxn/)
![DeepinScreenshot_select-area_20190725153953](https://user-images.githubusercontent.com/34878080/61866414-b8f6a000-aef2-11e9-98fc-f26058b63ce0.png)
Currently, it is aligned to the right. Is it possible to move the chart to the left like this?
![DeepinScreenshot_select-area_20190725154017](https://user-images.githubusercontent.com/34878080/61866495-daf02280-aef2-11e9-8582-01bd30c187f9.png)

**Comment by timocov** [comment]
It looks like a bug. As workaround you can try to apply this option after data is set - `chart.timeScale().applyOptions({ fixLeftEdge: true });` (but currently it moved chart a little, we'll fix it too).

**Comment by dotintechno** [comment]
Thanks for the quick response and this wonderful library.
