### ISSUE TITLE
Screen Reader Support

### ISSUE THREAD

**Issue by ChristopherJohnson25** [tradingview/lightweight-charts#1440]
Please add screen reader support. Advanced charts just added this in v26.002 (keyboard chart navigation). Can we expect it to be supported here? Thank you!

**Comment by SlicedSilver** [comment]
What would you expect this screen reader support to provide?

Are you asking about keyboard navigation, or descriptions of the chart?

Lightweight Charts is a single chart which is created within the element you provide on the page. You could add accessibility attributes to that element to support screen reader descriptions of the chart.
If you need to provide interactive actions via the screen reader then we recommend creating additional buttons on the page (which could be visually hidden but that the screen reader would notice) that perform the actions you want to make available.

For example, you could add a button with the label description of 'Scroll Chart To Realtime', and then have the click event handler for that button evoke the [scrollToRealtime](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#scrolltorealtime) method (`chart.timeScale().scrollToRealtime()`)

```html
<button
  class="hidden-button"
  onclick="myFunction()"
>Scroll Chart To Realtime</button>
```

**Comment by ChristopherJohnson25** [comment]
@SlicedSilver - this is helpful, thank you. 

Do you have any thoughts on keyboard navigation through each point in the chart?

**Comment by ChristopherJohnson25** [comment]
Sorry for the delay, thanks @SlicedSilver!

**Comment by SlicedSilver** [comment]
FYI: https://tradingview.github.io/lightweight-charts/tutorials/a11y/intro

**Comment by ChristopherJohnson25** [comment]
Excellent, thank you!
