### ISSUE TITLE
Method to listen to changes in the priceScale (left, right or both)

### ISSUE THREAD

**Issue by roysupriyo10** [tradingview/lightweight-charts#1442]
I would like to know if there is any option or method that lets me listen to the top most and bottom most values of the `priceScale` that is currently registered.

I would like get the maximum and minimum values of the `rightPriceScale` and listen to scaling changes made by the user and get the updated minimum and maximum values. I hope I have made myself clear enough.

I can get this functionality by using the `coordinateToPrice` method and listen to changes in `timeScale` but it is a little hectic to do so and it does not detect any changes when only the `priceScale` is scaled up or down.

I would like to know if this functionality already exists or if there is any plan to add so in the future.

**Comment by SlicedSilver** [comment]
There isn't currently a direct method to achieve this using the API.
However, it is also possible to implement a utility plugin that provides this functionality. As Plugins are a new feature in the library, I took this opportunity to create a plugin specifically for that purpose. This allows us to start growing the list of plugins available for Lightweight Charts. 🌱

The new plugin is available here: [SlicedSilver/lwc-plugin-visible-price-range-util](https://github.com/SlicedSilver/lwc-plugin-visible-price-range-util)

and can be installed via npm:
```bash
npm install lwc-plugin-visible-price-range-util
```

The plugin works by attaching to a series, and whenever there is an update to the chart which would require rendering then it measures the price range and emits an event if it has changed.

The one thing that a plugin can do that isn't exposed via the normal API is be notified whenever any visual update has been made to chart. The rest of the plugin is using a similar approach to what you tried (using `coordinateToPrice`).

You can learn more about Plugins here: https://tradingview.github.io/lightweight-charts/docs/plugins/intro

**Comment by roysupriyo10** [comment]
> There isn't currently a direct method to achieve this using the API. However, it is also possible to implement a utility plugin that provides this functionality. As Plugins are a new feature in the library, I took this opportunity to create a plugin specifically for that purpose. This allows us to start growing the list of plugins available for Lightweight Charts. 🌱
> 
> The new plugin is available here: [SlicedSilver/lwc-plugin-visible-price-range-util](https://github.com/SlicedSilver/lwc-plugin-visible-price-range-util)
> 
> and can be installed via npm:
> 
> ```shell
> npm install lwc-plugin-visible-price-range-util
> ```
> 
> The plugin works by attaching to a series, and whenever there is an update to the chart which would require rendering then it measures the price range and emits an event if it has changed.
> 
> The one thing that a plugin can do that isn't exposed via the normal API is be notified whenever any visual update has been made to chart. The rest of the plugin is using a similar approach to what you tried (using `coordinateToPrice`).
> 
> You can learn more about Plugins here: https://tradingview.github.io/lightweight-charts/docs/plugins/intro

I see. Thank you for your effort into this. This a nice piece of abstraction to use instead of all the `coordinateToPrice`.
