### ISSUE TITLE
Chart not shifting with new data (shiftVisibleRangeOnNewBar not working)

### ISSUE THREAD

**Issue by AndreasSjodin** [tradingview/lightweight-charts#1443]
**Lightweight Charts™ Version:** 4.1.0

**Steps/code to reproduce:**

Appending data to an existing serie via .update(), see JSFiddle below.

**Actual behavior:**

Series does not shift.

**Expected behavior:**

Series should shift, showing new data. 
E.g. as in [https://jsfiddle.net/TradingView/yozeu6k1/](https://jsfiddle.net/TradingView/yozeu6k1/)

**CodeSandbox/JSFiddle/etc link:**

4.0.1 working: [https://jsfiddle.net/TradingView/yozeu6k1/](https://jsfiddle.net/TradingView/yozeu6k1/)
4.1.0 broken: [https://jsfiddle.net/5a1w6e4f/](https://jsfiddle.net/5a1w6e4f/)

I believe the fix #1431 for issue #1201 broke the intended original functionality of shiftVisibleRangeOnNewBar.

**Comment by SlicedSilver** [comment]
Thanks for reporting this @AndreasSjodin.

We will work on a fix and add more test cases to cover this use-case.
