### ISSUE TITLE
how to vertical alignment the price visible range to the exact price

### ISSUE THREAD

**Issue by liesauer** [tradingview/lightweight-charts#1446]
i have a price percentage change chart, and i want to move the chart to make 0.5%(or any other value) at the middle of the chart, is that possible?

![image](https://github.com/tradingview/lightweight-charts/assets/8676741/1e1a6e76-db91-49ba-bb8f-31c2b04cc6eb)

**Comment by SlicedSilver** [comment]
On the series options, you can specify a [`autoscaleInfoProvider`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#autoscaleinfoprovider) to adjust the default autoscaling behaviour of the series. Using this, you would need to specify a min and max value. So if you specified a min & max of `-2` and `3` then the mid point should be `0.5`

**Comment by liesauer** [comment]
thanks, it works.
