### ISSUE TITLE
Why does my price axis on the right only display the current price? No other prices are displayed?

### ISSUE THREAD

**Issue by silsuer** [tradingview/lightweight-charts#1452]
<img width="336" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/16463031/21e0fbdc-c1b2-47b8-910a-7ed24976e109">

I'm using lightweight3.8 version, my configuration is

```
const defautlConfig = {
    // width: 400,
    height: 390,
    pane: 0,
    layout: {
        background: {
            type: 'solid',
            color: 'rgb(20,23,34)',
        },
        textColor: 'rgba(255, 255, 255, 0.9)',
    },
    grid: {
        vertLines: {
            color: 'rgba(200,200,200,0.1)'
        },
        horzLines: {
            color: 'rgba(200,200,200,0.1)'
        },
    },
    leftPriceScale: {
        // visible: true,
        color: '#ffffff'
    },
    rightPriceScale: {
        visible: true,
        ticksVisible: true,
        textColor: 'rgba(197, 203, 206, 1)',
        borderColor: 'rgba(197, 203, 206, 0.4)',
    },
    crosshair: {
        horzLine: {
            visible: true,
        }
    },
    handleScroll: {
        mouseWheel: true,
        pressedMouseMove: true,
        horzTouchDrag: true,
        // vertTouchDrag: true,
    },
    scaleMargins: {
        top: 0,
        bottom: 0.25
    },
    timeScale: {
        timeVisible: true,
        tickMarkFormatter: (time) => {
            return formatTimeString(time * 1000, false, true, true)
        }
    },
    localization: {
        priceFormatter: function (price) {
            return converToNumberString(price)
        },
        timeFormatter: function (time) {
            return formatTimeString(time * 1000, false, true)
        }

    }
}
```

At this time, only the closing price of the last candle will be displayed on my right price axis, and nearby prices will not be displayed. What should I do?

**Comment by SlicedSilver** [comment]
The tick marks on the price scale are built from the configuration of the [`priceformat`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat) for that series (which is part of the series options). 

You would most likely be wanting to use the built-in formatter which has it's options defined here: [PriceFormatBuiltIn ](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn)

example (you should experiment with the settings to see what works best for you):
```js
const chart = LightweightCharts.createChart(document.getElementById('container'));

const mainSeries = chart.addLineSeries({
	priceFormat: {
		minMove: 0.0001,
		precision: 5,
	},
});
```

**Comment by silsuer** [comment]
> The tick marks on the price scale are built from the configuration of the [`priceformat`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat) for that series (which is part of the series options).
> 
> You would most likely be wanting to use the built-in formatter which has it's options defined here: [PriceFormatBuiltIn ](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn)
> 
> example (you should experiment with the settings to see what works best for you):
> 
> ```js
> const chart = LightweightCharts.createChart(document.getElementById('container'));
> 
> const mainSeries = chart.addLineSeries({
> 	priceFormat: {
> 		minMove: 0.0001,
> 		precision: 5,
> 	},
> });
> ```

No, I'm sorry my description wasn't accurate enough.

for example:

<img width="338" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/16463031/7148089d-0d2b-44f1-992f-b7d5044390f1">

Here are the icons on other products, which have some other prices besides the current price


<img width="336" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/16463031/355dd6bf-d830-4307-a571-8965f0e6ced9">


⬆️ In my product, there is only the current price, and the other positions are empty.

I want to know how I can modify my configuration file so that the chart looks the same as the first picture?

thanks for your answer 🙏🙏🙏

**Comment by SlicedSilver** [comment]
Adding the `priceFormat` options for the series is required so the library knows where to place tick marks on the price scale. You can then use your existing priceFormatter (in the chart options) to change how the number is displayed.

```ts
const chart = createChart("container", {
  autoSize: true,
  localization: {
    priceFormatter: function (price: number) {
      return (
        price
          .toFixed(5)
          // /^0\.0+([1-9])(\d*)$/
          .replace(/^0\.0+([1-9])(\d*?)0*$/, (match, g1, g2) => {
            return `0.0{${g1}}${g2}`;
          })
      );
    },
  },
});

const mainSeries = chart.addLineSeries({
  priceFormat: {
    minMove: 0.00001,
    precision: 5,
  },
});
```

Example: https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-kcrnkf

**Comment by silsuer** [comment]
> Adding the `priceFormat` options for the series is required so the library knows where to place tick marks on the price scale. You can then use your existing priceFormatter (in the chart options) to change how the number is displayed.
> 
> ```ts
> const chart = createChart("container", {
>   autoSize: true,
>   localization: {
>     priceFormatter: function (price: number) {
>       return (
>         price
>           .toFixed(5)
>           // /^0\.0+([1-9])(\d*)$/
>           .replace(/^0\.0+([1-9])(\d*?)0*$/, (match, g1, g2) => {
>             return `0.0{${g1}}${g2}`;
>           })
>       );
>     },
>   },
> });
> 
> const mainSeries = chart.addLineSeries({
>   priceFormat: {
>     minMove: 0.00001,
>     precision: 5,
>   },
> });
> ```
> 
> Example: https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-kcrnkf

Thank you for your reply, but the problem I have is not the formatting of the prices, but a lot of prices missing in my icons. Please see my comparison chart above, I am using version 3.8, and my icons only have the current price, no Other prices selected in the picture

**Comment by SlicedSilver** [comment]
> The tick marks on the price scale are built from the configuration of the [priceformat](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat) for that series (which is part of the series options).

👆

> Example: https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-kcrnkf

The example I provided also works on `3.8`

If you are still having problems then can you please create a codesandox / jsFiddle example showing the problem.

**Comment by silsuer** [comment]
> > The tick marks on the price scale are built from the configuration of the [priceformat](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat) for that series (which is part of the series options).
> 
> 👆
> 
> > Example: https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-kcrnkf
> 
> The example I provided also works on `3.8`
> 
> If you are still having problems then can you please create a codesandox / jsFiddle example showing the problem.

I probably understand what the problem is.

<img width="1230" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/16463031/791cfb71-ebf2-43b2-a612-691fdd7bfb76">


After I reduced all the data uniformly by 10000000 times, the situation in the picture above appeared. There is only one price and no other prices. What should I do?


Below is my data on codesandbox:

```
function generateData(): (LineData | WhitespaceData)[] {
  return [
    { time: '2018-12-22', open: 75.16, high: 82.84, low: 36.16, close: 45.72 },
    { time: '2018-12-23', open: 45.12, high: 53.90, low: 45.12, close: 48.09 },
    { time: '2018-12-24', open: 60.71, high: 60.71, low: 53.39, close: 59.29 },
    { time: '2018-12-25', open: 68.26, high: 68.26, low: 59.04, close: 60.50 },
    { time: '2018-12-26', open: 67.71, high: 105.85, low: 66.67, close: 91.04 },
    { time: '2018-12-27', open: 91.04, high: 121.40, low: 82.70, close: 111.40 },
    { time: '2018-12-28', open: 111.51, high: 142.83, low: 103.34, close: 131.25 },
    { time: '2018-12-29', open: 131.33, high: 151.17, low: 77.68, close: 96.43 },
    { time: '2018-12-30', open: 106.33, high: 110.20, low: 90.39, close: 98.10 },
    { time: '2018-12-31', open: 109.87, high: 114.69, low: 85.66, close: 111.26 },
  ].map(item => {
    return {
        open: item.open / 10000000,
        high: item.high / 10000000,
        low: item.low / 10000000,
        close: item.close / 10000000,
        time: item.time

    }
})


}
```

**Comment by SlicedSilver** [comment]
> Below is my data on codesandbox:

Please share your code sandbox example so I can confirm that the `priceFormat` settings have been applied.
