### ISSUE TITLE
Missing Time Scale API in the docs

### ISSUE THREAD

**Issue by plagueinside** [tradingview/lightweight-charts#146]
Do we have the ability to programmatically set the zoom? I mean smth like that:
timeScale{
   start: '2019-08-07',
   end: '2019-08-08'
}

I found:
chart.timeScale()._model.setTimePointsRange(), but it doesn't work for me. 
Is it possible to set the start and end points for zoom?

**Comment by timocov** [comment]
Hm, we missed that in the docs. You can see usage of setting custom visible range in tests - https://github.com/tradingview/lightweight-charts/blob/2fc2bb2186aa733bb7c189bfb00264ce54346e75/tests/e2e/graphics/test-cases/set-visible-range.js#L23-L26

Here is declaration for that method https://github.com/tradingview/lightweight-charts/blob/2fc2bb2186aa733bb7c189bfb00264ce54346e75/src/api/itime-scale-api.ts#L42
