### ISSUE TITLE
Issue with price formatting in percentage mode

### ISSUE THREAD

**Issue by mhadikazemian** [tradingview/lightweight-charts#1461]
**Lightweight Charts™ Version: 4.1.1** 

**Description:**

I am encountering an issue with formatting the labels on the price scale (and eventually the text inside the colored box where the charts meet the price scale), specifically when the price scale mode is set to percentage. Despite the information provided in previous issues ([#1328](https://github.com/tradingview/lightweight-charts/issues/1328) and [#1291](https://github.com/tradingview/lightweight-charts/issues/1291)), the suggested solution of using priceFormatter to format the price scale labels while in percentage mode does not seem to be working as expected.

**Steps/code to reproduce:**

1. Set the price scale mode to percentage.
2. Use priceFormatter to format the price scale labels.
3. Observe that the formatting is not applied to the price scale labels.

**Actual behavior:**

The formatting applied using priceFormatter does not affect the price scale labels (and the text inside the colored box), and it only displays the percentage.

**Expected behavior:**

1. I expect to be able to format the price scale labels while using the percentage mode. 
2. My final goal is to only modify the text inside the colored box, while in percentage mode and would like to show the correlated chart's symbol (title) next to the percentage in the colored box. This would enable different symbols for each chart.

**CodeSandbox/JSFiddle/etc link:**

Here's the desired result, except it should be in percentage mode, and the format should only apply on the colored box [JSFiddle Link](https://jsfiddle.net/1tgmbo4q/1/)

**Note:**

Please let me know if there is any additional information needed or if there are alternative approaches to achieving the desired formatting in the colored box while in percentage mode. Thank you.

**Comment by SlicedSilver** [comment]
Have you been able to try the [`percentageFormatter`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LocalizationOptions#percentageformatter) within the Localization settings?

**Comment by mhadikazemian** [comment]
> Have you been able to try the [`percentageFormatter`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LocalizationOptions#percentageformatter) within the Localization settings?

Thank you for your prompt response. The use of `percentageFormatter` in the Localization settings, resolved my formatting issue in percentage mode.
