### ISSUE TITLE
Smooth animation on series chart with live data

### ISSUE THREAD

**Issue by Ahtisham-01** [tradingview/lightweight-charts#1465]
![yyyyy](https://github.com/tradingview/lightweight-charts/assets/108873543/dbf23b3f-1b00-4bb9-974b-4abd447c7289)
the animation is not going smoothly it just jumps from one point to another.
How to add buffer animation when price jumps

**Comment by carvinlo** [comment]
Any recent plans to enhance smooth animation for this great project?

**Comment by SlicedSilver** [comment]
There are no plans in motion for changing the live data update animations.
