### ISSUE TITLE
Priceline cant be deleted

### ISSUE THREAD

**Issue by rashearth** [tradingview/lightweight-charts#1467]
Hi, 
I tried to delete the priceline by using the below code 
```
chart.addLineSeries({color: '#0068ff',lineWidth: 2,priceLineVisible: false, lastValueVisible: false,});
```
But as seen in the fiddle,  it wont work.
Is this a bug?
https://jsfiddle.net/ktjfcpu3/13/

What am i missing...

**Comment by SlicedSilver** [comment]
The API for a series (described here: [ISeriesApi](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi)) has the following methods:
- [createPriceLine](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#createpriceline)
- [removePriceLine](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#removepriceline)

You can create and then remove a priceline as follows:
```js
// create a priceline
const myPriceLine = series.createPriceLine({ price: 80.0 });

// and then later remove it
series.removePriceLine(myPriceLine);
```

One possible source of confusion could be that a series can show a [priceline for the latest value](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#pricelinevisible). This is what the series options around price lines is for. But this is not the same as the pricelines created separately with the `createPriceLine` method, those need to be removed via `removePriceLine`.
