### ISSUE TITLE
A fixed or variable name for the lightweight chart window

### ISSUE THREAD

**Issue by AltePfeife** [tradingview/lightweight-charts#1469]
![window1](https://github.com/tradingview/lightweight-charts/assets/72685817/f8243c19-29e5-43de-bd92-f165d4da2d6a)

Is it possible to give the lightweight chart window a fixed or variable name?

If I run several Python scripts with VS Code and several lightweight chart windows open, I quickly lose track of which window belongs to which code. It would be very helpful if you could give the respective windows fixed/variable names (see picture)

**Comment by SlicedSilver** [comment]
The name 'WINDOW 1' is not coming from the Lightweight Charts library. It is most likely coming from within your Python code (or the Python library you are using).

Lightweight Charts is only creating the chart within the DOM elements (container elements passed to the chart constructors) on the HTML page. Everything else above that like the rest of the page HTML, and the window is handled outside of the scope of the library.

**Comment by AltePfeife** [comment]
Exactly, I added the name WINDOW 1 using Photoshop so that you can see the problem of the missing window name. If I understand correctly, lightweight charts itself cannot assign its own names for the window, correct?

**Comment by SlicedSilver** [comment]
>  If I understand correctly, lightweight charts itself cannot assign its own names for the window, correct?

Yes, that is correct. This issue isn't related to the library itself, and should be fixed within the Python code.
