### ISSUE TITLE
Custom bar spacing per series

### ISSUE THREAD

**Issue by t-anyu** [tradingview/lightweight-charts#1470]
**Is your feature request related to a problem? Please describe.**

When plotting candlestick/bar series and line series with different timeframes, the chart tends to calculate spacing based on the lowest interval, which is very logical. However for example I plot candlestick with 5min data and draw a line with 10s data, the candlesticks are very narrow.

**Describe the solution you'd like**

Could there be an option to de-couple bar spacing / bar width, as I assume this problem only affects series with bars and not lines.

Thanks

**Comment by SlicedSilver** [comment]
> Could there be an option to de-couple bar spacing / bar width, as I assume this problem only affects series with bars and not lines.

This wouldn't be possible with this library due to it's internal design. So it is not currently planned to implement this as a feature / update.
