### ISSUE TITLE
visible: false disables scaleMargins in priceScale

### ISSUE THREAD

**Issue by GabGett** [tradingview/lightweight-charts#1473]
**Lightweight Charts™ Version:** 4.1.1

**Steps/code to reproduce:**

Set custom margins and visible: false in priceScale options in CandleChart

```js
rightPriceScale: {
    scaleMargins: {
        top: 0.1,
        bottom: 0.1,
    },
    visible: false, // this seems to disable scaleMargins :/
},
```

**Actual behavior:**

Setting visible: false in priceScale disables scaleMargins

**Expected behavior:**

Keep the custom margins even if priceScale is not visible

**CodeSandbox/JSFiddle/etc link:**

[https://jsfiddle.net/tybusmao/](https://jsfiddle.net/tybusmao/)

**Comment by SlicedSilver** [comment]
If you don't want to have the price scale visible then you would probably want to use an 'overlay' price scale instead.

If the priceScaleId for a series is not `left` or `right` then it will be an overlay scale (which don't have a visible price scale). [Docs](https://tradingview.github.io/lightweight-charts/docs/price-scale)

You can access the [`IPriceScaleApi`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPriceScaleApi) for any price scale via the [`priceScale`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#pricescale) method on the [`IChartApi`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi), and apply options for that scale via [`applyOptions`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPriceScaleApi#applyoptions).

```js
const chart = createChart('container', {
	rightPriceScale: {
		visible: false,
	},
	leftPriceScale: {
		visible: false,
	},
});

const candleSeries = chart.addCandlestickSeries({
	priceScaleId: 'my-overlay'
});

const priceScale = chart.priceScale('my-overlay');
priceScale.applyOptions({
	scaleMargins: {
		top: 0,
		bottom: 0,
	},
});
```

**Comment by GabGett** [comment]
Thank you, that works perfectly.

I didn't realize overlay scales didn't have a visible price scale.
