### ISSUE TITLE
IPriceScaleApi needs setVisibleRange and getVisibleRange methods

### ISSUE THREAD

**Issue by dkvirus** [tradingview/lightweight-charts#1479]
**Is your feature request related to a problem? Please describe.**

step1: Using lightweight-charts we created a diagram
step2: We manually changed time scale and price scale
step3: We changed the api query conditions, and the data above the graph will also change
step4: We want to keep the Settings(time scale and price scale) we selected last time

I have seen that the ITimeScaleApi includes getVisibleRange and setVisibleRange methods, it's good, I can keep the time scale that we selected last time.

But I can't find getVisibleRange and setVisibleRange methods in IPriceScaleApi, so I can't keep the price scale that we selected last time.

I've been reading the source code for a week and haven't found any way to do this. 
Can someone tell me what to do? It's also good to give a hint.

**Comment by SlicedSilver** [comment]
There isn't a direct way to read or set the visible range for the price scale. Typically the price scale has an autoscale behaviour (to fit all the content nicely on the chart). This autoscale behaviour can be adjusted (such as controlling the margins), and it is also possible for each series to have the autoscale calculation be overridden so you can specify the visible range you would like to use. 

- [autoScaleInfoProvider](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#autoscaleinfoprovider)

It is possible for the user to click and drag on the price scale so they can disable autoscale and control the vertical pricing scaling themselves but while autoScale is active it is possible to use the above option to gain more control over the price scaling for that specific series.

If you need to read the current visible price range then you can use the [coordinateToPrice](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#coordinatetoprice) method on the SeriesAPI and use `0` and the height of the price scale in pixel as the two coordinates to check and obtain the price values for.

There is also this plugin I've developed for assisting with reading the price range and reacting to changes: https://github.com/SlicedSilver/lwc-plugin-visible-price-range-util

**Comment by dkvirus** [comment]
Thanks for the reply, which provided some useful information. I will continue to make some attempts.
