### ISSUE TITLE
Changing the time of last point is not moving the point

### ISSUE THREAD

**Issue by raul1ro** [tradingview/lightweight-charts#1483]
To reduce the usage of RAM and also CPU usage in some cases (calculating some stats based on data from lines).
Before adding (update) a new point, I am checking if the last point has the same value.
If the last point has the same value, I am just changing the time of the last point. And no longer add a new point.

The issue at doing this is that the last point is not moving more right, to increase the length between the last point and the second last point, to maintain the same scale.

Visual sample:
![chartChangeTime](https://github.com/tradingview/lightweight-charts/assets/23010750/4cdeca69-b9a2-420a-a884-5ace4f1302fc)

JSFiddle: https://jsfiddle.net/L5d72ujk/

Someone has any idea how to fix this?

**Comment by raul1ro** [comment]
Even if I set the last point `{ time: time5sAgo + 99999999999500, value: 13 }` 
The distance between points is not equal:
![Screenshot 2023-12-22 185442](https://github.com/tradingview/lightweight-charts/assets/23010750/20bbdd8f-ddd6-4998-b137-1ea2746a4c1e)

**Comment by SlicedSilver** [comment]
The time scale isn't linear but rather there is a fixed width for each data point. So the distance between each data point will always be the same even if the time between those points are different.

For your use-case I would suggest adding a new data point even if the values haven't changed.
