### ISSUE TITLE
about zoom out limitation.

### ISSUE THREAD

**Issue by wangtae** [tradingview/lightweight-charts#1488]
Compared to 'trading view', 'lightweight chart' has less 'zoom out'.

It's about a quarter.

So I can't see 20 years of data on one screen.

Is there any way to solve these problems?

<img width="1883" alt="캡처" src="https://github.com/tradingview/lightweight-charts/assets/8221486/ac0eef5b-5945-44c5-ab86-0f799a28933c">

**Comment by SlicedSilver** [comment]
The [`minBarSpacing`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/HorzScaleOptions#minbarspacing) setting for the time scale defines the limit for zooming out. If you make this number smaller (but must not equal zero) then you will be able to zoom out further.

```js
const chart = createChart(container, { timeScale: { minBarSpacing: 0.05 }});

// or
chart.timeScale().applyOptions({
    minBarSpacing: 0.05,
});
```

The default value is `0.5`.

**Comment by wangtae** [comment]
Thank you very much. ^^
