### ISSUE TITLE
Feature Request - Area Series anchored to price axis

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#149]
Both orderbook depth and market profile are often visualised on the price axis, to give a snapshot of historic volume or current market demand at certain price points.

A couple of examples below:

![image](https://user-images.githubusercontent.com/4056227/61833887-b43bd880-ae6d-11e9-94f8-732018f02b00.png)

![image](https://user-images.githubusercontent.com/4056227/61833988-08df5380-ae6e-11e9-878a-ee7f86b660bb.png)

The capability to map which axis should represent the X values, and the ability to present a rotated series accordingly would be very beneficial

**Comment by timocov** [comment]
Hey @jimeney! Thank you for your suggestion, but unfortunately we won't implement it in the lightweight-charts by some reasons. One of that is it's a little complicated thing for lightweight-charts.
