### ISSUE TITLE
Plugin not responding to data update

### ISSUE THREAD

**Issue by mrzli** [tradingview/lightweight-charts#1491]
**Lightweight Charts™ Version:** 4.1.1

**Steps/code to reproduce:**

Have not tried this myself on your example, but you should be able to reproduce the issue with the change described here.

In the [session highlight example](https://github.com/tradingview/lightweight-charts/blob/86da4820bc2d81126122496ae6c7bca1b98b216a/plugin-examples/src/plugins/session-highlighting/example/example.ts), move `candleSeries.setData(data);` to the end of the file, after `candleSeries.attachPrimitive(sessionHighlighting);`.

```ts
// ...
const candleSeries = chart.addCandlestickSeries();
const data = generateAlternativeCandleData();
// make sure this is commented out or removed to be able to reproduce the problem
// candleSeries.setData(data);

function getDate(time: Time): Date {
// ...
// ...
const sessionHighlighting = new SessionHighlighting(sessionHighlighter);
candleSeries.attachPrimitive(sessionHighlighting);
candleSeries.setData(data);
```

**Actual behavior:**

Session highlighting does not work in the above case - when `attachPrimitive` is called before `setData`.

**Expected behavior:**

It should work :). Plugin should respond to data update.

**Potential solution:**

The issue seems to be caused by this line:

https://github.com/tradingview/lightweight-charts/blob/61d45db057c36c1b0d95e9a0d909fb5a60e5a19f/plugin-examples/src/plugins/plugin-base.ts#L25C5-L25C5

`_fireDataUpdated` is using `this` inside the function body:

```ts
	private _fireDataUpdated(scope: DataChangedScope) {
		if (this.dataUpdated) {
			this.dataUpdated(scope);
		}
	}
```

This `this` is not bound to a `SessionHighlighting` object (which inherits from `PluginBase`), but to something else. That other thing does not have `this.dataUpdated`, and it will always be `undefined`, whether `SessionHiglighting` object defines `dataUpdated` method or not.

Line 25 in `plugin-base.ts` should probably be changed:

```ts
// old
this._series.subscribeDataChanged(this._fireDataUpdated);

// fixed (option 1)
this._series.subscribeDataChanged((scope) => this._fireDataUpdated(scope));

// fixed(option 2)
this._series.subscribeDataChanged(this._fireDataUpdated.bind(this));
```

After the change, `this` inside `_fireDataUpdated` should be properly bound to the `SessionHighlighting` instance.

**Comment by xxprzemoxx** [comment]
I have not received any funds from any address, please transfer the money
to the bank account number...                     BE60 9501 0866 3270 Mr-
PRZEMYSLAW KARCZEWSKI I am waiting for a quick transfer ((((((FINALLY))))
to my bank account and please hurry because I have submitted papers for
fraud regarding cryptocurrencies and their withdrawals... If you still have
any problems in withdrawing this huge amount, please contact me, then you
will be in contact with my team of lawyers from TESTACHA.be. I am waiting
for a positive resolution.... ...

pon., 8 sty 2024 o 11:44 Romain Francois ***@***.***>
napisał(a):

**Comment by xxprzemoxx** [comment]
pon., 8 sty 2024 o 16:26 Przemyslaw Karczewski ***@***.***>
napisał(a):
