### ISSUE TITLE
Plot two axes for same chart

### ISSUE THREAD

**Issue by antter** [tradingview/lightweight-charts#1493]
Hi! New user here, thanks for maintaining this package.

**Is your feature request related to a problem? Please describe.**

I would like to plot two axes for the same chart. One represents the price, and the other is some non-linear (but still monotically increasing) function of price. Some metric of price that is useful to our customers. An example in the chartjs library [is here](https://github.com/chartjs/Chart.js/issues/5414). I'm attaching a screenshot so its clear what the feature is.

<img width="541" alt="Screen Shot 2024-01-10 at 2 19 21 PM" src="https://github.com/tradingview/lightweight-charts/assets/58586369/007b23ee-30bb-4770-8f80-ea3bb62a4af3">

**Describe the solution you'd like**

Not sure what the ideal way to go about this is, but maybe a way to set a "mirror" arg and a `PriceFormatterFn`?

Maybe something like

```
chart.priceScale('left'}.applyOptions({
    mirror: 'right',
    format: MyPriceFormatter
})
```

Looking through the source, it's hard to tell how difficult this is to implement, and what other quirks may arise but I have some progress going on a fork. Let me know if this is something you guys are interested in, I could make a PR if I figure this out.

As far as I can tell this isn't possible with a plugin? A plugin does not allow you to mess with the Axes from what I can see.

**Comment by antter** [comment]
Also note in the example I provided the ticks are different. For my use case they don't need to be, and it removes a lot of the complexity.

**Comment by SlicedSilver** [comment]
I think this example is what you are looking for: [Two Price Scales | Lightweight Charts](https://tradingview.github.io/lightweight-charts/tutorials/how_to/two-price-scales)

> A plugin does not allow you to mess with the Axes from what I can see.

You can use a plugin to implement a completely new axis. As you can see on [this simple example](https://tradingview.github.io/lightweight-charts/docs/plugins/series-primitives#interactive-demo-of-zorder-layers), it is possible to draw anything you want, however re-implementing a price scale in a new plugin wouldn't be the quickest task.

There is also this somewhat similar plugin example of how to create a price scale which appears above the chart: [Lightweight Charts - Overlay Price Scale Plugin Example](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/overlay-price-scale/example/)

**Comment by antter** [comment]
Thanks for the response. It is nice to know I was wrong about not being able to use a plugin to implement a new axis.

The two price scales examples isn't exactly what I'm looking for because each dataset is only attached to one price scale. I briefly thought about making two `LineSeries` with the same data but figured that wouldn't work too well for other reasons. Let me know if I'm misunderstanding that about price scale. Otherwise, I can close and make this as a plugin.

**Comment by antter** [comment]
Ahh looking at it it really may be easier to just continue working on a fork than implementing another price scale. The difficulty is that I don't know where the `PriceMark`s are on the right side, and it would be difficult to coordinate between both scales. Further I do want them to look similar so it would essentially be me copying as much as I can from `PriceAxisWidget`

**Comment by antter** [comment]
Unfortunately I do not have a screenshot but I can describe my use case. The screenshot above, albeit kind of silly
I am plotting gambling odds across different sportsbooks to see if one can find an edge by placing bets on different books. Each sportsbook is a line series. So we are not *exactly* working with financial data.

Idk if you're familiar, but american odds can look like +400, -400. A probability value can be associated with these odds. Here is a table of some values.

| American Odds | Implied Probability (%) |
|---------------|-------------------------|
| -1000         | 90.91                    |
| -500          | 83.33                    |
| -200          | 66.67                    |
| +100          | 50.00                    |
| +200          | 33.33                    |
| +500          | 16.67                    |
| +1000         | 9.09                     |


You can see the scale is nonlinear, and the american odds explode at high/low values of implied probability. Implied probability is really what should be charted, as it corresponds linearly with a gamblers expected value and the values near 1 and 0 do not dwarf all the values in the middle. Two books having a discrepancy of -4000 vs -8000 is not that large; -200 to -600 is quite a massive one though. Charting with american odds on the Y axis just doesn't make much sense.


However sports gamblers who are our end users are quite used to the american odds, and it is important to display the american odds. What we currently do in my prototype is chart implied probability and use a formatter to convert to american odds. But ideally I would want to show both values, with the probability using the other axis. This is the best way to analytically process a discrepancy across books without the user having to do any quick math. It would be the same data, same tick mark locations, just a different formatter.


And yes, it would be easier to use Chartjs for this use case, but our team is going to be making lots of time series charts and we rather like the out of the box features and the UI of this library. Maintaining a fork is indeed a pain which is why I would like to contribute if there is interest in adding this feature. However I understand our use case is nonstandard although I can imagine there is use for showing two metrics of the same data in financial charting as well.

**Comment by SlicedSilver** [comment]
If I understand your goal correctly, you can achieve it by using two different line series and two different price scales.

Plot the exact same data for both line series and assign one series to the left price scale and the other to the right price scale. This will make the lines overlap and appear as a single line. Then, apply a different price formatter to one of the scales to display the numbers differently. Finally, disable the user's ability to manually scale or shift the price scale, ensuring that the lines always stay on top of each other. The resulting chart will resemble this:
https://codesandbox.io/p/sandbox/lwc-mirror-price-scales-js5lxg

**Comment by antter** [comment]
Sorry for the late response. That is what I was experimenting with but I am not a big fan of disabling scaling/shifting. I was able to get decent results on a fork. Let me know if this could be something you're interested in integrating and I can clean it up and open a PR.

**Comment by SlicedSilver** [comment]
If you've got a working fork then we would be interested in having a look. 😊

One of our main concerns with new features, or improvements, is the effect on the bundle size of the library. If the change in bundle size is minimal then it is something that could be merged into the library.

You can check the size with the following commands:
```bash
npm run clean

npm run build:prod

npm run size-limit
```

**Comment by antter** [comment]
sweet! thanks for your quick responses, and you may see a PR from me soon.
