### ISSUE TITLE
Can we change the text color of time scale ?

### ISSUE THREAD

**Issue by Dhan3777** [tradingview/lightweight-charts#1497]
How to change the text color of time scale as there is no option in [TimeScaleOptions](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions)

**Comment by Jordanelis** [comment]
You can change it for both time and price scales. It is the  textColor: 'red' in the following code

this.chart = createChart(this.container, {
      width: 1100,
      height: 600,
     layout: {
        background: { color: 'grey'},
        textColor: 'red',
      },
    });

**Comment by philippe-architect** [comment]
The `createChart` method doesn't have a `textColor` option?
[TimeChartOptions](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeChartOptions)

Any other options?

**Comment by SlicedSilver** [comment]
It is defined within the 'layout' options ([`LayoutOptions`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LayoutOptions)).

For example: https://tradingview.github.io/lightweight-charts/tutorials/customization/chart-colors#adjusting-the-background-and-text-colors-for-the-chart

**Comment by philippe-architect** [comment]
Awesome thank you!
