### ISSUE TITLE
Lightweight Chart price scale issue on adding custom series

### ISSUE THREAD

**Issue by DanishAhmedKhan** [tradingview/lightweight-charts#1498]
I am trying to add a custom series to the chart. When I add the custom series the price scale stretches to a very large value. I tried applying autoScale: true to the price scale, but it did not work.

[Here](https://codepen.io/danishahmedkhan/pen/BabRvQx) is an example demonstrating this issue. Can someone point out what i am doing wrong?

**Comment by SlicedSilver** [comment]
It is most likely that the values provided to priceValueBuilder are incorrect:
- https://tradingview.github.io/lightweight-charts/docs/plugins/custom_series#price-value-builder

> The largest and smallest values in the array will be used to specify the visible range of the painted item, and the last value will be used for the crosshair and price line position.
