### ISSUE TITLE
Add support for importing default chart options

### ISSUE THREAD

**Issue by vad99lord** [tradingview/lightweight-charts#1502]
**Is your feature request related to a problem? Please describe.**

I'm having a set of configurable options that are built around the default options from the chart api. I'd like to have a possibility to extract the defaults from the library, so that if some of the configurable options are turned off dynamically it's possible to easily revert back to a default configuration for these options.

**Describe the solution you'd like**

Expose the defaults for chart options so it's possible to consume it on the client.

**Additional context**

_Example:_ i have a logic that configures price line colors based on the series that are attached to the line, this option may be disabled dynamically, and i'd like to extract the default options to pass to the config in this case.

**Comment by SlicedSilver** [comment]
You can read the default options by creating a chart with no custom options and then using the `options()` method to read the options on that chart:

```js
const chart = createChart('container');
const defaults = chart.options(); // read the default options
chart.remove(); // remove empty chart
```
