### ISSUE TITLE
Exports scalePriceTo, startScalePrice, endScalePrice apis

### ISSUE THREAD

**Issue by zbinlin** [tradingview/lightweight-charts#1507]
I want to handle price scale outside the chart; should it export those APIs for scale?

**Comment by SlicedSilver** [comment]
You could explore the usage of a plugin to expose this data for reading the price scale values. For example: https://github.com/SlicedSilver/lwc-plugin-visible-price-range-util

If you want to control the price scale range programatically then you can use the [autoscaleInfoProvider](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#autoscaleinfoprovider) to control the visible price range unless the user has manually moved the price scale.
