### ISSUE TITLE
Seconds Hours Minutes

### ISSUE THREAD

**Issue by Gloomy1233** [tradingview/lightweight-charts#1512]
Is there anyway to show Hours minutes o seconds cause i only see you can use Days, months , Years

**Comment by tpunt** [comment]
If you're referring to the timescale axis, then you need to configure it via `timeVisible`. Example:
```js
const chart = LightweightCharts.createChart(
  document.getElementById('container'),
  {
    timeScale: {
      timeVisible: true,
    },
  },
);
```

**Comment by SlicedSilver** [comment]
You can use a formatter function for the time:
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LocalizationOptions#timeformatter
