### ISSUE TITLE
How to stop zoom feature ?

### ISSUE THREAD

**Issue by Dhan3777** [tradingview/lightweight-charts#1522]
I want chart to stay put. No scrolling . No zoom.

**Comment by SlicedSilver** [comment]
Set these to `false` in your options:
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptionsBase#handlescroll
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptionsBase#handlescale
