### ISSUE TITLE
How to get the price of the horizontal line of crosshair

### ISSUE THREAD

**Issue by GuillaumeA07** [tradingview/lightweight-charts#1524]
Hi guys,

I'm new using this library.
Worked all week-end on a tool for my trading. Still needs to implement a func.
Is there a possibility to get the value (price) targeted by the horizontal line of the crosshair.
I know that I could get coordinates or OHLC values. But I need the exact price in order to synchronize crosshair on two charts and save this price on click for others actions.

Thanks for your help

**Comment by SlicedSilver** [comment]
Depending on the setting for have for the crosshair ([mode](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/CrosshairOptions#mode)), you would either want the price of the datapoint at that x-axis position (time), or the price equivalent for the cursor position.

```js
function myCrosshairMoveHandler(param) {
  if (!param.point) {
    return;
  }
  const yPrice = mainSeries.coordinateToPrice(param.point.y);
  console.log(`The cursor position in price is ${yPrice}.`);
  const dataPoint = param.seriesData.get(mainSeries);
  console.log(`The price for the datapoint is ${dataPoint.value}.`);
}

chart.subscribeCrosshairMove(myCrosshairMoveHandler);
```

Example: https://codesandbox.io/p/devbox/funny-framework-cw7gsw

If you are looking to sync the crosshair on two charts then you might find this example useful: https://tradingview.github.io/lightweight-charts/tutorials/how_to/set-crosshair-position

**Comment by GuillaumeA07** [comment]
Thank you so much!! Exactly why i need.
