### ISSUE TITLE
Show latest data on legend

### ISSUE THREAD

**Issue by domrongpon-tanpaibul** [tradingview/lightweight-charts#153]
I'm trying to implement chart legend to always show the latest data, e.g. when you append the new data point. However, it must not update legend if crosshair is showing.

I find that currently, the API is not enough to implement this use case. Potentially, we need two more APIs.

1. Event when data is updated, so legend can be updated accordingly
2. Property to check if crosshair is showing or not, so we can skip the legend update if it's true

Would you please help to review if this makes sense?

**Comment by Tucsky** [comment]
You could do store somewhere on your code a boolean which is true when crosshair is active false when isn't, and update it on crosshair move

```
this.isCrosshairVisible;

chart.subscribeCrosshairMove((param) => {
		if (param.point === undefined || !param.time || param.point.x < 0 || param.point.x > container.clientWidth || param.point.y < 0 || param.point.y > container.clientHeight) {
			this.isCrosshairVisible = false
			updateLegendWithLatestData()
		} else {
			this.isCrosshairVisible = true
			updateLegendWithCrosshair(param)
		}
});
```

Then when you add the data point you will know if you have to update the legend

**Comment by domrongpon-tanpaibul** [comment]
@Tucsky Thanks for the solution! I will try.

**Comment by timocov** [comment]
@kirchet could you please take a look here? I've thought `subscribeCrosshairMove` have some "special" params when it's outside of the bars (for example `time` is null or something).

**Comment by domrongpon-tanpaibul** [comment]
It seems that the solution works. Also, another issue, when the data is updated e.g. when simulating realtime data, we want the value on legend updated respectively.

We are trying with `subscribeVisibleTimeRangeChange` event and it seems promising. the event is trigger when data is updated. 

Would you please advise if this is a good solution?

**Comment by timocov** [comment]
Just fyi it seems that we've an example with such legend https://jsfiddle.net/TradingView/8a29s0qj/ 🙂

**Comment by timocov** [comment]
> when the data is updated e.g. when simulating realtime data, we want the value on legend updated respectively.

I believe you can handle it in your datafeed and check that if you need to update the legend (if it shows that latest data) - just do it)

**Comment by domrongpon-tanpaibul** [comment]
I mean, if the code is something like this, the legend doesn't show the latest data.

https://jsfiddle.net/4y3mjckg/

**Comment by timocov** [comment]
Ah, in this case you need to handle updates somehow.

**Comment by kirchet** [comment]
@domrongpon-tanpaibul you need do something like this:

```js
var lastBar = data[data.lenth - 1];

function updateLegend(price, time) {
  // .....
}

chart.subscribeCrosshairMove(function(param) {
  // get price and time from param or lastBar
  updateLegend(price, time);
}

lastBar = { time: "2019-06-06", value: 860.51 };
series.update(lastBar);
// get price and time lastBar
updateLegend(price, time);

**Comment by domrongpon-tanpaibul** [comment]
Thanks all!
As it's confirmed that this has to handle outside the library. I'm happy to close this issue.
