### ISSUE TITLE
Lines with different y-axis values

### ISSUE THREAD

**Issue by Dawei-Simayi** [tradingview/lightweight-charts#1542]
**Is your feature request related to a problem? Please describe.**

I want to draw two lines with lightweight. The vertical coordinates of the two lines are dates. But the horizontal coordinates may not be of the same order of magnitude, one is the normal transaction price, but the other is the number of corresponding transactions. Is there any implementation example of this? Thanks

**Describe the solution you'd like**

**Additional context**

**Comment by SlicedSilver** [comment]
Could you provide a screenshot of the desired implementation?
