### ISSUE TITLE
Rectangle plugin

### ISSUE THREAD

**Issue by ionkorol** [tradingview/lightweight-charts#1548]
**Is your feature request related to a problem? Please describe.**

Seems like there is no way to add rectangles from within the code but only using the ui with the rectangle drawing tool.

**Describe the solution you'd like**

Adding a simple rectangle plugin similar to the trend line plugin would solve this.

**Additional context**

I have the plugin code. If the moderators are interested let me know. Otherwise you can close this issue.

**Comment by SlicedSilver** [comment]
If you want a simple rectangle plugin without needing to have the user draw the rectangle then you can use the `Rectangle` plugin class in our example: https://github.com/tradingview/lightweight-charts/blob/de75f8174c04b3358b241006fd27199a9f94bb6b/plugin-examples/src/plugins/rectangle-drawing-tool/rectangle-drawing-tool.ts#L267

The starting point for the Primitive plugin template on [create-lwc-plugin](https://github.com/tradingview/lightweight-charts/tree/master/packages/create-lwc-plugin) is a simple rectangle plugin if you want to start building your own version.
