### ISSUE TITLE
Line is thinner on retina display

### ISSUE THREAD

**Issue by domrongpon-tanpaibul** [tradingview/lightweight-charts#155]
**Lightweight Charts Version:** 1.0.2

**Steps/code to reproduce:**
- Open https://jsfiddle.net/ueq2b7Lm
- Compare, visually, line width on Retina display vs retina display

**Actual behavior:**
Line width on Retina is noticeable thinner than non-retina

**Expected behavior:**
Line width should be a similar size between retina and non-retina. ChartJs seems handle this better.

**Comment by timocov** [comment]
Can you please check it with https://github.com/tradingview/lightweight-charts/tree/141-fancy-canvas branch? According test cases there a line on the higher `devicePixelRatio` is wider.

Just to compare how it looks like with drp=2:

- on master https://3086-188438191-gh.circle-artifacts.com/0/home/circleci/project/graphics-cmp-data/devicePixelRatio%3D2.00/series/line/1.golden.png
- on fancy-canvas branch https://3086-188438191-gh.circle-artifacts.com/0/home/circleci/project/graphics-cmp-data/devicePixelRatio%3D2.00/series/line/2.test.png

**Comment by domrongpon-tanpaibul** [comment]
@timocov I've pulled code from that brand and checked. It works! :)

Do you want me to close this issue?

**Comment by timocov** [comment]
If it works as expected you can close it favor to #141.
