### ISSUE TITLE
CDN link on Unpkg.com doesnt work.

### ISSUE THREAD

**Issue by mozel84** [tradingview/lightweight-charts#1559]
https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js

this link doesn't work so that any lightweight chart on my website doesn't work too.

in chrome inspect console : LightweightCharts is not defined
unpkg.com returns 520 status code.

**Comment by SlicedSilver** [comment]
We don't manage the `unpkg` server. It will probably resolve itself shortly but if it doesn't then we will change the links mentioned in our README.md.

Until then you could rather host the library files on your website so you aren't reliant on a 3rd party CDN server.

**Comment by SlicedSilver** [comment]
Seems to be working again.

**Comment by Bradtus** [comment]
not anymore, again

**Comment by Bradtus** [comment]
It seems to be down regulary the last few days.
It might be a good idea to use jsDelivr instead. It could be more reliable because it uses many fallbacks.
You can convert your link using https://www.jsdelivr.com/unpkg
