### ISSUE TITLE
Lightweight-charts not working on Android browser

### ISSUE THREAD

**Issue by yuyic** [tradingview/lightweight-charts#156]
Android version: 5.0 and 6.0.1
Lightweight-charts demo can not be rendered on Android browser, but Chartinglibrary of TradingView work correctlly, it is a serious problem. Does anyone have solutions?

**Comment by timocov** [comment]
I think the reason is in polyfills, see https://github.com/tradingview/lightweight-charts/issues/101#issuecomment-517117573.

**Comment by yuyic** [comment]
I've imported pollyfill, it's not polyfill reason, the problem is canvas rendering a weird black and white content, I tried in two devices, Android5 and 6.0.1, both have the same issue.

**Comment by timocov** [comment]
Do you have any errors on the page? Can you please share screenshots what's going wrong?

**Comment by yuyic** [comment]
There are no errors on the page, here are some screenshots in Android 6.0.1 native browser.
![20190805173752](https://user-images.githubusercontent.com/785660/62455018-1074f580-b7a8-11e9-8b37-10aecf38aeba.jpg)
![20190805173831](https://user-images.githubusercontent.com/785660/62455020-1074f580-b7a8-11e9-8f2c-2f8eb985a744.jpg)
![20190805173851](https://user-images.githubusercontent.com/785660/62455022-110d8c00-b7a8-11e9-92ea-b4d05123691f.jpg)
![20190805173916](https://user-images.githubusercontent.com/785660/62455023-110d8c00-b7a8-11e9-9d2d-8895b35bdebe.jpg)

**Comment by SuperPenguin** [comment]
I tried on my old phone and it worked fine. Mi 4i with android 5.0.2, but I use latest chrome browser from play store.

**Comment by yuyic** [comment]
> I tried on my old phone and it worked fine. Mi 4i with android 5.0.2, but I use latest chrome browser from play store.
> 
> ![Screenshot_2019-08-05-18-55-01-164_com android settings](https://user-images.githubusercontent.com/1574722/62463049-318f1380-b7b3-11e9-9338-8824315d9cc9.png)
> ![Screenshot_2019-08-05-18-54-38-437_com android chrome](https://user-images.githubusercontent.com/1574722/62463050-3227aa00-b7b3-11e9-9b5d-36b3c5ac81c5.png)

Hi, you should try in Android Native Browser, it not works!
I want use the chart in React-Native, so I need native browser support.
Any solutions?

**Comment by timocov** [comment]
We'll investigate it and will back here with updates.

**Comment by timocov** [comment]
@yuyic can you please check it on https://github.com/tradingview/lightweight-charts/tree/141-fancy-canvas branch?

**Comment by timocov** [comment]
It looks like Android browser doesn't like `undefined` as the first argument in [fill](https://github.com/tradingview/lightweight-charts/blob/044ed75941a970f85b388c673c31636e4b8e0680/src/helpers/canvas-wrapper.ts#L216) method (we have a lot of errors about it - are you sure that you haven't any JS error?).

**Comment by yuyic** [comment]
Thanks for your quick response, it works now! 
Sorry I didn't do a complete debug, it's my fault, I just saw the errors...
