### ISSUE TITLE
chart.resize parameter is inverted

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#157]
**Lightweight Charts Version:** 1.0.0

**Steps/code to reproduce:**
```javascript
chart.resize(800, 600);
```

**Actual behavior:**
Chart is resized to 600 (width) x 800 (height)

**Expected behavior:**
Chart should be resized to 800 (width) x 600 (height)

I don't know whether this is intended or not, since it's very common to use width x height like `.resize(width, height)`. But, if this is intended as `.resize(height, width)`, this should be mentioned in documentation.

**Comment by timocov** [comment]
[Oh sh](https://github.com/tradingview/lightweight-charts/blob/044ed75941a970f85b388c673c31636e4b8e0680/src/api/ichart-api.ts#L38-L44)... 🤦‍♂

Yes, I agree that we need to have `width, height` there, not `height, width`. But it'll breaking change...

**Comment by timocov** [comment]
@SuperPenguin I would suggest you use `applyOptions` instead to resize the chart - it works the same, but have "named" params instead of positional ones.

**Comment by SuperPenguin** [comment]
@timocov ah okay, that is actually better for readability

**Comment by timocov** [comment]
Looks like we already have breaking change assigned to the next version (2.0), so let's fix this issue in 2.0 🙂
