### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_internal_addDataSource')

### ISSUE THREAD

**Issue by 0x33dm** [tradingview/lightweight-charts#1578]
I been using a modified version of the React example found on the documentation that suggests `chart.remove();` to be called once the useEffect is called.

The problem is that sometimes due to race conditions with "await" functions to fetch candle data the removed chart ends up receiving a call, for instance "const mainSeries = chart.addCandlestickSeries(....)" and when this call happens that error happens:

TypeError: Cannot read properties of undefined (reading '_internal_addDataSource')

**Lightweight Charts™ Version:** 

Latest

**Steps/code to reproduce:**

```js
    useEffect(
        () => {
          const chart = createChart(chartContainerRef.current, chartOptions)

          //sudo code

          candles = await fetchCandles()

          // hack needed to avoid errors when refreshing the chart
          // if I comment the if condition problems will be thrown on the console
          if (chart['isRemoving']) {
             return
          }

         chart.const mainSeries = chart.addCandlestickSeries(candles)

        // error happens

            return () => {
                window.removeEventListener('resize', handleResize);

                chart['isRemoving'] = true // hack to fix the problem

                chart.remove();
            };
        },
        [data, backgroundColor, lineColor, textColor, areaTopColor, areaBottomColor]
    );
```

**Actual behavior:**

TypeError: Cannot read properties of undefined (reading '_internal_addDataSource')

**Expected behavior:**

after chat.remove() is called function calls such as addCandlestickSeries ( and others that would error ) should silently fail as the chart is already removed?

not sure if that's ideal, but you got the idea ( :

**Comment by illetid** [comment]
Hi, for cases like this when you have some race conditions, we suggest you use [`React.useRef`](https://react.dev/reference/react/useRef) to check if the component is still mounted.


```javascript
const isMounted = useRef(true);

  useEffect(
        () => {
          const chart = createChart(chartContainerRef.current, chartOptions)
          candles = await fetchCandles()
          if (isMounted.current) {
             // Do whatever you want to do with chart
             const mainSeries = chart.addCandlestickSeries(candles)
          }

            return () => {
                window.removeEventListener('resize', handleResize);
                isMounted.current = false;
                chart.remove();
            };
        },
        [deps]
    );
```

Also, you could use [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to prevent fetching the data if the component is already unmounted

**Comment by 0x33dm** [comment]
> Hi, for cases like this when you have some race conditions, we suggest you use [`React.useRef`](https://react.dev/reference/react/useRef) to check if the component is still mounted.

> Also, you could use [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to prevent fetching the data if the component is already unmounted

Thanks for the suggestions @illetid definitely more elegant than my `['isRemoving']` hack. 

Still, due the fact this happens with the most basic react example on the documentation when used on Next.js ( due to the re-render nature of hydration, etcs ) wouldn't it make sense to have the library not trying to read some `_internal*` variable after the `remove()` method has been called?

**Comment by illetid** [comment]
The library is client-side only, so you shouldn't render it on the server; in the case of the modern Next.js, you should use the `'use client'` directive. Regarding accessing some properties after `remove()`, we don't have plans to change the current behavior, at least in the near future.

**Comment by 0x33dm** [comment]
> The library is client-side only, so you shouldn't render it on the server; 
i'm not rendering on the server, on the server i show a "skeleton"

> in the case of the modern Next.js, you should use the `'use client'` directive. Regarding accessing some properties after `remove()`, we don't have plans to change the current behavior, at least in the near future.

thank you, your suggestions and explanations were very helpful.
