### ISSUE TITLE
Using the Empty Corner of the Chart

### ISSUE THREAD

**Issue by bmatusiak** [tradingview/lightweight-charts#158]
What would be the best way to reuse this corner? 

Most use case would be a context menu button. 
another would be scroll to realtime ,

under inspection, the corner is nested under
`#chart > div.tv-lightweight-charts > table > tr:nth-child(2) > td:nth-child(3) > div > canvas`

![image](https://i.imgur.com/ecL3lnD.png)

So please offer your ideas.

**Comment by timocov** [comment]
In some cases this corner used to draw "connection pixel" for time and price axises' borders. Also, this "corner" is only when price axis is enabled, also it can be at the left of the chart.

**Comment by bmatusiak** [comment]
Humm,  if enabled, and on left and right, without blocking the connection pixels....

do you think it would be a good idea if there was an api to write some text or blob/base64 png icon to draw on that canvas with a mouse click event?  

or should i somehow alight a <div/> over it

**Comment by timocov** [comment]
> or should i somehow alight a <div/> over it

I believe it already can be done somehow :)

> do you think it would be a good idea if there was an api to write some text or blob/base64 png icon to draw on that canvas with a mouse click event?

Interesting... Let's wait some feedback and other suggestion for that place.

**Comment by timocov** [comment]
It seems that no one needs this so far, so I'm going to close the issue. If someone would have any idea - please ping me here with your thoughts.
