### ISSUE TITLE
Can I fit the serie to the size of the chart?

### ISSUE THREAD

**Issue by KendoJaaa** [tradingview/lightweight-charts#159]
this is more like a question, I'm not sure this is possible. If not, I will create a feature request.

I'm developing a react-native app. In the chart, I have a small amount of data-set but I want to autosize the serie so that it's fit the chart. 

![image](https://user-images.githubusercontent.com/14807517/62598400-7205a300-b913-11e9-8843-61ec9dfa2906.png)

what I want users to see when they open the screen is that, I don't want them to see the space on the left side of the chart.

or is there any other way to achieve the same result? something like setting the default zoom level or setting default bar size.

**Comment by little-wave** [comment]
yourChart.timeScale().fitContent();

**Comment by timocov** [comment]
@little-wave suggests the right solution. Also see #144.

**Comment by KendoJaaa** [comment]
@little-wave @timocov  thanks a lot. it works.

**Comment by jadhavsaurabh** [comment]
@KendoJaaa Can you share how you implemented lightweightcharts in native?
