### ISSUE TITLE
Feature: Is it possible to customize axis label behaviour in Price Line?

### ISSUE THREAD

**Issue by 17etro** [tradingview/lightweight-charts#1597]
The problem is regarding axis labels when there are many price lines with little spread. When I have situation like this

![image](https://github.com/tradingview/lightweight-charts/assets/55106769/0a0aed7f-00c9-4ef9-b63c-6b19a9dcc2df)

See that all labels shifting into one heap. And it is getting worse when their count became higher.

I wish I could remove this shifting behaviour with existing tools, but I don't find solution yet, maybe you can help me?
As a resolution I see something like that, when text sticks to line and they overlapped, like in screenshot:

![image](https://github.com/tradingview/lightweight-charts/assets/55106769/46fa368b-0703-46ce-b466-7b21bc68b828)

**Comment by SlicedSilver** [comment]
You could try setting the [`alignLabels`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceScaleOptions#alignlabels) option to `false` in the Price Scale options.

**Comment by 17etro** [comment]
Awesome, it works! Thank you
