### ISSUE TITLE
Charts disappear when changing tabs in Arc browser

### ISSUE THREAD

**Issue by Thimows** [tradingview/lightweight-charts#1598]
It seems to be happening when opening a chart on Arc and switching tabs. This is also happening on the official demo page (see attached video)

**Screenshots:**

https://github.com/tradingview/lightweight-charts/assets/62159496/1eddd408-716a-4ce1-9dbf-364dc7af9a0e

**Comment by x1i4b1x2** [comment]
It happens in Chrome, though less frequently, the issue is in 4.1.4. The version 4.1.3 is fine.

**Comment by SlicedSilver** [comment]
This appears to be a chrome bug (see https://issues.chromium.org/issues/328755781).

As a temporary workaround, you could use the following:
```js
document.addEventListener('visibilitychange', () => {
    const canvasElements = document.querySelectorAll('.tv-lightweight-charts canvas');
    Array.from(canvasElements).forEach((el) => {
        const ctx = el.getContext('2d');
        ctx.save();
        ctx.fillStyle = "rgba(0, 0, 0, 0)";
        ctx.fillRect(0, 0, 1, 1);
        ctx.restore();
    });
});
```

or just call `applyOptions({})` on the charts when the tab is restored:
```js
const chart = createChart('container');
// ...
document.addEventListener('visibilitychange', () => chart.applyOptions({}));
```

I'll look into a patch release for the library which will include a workaround for this issue.

**Comment by SlicedSilver** [comment]
https://issues.chromium.org/issues/328755781#comment95
> The fix is currently rolling out via a server-side config. Once the gradual rollout is complete (it takes a few hours), impacted users can restart their browser and get the fix. Separately, the fix is getting backported to Chrome 125 and 126. The next minor update of Chrome Stable 125 will thus get the fix, independently of the server-side rollout (which will be quicker).

Seems like this fix won't be required since Chrome is going to push a server-side fix.
