### ISSUE TITLE
How i can disable only price axis scaling?

### ISSUE THREAD

**Issue by little-wave** [tradingview/lightweight-charts#160]
Hi there.
Docs says that i can disable scaling on PressedMouseMove like that

`
handleScale: {
   axisPressedMouseMove: false,
}
`

But it also disabling time scaling on PressedMouseMove.
How can i disable only price axis scaling on PressedMouseMove?
Maybe i missed something?
Thanks in advance.

**Comment by kirchet** [comment]
Currently there is no way to disable only price scaling without time scaling

**Comment by little-wave** [comment]
So, with `axisPressedMouseMove: true` i can do something like this by press and move price axis several times
![image](https://user-images.githubusercontent.com/47245891/62636127-a728ea00-b941-11e9-99df-cf917f965502.png)

**Comment by kirchet** [comment]
I don't know, if a user wants to do it why should we limit him?

**Comment by little-wave** [comment]
Thanks for answer
