### ISSUE TITLE
Separate formatting for crosshair and priceScale labels?

### ISSUE THREAD

**Issue by tropnikov** [tradingview/lightweight-charts#1604]
**Is your feature request related to a problem? Please describe.**

The number of decimal digits in both priceScale labels and crosshair labels is regulated with precision (or formatter) options. We have data that contains 6 decimal digits and we want to show that in full in crosshair label. So we set precision to 6 and minMove to 0.000001 (or formatter function with toFixed(6)). Setting that gives priceScale labels with a lot of zeros.

**Describe the solution you'd like**

Can we separate formatting for crosshair label and priceScale labels?
or
Can we trim zeros in priceScale labels? I found an issue and associated PR – https://github.com/tradingview/lightweight-charts/issues/1088

Also, is there an option to set the number or priceScale labels or how frequent they are shown?

**Additional context**

<img width="298" alt="SCR-20240523-nemy" src="https://github.com/tradingview/lightweight-charts/assets/8367251/6a1590fe-1590-465e-8255-78fb141ab9e7">

**Comment by edew** [comment]
Hi @tropnikov 

The price scale would still need to be the full width of the crosshair so there would be blank space on the price scale.

Something like this:

![image](https://github.com/tradingview/lightweight-charts/assets/7424084/e5484314-6938-4c09-9fc6-8d44c002476d)

Is that what you want?

**Comment by tropnikov** [comment]
@edew Yes.

Btw, is there an option to choose the number of priceScale labels that are shown or its positions (like show only min / max price labels)?

**Comment by iurinunu** [comment]
Has this been implemented?
