### ISSUE TITLE
Chart is not start from left since I set setVisibleRange 

### ISSUE THREAD

**Issue by sibithabijesh** [tradingview/lightweight-charts#161]
Hello, 

I am using this chart to display price change based on different time period ( 1W, 1M, 6M & 1Y) . I am facing an issue in positioning of the chart.  If there is no much data in the current month, it display from the right since I set the date range. For fixing this problem, I've provided fixLeftEdge: true, which causes some data not showing in the chart.

Could you please let me know the right setting to fix this issue. 

**setVisibleRange without  fixLeftEdge** 
![screenshot-localhost-3000-2019 08 08-10-58-45](https://user-images.githubusercontent.com/20728188/62677330-902eda00-b9cb-11e9-93f3-703cf5262239.png)

**fixLeftEdge: true without setVisibleRange produce different chart. when page refresh, it show below one.  if we switch time period, it shows different chart for same time period**

![screenshot-localhost-3000-2019 08 08-11-02-28](https://user-images.githubusercontent.com/20728188/62677468-0e8b7c00-b9cc-11e9-8433-5b0c10db940a.png)

**showing different chart for the same timer period ( 1month)** 
![screenshot-localhost-3000-2019 08 08-11-05-51](https://user-images.githubusercontent.com/20728188/62677586-83f74c80-b9cc-11e9-8603-65db37fa79f4.png)

**Comment by kirchet** [comment]
After calling `setData` you should do something like this:

```js
chart.timeScale().scrollToPosition(-5);
```

**Comment by timocov** [comment]
I believe that the problem here is that there is not enough data to display and the chart decide to move the chart to the right edge instead of ... what? centering? moving to the left? We need to have option to describe behavior in such situations? Maybe.

/cc @eugene-korobko @ezhukovskiy 

> I've provided fixLeftEdge: true, which causes some data not showing in the chart.

I hope we'll fix it in https://github.com/tradingview/lightweight-charts/issues/144#issuecomment-514987397.

**Comment by timocov** [comment]
@sibithabijesh is your problem resolved with @kirchet's suggestion?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
