### ISSUE TITLE
topbar font size

### ISSUE THREAD

**Issue by blair-anson** [tradingview/lightweight-charts#1611]
Is there anyway to set the font size of the textbox, switcher widgets in the topbar?
It is a bit small to read on a 4k screen

**Comment by SlicedSilver** [comment]
Could you please provide a screenshot of the text which you would like to increase in size? (I'm unsure what the 'textbox, and switcher widgets in the topbar' are).

**Comment by blair-anson** [comment]
Please see attached image. The example shows the topbar.text = TSLA, and the topbar.switcher has 1min, 5min, and 30min options.
![image](https://github.com/tradingview/lightweight-charts/assets/5399102/20a0c50d-8d7c-43fd-ae57-509f05149317)

**Comment by blair-anson** [comment]
sorry, I meant to ask this in the python port of this library
