### ISSUE TITLE
Error: Assertion failed: right should be >= left

### ISSUE THREAD

**Issue by tasteitslight** [tradingview/lightweight-charts#1617]
**Lightweight Charts™ Version:** 4.1.4

This is a strange behavior. Not sure how to reproduce. Sometimes it happens, sometimes it doesn't. Unsure if it is a problem with our code or the library. Thanks for taking a look. Appreciate your help. 

![Screenshot 2024-06-13 at 13 06 06](https://github.com/tradingview/lightweight-charts/assets/33602987/5bebc0ad-f03f-49c2-bff1-be6b6c5f21a9)

`<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(222, 227, 229); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:195" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.development.js:195</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><div style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Assertion failed: right should be &gt;= left
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at assert (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:195:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>velopment.js:195:19</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at new RangeImpl (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:6518:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:6518:13</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TimeScale._private__updateVisibleRange (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:7155:34" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:7155:34</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TimeScale._internal_visibleStrictRange (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:6768:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:6768:18</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pane._private__recalculatePriceScaleImpl (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:6422:62" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:6422:62</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pane._internal_recalculatePriceScale (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:6381:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:6381:18</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pane._internal_recalculate (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:6397:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:6397:18</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:7773:51" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:7773:51</button>
</span>    at Array.forEach (&lt;anonymous&gt;)
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ChartModel._internal_recalculateAllPanes (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://unpkg.com/lightweight-charts@4.1.4/dist/lightweight-charts.standalone.development.js:7773:34" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">lightweight-charts.s<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>elopment.js:7773:34</button>)</span></div></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(222, 227, 229); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 915.375px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | assert | @ | lightweight-charts.s….development.js:195
-- | -- | -- | --
  | RangeImpl | @ | lightweight-charts.s…development.js:6518
  | _private__updateVisibleRange | @ | lightweight-charts.s…development.js:7155
  | _internal_visibleStrictRange | @ | lightweight-charts.s…development.js:6768
  | _private__recalculatePriceScaleImpl | @ | lightweight-charts.s…development.js:6422
  | _internal_recalculatePriceScale | @ | lightweight-charts.s…development.js:6381
  | _internal_recalculate | @ | lightweight-charts.s…development.js:6397
  | (anonymous) | @ | lightweight-charts.s…development.js:7773
  | _internal_recalculateAllPanes | @ | lightweight-charts.s…development.js:7773
  | _internal_setBarSpacing | @ | lightweight-charts.s…development.js:6879
  | _internal_zoom | @ | lightweight-charts.s…development.js:6970
  | _internal_zoomTime | @ | lightweight-charts.s…development.js:7659
  | _private__onMousewheel | @ | lightweight-charts.s…evelopment.js:11724

</span></div>`

**Comment by SlicedSilver** [comment]
This is the line of code throwing the error: https://github.com/tradingview/lightweight-charts/blob/86aa897398d24a0f0f8a064dc5364ae07d7d62ed/src/model/range-impl.ts#L8

Which is being called by this: https://github.com/tradingview/lightweight-charts/blob/86aa897398d24a0f0f8a064dc5364ae07d7d62ed/src/model/time-scale.ts#L836-L842

So for the error to occur, newBarsLength would need to be less than `1`.

The width is the time scale width in pixels and the barSpacing the width for each data point (effectively the zoom level). So for this issue to occur, the time scale (and thus the chart) would need to be very narrow, or the zoom level would be such that the bars are very large.

The bar spacing is limited here: https://github.com/tradingview/lightweight-charts/blob/86aa897398d24a0f0f8a064dc5364ae07d7d62ed/src/model/time-scale.ts#L855
So either that code didn't correct the bar spacing or the chart had a sudden change in size.

Do you have any code related to visible range / barSpacing or similar to the items discussed above? If so could you please share it? or try create a small example which reproduces the issue?

**Comment by tasteitslight** [comment]
Thanks for the reply. After some effort, I have not yet been able to reliably reproduce this issue in our environment. It may be due to an async data issue, but this requires more investigation. In the meantime, here are some code snippets that involve visible range / barSpacing.

These are called when initializing the main chart:

```
// Resize chart dimensions if window is resized
this.setResizeObserver(this.charts.main, this.chartContainers.main);

// Reloads the chart when user scrolls back in time.
this.charts.main.timeScale().subscribeVisibleLogicalRangeChange(this.onVisibleLogicalRangeChanged.bind(this));

onVisibleLogicalRangeChanged(logicalRange) {
		// Save zoom
		// logicalRange: { "from": 224.66265060240966, "to": 318 }
		if (logicalRange) {
			const currentBarSpacing = this.charts.main.timeScale().width() / (logicalRange.to - logicalRange.from);
			this.settings.update("barSpacing", currentBarSpacing);
			if (!this.series.price) {
				return;
			}

			// if there less than 50 bars to the left of the visible area
			const barsInfo = this.series.price.barsInLogicalRange(logicalRange);
			if (barsInfo !== null && barsInfo.barsBefore < 0 && !this.isLoadingChartData) {
				this.debouncedGetPriceData();
			}

			try {
				this.charts.aux1.timeScale().setVisibleLogicalRange({
					from: logicalRange.from,
					to: logicalRange.to,
				});
			} catch (e) {
				console.error(e);
			}

			try {
				if (this.charts.aux2) {
					this.charts.aux2.timeScale().setVisibleLogicalRange({
						from: logicalRange.from,
						to: logicalRange.to,
					});
				}
			} catch (e) {
				console.error(e);
			}
		}
	}
```

The below code uses some hacking to get retrieve the chart width. This was done because `const chartWidth = dimensions.width;` did not work as reliably when mobile browsers were rotated. Included just in case.

```
setResizeObserver(self, container, leader = false) {
		new ResizeObserver((entries) => {
			if (entries.length === 0 || entries[0].target !== container) {
				return;
			}
			if (leader) {
				// const dimensions = this.charts.main.paneSize();
				// const chartWidth = dimensions.width;
				// const chartWidth = this.charts.main.Yb.h_ - this.charts.main.Yb.Em; // production
        const chartWidth = this.charts.main._private__chartWidget._private__width - this.charts.main._private__chartWidget._private__rightPriceAxisWidth; // development
				const chartHeight = entries[0].contentRect.height;
				self.applyOptions({
					height: chartHeight,
					width: chartWidth,
				});
			} else {
				const newRect = entries[0].contentRect;
				this.charts.main.applyOptions({
					height: newRect.height,
					width: newRect.width,
				});
			}
		}).observe(container);
	}
```

Thanks again for your help. I'll continue to do more digging.

Not sure if this is related, but the following new errors did just appear. I can make a new card for this issue later if it persists and is unrelated. But just in case it is:

```
Uncaught TypeError: Cannot set properties of undefined (setting '_internal_visibleRange')
    at lightweight-charts.standalone.development.js:799:49
    at Array.forEach (<anonymous>)
    at CrosshairMarksPaneView._private__updateImpl (lightweight-charts.standalone.development.js:794:22)
    at CrosshairMarksPaneView._internal_renderer (lightweight-charts.standalone.development.js:784:22)
    at drawSourcePaneViews (lightweight-charts.standalone.development.js:9018:39)
    at PaneWidget._private__drawSourceImpl (lightweight-charts.standalone.development.js:10669:13)
    at PaneWidget._private__drawCrosshair (lightweight-charts.standalone.development.js:10649:18)
    at PaneWidget._internal_paint (lightweight-charts.standalone.development.js:10594:22)
    at ChartWidget._internal_paint (lightweight-charts.standalone.development.js:11437:47)
    at ChartWidget._private__drawImpl (lightweight-charts.standalone.development.js:11759:18)
```

**Comment by SlicedSilver** [comment]
Had another thought. Are you perhaps creating the chart without any series or data for the series? and then only adding the series/data at a later stage?

This would be unexpected for the library and the expected approach is only create the chart when it has some data to show.

**Comment by tasteitslight** [comment]
Yeah, we are. 

```
// Init charts
this.initChartMain();
this.initChartIndicatorsMain();
this.initChartAux1();
this.initChartAux2();
this.addServerIndicatorSeries();
```

```
initChartMain() {
		this.charts.main = LightweightCharts.createChart(this.chartContainers.main, {
			handleScroll: true,
			handleScale: true,
			layout: {
				background: { type: "solid", color: "transparent" },
				textColor: this.chartStyle.color.text,
				fontSize: 11,
			},
			grid: {
				vertLines: {
					visible: false,
				},
				horzLines: {
					visible: false,
				},
			},
			timeScale: {
				timeVisible: true,
				secondsVisible: false,
				borderVisible: false,
				barSpacing: this.settings.get("barSpacing"),
			},
			crosshair: {
				mode: 0,
				// Vertical crosshair line (showing Date in Label)
				vertLine: {
					width: 3,
					color: this.chartStyle.color.crosshair,
					style: LightweightCharts.LineStyle.Solid,
					labelBackgroundColor: window.localStorage.getItem("mode") == "light" ? "#DEE2FF" : "#0F133F",
				},
				// Horizontal crosshair line (showing Price in Label)
				horzLine: {
					width: 3,
					color: this.chartStyle.color.crosshair,
					style: LightweightCharts.LineStyle.Solid,
					// color: this.chartStyle.color.blue,
					labelBackgroundColor: window.localStorage.getItem("mode") == "light" ? "#DEE2FF" : "#0F133F",
				},
			},
			rightPriceScale: {
				mode: this.settings.get("logChart") ? 1 : 0,
				borderVisible: false,
				entireTextOnly: true,
				scaleMargins: this.chartStyle.margin.main,
			},
			leftPriceScale: {
				mode: this.settings.get("logChart") ? 1 : 0,
				borderVisible: false,
				entireTextOnly: true,
				scaleMargins: this.chartStyle.margin.main,
			},
		});

		this.series.price = this.charts.main.addCandlestickSeries({
			upColor: this.chartStyle.color.green,
			downColor: this.chartStyle.color.red,
			wickUpColor: this.chartStyle.color.green,
			wickDownColor: this.chartStyle.color.red,
			borderVisible: false,
		});

		// Resize chart dimensions if window is resized
		this.setResizeObserver(this.charts.main, this.chartContainers.main);

		// Reloads the chart when user scrolls back in time.
		this.charts.main.timeScale().subscribeVisibleLogicalRangeChange(this.onVisibleLogicalRangeChanged.bind(this));

		// Push name and chart to this.activeCharts for Crosshair Sync
		this.activeCharts.push({
			name: "this.charts.main",
			chart: this.charts.main,
		});
	}
	```
