### ISSUE TITLE
Chart is not drawn on Edge (Windows)

### ISSUE THREAD

**Issue by little-wave** [tradingview/lightweight-charts#162]
**Lightweight Charts Version:** 1.0.2

**Steps/code to reproduce:**

See jsfiddle link below

**Actual behavior:**

Bug founded on latest edge version on Windows (44.18362.267)
When setted **rgb**
```
chart.addAreaSeries({
    bottomColor: 'rgb(0, 120, 255, 0.0)',
});
```
Instead of **rgba**
```
chart.addAreaSeries({
    bottomColor: 'rgba(0, 120, 255, 0.0)',
});
```

**Expected behavior:**

Chart is visible?

**Screenshots**
Any other browser: 
![image](https://user-images.githubusercontent.com/47245891/62710857-ba4ebf00-ba00-11e9-8c9b-27c6f21b8b8d.png)
Edge:
![image](https://user-images.githubusercontent.com/47245891/62711157-38ab6100-ba01-11e9-8417-8392c0e7f436.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/syllik/6mt7vn3e/3/

**Comment by bmatusiak** [comment]
in this fiddle,,   i changed line #8

to rgba()     you had rgb()

    bottomColor: 'rgba(0, 120, 255, 0.0)',


im guessing this is an EDGE issue,  because  the other browsers dont care if rgb has 4 arguments

**Comment by little-wave** [comment]
Thanks for answer, I wrote here just in case anyone has a similar problem.
I think we can close this issue
