### ISSUE TITLE
Need subscribeVisiblePriceRangeChange method.

### ISSUE THREAD

**Issue by Hudrolax** [tradingview/lightweight-charts#1623]
It has the **subscribeVisibleTimeRangeChange** method, but doesn’t have the **subscribeVisiblePriceRangeChange**. I can do something when the time range changes, but can’t when the price range changes.

**Comment by SlicedSilver** [comment]
Typically the only times that the price range can change are:
- The visible time range changes (subscribeVisibleTimeRangeChange would help here)
- New data is added / changed (your code would initialise this action)
- The user adjusts the price scale manually.

It is difficult to detect the final case using the default API. However there is an existing plugin to the library which can help with your request: https://github.com/tradingview/lightweight-charts/issues/1442#issuecomment-1760463045

**Comment by Hudrolax** [comment]
Thanx! This plugin works fine in my case!
