### ISSUE TITLE
Load animation

### ISSUE THREAD

**Issue by xuzhaobin** [tradingview/lightweight-charts#1627]
Can add a data loading animation like this?
![20240702153907_rec_](https://github.com/tradingview/lightweight-charts/assets/23274895/f19e9ce2-30b7-4d3c-b443-7ce4e3235b68)

**Comment by SlicedSilver** [comment]
You could try adding the data points one at a time (using `series.update()`), or create a [plugin](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) which draws a white box over the chart and then moves to the right (revealing the underlying line).

There are not plans to add animations like this into the base library.
