### ISSUE TITLE
Crash when the dataset is strictly above 1567 rows

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1637]
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:**

Try to load a dataset with more than 1567 rows.

**Actual behavior:**

I try to load the full daily chart of the BTC since 2017, I have around 2500 candles to display. 
As soon as the dataset is greater than 1567 rows, the display crashed.

The dataset is completely clean because I tried first to display the first 1500 rows and then the last 1000 rows and it works.

**Expected behavior:**

Display all my daily chart.

**Screenshots:**

![Xnip2024-07-14_11-55-23](https://github.com/user-attachments/assets/64826bbd-dfd7-4afb-8e0a-a143bb7bf606)

**Comment by SlicedSilver** [comment]
Here is a working example of a candlestick chart showing BTCUSD daily data from 2017: https://codesandbox.io/p/sandbox/lwc-btcusd-candlesticks-lfcngv

So I'm unable to reproduce your issue myself. Could you please share more details?

If you use the development version of the library then the error messages will make more sense, and if you are still unable to work out the issue then could you please share a code reproduction?

**Comment by 777Bridges** [comment]
@SlicedSilver , thank you for your answer. I found the issue, it was coming from my data. I had one duplicated row...
I removed it from my DB and now it is all good.

Thank you!
