### ISSUE TITLE
Display HOLC value on the chart

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1638]
Good day,

is there any way to display the HOLC values on the left corner of the lightweight chart?

Thank you

**Comment by SlicedSilver** [comment]
I would recommend looking at this tutorial guide as a starting point: https://tradingview.github.io/lightweight-charts/tutorials/how_to/legends

**Comment by 777Bridges** [comment]
@SlicedSilver thank you for your support, it is done!

![image](https://github.com/user-attachments/assets/9bf85138-c56e-43d1-930a-5b5f6cf2b8cd)
