### ISSUE TITLE
How to work with Range switcher and a call API (with fetch)

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1640]
Good day, 

I have a question how to implement the range switcher when I use a call API with fetch.

I saw in this example that we need to map the data at the initialisation :
https://tradingview.github.io/lightweight-charts/tutorials/demos/range-switcher

const seriesesData = new Map([
    ['1D', dayData],
    ['1W', weekData],
    ['1M', monthData],
    ['1Y', yearData],
]);

setChartInterval('1D');

In my code I get my data with a call API like that:

fetch(
    "http://127.0.0.1:5000/api/kline/get_klines_pair?" +
      new URLSearchParams({
        exchange: "Binance",
        product_type: "SPOT",
        pair: "BTCUSDT",
        timeframe: "1d",
        result_format: "TV",
      }).toString(),
    {
      method: "GET",
      mode: "no-cors",
      headers: {
        "Content-Type": "application/json",
      },
    }
  )
    .then(function (response) {
      return response.json(); // But parse it as JSON this time
    })
    .then(function (json) {
      series.setData(json);
      return json;
    });

So my data are only available in the fetch and not when I set the seriesesData. Do you have any workaround?

Thank you

**Comment by illetid** [comment]
Maybe I didn't fully understand your question, but I don't see any issues here. you can fetch your data on interval change and set data after you get it from the response 
```js
const dataByRangeCache = new Map();
// your fetch function
const fetchDataByInterval = async (interval) => fetch(...)
function setChartInterval(interval) {  
	lineSeries.setData(dataByRangeCache.get(interval));  
	lineSeries.applyOptions({  
	color: intervalColors[interval],  
	});  
	chart.timeScale().fitContent();  
}


const intervals = ['1D', '1W', '1M', '1Y'];  
intervals.forEach(interval => {  
const button = document.createElement('button');  
button.innerText = interval;
// change the click handler to get the data from api if it is not in cache yet
// you can avoid this cache completely and just fetch data each time interval changed
button.addEventListener('click', async () => {
	if (dataByRangeCache.has(interval)) {
		setChartInterval(interval)
	} else {
		const data = await fetchDataByInterval(interval);
		dataByRangeCache.set(interval, data);
		setChartInterval(interval)
	}
});  
buttonsContainer.appendChild(button);  
});

```
