### ISSUE TITLE
Optimisation question about multiple addLineSeries

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1642]
Good day,

on my chart I would like to draw like some break os structure. To do so I use LinesSeries with 2 points ( I can't draw a trend line like on TV). But for a 4h chart with a deep historic, it is very long.

![image](https://github.com/user-attachments/assets/ce060451-8cde-4a3e-8c29-484725744257)

My code is that one. I receive a Json with all the lines to display (dates and price level) and I transform them to a LinesSeries. For example on the H4 timeframe, I have to draw around 2000 lines, it takes very long....
Any idea of optimisation?

Thank you

json_orderflow.forEach((order_flow) => {
    Object.entries(order_flow).forEach(([key, value]) => {
      if (key == "lkline_open_time") {
        lkline_open_time = value;
        // date_open_time = new Date(value * 1000);
      }
      if (key == "lkline_high") {
        lkline_high = value;
      }
      if (key == "lkline_low") {
        lkline_low = value;
      }
      if (key == "lkline_open_time_1") {
        lkline_open_time_1 = value;
        // date_open_time1 = new Date(value * 1000);
      }
      if (key == "lkline_of_type") {
        lkline_of_type = value;
      }
    });
    LineSeries[i] = chart.addLineSeries({
      lastValueVisible: false,
      priceLineVisible: false,
      color: color_order_flow,
      lineStyle: style_order_flow,
      lineWidth: width_order_flow,
    });
    var tldata = [];
    if (lkline_of_type == "Bull") {
      tldata.push({
        time: lkline_open_time,
        value: lkline_high,
      });
      tldata.push({
        time: lkline_open_time_1,
        value: lkline_high,
      });
    } else {
      tldata.push({
        time: lkline_open_time,
        value: lkline_low,
      });
      tldata.push({
        time: lkline_open_time_1,
        value: lkline_low,
      });
    }
    LineSeries[i].setData(tldata);

    i++;
  });

**Comment by SlicedSilver** [comment]
I would recommend using [Plugins](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for something custom like those horizontal lines. (instead of adding 2000 line series).

You could probably use the Trend Line example plugin as a starting point:
- Demo: https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/trend-line/example/
- Code: https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/trend-line

**Comment by 777Bridges** [comment]
Thank you for your answer.

I have already installed the lightweight chart in my project. so I have the node_modules folder.
How could I add and install the plugins?Could you help?

Thank you

**Comment by SlicedSilver** [comment]
The sample plugins aren't an NPM package which can be installed.

You can either define the plugin within your code (some copy and paste, and then refinement), or you could use the [`create-lwc-plugin`](https://www.npmjs.com/package/create-lwc-plugin) package to scaffold out a new plugin which you can publish yourself on NPM

- https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples#using-an-example
- https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples#creating-your-own-plugin

**Comment by 777Bridges** [comment]
Just to be sure to understand. I have already initiated my project and installed Lightweight with the command "npm install lightweight-charts" in a specific folder.

Do I have to clone the lightweight repo in an other folder of my project or I replace the existing one?

Thank you for your support

**Comment by 777Bridges** [comment]
The difference of speed is amazing. Everything is working perfectly well with the plugin!!

I also customised the lines and Label but there is one thing that is missing for me : is there any option about the lineStyle?

Thank you

**Comment by SlicedSilver** [comment]
You could change the line style by adding the following code here: https://github.com/tradingview/lightweight-charts/blob/f93491187eec7e147b739eee90f25d11a5d65d37/plugin-examples/src/plugins/trend-line/trend-line.ts#L46

```js
ctx.setLineDash([5, 15]);  // 5 pixels on, 15 pixels off
```

Reference: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash

**Comment by 777Bridges** [comment]
That s quite an issue as I need to draw different lines with different styles (one for each timeframe i work with). Thank you!
