### ISSUE TITLE
Chart.show() not working in spyder (python)

### ISSUE THREAD

**Issue by gitraj123** [tradingview/lightweight-charts#1646]
**Lightweight Charts™ Version:** 
I created a candlestick chart by using the following code

from lightweight_charts import Chart
chart = Chart()
chart.set(data)
chart.show(block = True)

and run it in spyder installed via anaconda.
first run is sucessful but on second run it is showing the follwoing error message: --

  File ~\miniconda3\envs\stockenv\Lib\multiprocessing\process.py:115 in start
    assert self._popen is None, 'cannot start a process twice'

**Comment by SlicedSilver** [comment]
Lightweight charts doesn't directly support Python.

You should open this issue in the repo for the Python package you are using instead (perhaps it is https://github.com/louisnw01/lightweight-charts-python)
