### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by guidra-rev** [tradingview/lightweight-charts#1647]
**Lightweight Charts™ Version:** 4.1.7

**Steps/code to reproduce:**

I have read https://github.com/tradingview/lightweight-charts/blob/master/BUILDING.md

git clone --depth 1 --branch v4.1.7 https://github.com/tradingview/lightweight-charts
cd .\lightweight-charts\
npm install 

**Actual behavior:**

npm ERR! code ETARGET
npm ERR! notarget No matching version found for ws@^8.18.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

I tried pinning many node versions with volta

**If I use node@16.16.0**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-jsdoc@~48.5.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**If node@17.9.1**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-jsdoc@~48.5.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**If node@18.20.4**
npm error code ETARGET
npm error notarget No matching version found for ws@^8.18.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

**If node@19.9.0**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-jsdoc@~48.5.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**if node@20.15.1**
npm error code ETARGET
npm error notarget No matching version found for ws@^8.18.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

**Expected behavior:**

Expecting no errors

**Comment by SlicedSilver** [comment]
It has been installing fine on our CI and on our local machines so I would suspect that potentially your npm cache needs to be cleared. Could you try running this command:
```bash
npm cache clean --force
```

TIP: If you aren't planning on running the tests then you will get a faster install by skipping the Puppeteer dependency trying to install Chrome:
```bash
PUPPETEER_SKIP_DOWNLOAD=true npm install
```

**Comment by guidra-rev** [comment]
@SlicedSilver It worked ! Thank you
