### ISSUE TITLE
OHLC charts render incorrect when `value` is provided

### ISSUE THREAD

**Issue by ronnyhaase** [tradingview/lightweight-charts#165]
**Lightweight Charts Version:** 1.0.2

**Steps/code to reproduce:**
Render a candlestick or bars chart with data containing a `value`, aside correct `open`, `high`, `low`, `close`

**Actual behavior:**

When `value` is provided the candle doesn't render properly, it's only a thin horizontal line at the close price.

**Expected behavior:**

Ignore value or treat it as close, and render candle properly.

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/9botcdL5/9/

As you can see the first candle is incorrect.

**Comment by timocov** [comment]
The reason is [this bad guy](https://github.com/tradingview/lightweight-charts/blob/559bb9316494cef9d097dbcafe76c430a17c0bf2/src/api/data-layer.ts#L98-L114). I believe we need to have different check there. As workaround we can just don't provide `value` along with other OHLC values :)
