### ISSUE TITLE
Plot a rectangle (with the plugin)

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1653]
Good day,

I am wondering if I can draw a rectangle with some lines of code with the "rectangle drawing" plugin. 
I don't want to draw on the chart but just plotting rectangle when I init the chart ( as I plot some trend-lines).

It would be something like :

const point1 = {
      time: ltrade_entry_open_time,
      price: ltrade_entry_price,
    };
    const point2 = {
      time: ltrade_entry_open_time+1000,
      price: ltrade_sl_price,
    };

    const rect = new RectangleDrawingTool(chart, series, point1, point2, {
      Color: "#2962FF",
      width: 1,
    });
    series.attachPrimitive(rect);

Is there any way to achieve that with the plugin?

Thank you

**Comment by SlicedSilver** [comment]
Luckily, this is exactly what the base 'primitive' example does which is created by [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin). (It is a plugin to render rectangles on the chart.)

1. Run `npm create lwc-plugin@latest`
2. then pick 'Drawing Primitive' and answer the rest of the questions.
3. `cd` into the created directory (for example: `cd lwc-plugin-rectangle`)
4. Run `npm install` and then `npm run dev`
5. You will see a preview of the created plugin on `http://localhost:5173/`.
6. Modify the create plugin as you see fit.

**Comment by 777Bridges** [comment]
In the plugin I have that line :
import { isBusinessDay as m } from "lightweight-charts";

But when I try to import it from my production lightweightchart file
lightweight-charts.standalone.production.js

I have the error

![image](https://github.com/user-attachments/assets/442ad82e-b707-4708-aabd-fe551f9e46c1)


Could you help?

**Comment by 777Bridges** [comment]
I tried that code (removing the business Day constraint)

const primitive = new Rectangle(
      { price: 60000, time: 1719392400 },
      { price: 65000, time: 1719565200 }
    );

    series.attachPrimitive(primitive);

But it always tells me "Invalid Date"

![image](https://github.com/user-attachments/assets/61552a74-80c5-413e-8978-1d68ad296183)

**Comment by SlicedSilver** [comment]
You shouldn't be trying to import from the 'standalone' version of the library. Rather use the `lightweight-charts.production.mjs` version.

**Comment by 777Bridges** [comment]
thank you for your support, almost everything is sorted out. It remains only one question about the transparency.

I have this piece of code
    const primitive = new Rectangle(
      { price: 60000, time: 1719392400 },
      { price: 65000, time: 1719565200 },
      { showLabels: false, fillColor: "rgba(39, 245, 80, 0.01)" }
    );

    series.attachPrimitive(primitive);


and I have this result (not really transparent...). Do you have any idea?

Thanbk you!

![image](https://github.com/user-attachments/assets/fd130bcc-25c0-4c02-873b-88c9b8521948)

**Comment by SlicedSilver** [comment]
Are sure that the series primitive is only being created once? It might appear to be a more opaque colour if it is drawn multiple times on top of itself.
