### ISSUE TITLE
Line Break in a marker Text

### ISSUE THREAD

**Issue by 777Bridges** [tradingview/lightweight-charts#1671]
Good day,

I would like to know if there is any way to include a line breaker inside a text of a marker

displayed_text = ["Sell", ltrade_is_valid, ltrade_valid_reason].join("/");

I tried to add \r\n or even a <br/> but nothing work, maybe it is not possible...

Do you have an idea?

Thank you

**Comment by illetid** [comment]
The library doesn't support drawing text in multiline, as HTML canvas does not support such a thing. You could try to achieve something like this with stacking two markers on the same timestamp and set size of the second marker to `0`. Here is the example
<img width="323" alt="image" src="https://github.com/user-attachments/assets/c8436dfb-7777-46d4-95c2-13a68cd3c3b2">

https://codesandbox.io/p/sandbox/lightweight-charts-skeleton-forked-3mlk58
