### ISSUE TITLE
The curve and time axis jitter when moving left

### ISSUE THREAD

**Issue by GuangliHuang** [tradingview/lightweight-charts#1673]
My project requires the implementation of dynamic curve drawing effect, but the current effect is not ideal. There is obvious jitter in the curve area and timeline movement effect. I am using Lightweight Charts v4.1.2. Can the framework source code be optimized to a smoother effect? Thank you.
The effect is as follows:
https://guanglihuang.github.io/tg-app/
![666666](https://github.com/user-attachments/assets/d19ed5e6-f315-4659-b138-0939b9a3af82)

**Comment by edew** [comment]
You should use `update` instead of `setData` https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates

**Comment by GuangliHuang** [comment]
Thank you very much for your reply and guidance. I used update to replace setData, but the effect is still not improved. We want to achieve the curve animation effect like this website: https://rollbit.com/trading/ETH. How can we achieve it? Thank you!

**Comment by GuangliHuang** [comment]
> You should use `update` instead of `setData` https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates

Thank you very much for your reply and guidance. I used update to replace setData, but the effect is still not improved. We want to achieve the curve animation effect like this website: https://rollbit.com/trading/ETH. How can we achieve it? Thank you!

**Comment by edew** [comment]
@GuangliHuang I can't view https://rollbit.com/trading/ETH from my country.

What exactly are you trying to achieve?

**Comment by GuangliHuang** [comment]
@edew I recorded a video, you can watch it at this address:
https://guanglihuang.github.io/tg-app/video.html

The effect I want to achieve is that the chart can move smoothly when they move to the left. The current problem is that the chart will jitter and freeze every time it moves.

**Comment by GuangliHuang** [comment]
This question can be closed and I'll consider trying other framework solutions. Thanks!

**Comment by blancos13** [comment]
> This question can be closed and I'll consider trying other framework solutions. Thanks!

yo do you know how to make smoother moves like rollbit

**Comment by GuangliHuang** [comment]
This chart framework can achieve curve sliding movement.


https://live.demo.chartiq.com/#active-trader.demo.chartiq.com




---Original---
From: ***@***.***&gt;
Date: Sat, Sep 14, 2024 19:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tradingview/lightweight-charts] The curve and time axis jitterwhen moving left (Issue #1673)




  
This question can be closed and I'll consider trying other framework solutions. Thanks!
  
yo do you know how to make smoother moves like rollbit
