### ISSUE TITLE
missing very small numbers

### ISSUE THREAD

**Issue by Pp-Tomo** [tradingview/lightweight-charts#1679]
**Lightweight Charts™ Version:** 
"lightweight-charts": "^4.2.0",

**Steps/code to reproduce:**

```tsx
import React, { useEffect, useRef } from "react";
import "./App.css";
import { createChart } from "lightweight-charts";

function App() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef?.current) return;
    const chart = createChart(containerRef.current, {
      height: 400,
      width: 400,
    });
    const series = chart.addCandlestickSeries({});

    // Cryptocurrencies have less precision( > 1e18)
    series.setData([
      {
        time: 1723118400000,
        open: 0.00000259156993297133,
        close: 0.00000270062606671658,
        high: 0.00000271419321101925,
        low: 0.00000258994313782098,
        value: 181690.2,
      },
      {
        time: 1723122000000,
        open: 0.00000270062606671658,
        close: 0.00000273456803891399,
        high: 0.00000276439570539845,
        low: 0.00000264702985918424,
        value: 153514.3,
      },
      {
        time: 1723125600000,
        open: 0.00000273456803891399,
        close: 0.00000272255080043839,
        high: 0.00000277857035163983,
        low: 0.00000268630291292406,
        value: 15966.9,
      },
      {
        time: 1723129200000,
        open: 0.00000272255080043839,
        close: 0.00000279213164316431,
        high: 0.00000279213164316431,
        low: 0.00000272255080043839,
        value: 43375.5,
      },
      {
        time: 1723132800000,
        open: 0.00000279213164316431,
        close: 0.00000278222472467185,
        high: 0.00000285469467700814,
        low: 0.00000272695091763052,
        value: 157521.3,
      },
      {
        time: 1723136400000,
        open: 0.00000278222472467185,
        close: 0.00000275678487508767,
        high: 0.00000278222472467185,
        low: 0.00000270339339114587,
        value: 36381.4,
      },
      {
        time: 1723140000000,
        open: 0.00000275678487508767,
        close: 0.00000274014820763413,
        high: 0.00000275678487508767,
        low: 0.00000268562824034948,
        value: 20389.2,
      },
      {
        time: 1723143600000,
        open: 0.00000274014820763413,
        close: 0.00000272325608959985,
        high: 0.00000274141793578471,
        low: 0.00000267333463370322,
        value: 14105.3,
      },
      {
        time: 1723147200000,
        open: 0.00000272325608959985,
        close: 0.00000267647064539773,
        high: 0.00000273084516135978,
        low: 0.0000026697981155535,
        value: 10385.5,
      },
      {
        time: 1723150800000,
        open: 0.00000267647064539773,
        close: 0.00000277372035519743,
        high: 0.00000277372035519743,
        low: 0.00000267647064539773,
        value: 6688.7,
      },
      {
        time: 1723154400000,
        open: 0.00000277372035519743,
        close: 0.0000027537541408779,
        high: 0.00000280808163037818,
        low: 0.00000271013369822416,
        value: 11307.1,
      },
      {
        time: 1723158000000,
        open: 0.0000027537541408779,
        close: 0.00000284961846512869,
        high: 0.00000285654818653974,
        low: 0.0000027537541408779,
        value: 90542.1,
      },
      {
        time: 1723161600000,
        open: 0.00000284961846512869,
        close: 0.0000027984540457049,
        high: 0.00000287328567714431,
        low: 0.00000278344384120351,
        value: 63199.5,
      },
      {
        time: 1723165200000,
        open: 0.0000027984540457049,
        close: 0.00000287714913920343,
        high: 0.00000287762058767082,
        low: 0.00000279274530959931,
        value: 35651.8,
      },
      {
        time: 1723168800000,
        open: 0.00000287714913920343,
        close: 0.0000028107421473334,
        high: 0.00000287714913920343,
        low: 0.0000028107421473334,
        value: 12985.4,
      },
      {
        time: 1723172400000,
        open: 0.0000028107421473334,
        close: 0.00000290277077857219,
        high: 0.00000290277077857219,
        low: 0.00000280962627955995,
        value: 59419.5,
      },
      {
        time: 1723176000000,
        open: 0.00000290277077857219,
        close: 0.00000278838140074049,
        high: 0.00000290488339369962,
        low: 0.00000278838140074049,
        value: 74716.2,
      },
      {
        time: 1723179600000,
        open: 0.00000278838140074049,
        close: 0.00000281500311348989,
        high: 0.00000283771909642947,
        low: 0.00000275689652356568,
        value: 40572.5,
      },
      {
        time: 1723183200000,
        open: 0.00000281500311348989,
        close: 0.00000276175272680401,
        high: 0.00000282104905121399,
        low: 0.00000275659616859176,
        value: 11104.1,
      },
      {
        time: 1723186800000,
        open: 0.00000276175272680401,
        close: 0.00000275544872739402,
        high: 0.00000282438646244086,
        low: 0.00000275544872739402,
        value: 12041.3,
      },
    ]);

    chart.timeScale().fitContent();
  }, []);

  return (
    <div>
      <div ref={containerRef} id="chart"></div>
    </div>
  );
}

export default App;


```

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

[]]

[https://codesandbox.io/p/devbox/cold-browser-7xx2rf](https://codesandbox.io/p/devbox/cold-browser-7xx2rf)

**Comment by illetid** [comment]
Hi, could you pls explain more of what you are trying to achieve? From the code you submitted, there is no issue it is just how it works. your value is around `1e-22`  and in `priceFormatter`  you have a `.toFixed(2)` which is '`0.00'` for such small numbers

**Comment by Pp-Tomo** [comment]
> Hi, could you pls explain more of what you are trying to achieve? From the code you submitted, there is no issue it is just how it works. your value is around `1e-22` and in `priceFormatter` you have a `.toFixed(2)` which is '`0.00'` for such small numbers

Yes, there is no problem with the code.
But when value is extremely small, rightPriceScale is no longer displayed.

I hope the final format is
`0.0000000001 => 0.0{9}1`

**Comment by Pp-Tomo** [comment]
> > Hi, could you pls explain more of what you are trying to achieve? From the code you submitted, there is no issue it is just how it works. your value is around `1e-22` and in `priceFormatter` you have a `.toFixed(2)` which is '`0.00'` for such small numbers
> 
> Yes, there is no problem with the code. But when value is extremely small, rightPriceScale is no longer displayed.
> 
> I hope the final format is `0.0000000001 => 0.0{9}1`

I tried to enlarge its precision, turn it into an integer, and then reduce its precision through

`localization.priceFormatter,` and achieved my purpose.

But it has a new problem.

The height of the candlestick chart is very small and there are negative numbers.



![image](https://github.com/user-attachments/assets/0bf0f6bf-1ea1-4982-8f38-22d2cbd1b32d)

**Comment by illetid** [comment]
Did you specify `minMove` https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/PriceFormatCustom for the series? I tried  to modify your original code in [code sandbox](https://codesandbox.io/p/sandbox/lightweight-charts-skeleton-forked-qqhql5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzl7foxt00063b6lxaqiqw4f%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzl7foxs00023b6l4ud9m9xw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzl7foxt00033b6lxhdyqyvh%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzl7foxt00053b6lx0crl0lg%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzl7foxs00023b6l4ud9m9xw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzl7foxs00013b6lzcsjaeog%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A20%257D%255D%257D%255D%252C%2522id%2522%253A%2522clzl7foxs00023b6l4ud9m9xw%2522%252C%2522activeTabId%2522%253A%2522clzl7foxs00013b6lzcsjaeog%2522%257D%252C%2522clzl7foxt00053b6lx0crl0lg%2522%253A%257B%2522id%2522%253A%2522clzl7foxt00053b6lx0crl0lg%2522%252C%2522activeTabId%2522%253A%2522clzl7gckr001f3b6ll7o7k94y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzl7foxt00043b6lrbpqt23h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzl7gckr001f3b6ll7o7k94y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzl7foxt00033b6lxhdyqyvh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzl7foxt00033b6lxhdyqyvh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D) and added formatting and I can't reproduce case with negative numbers. Could you provide more detailed example of how to reproduce your issue? C

**Comment by illetid** [comment]
you need to specify the series' `priceFormat` https://codesandbox.io/p/devbox/cocky-murdock-gq5kwh?file=%2Fsrc%2FApp.tsx%3A18%2C12  Please check the docs https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn and https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatCustom

**Comment by Pp-Tomo** [comment]
> Did you specify `minMove` https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/PriceFormatCustom for the series? I tried to modify your original code in [code sandbox](https://codesandbox.io/p/sandbox/lightweight-charts-skeleton-forked-qqhql5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzl7foxt00063b6lxaqiqw4f%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzl7foxs00023b6l4ud9m9xw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzl7foxt00033b6lxhdyqyvh%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzl7foxt00053b6lx0crl0lg%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzl7foxs00023b6l4ud9m9xw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzl7foxs00013b6lzcsjaeog%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A20%257D%255D%257D%255D%252C%2522id%2522%253A%2522clzl7foxs00023b6l4ud9m9xw%2522%252C%2522activeTabId%2522%253A%2522clzl7foxs00013b6lzcsjaeog%2522%257D%252C%2522clzl7foxt00053b6lx0crl0lg%2522%253A%257B%2522id%2522%253A%2522clzl7foxt00053b6lx0crl0lg%2522%252C%2522activeTabId%2522%253A%2522clzl7gckr001f3b6ll7o7k94y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzl7foxt00043b6lrbpqt23h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzl7gckr001f3b6ll7o7k94y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzl7foxt00033b6lxhdyqyvh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzl7foxt00033b6lxhdyqyvh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D) and added formatting and I can't reproduce case with negative numbers. Could you provide more detailed example of how to reproduce your issue?


Thanks for your quick answer. 

The negative numbers are another solution I tried, 

but the problem I have now is that the price on the right disappears. As shown in the sandbox

**Comment by illetid** [comment]
did you check the https://codesandbox.io/p/devbox/cocky-murdock-gq5kwh?file=%2Fsrc%2FApp.tsx%3A18%2C12 ?

**Comment by Pp-Tomo** [comment]
> 您检查过https://codesandbox.io/p/devbox/cocky-murdock-gq5kwh?file=%2Fsrc%2FApp.tsx%3A18%2C12吗？

Thanks for your idea, I have solved the problem.
