### ISSUE TITLE
Unable to display the real-time price of priceLine on the price axis

### ISSUE THREAD

**Issue by ZhangPeibin** [tradingview/lightweight-charts#1682]
I implemented the candlestick chart according to the example, but there is no real-time price display on the price axis on the right.
<img width="886" alt="截屏2024-08-26 11 20 34" src="https://github.com/user-attachments/assets/61eb39b4-2ff9-4bf6-830c-5a4db2890e5c">

I hope to see a green area like the official example.
<img width="886" alt="截屏2024-08-22 16 47 24" src="https://github.com/user-attachments/assets/7059adbd-a6c0-403b-bfd2-d3cf2f75abe0">

Below is my code:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/df1ec0ca-a80e-4ba4-a86d-f4dc3be12c2b">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/fb3e5094-c217-4e6a-b9b6-6ef769aa2329">

**Comment by ZhangPeibin** [comment]
Please help me, thank you very much！

**Comment by illetid** [comment]
Hi, could you pls check that series has [lastValueVisible](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/SeriesOptionsCommon) option set to `true`. It is true but pls double-check

**Comment by ZhangPeibin** [comment]
> Hi, could you pls check that series has [lastValueVisible](https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/SeriesOptionsCommon) option set to `true`. It is true but pls double-check

Thanks bro ! 
I change ' const chart = ref() ' to  'let chart :any ' and it worked.
