### ISSUE TITLE
Is it possible to real-time update chart per minute and not per day?

### ISSUE THREAD

**Issue by GordeySt** [tradingview/lightweight-charts#1684]
I am trying to update chart data in real-time with using WebSockets. All the examples provided by documentation shows the real-time update per day. When I'm trying to update data per minute, my candlestick are not created on every new minute but staying in one place with changed time. All the time values are specified to seconds.

![image](https://github.com/user-attachments/assets/dd9689e7-1860-46ee-91cd-4410e9f2acd0)

![image](https://github.com/user-attachments/assets/fa044b34-21fa-4a7a-8085-01d4f559874a)

**Comment by SlicedSilver** [comment]
To update the candlestick chart in real-time per minute using WebSockets, you need to ensure that the time value for each candlestick is defined as the start of the candle. While a candlestick is receiving updates (such as during the current minute), the time value should remain unchanged. This way, the library will update the last candlestick by replacing it with the new data.

When you call the `update` method with a candlestick that has a new timestamp larger than the previous one, it will create a new candlestick on the chart.

Here's a brief explanation and code snippet to illustrate this:

1. **Initialize the chart and series:**
    ```javascript
    const chart = createChart(document.getElementById('container'));
    const series = chart.addCandlestickSeries();
    ```

2. **Set initial data:**
    ```javascript
    series.setData([
        { time: 1693526400, open: 100, high: 110, low: 90, close: 105 }, // Example data
        // Add more initial data points here
    ]);
    ```

3. **Update the chart in real-time:**
    ```javascript
    const socket = new WebSocket('wss://example.com/socket');
    socket.onmessage = function(event) {
        const data = JSON.parse(event.data);
        const lastCandle = series.data().slice(-1)[0];

        if (data.time === lastCandle.time) {
            // Update the last candle
            series.update({
                time: lastCandle.time,
                open: lastCandle.open,
                high: Math.max(lastCandle.high, data.high),
                low: Math.min(lastCandle.low, data.low),
                close: data.close,
            });
        } else if (data.time > lastCandle.time) {
            // Add a new candle
            series.update(data);
        }
    };
    ```

For more detailed information, you can refer to the [[Realtime updates | Lightweight Charts](https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates)](https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates) page.
