### ISSUE TITLE
Is it possible to show weekly data, depending on daily data ?

### ISSUE THREAD

**Issue by ZeroChaininfo** [tradingview/lightweight-charts#1686]
Good day,

I have chart with daily data.
Is it possible to make it display weekly data depending on daily data i have ?

Thanks for your time!

**Comment by SlicedSilver** [comment]
To achieve this, you will need to handle the data aggregation on your end. The Lightweight Charts library (LWC) is designed to display the data as provided and does not perform any internal data aggregation, such as converting daily data into weekly data. You will need to preprocess your daily data into the desired weekly format before passing it to the chart.

**Comment by ZeroChaininfo** [comment]
thanks for the clear answer, have a good day!
