### ISSUE TITLE
Keep Order Lines Always on Top in TradingView Charts Library

### ISSUE THREAD

**Issue by flipflopapp** [tradingview/lightweight-charts#1696]
**Is your feature request related to a problem? Please describe.**

I'm working with the TradingView Charting Library, and I've created some custom order lines using the createOrderLine function. The problem I'm facing is that these lines sometimes get hidden behind the candles, especially when the mouse is hovering over the candles.

**Describe the solution you'd like**

I would like an additional function in createOrderLine API that will ensure that the order lines always stay on top (z-index-wise) and never get hidden by other chart elements like candles. 

**Additional context**

The order line is created like below,

  const line = chart.createOrderLine(...)
    .onCancel(...)
    .setPrice(...)
    .setText(orderText)
    .setTooltip(tooltip)
     ...
    
Here I would like to specify to keep the `line` allways on top or something akin.  

   .allwaysOnTop()

**Comment by illetid** [comment]
Hi @flipflopapp this repository is for the lightweight charts. To submit a ticket related to advanced charts, please use the following repository: https://github.com/tradingview/charting_library/issues

**Comment by flipflopapp** [comment]
> Hi @flipflopapp this repository is for the lightweight charts. To submit a ticket related to advanced charts, please use the following repository: https://github.com/tradingview/charting_library/issues

This link is broken. What is the renamed repo name? Ty

**Comment by illetid** [comment]
the link is not broken, you need to get an access https://www.tradingview.com/charting-library-docs/v26/getting_started/quick-start#getting-access

**Comment by ankitpal1029** [comment]
Hey did you figure out a way to do this @flipflopapp
