### ISSUE TITLE
Key "zb" is being added to javascript object

### ISSUE THREAD

**Issue by Daniel-Gins** [tradingview/lightweight-charts#1698]
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:**

```
function updated_stock_data() {
    import_raw_data = lineData();//initliaze data 
    if (typeof import_raw_data === 'object' && Object.keys(import_raw_data).length > 0) {
        let initialized_data = import_raw_data; // Fetch the data once
        let keysToKeep = ['t', 'p'];
        let keyMap = { 't': 'time', 'p': 'value' }; // Mapping old keys to new keys

        filtered_data = keysToKeep.reduce((obj, key) => {
            if (key in initialized_data) { //if string(key) is in initialized_data continue on 
                let newKey = keyMap[key] || key; // Use the new keys from keyMap, or default to the original key if no mapping exists
                    if (newKey === "time"){
                        obj[newKey] = Date.parse(initialized_data[key])

                }   else{
                        obj[newKey] = initialized_data[key];
                        }
                
            }
            return obj;
            
        }, {});
        
        series.update(filtered_data); 
        console.log("Data: ",filtered_data);
    } else {
        console.log("Data not ready");
    }
}
```

**Actual behavior:**
```
Data:
{
    "time": 1726691470506,
    "value": 134.56,
    "zb": 1726691470506
}
```

**Expected behavior:**
```
Data:
{
    "time": 1726691470506,
    "value": 134.56,
}
```

I expected my initial data when sent to the client to be processed and when done processing be returned as ...

```
{
    "T": "t",
    "S": "FAKEPACA",
    "i": 1,
    "x": "N",
    "p": 134.56,
    "s": 3,
    "c": [
        " "
    ],
    "z": "A",
    "t": "2024-09-18T20:30:55.502674632Z"
}
```
```
Data:
{
    "time": 1726691470506,
    "value": 134.56,
}
```
**Screenshots:**

![image](https://github.com/user-attachments/assets/c8453dd5-b191-4223-aad1-1f512df430cb)

![image](https://github.com/user-attachments/assets/c6a7876e-00c0-43a6-b4fb-677d4149fb32)

**CodeSandbox/JSFiddle/etc link:**

**Comment by Daniel-Gins** [comment]
This is showing that the function update() is adding key:value pair. Will this cause issues or should I ignore?

```
 console.log("filtered data before",filtered_data)
 series.update(filtered_data); // Update the chart with the shallow copy of filtered data 
 console.log("Filtered Data after: ", filtered_data);
```

![image](https://github.com/user-attachments/assets/4b5a4192-a77d-4ce6-aa7b-91a91260e33d)

**Comment by illetid** [comment]
Hi, @Daniel-Gins library converts the time if needed to internal time value. there is no error. if you want to work with an object that you've passed to the library after that. you need to do a copy of that object before. something like  ` series.update({...filtered_data}); `

**Comment by Daniel-Gins** [comment]
> Hi, @Daniel-Gins library converts the time if needed to internal time value. there is no error. if you want to work with an object that you've passed to the library after that. you need to do a copy of that object before. something like  ` series.update({...filtered_data}); `

Thank you! Will do that!
