### ISSUE TITLE
add unsubscribe all event API for chart

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#170]
**Is your feature request related to a problem? Please describe.**
There is no way to unsubscribe event if I didn't have reference to function. For example
```
chart.subscribeCrosshairMove(function (param) {
    console.log(param);
}
```

**Describe the solution you'd like**
Something like this
```
chart.unsubscribeAllClick();
chart.unsubscribeAllCrosshairMove();
chart.unsubscribeAllVisibleTimeRangeChange();

chart.unsubscribeAllEvents(); // This basically does all 3 above in 1 line
```

**Additional context**

Also it would be nice to unsub all event with one line, rather than unsub event one by one. I did look at `chart-api.ts` and it does have unsub all on `remove()` , it just not exposed as separate API (I don't want to remove the chart, just unsub all)

**Comment by timocov** [comment]
Hey @SuperPenguin,

it's interesting suggestion. Did you see something similar in other libraries? If so, could you point to their docs with that please?

**Comment by SuperPenguin** [comment]
I think the closest thing I know is this one, [jQuery callbacks.empty()](https://api.jquery.com/callbacks.empty/)

**Comment by timocov** [comment]
I'm not sure that jQuery has the best API to measure up to, unfortunately.

I've asked you to provide any example in other or/and similar libraries because it seems that I didn't faced such methods in anywhere else and I hope there is some causes for that.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
