### ISSUE TITLE
Multi pane support 

### ISSUE THREAD

**Issue by vishnuc** [tradingview/lightweight-charts#1708]
HI , I saw in some github post that multi pane has been implemented , But If I click v5 , page is not found.When can I access the multi pane feature.

**Comment by SlicedSilver** [comment]
Version 5 is still in development, and we can't offer a definitive release date at this point.
If you would like to start using the multi-pane support then you can checkout the [`v5-candidate` branch](https://github.com/tradingview/lightweight-charts/tree/v5-candidate) and build the library package yourself and install it locally in your project.

**Comment by vishnuc** [comment]
Thanks any internal documentation on how to use multi panes.

**Comment by SlicedSilver** [comment]
- https://github.com/tradingview/lightweight-charts/blob/0fc1c72e392aa4f1b1401618d82391ffe2131307/website/docs/panes.md
- https://github.com/tradingview/lightweight-charts/blob/0fc1c72e392aa4f1b1401618d82391ffe2131307/website/tutorials/how_to/panes.mdx

**Comment by vishnuc** [comment]
Thank you will test and report if any  bugs :)

**Comment by patil-tejas** [comment]
@vishnuc  did you figure it out ?

**Comment by vishnuc** [comment]
yea yea I am using it , multipane works fine as of now with the link sent by SlicedSilver

**Comment by patil-tejas** [comment]
> yea yea I am using it , multipane works fine as of now with the link sent by SlicedSilver

Could you help me set up the V5 so I can import it in my project .

I cloned the V5 branch but couldn't build it .
I did npm install & but had issues with multiple dependencies not installing.

Any steps you could suggest

**Comment by vishnuc** [comment]
my npm install and npm run build went smooth.. what os are u using..? try with sudo npm install

**Comment by patil-tejas** [comment]
> my npm install and npm run build went smooth.. what os are u using..? try with sudo npm install

I am using windows.

git clone --branch v5-candidate https://github.com/tradingview/lightweight-charts.git

after running npm install i get this ...and even if i manually get some version of roll up further packages give same error
![image](https://github.com/user-attachments/assets/1f550e12-14f6-4939-8d28-0e9c27316971)

**Comment by vishnuc** [comment]
try 

npm cache clean --force
npm install rollup@latest

**Comment by patil-tejas** [comment]
> try
> 
> npm cache clean --force npm install rollup@latest

Thanks a lot!
somehow i think clean cache worked

**Comment by vishnuc** [comment]
Nice , shall we connect via whatsapp/telegram , I would like to have some friends who is doing tradingview lightweight chart.So we can help each other.

**Comment by patil-tejas** [comment]
[> Nice , shall we connect via whatsapp/telegram , I would like to have some friends who is doing tradingview lightweight chart.So we can help each other.

Join this official TV discord

https://github.com/tradingview/lightweight-charts/issues/241#issuecomment-549897381

**Comment by patil-tejas** [comment]
> Nice , shall we connect via whatsapp/telegram , I would like to have some friends who is doing tradingview lightweight chart.So we can help each other.

I too am connecting with people there . Username: bOOmer (ID:boomer08)

**Comment by vishnuc** [comment]
not able to find u , add me at https://t.me/vishnu_trader
