### ISSUE TITLE
Add coordinateToPrice method to ISeriesApi

### ISSUE THREAD

**Issue by kriw** [tradingview/lightweight-charts#171]
**Is your feature request related to a problem? Please describe.**

I would like to know the price which mouse cursor points to.
`coordinateToPrice` is implemented in `PriceScale`, but `IPriceScaleApi` does not export this function. I think we can get the price with the argument of `MouseEventHandler` if the function is exported.

**Describe the solution you'd like**

Add `coordinateToPrice` to `IPriceScaleApi`.

**Comment by timocov** [comment]
It looks like you [already can get prices](https://github.com/tradingview/lightweight-charts/blob/3f9dbecd227813f45de67ba0661442cdb7c3b451/src/api/ichart-api.ts#L20-L26) in mouse event handlers (or [in the docs](https://github.com/tradingview/lightweight-charts/blob/master/docs/events.md#crosshair-move)). Do you need something specific?

**Comment by kriw** [comment]
The `param` contains `x`, `y` and the prices of series at `x`, but does not have price.

So, I would expect the `param` to have
```
export interface MouseEventParams {
	time?: UTCTimestamp | BusinessDay;
        price?: number;
	point?: Point;
	seriesPrices: Map<ISeriesApi<SeriesType>, BarPrice | BarPrices>;
}
```

**Comment by timocov** [comment]
> I think we can not get the price at the mouse cursor, but can get the price on the serieses.

Ah, you're right!

We already have [`priceToCoordinate`](https://github.com/tradingview/lightweight-charts/blob/c3069a4ce6fffcfbf54f4f099bd00b301da53699/src/api/iseries-api.ts#L28-L32) method in `ISeriesApi`, and I don't think that it's big deal to add `coordinateToPrice` as well.

If you wish - you can make a PR with adding this method.
