### ISSUE TITLE
LastPriceAnimation indicator overlaps priceLine axis label

### ISSUE THREAD

**Issue by ChristopherJohnson25** [tradingview/lightweight-charts#1711]
**Lightweight Charts™ Version:** 4.1.1

Add a price line with axis label 
Add LastPriceAnimationMode.OnDataUpdate and see the pulsing dot indicator overlaps the priceLine axis label

**Comment by SlicedSilver** [comment]
Could you please try with version `4.1.4` or later?
We had a fix related to this issue in that release.

**Comment by ChristopherJohnson25** [comment]
@SlicedSilver I've upgraded and still see the issue. Do I need to do anything with zOrder?

**Comment by SlicedSilver** [comment]
The fix was for the Plugins API, and didn't fix the behaviour that you've noticed.

Reproduction here: https://stackblitz.com/edit/lwc-1650-2xqevb?file=src%2Fmain.ts
