### ISSUE TITLE
updateData is not a function

### ISSUE THREAD

**Issue by pigloo** [tradingview/lightweight-charts#173]
Using the .updateData() function from the documentation [here](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md) for a series produces a `is not a function` error in the console.

```javascript

import { createChart } from 'lightweight-charts';
const chart = createChart(document.body, { width: 400, height: 300 });
const candlestickSeries = chart.addCandlestickSeries();

candlestickSeries.setData([
    { time: '2018-12-19', open: 141.77, high: 170.39, low: 120.25, close: 145.72 },
    { time: '2018-12-20', open: 145.72, high: 147.99, low: 100.11, close: 108.19 },
]);

candlestickSeries.updateData({
    time: '2018-12-21',
    open: 141.77,
    high: 170.39,
    low: 120.25,
    close: 145.72,
});

```

**The console produces:**
`Uncaught TypeError: candlestickSeries.updateData is not a function`

**Comment by SuperPenguin** [comment]
The function is actually `update(...)` not `updateData(....)`

**Comment by timocov** [comment]
Yeah, it's typo in the docs. Fixed in 078541a.

**Comment by pigloo** [comment]
Perhaps some documentation about the updated function should be added to the individual series type pages as well?

https://github.com/tradingview/lightweight-charts/blob/master/docs/area-series.md
https://github.com/tradingview/lightweight-charts/blob/master/docs/bar-series.md
https://github.com/tradingview/lightweight-charts/blob/master/docs/candlestick-series.md
https://github.com/tradingview/lightweight-charts/blob/master/docs/histogram-series.md
https://github.com/tradingview/lightweight-charts/blob/master/docs/line-series.md

**Comment by timocov** [comment]
@pigloo Currently these methods are described in [series-basics](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#update) page (common for all series types). I'm not sure that we need to have these duplication (that docs aren't API references), but if you think that it would be good for everybody you can make a PR with changes you want to see there.
