### ISSUE TITLE
Add time, minute, and second

### ISSUE THREAD

**Issue by gebilaofan** [tradingview/lightweight-charts#174]
**Is your feature request related to a problem? Please describe.**
Regarding the time format, only the year, month, and day. If I want to be accurate to the minute and minute, is there still no documentation?

**Describe the solution you'd like**
Tiem accurate to hour, minute and second

**Comment by timocov** [comment]
What's about [`timeVisible` and `secondsVisible` options](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#time-axis)?

**Comment by gebilaofan** [comment]
> 有什么关系[`timeVisible`和`secondsVisible`选择](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#time-axis)？

How the date on the timeline is accurate to the second, how to write the format. I see the time written in the document is the year, month and day. For example: 2018-06-25. If I want 2018-06-25 hh-mm-ss, how to write time when setting the value

**Comment by timocov** [comment]
Can you provide a screenshot what are you talking about please?

**Comment by gebilaofan** [comment]
I want to add time and seconds in the timeline
like this

![微信图片_20190816163700](https://user-images.githubusercontent.com/46524158/63154928-38841480-c044-11e9-9b55-8587bdc06636.png)
I have a requirement to update the data every second. So I want the timeline to be accurate to the second.

```
areaSeries.setData([
                { time: '2019-08-16-01-00', value: 10 },
                { time: '2019-08-16-01-01', value: 12 },
                { time: '2019-08-16-01-02', value: 13 },
                { time: '2019-08-16-01-03', value: 14 },
                { time: '2019-08-16-01-04', value: 15 },
                { time: '2019-08-16-01-05', value: 14 },
                { time: '2019-08-16-01-06', value: 13 },
                { time: '2019-08-16-01-07', value: 11 },
                { time: '2019-08-16-01-08', value: 12 },
                { time: '2019-08-16-01-09', value: 6 },
                { time: '2019-08-16-01-10', value: 15},
                { time: '2019-08-16-01-11', value: 12 },
                { time: '2019-08-16-01-12', value: 17 },
                { time: '2019-08-16-01-13', value: 24 },
                { time: '2019-08-16-01-14', value: 25 },
                { time: '2019-08-16-01-15', value: 21 },
            ]);
```
![微信图片_20190816163043](https://user-images.githubusercontent.com/46524158/63154551-76cd0400-c043-11e9-981e-78758a4f3794.png)

How to write the year, month, day, hour, minute, second？

**Comment by timocov** [comment]
https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp

> If your chart displays an intraday interval, you should use a UNIX Timestamp format for time point data transfer.

**Comment by gebilaofan** [comment]
> https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp
> 
> > 如果图表显示日内间隔，则应使用UNIX时间戳格式进行时间点数据传输。
Ok, let me try
Thank you！

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by ErcinDedeoglu** [comment]
> What's about [`timeVisible` and `secondsVisible` options](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#time-axis)?

I couldnt find it "timeVisible"

**Comment by timocov** [comment]
@ErcinDedeoglu my bad - I needed to post permalink to that options. See https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options.

**Comment by tghilardi** [comment]
Hey @timocov,

I am using unixtimestamp as per instructions and I get the opposite error message.

![image](https://user-images.githubusercontent.com/2612420/64567808-787ea480-d32f-11e9-84ea-a49945481e51.png)

using 
{ time: '1566831600', open: '206.1773', high: '206.59', low: '206.1', close: '206.45' },{ time: '1566831900', open: '206.47', high: '206.55', low: '206.11', close: '206.3395' },....

**Comment by ErcinDedeoglu** [comment]
Remove ' char. it's waiting int value. You passing string

**Comment by tghilardi** [comment]
Thank you @ErcinDedeoglu ! Works now.

**Comment by Abidjon** [comment]
If we move the scale in a wider range there are some values appear with huge precision like 1.4000000000000001 or even 1.450000000000000002
How to avoid this precision?
![image](https://user-images.githubusercontent.com/41767515/113061428-d4d83c00-91d3-11eb-8a0c-8f67ef77da2c.png)

**Comment by Abidjon** [comment]
just made it work as follow:

> priceFormat: {
    type: 'custom',
    minMove: '0.000001',
    formatter: (price) => {
      if (price < 0.000001) return parseFloat(price).toPrecision(8)
      else if (price >= 0.000001 && price < 1) return parseFloat(price).toPrecision(6)
      else return parseFloat(price).toPrecision(6)
    }
  },                                         priceScale: {
    autoScale: true
  },
  localization: {
    locale: 'en-US',
    priceFormatter:  (price) => {
      if (price < 0.000001) return parseFloat(price).toPrecision(8)
      else if (price >= 0.000001 && price < 1) return parseFloat(price).toPrecision(6)
      else return parseFloat(price).toPrecision(6)
    }
  },
![image](https://user-images.githubusercontent.com/41767515/113065462-c3def900-91da-11eb-8065-d5f1d5aec9da.png)
