### ISSUE TITLE
Symbol Search dialog missing Year column

### ISSUE THREAD

**Issue by BillionShields** [tradingview/lightweight-charts#1749]
Symbol Search dialog missing Year column. Should show year from the data is available for each data source 
![GeCJMfEX0AArBL4](https://github.com/user-attachments/assets/1647b861-717f-45c0-9dfe-524f1ece9ba6)

**Comment by SlicedSilver** [comment]
This repo is for the Lightweight Charts open source project and is unrelated to Chart provided on TradingView.com.

Please use the support system on the TradingvView.com site
