### ISSUE TITLE
Bug: Parallel channel resize controls  invisible beyond the screen 

### ISSUE THREAD

**Issue by BillionShields** [tradingview/lightweight-charts#1751]
Resize controls for Parallel Channel control should be always visible at cursor click position
now bug resizes controls beyond the screen, impossible to access 
Make controls visible at the point of click. Both controls should always be visible on the screen
![parallcha](https://github.com/user-attachments/assets/019a8d72-ab30-49b7-944e-5f674cbc806e)

**Comment by SlicedSilver** [comment]
This repo is for the Lightweight Charts open source project and is unrelated to Chart provided on TradingView.com.

Please use the support system on the TradingvView.com site
