### ISSUE TITLE
Bug: Magnet mode works incorrectly USE ZIG ZAG PIVOTS! 

### ISSUE THREAD

**Issue by BillionShields** [tradingview/lightweight-charts#1752]
Magnet mode should attach controls to the Pivot points (use ZigZag) not random points
It's impossible to set a pitchfork with magnet attaching to random candles! 
USE ZIG ZAG To attach controls like Lines, Pitchforks, Fibonacci tools etc to PIVOT POINTS and not random candles!
TIME WASTER! 

![image](https://github.com/user-attachments/assets/a8d4274d-0b8e-4d1e-a4f0-721fc3d1256f)

**Comment by SlicedSilver** [comment]
This repo is for the Lightweight Charts open source project and is unrelated to Chart provided on TradingView.com. 

Please use the support system on the TradingvView.com site
