### ISSUE TITLE
[BUG] autoScale of priceScale can not work after setDate 

### ISSUE THREAD

**Issue by yoyo201626** [tradingview/lightweight-charts#1759]
**Lightweight Charts™ Version:** 
^4.2.0
**Steps/code to reproduce:**
1.  go to lightweight-charts official document website -> tutorials -> Example -> [range-switcher](https://tradingview.github.io/lightweight-charts/tutorials/demos/range-switcher)

2. look at the chart example
![image](https://github.com/user-attachments/assets/47d628d3-a147-43bb-aefc-4b297b9ceab4)

3.  scroll up priceScale 
![image](https://github.com/user-attachments/assets/6e905a96-4d03-4b3e-8496-c6ee7a5f3d69)

4. drag the chart  up
![image](https://github.com/user-attachments/assets/ac9d1645-1239-44ac-94f7-986a6d3faa73)
![image](https://github.com/user-attachments/assets/a7ccf01d-d659-4d6b-bba6-be20d49539f9)

5. change range to “1W”
![image](https://github.com/user-attachments/assets/184803cc-88d1-4595-9037-4c787d2475d9)

**Actual behavior:**

the chart can not auto Scale to effective curve
![image](https://github.com/user-attachments/assets/2e5e84f0-d632-4a15-9d8c-d3f05ba98194)

**Expected behavior:**

I expected Provides apis to control priceScale, just like [timeScale ](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#setvisiblelogicalrange), or make [autoscale](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceScaleOptions#autoscale) fix

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
It is the expected behaviour that the chart maintains the price scale position / range defined by the user manually.

If you would like to reset the price scale then you can apply the `autoScale: true` option via the price scale api. For example:
```js
chart.priceScale('right').applyOptions({ autoScale: true });
```

- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#pricescale
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPriceScaleApi#applyoptions
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceScaleOptions#autoscale

**Comment by yoyo201626** [comment]
> It is the expected behaviour that the chart maintains the price scale position / range defined by the user manually.
> 
> If you would like to reset the price scale then you can apply the `autoScale: true` option via the price scale api. For example:
> 
> ```js
> chart.priceScale('right').applyOptions({ autoScale: true });
> ```
> 
> * https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#pricescale
> * https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPriceScaleApi#applyoptions
> * https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceScaleOptions#autoscale

It work when i put  `priceScale().applyOptions({ autoScale: true });` before `setData` ! Thank you @SlicedSilver .
I thought the default value of 'autoscale' was' true 'which meant that auto scaling was always active:

![image](https://github.com/user-attachments/assets/7f5a4409-d189-4b3c-be14-ce5285fe48c6)
