### ISSUE TITLE
How to create chart with both candlestick and histogram? just like "charting_library"

### ISSUE THREAD

**Issue by hitbear518** [tradingview/lightweight-charts#176]
I mean like ohlc on top and volume on bottom

**Comment by timocov** [comment]
Something like that? https://jsfiddle.net/TradingView/cnbamtuh/

**Comment by hitbear518** [comment]
Thanks for reply.

Not exactly like the example...
I have tried that example, but just like it, I only have One Y axis, And because my price is like 180, but my volume is like 2000, which makes the Volume Overlaps my price.

**Comment by timocov** [comment]
So, do you want to have multiple price axes, right? #129

**Comment by hitbear518** [comment]
Oh, Yes, so for now lightweight-charts will not support that?

Also here's the demo with my data
![image](https://user-images.githubusercontent.com/5070531/63247904-b6d8f480-c298-11e9-9e6d-b0b659062721.png)

**Comment by timocov** [comment]
> Oh, Yes, so for now lightweight-charts will not support that?

Yes, lightweight-charts will not support multiple price axes.

> Also here's the demo with my data

In your case you can try to play with margins for price scales. It might reduce cases when overlapping happen. Also, it looks like you've added both series on the same scale instead of adding volume to overlay.

**Comment by hitbear518** [comment]
thanks, scaleMargin do make it better, 
For now I don't quite understand the options, I will try to tweak it more.

**Comment by timocov** [comment]
> I don't quite understand the options

Which one?

**Comment by hitbear518** [comment]
Previously I mean timeScale.barSpace and scaleMargins, but after playing with it, I think I have got it, thanks.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by satyam-systango** [comment]
@timocov How can we implement volume bar from top to bottom ?

**Comment by romfrancois** [comment]
> @timocov How can we implement volume bar from top to bottom ?

What do you mean by top to bottom?

There's an example [here](https://jsfiddle.net/TradingView/cnbamtuh/) or a bigger list [here](https://www.tradingview.com/lightweight-charts/) that could probably help you.

**Comment by satyam-systango** [comment]
![image](https://user-images.githubusercontent.com/77108993/213674352-dc8eb988-f67a-465a-a0a1-51818ca0b1e7.png)

Here volume bar showing bottom to top direction How can we invert it to top to bottom direction ? is this any way to show volume bar at top of chart ?

**Comment by satyam-systango** [comment]
![image](https://user-images.githubusercontent.com/77108993/213674814-0d054b2f-1800-4cc6-baf1-b09737008ae3.png)

I am trying to invert it but there is no solution i got at the moment Can you please suggest ? @timocov 
@romfrancois

**Comment by romfrancois** [comment]
You could actually change the `scaleMargin` prop to that
```
scaleMargins: {
	top: 0,
	bottom: 0.8,
},
```

and it would render something like

<img width="614" alt="Screenshot 2023-01-20 at 16 22 15" src="https://user-images.githubusercontent.com/3977635/213750459-587011fb-b8cf-497d-b803-01a815922b51.png">

**Comment by romfrancois** [comment]
or are you asking for something like that?

<img width="614" alt="Screenshot 2023-01-20 at 16 23 42" src="https://user-images.githubusercontent.com/3977635/213751154-8d2a11f3-2ebf-489c-84ba-7a1960d90114.png">

**Comment by satyam-systango** [comment]
yes that's i want

**Comment by satyam-systango** [comment]
But one more thing the position is wrong left --> right see look at this. They are vise versa to each other 
![](https://user-images.githubusercontent.com/3977635/213751154-8d2a11f3-2ebf-489c-84ba-7a1960d90114.png)

![](https://user-images.githubusercontent.com/3977635/213750459-587011fb-b8cf-497d-b803-01a815922b51.png)

**Comment by satyam-systango** [comment]
@romfrancois please suggest me how do i get this

**Comment by romfrancois** [comment]
@satyam-systango ... I've answered on your dedicated [ticket](https://github.com/tradingview/lightweight-charts/issues/1247). Please avoid raising the same issue on multiple places; this is slowing us down vs properly helping you.
