### ISSUE TITLE
separate import for each series in v5 ?

### ISSUE THREAD

**Issue by vishnuc** [tradingview/lightweight-charts#1762]
Hi , I was working with old v5 candidate and updated recently and my chart stopped working , later found that we must use 

`import { createChart, CandlestickSeries, HistogramSeries } from 'tv.mjs';
`
So these is major change in v5  , I am building a new project based on v5 and can some one tell if there is going to be any other major change ?

If possible can some one tell when v5 is going to release ? If its within 1 or 2 months (new year gift ;) ) , I will wait some more time.

**Comment by SlicedSilver** [comment]
All the breaking changes we expect to make for v5 have been completed and merged into the v5-candidate branch. The release is targeted for next month. The main remaining tasks are related to QA, internal feedback, and documentation.

I would say that it can now be considered at a release candidate level and you should be able to start using the new version in your project. 👍
