### ISSUE TITLE
Extended hours future projection on any control (ie triangle, pitchfork etc) BUG Future time point not correct!!!!

### ISSUE THREAD

**Issue by BillionShields** [tradingview/lightweight-charts#1763]
1. In Regular Hours Mode 
2. Place line and control, one point into the future, line will reference control point in the future. 
3. Switch to Extended hour – BUG – future point of the control is not saved but incorrectly adjusted! 

Any control - triangle, pitchfork incorrectly adjusted future time point! FIX!  
This messes up forecast projections! 
![image](https://github.com/user-attachments/assets/6cb7af00-8ec1-492d-81c1-b112ccb8da23)

**Comment by SlicedSilver** [comment]
This repo is for the Lightweight Charts open source project and is unrelated to Chart provided on TradingView.com.

Please use the support system on the TradingvView.com site
