### ISSUE TITLE
Hide T7 trademark

### ISSUE THREAD

**Issue by traidzord** [tradingview/lightweight-charts#1765]
Is it possible to hide the T7 logo from the chart when i use lightweight charting library?

**Comment by SlicedSilver** [comment]
This is explained within our release notes: https://tradingview.github.io/lightweight-charts/docs/release-notes#420
and documentation: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LayoutOptions#attributionlogo

Essentially, you need to set the following chart option:
```js
{ layout: { attributionLogo: false } }
```
