### ISSUE TITLE
How to use timeFormatter?

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#180]
Is there any way to display utc timestamp as is without formatting? For example, I just want to display time like `1529884800`

**Comment by timocov** [comment]
I just fixed example in our docs https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#time-format.

Also you can see related test case https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/initial-options/time-formatter.js.
