### ISSUE TITLE
Compilation Error after running initial install

### ISSUE THREAD

**Issue by saurabBajgain** [tradingview/lightweight-charts#181]
**Lightweight Charts Version:** 1.0.2

**Steps/code to reproduce:**  
just did npm install lightweight-charts  and in code:
import { createChart } from 'lightweight-charts'; in intended component.ts
after this just run npm run ng serve.

**Actual behavior:**
thew bunch of compilation errors from library file.

**Expected behavior:**
 ｢wdm｣:  compile successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/14971466/63319946-8eabcd00-c34e-11e9-829e-238ddc8822a7.png)

**CodeSandbox/JSFiddle/etc link:**

typescript version:-3.5.3

**Comment by saurabBajgain** [comment]
export declare type DeepPartial<T> = {
	[P in keyof T]?: T[P] extends Array<infer U> ? Array<DeepPartial<U>> : T[P] extends ReadonlyArray<infer X> ? ReadonlyArray<DeepPartial<X>> : DeepPartial<T[P]>;
};


ERROR in node_modules/lightweight-charts/dist/typings.d.ts(63,24): error TS1005: ';' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,44): error TS1005: ';' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,47): error TS1109: Expression expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,71): error TS1005: '(' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,78): error TS1005: ',' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,106): error TS1005: ',' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,109): error TS1109: Expression expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,141): error TS1005: '(' expected.
node_modules/lightweight-charts/dist/typings.d.ts(63,160): error TS1005: '(' expected.
node_modules/lightweight-charts/dist/typings.d.ts(64,1): error TS1128: Declaration or statement expected.

**Comment by timocov** [comment]
What version of the typescript you use?

**Comment by timocov** [comment]
It looks like `ng serve` uses differ version of the TypeScript. Can you please provide repo/snippet with the minimal repro of the issue?

**Comment by saurabBajgain** [comment]
![image](https://user-images.githubusercontent.com/14971466/63334390-e73e9280-c36d-11e9-8336-72d61bc31a75.png)
 you mean this?

**Comment by timocov** [comment]
Exactly! As you can see it uses 2.4.2 version.

**Comment by saurabBajgain** [comment]
so globally i have typescript version:-3.5.3 installed and ng serve using 2.4.2 then what would be the possible suggestion for me to handle this situation?

**Comment by timocov** [comment]
Update `ng`? I believe `ng` is able to use the latest version of the TypeScript.

I'm going to close this issue because it's not related to the lightweight charts itself (it's about TypeScript and Angular actually).
