### ISSUE TITLE
only full datapoints are visible, if we move, we have a padding till the next datapoint is there

### ISSUE THREAD

**Issue by krtschmr** [tradingview/lightweight-charts#182]
if we scroll, there are paddings left and right which will be there untill a new datapoint is visible.

what is causing this behavior?

![ezgif-2-b408a549e3c0](https://user-images.githubusercontent.com/13366714/63341790-3687c180-c374-11e9-9df3-bb0c9c193e9a.gif)

**Comment by timocov** [comment]
Can you please check that it works on the master branch? I believe we've fixed it in #116.

**Comment by timocov** [comment]
I hope it's fixed in #116. If it don't - please re-open that issue.
