### ISSUE TITLE
Manipulate time in UNIX timestamp format

### ISSUE THREAD

**Issue by dekaj96** [tradingview/lightweight-charts#184]
My timeFormatter function is giving me time in client's timezone format due to casting timestamp using `moment.unix(crosshairTimestamp)`

Is there any posibility to cast time displayed in timeline to client's timezone?

![time](https://user-images.githubusercontent.com/18724243/63499904-1c132c80-c4c9-11e9-8a72-28520d73029e.png)

**Comment by timocov** [comment]
> Is there any posibility to cast time displayed in timeline to client's timezone?

You can try to manipulate with times you provide and add the TZ offset to them. So, instead of `timestamp` you need to provide `timestamp + tzOffset` as time for the item. In this case you don't need to provide `timeFormatter` to format in client's timezone because we'll do it.

**Comment by timocov** [comment]
But please make sure that you've added a correct offset for every time value (it might be changed along the time goes in case of DST for instance).

**Comment by deantheiceman** [comment]
@dekaj96 @timocov what do you use to provide the offset? 1569752847+10H ?

**Comment by deantheiceman** [comment]
when I try the timestamp +10H it throws an error asking for the normal date format. Is it possible to still pass the unix timestamp?

**Comment by timocov** [comment]
@deantheiceman you need to convert 10H to seconds first (`1569752847 + 10 * 60 * 60`), did you do it?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
