### ISSUE TITLE
Display price scale both on left and right side

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#186]
**Describe the solution you'd like**

```
chart.applyOptions({
    priceScale: {
        position: 'both'
    }
});
```

**Additional context**
Might be nice to have option for price scale on both left and right position for a big/wide chart.

**Comment by timocov** [comment]
Hey @SuperPenguin, sorry for long delay.

The case you described is very interesting, and we even had something like like that some time ago in our `charting_library` library and on the main site www.tradingview.com (currently we have ability to use up to 8 scales at the same time).

But this is not case of the `lightweight-charts`, unfortunately - we want to leave the library simple as much as possible and cover the main cases at the same time. In this case, if we add mirroring to the library, I believe that the next request will be "add ability to use 2 scales separately" - and there are edge cases, and the hardest part here is clear and easy understandable API.

**Comment by compunect** [comment]
Given that 3.0 now has two scales this should be a tiny addition.
Right now you can only specify left or right, why not allow it on both ?

**Comment by SuperPenguin** [comment]
> Given that 3.0 now has two scales this should be a tiny addition.
> Right now you can only specify left or right, why not allow it on both ?

At the moment you can use 2 series with identic properties and data, but one of them is transparent color to achieve this.
Here is the example

```ts
import {
  BusinessDay,
  createChart,
  isBusinessDay,
  LineData,
  LineStyle,
  PriceLineSource,
  TickMarkType,
  UTCTimestamp
} from "lightweight-charts";

function formatTime(utcTimestamp: UTCTimestamp): string {
  const dt = new Date(utcTimestamp * 1000);
  const hour = dt.getUTCHours() < 10 ? `0${dt.getUTCHours()}` : dt.getUTCHours().toString();
  const minute = dt.getUTCMinutes() < 10 ? `0${dt.getUTCMinutes()}` : dt.getUTCMinutes().toString();

  return `${hour}:${minute}`;
}

const chartRoot = document.getElementById("main-chart") as HTMLDivElement;
const chart = createChart(chartRoot, {
  width: 400,
  height: 300,
  timeScale: {
    tickMarkFormatter: (time: UTCTimestamp | BusinessDay, tickMarkType: TickMarkType, locale: string) => {
      if (isBusinessDay(time)) {
        return "";
      } else {
        return formatTime(time);
      }
    }
  },
  localization: {
    timeFormatter: (time: BusinessDay | UTCTimestamp) => {
      if (isBusinessDay(time)) {
        return "";
      } else {
        return formatTime(time);
      }
    }
  },
  leftPriceScale: {
    visible: true
  }
});

const lineLeft = chart.addLineSeries({
  priceScaleId: "left",
  color: "#FF000000", // Red Transparent
  lineStyle: LineStyle.Solid,
  lineWidth: 1,
  priceLineSource: PriceLineSource.LastVisible
});

const lineRight = chart.addLineSeries({
  color: "#FF0000", // Red
  lineStyle: LineStyle.Solid,
  lineWidth: 1,
  priceLineSource: PriceLineSource.LastVisible
});

const data: LineData[] = [];
const now = Math.round(Date.now() / 60000) * 60000;

for (let i = 1; i < 1000; i++) {
  const value = Math.sin((i * 10 * Math.PI) / 180);

  data.push({
    time: (now + i * 60) as UTCTimestamp,
    value: value
  });
}

lineLeft.setData(data);
lineRight.setData(data);
```
![image](https://user-images.githubusercontent.com/1574722/111402128-350fae00-86fd-11eb-945f-167e6370ca38.png)

**Comment by timocov** [comment]
> Right now you can only specify left or right, why not allow it on both ?

@compunect am I right that you want to get something like "mirroring" for price scales? I meant, attach a series to both price scale at the time so change on one price scale will update other scale as well?

**Comment by compunect** [comment]
First thanks for the solution with the invisible series, but it’s also a performance hit to draw two.

@timocov I wanted to display the percentage left and the absolute price right

**Comment by timocov** [comment]
Ah, I see, we didn't plan to add this feature though.
