### ISSUE TITLE
Get candle data (OHLC) with subscribeCrossHairMove ?

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#189]
Hi!

How to get candle data (OHLC) with **subscribeCrossHairMove** ? I can only get the current price.

```javascript
chart.subscribeCrossHairMove(param => {
	if (param.time) {
		const price = param.seriesPrices.get(this.series)
		row.innerText = 'String' + '  ' + price.toFixed(2)
	} else {
		row.innerText = 'String'
	}
})
```

**Comment by pinal-knoxpo** [comment]
@nikitamarcius If you have set data like below object 
candlestickSeries.setData([
    { time: "2018-12-19", open: 141.77, high: 170.39, low: 120.25, close: 145.72 },
    { time: "2018-12-20", open: 145.72, high: 147.99, low: 100.11, close: 108.19 }
]);
You will get active data i.e. object using 
**const ohlc =  param.seriesPrices.get(this.candlestickSeries)**. i.e -> 
 { open: 141.77, high: 170.39, low: 120.25, close: 145.72 }

**Comment by nikitamarcius** [comment]
@pinal-knoxpo thnx, it`s works
