### ISSUE TITLE
hoveredSeries in mouse events params is always undefined

### ISSUE THREAD

**Issue by DanTup** [tradingview/lightweight-charts#190]
Using the v1.1.0 at https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js and the code from the [markers example](https://github.com/tradingview/lightweight-charts/blob/dd7fb362a646bc8021b050b32f2dca233baf5e12/docs/series-basics.md#setmarkers), the `hoveredObject` is always undefined.

```ts
chart.subscribeCrosshairMove(function(param) {
	console.log(param.hoveredSeries);
    console.log(param.hoveredObject);
});

chart.subscribeClick(function(param) {
    console.log(param.hoveredSeries);
    console.log(param.hoveredObject);
});
```

Example: https://jsfiddle.net/nu7qp2yo/

If you open the console and hover over the line/arrow you just see a lot of `undefined` printed. I believe from the docs and #154 that it should allow me to check the marker being hovered over?

**Comment by timocov** [comment]
> param.hoveredObject

Hm, looks like typo in the docs. There is `hoveredMarkerId`, not `hoveredObject`.

> param.hoveredSeries

Currently this param is always `undefined`. I believe it's bug.

/cc @kirchet
