### ISSUE TITLE
Full screen?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [tradingview/lightweight-charts#192]
How can I set the chart as fullscreen for a browser? I would like to it cover all document body and auto resize with browser sizes?  example: https://tr.tradingview.com/lightweight-charts/

**Comment by timocov** [comment]
Did you want to set it something like as "wallpaper" of the page or enable full screen mode for the chart?

**Comment by ErcinDedeoglu** [comment]
@timocov yes like a wallpaper. It should cover whole browser window. Is there a best practice for doing this?

**Comment by timocov** [comment]
I believe that question should be like "how to do any DOM element as wallpaper/fullscreen on the page?" (because it doesn't related to lightweight-charts itself). I would say that you need to make a container absolute positioning and left=right=top=bottom=0px (or something like that).

**Comment by ErcinDedeoglu** [comment]
But contructor needs to implement parameter as
LightweightCharts.createChart(document.body, {
**width: 600,
height: 300,**

and it doesn't accept percentage.

**Comment by timocov** [comment]
Ah, in this case you need to handle resize event of the window and resize the chart by applying options with new width/height. See also #71

**Comment by ErcinDedeoglu** [comment]
Dear @timocov,
I really thankful to you for your quick answers.
Is there an api method that I can change chart's size?
Like:
var chart = LightweightCharts.createChart *
chart.setSize(1400, 500); etc.

**Comment by ErcinDedeoglu** [comment]
Ahh! Ok i found it.
chart.resize(500,600)
Closing. Thanks a lot.

**Comment by timocov** [comment]
> Ahh! Ok i found it.

I strongly recommend you think twice before use this method 🙂  We've made fatal failure with that method - see #157. You can just use `chart.applyOptions({ width: 500, height: 600 });` instead.

**Comment by neobie** [comment]
no solution for responsive full screen ?

**Comment by timocov** [comment]
@neobie you can put a library to fullscreen container and resize it accordingly to the window size. Probably after #71 it will work automatically but in the modern browsers only.

**Comment by rajilesh** [comment]
just try a timeout
 setTimeout(() => {
  chart.resize(tv.width,tv.height)
              }, 10);
