### ISSUE TITLE
Missing docs for generating screenshots

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#193]
_Originally posted by @hazhir1811 in https://github.com/tradingview/lightweight-charts/pull/48#issuecomment-528198514_

**Comment by hazhir1811** [comment]
looks like when taking screenshots the legends are not part of screen shot. also if we take the screenshot immediately after the page has loaded the markers above or below the candles would be a little bit above the candles that normally would be you can see this part when you refresh a series of candles that has some markers above the candles with a very short delay the markers get adjusted to the candles.

**Comment by timocov** [comment]
> looks like when taking screenshots the legends are not part of screen shot

@hazhir1811 The lightweight-charts doesn't have legend out of the box. What legend are you talking about?

> also if we take the screenshot immediately after the page has loaded the markers above or below the candles would be a little bit above the candles that normally would be you can see this part when you refresh a series of candles that has some markers above the candles with a very short delay the markers get adjusted to the candles.

I hope that this issue is #212 or has really similar reason.
