### ISSUE TITLE
Custom horizontal line for: order, alerts etc.

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#194]
Hi!

I did not find functionality in the docs, as in the picture. How can I do that?

![1](https://user-images.githubusercontent.com/10992863/64323388-150e1300-cfcd-11e9-9b90-d9ffc9b6a952.PNG)

**Comment by timocov** [comment]
Related issue #183

**Comment by timocov** [comment]
We have issue to add ability to add custom price levels (see #183), but not as on your screenshot (with buttons for instance). I'm not sure that it's what we need to have in lightweight-charts, though.

**Comment by nikitamarcius** [comment]
@timocov buttons are not needed, line itself and the price are important.
Will try

**Comment by timocov** [comment]
In this case I'd say that #183 is what you need.

**Comment by nikitamarcius** [comment]
@timocov not what i need https://jsfiddle.net/1qjwe4oh/ 
even if I draw a direct custom, I can’t create them more. To do this, you need to recreate the component a few times, because one component = 1 line

```javascript
var chart = LightweightCharts.createChart(document.body, { width: 400, height: 300 });
var lineSeries = chart.addLineSeries({
lineWidth: 1,
lineStyle: 2,
lineType: 1,
});
lineSeries.setData([
    { time: '2019-04-11', value: 80 },
    { time: '2019-04-12', value: 80},
    { time: '2019-04-20', value: 80 },
]);
```

**Comment by timocov** [comment]
> even if I draw a direct custom, I can’t create them more. 

I'm not sure that understand you correctly. Can you please describe a little bit more what you mean here?

**Comment by nikitamarcius** [comment]
@timocov ok, let's start from the beginning. In my app, in addition to the chart, there is a block of alerts and orders from the exchange. Orders and alerts i need visualize in chart. Solution - dashed line with custom color price highlight as in the screenshot above (without buttons).

You suggested using ``'addLineSeries'`` this series draws one graph that is tied to coordinates. This solution does not fit, because it is tied to time coordinates ``{ time: 'THIS TIME', value: 80 }``, on the chart need to place a lot of orders and alerts 1 ``'addLineSeries'`` = 1 line on the chart.

This function is already implemented in the library, it shows the current price and draws a dashed, horizontal line. I need to create the exact same custom (one or many). Line that will be tied to price, not for technical analysis.

```javascript
const options_example = {
value: '111,26',
color: 'yellow',
lineStyle: 0,
}
```

![1](https://user-images.githubusercontent.com/10992863/64408383-4d762580-d08f-11e9-855e-16760435acb9.png)

RU:
Нужна горизонтальная линия, не для тех. анализа, которая будет принимать значение цены, без привязки к координатам (добавить по типу ``setMarkers`` ). Визуально она выглядит как текущее отображение цены (подсветка цены и пунктирная линия).

**Comment by timocov** [comment]
> You suggested using 'addLineSeries' this series draws one graph that is tied to coordinates

I suggested it as workaround - you can add line series with 2 points. It's just suggestion for workaround, nothing more.

But for complex solution you need to wait #183.
