### ISSUE TITLE
Custom color for items of candlestick and line series

### ISSUE THREAD

**Issue by AhmadzadehHazhir** [tradingview/lightweight-charts#195]
Hello, a feature to be able change the color of candlesticks and lineSeries based on a condition think of it like the VolumeSeries that are already implemented that accepts a color as a variable but this time for lines and candlesticks. the image below can be a good example of this , the line is the same but in some times the color is red or green based on the condition.
![Screenshot_2019-09-06 BTCUSD 10716 0 ▲ +1 26% SEP](https://user-images.githubusercontent.com/17275314/64414888-70adce80-d0a9-11e9-8f9c-c6d1c5e8fee2.png)

**Comment by ColCh** [comment]
@timocov Hi! Any workaround for this? 

I wonder why TradingView itself has this feature. It uses Lightweight Charts too?

**Comment by timocov** [comment]
> Any workaround for this?

I don't think there is a workaround for that.

> It uses Lightweight Charts too?

TradingView's chart is different product, but they all are have the same roots and moving together.

> I wonder why TradingView itself has this feature.

We have this feature in Charting Library and Trading Terminal though (they are based on TradingView's code).

> for example, like plotting 2 line series (with different colors), as demo with plot.ly here community.plotly.com/t/color-change-by-range-in-line-chart/17829/2

Sure, we understand where it might be helpful (we have this feature in the main product for long time I guess) and that's why this issue doesn't have a "need more feedback" label. We just didn't think that this feature is important to have in the first releases of lightweight-charts. One thing is important for you, another one for others and we can't implement everything at the same time.

Meantime, I think that this feature should be easy to implement (at least for candlesticks and bars it should be pretty easy, for line it could be a bit tricky though) and if someone who wants to have this feature in lightweight-charts and who doesn't want to wait until we implement it - it can provide a proposal here (with some high-level changes, especially on the API level) and after a proposal will be approved - implements the feature.

Someday we implement everything we think should be in lightweight-charts and fix all bugs, but we don't have infinite resources to make it instantly, unfortunately.

**Comment by ColCh** [comment]
> TradingView's chart is different product, but they all are have the same roots and moving together.

ahh it says about everything. Thank you for your answer!

> Someday we implement everything we think should be in lightweight-charts and fix all bugs, but we don't have infinite resources to make it instantly, unfortunately.

Sure guys, have your time.

**Comment by allartdo** [comment]
@ColCh There is a workaround possible. But it is not best for performance if you want to make years of data in your chart. 
![image](https://user-images.githubusercontent.com/32697889/91303653-9c3d3380-e7a8-11ea-84e9-9974bd8d91dd.png)

What I did is each time you want to change your line color you need to create a new line series that starts with the old data (to make it at the right x/y as) and then also the new data spot. If you dont take the last data with the new line series you will see a gap when changing color. I guess you understand the performance issue here :) Still, this works for me.

Here is some example code:
```
/**
 * Creates a red or green line.
 * 
 * @param {String} color Color code
 * @param {String} date Timestamp or yyyy-mm-dd format
 * @param {Number} lastMovingAverage  
 */
function createLine(color, date, lastMovingAverage) {
    // Create line
    buySellLine = chart.addLineSeries();

    // Make sure there is no gap when changing to new line color. (keep in mind that date is the last date and for value aswell)
    // The new data is added later for me.
    buySellLine.setData([{time: date, value: lastMovingAverage}]);

    // Settings
    buySellLine.applyOptions({
        color: color,
        priceLineVisible: false,
        lastValueVisible: false
    });
}
```

**Comment by ColCh** [comment]
Wow such an elegant solution! Thank you! 👍

**Comment by allartdo** [comment]
Ty! Good luck coding :) Btw keep in mind that your markers will be set diffrently aswell. Since your setting markers on a serie. Collect them in an array and set them each time again and you should be done :D

**Comment by hp8wvvvgnj6asjm7** [comment]
is this still planned to be added? would be a great feature.

**Comment by gajus** [comment]
Would you accept a PR if I work on this?

**Comment by timocov** [comment]
@gajus sorry for late reply.

> if someone who wants to have this feature in lightweight-charts and who doesn't want to wait until we implement it - it can provide a proposal here (with some high-level changes, especially on the API level) and after a proposal will be approved - implements the feature.

**Comment by thanhlmm** [comment]
For the proposal I would suggest that we update the option that
```js
// Line color
color: String | (LineData) => String
```

By doing so, we can guarantee backward compatibility and accept new custom

**Comment by timocov** [comment]
@thanhlmm not sure about providing a function as a color though, because we would offer this, how the library should know that it needs to refresh all colors? Also, as soon as you provide a data for the series you can calculate the color based on series' values. I think that providing just `color` for line series is good enough, what's about candlesticks? What's about border color, body color, etc?

**Comment by thanhlmm** [comment]
If so we could do something like the histogram is doing. It has a default color, and in each data point, the developer can provide a custom color for it.
For the line series context, custom color gonna have this problem:
Eg: We have 3 points: A -- B -- C
If A and C are red, and B is green. What is the color for the line should be? A-red-B-red-C or A-green-B-green-C or A-red-B-green-C
I'm not sure

**Comment by thanhlmm** [comment]
![download (24)](https://user-images.githubusercontent.com/9281080/127478433-5c06eac8-3ab6-41ae-a4a1-2e930e731cb4.png)
I'm also working on a case that I'd like to change color for the series if it is below a price. If set color based on data point, it will look broken
![download (25)](https://user-images.githubusercontent.com/9281080/127478645-b31c3d66-a3d7-400d-b147-f05875c47280.png)

**Comment by allartdo** [comment]
@thanhlmm I see what you want, would be really cool if that would be possible. I think it's like putting some sort of a filter over your screen. Everything below 2158.36 is red and above is green. Something like this: https://www2.lunapic.com/editor/?action=tint

**Comment by thanhlmm** [comment]
I have thought about that but it will affect others panel (Axis, histogram,...etc) so this is not the way I can work around.

**Comment by timocov** [comment]
> I'm also working on a case that I'd like to change color for the series if it is below a price. If set color based on data point, it will look broken

@thanhlmm @allartdo see #151

**Comment by bitrozex** [comment]
Hi Team, is there any one can guide me How to get customized color background of chart? I mean the whole screen  of chart section. 😊

**Comment by thanhlmm** [comment]
@bitrozex I believe that you can change the background of chart in v3.6.0 https://github.com/tradingview/lightweight-charts/releases/tag/v3.6.0

**Comment by timocov** [comment]
It seems that it is quite easy to implement the feature for candlestick and bar series, but I have a question regarding a line series.

Let's say you have 3 points `[{ time: 1, value: 1, color: 'red' }, { time: 2, value: 2, color: 'green' }, { time: 3, value: 1, color: 'blue' }]`, and each point has its own color. How it should be displayed in your opinion? The possible options are:

- a new color is started from the previous point, i.e. it "highlights" previous period of time
  ![image](https://user-images.githubusercontent.com/3112183/140502148-204de28b-6dcc-464c-9e58-ee031ec1c487.png)

- a new color is started from the middle between current and previous points
  ![image](https://user-images.githubusercontent.com/3112183/140508912-5e53925d-40b3-49e6-8b90-80862bb69e89.png)

- a new color is started from the current point, i.e. it "highlights" the next period of time
  ![image](https://user-images.githubusercontent.com/3112183/140503003-b9e83f80-fa99-4865-87da-2d3fe67a9dea.png)

But please keep in mind that there is a line type `WithSteps`, which displays a steps _on the current point_, i.e. a step is started from the current point to the right (to "highlight" the next period of time):

![image](https://user-images.githubusercontent.com/3112183/140509247-99492c5b-ea62-4374-b8a3-7cf5d7698ffd.png)

**Comment by allartdo** [comment]
I think image 3 makes the most sense. Since image 1 seems to make point 1 useless. Like sure if you hover over it, it turns red, but I dont see how this helps anyone.

Image 2 seems interresting but I belive things would go weird if you have a chart where the value in point 1 is 1 and in point 2 in 100. It would mean that from a value of 50, the color would change.

I personally use mutliple colors in a single line to determine if the line goes up or down. Splitting the line color in half like in image 2 would give incorrect results for me. At least as long as I understand why you have the colors like that.

Dont know anything about the WithSteps part, so can't help you with that :(.

PS: If this is also supposed to help @thanhlmm I think neither of these options will work. I belive for that you need to be able to set a specific value. And say everything above it should be X color, and everything below should be Y color.

**Comment by thanhlmm** [comment]
Yeah, I have raised the same case before. To be honest, IDK, but I think we can follow the behavior of TradingView full chart

**Comment by timocov** [comment]
Re https://github.com/tradingview/lightweight-charts/issues/195#issuecomment-961850692 - after internal discussion we decided to do the following:

- it seems that the first example makes almost no sense so we aren't going to implement it
- as for 2 and 3 - we will implement them both and you will be able to control the way it is displaying via an option. But probably for now we'll leave the solution as-is (3rd one) and then will create another issue to implement other option (if anybody will need this)
- as for step line - the same as above

**Comment by caiusCitiriga** [comment]
I've managed to implement a line series with the line of multiple colors (for this case 'red', 'green', or 'gray') with a `CustomSeries` implementation.


Here's the Renderer class of the series, the rest of the custom series is pretty much straight forward as the example generated by the `create-lwc-plugin`:

```ts
import {
  CanvasRenderingTarget2D,
  MediaCoordinatesRenderingScope,
} from 'fancy-canvas';
import {
  PaneRendererCustomData,
  ICustomSeriesPaneRenderer,
  PriceToCoordinateConverter,
  Time,
} from 'lightweight-charts';
import { MyTestSeriesData } from './data';
import { MyTestSeriesOptions } from './options';

export class MyTestSeriesRenderer<TData extends MyTestSeriesData>
  implements ICustomSeriesPaneRenderer
{
  _data: PaneRendererCustomData<Time, TData> | null = null;
  _options: MyTestSeriesOptions | null = null;

  draw(
    target: CanvasRenderingTarget2D,
    priceConverter: PriceToCoordinateConverter
  ): void {
    target.useMediaCoordinateSpace((scope) =>
      this._drawImpl(scope, priceConverter)
    );
  }

  update(
    data: PaneRendererCustomData<Time, TData>,
    options: MyTestSeriesOptions
  ): void {
    this._data = data;
    this._options = options;
  }

  _drawImpl(
    renderingScope: MediaCoordinatesRenderingScope,
    priceToCoordinate: PriceToCoordinateConverter
  ): void {
    if (
      this._data === null ||
      this._data.bars.length === 0 ||
      this._data.visibleRange === null ||
      this._options === null
    ) {
      return;
    }

    const bars = this._data.bars.map((bar) => ({
      x: bar.x,
      close: priceToCoordinate(bar.originalData.close)!,
      segment: bar.originalData.segment, // <-- custom field holding color of the line segment
    }));

    const ctx = renderingScope.context;
    ctx.lineJoin = 'round';
    ctx.lineWidth = this._options.baseLineWidth;

    let currentPath = new Path2D();
    let currentSegment = bars[this._data.visibleRange.from].segment;
    currentPath.moveTo(
      bars[this._data.visibleRange.from].x,
      bars[this._data.visibleRange.from].close
    );

    let prevBar = bars[this._data.visibleRange.from];

    for (
      let i = this._data.visibleRange.from + 1;
      i < this._data.visibleRange.to;
      i++
    ) {
      const bar = bars[i];

      if (bar.segment !== currentSegment) {
        // Draw the current segment with correct color
        ctx.strokeStyle = this.getColorForSegment(currentSegment);
        ctx.stroke(currentPath);

        // Begin a new path connecting it to the end of the previous one
        // so we don't render gaps between lines
        currentPath = new Path2D();
        currentPath.moveTo(prevBar.x, prevBar.close); // <--- previous point
        currentPath.lineTo(bar.x, bar.close); // <--- current point

        currentSegment = bar.segment;
      } else {
        currentPath.lineTo(bar.x, bar.close);
      }

      prevBar = bar; // update the last segment for next iteration
    }

    // Draw the last segment
    ctx.strokeStyle = this.getColorForSegment(currentSegment);
    ctx.stroke(currentPath);
  }

  getColorForSegment(segment: string): string {
    switch (segment) {
      case 'green':
        return 'green';
      case 'red':
        return 'red';
      default:
        return 'gray';
    }
  }
}
```

Creating a custom series is not an easy task if you want complex renderings and you are not familiar with the canvas system (like me 😆) but once you created one you can easily use it as chart plugin like this:

```ts
const series = chart.addCustomSeries(new MyTestSeries(), {
  baseLineWidth: 2,
});

const data: MyTestSeriesData[] = sampleData.map((row) => ({
  close: row[4],
  high: row[2],
  low: row[3],
  open: row[1],
  time: (row[0] / 1000) as Time,
  segment: getSegmentType(row),
}));

series.setData(data);
```

Here's the outcome:

![Image](https://github.com/user-attachments/assets/c954c20e-c70c-437f-9177-06471d855cd5)

Hope it helps someone ❤
