### ISSUE TITLE
crossHairMarkerVisible not working

### ISSUE THREAD

**Issue by hazhir1811** [tradingview/lightweight-charts#196]
check this example i assume after setting crossHairMarkerVisible to false the little dot on lineSeries should not be visible.

here is the default example from tradingview page which the demo on tradingview and the jsfiddle one are different
https://jsfiddle.net/TradingView/dtehqksw/

**Comment by kirchet** [comment]
https://github.com/tradingview/lightweight-charts/blob/master/docs/area-series.md#customization

`crossHairMarkerVisible` was renamed to `crosshairMarkerVisible `
