### ISSUE TITLE
put zero value in the middle of the visible area

### ISSUE THREAD

**Issue by primozv** [tradingview/lightweight-charts#198]
I have an overlay histogram that has values from +100 to -70 (example, they can be from -90 to +20). Is there a way to put histogram value 0 in the middle of the visible area?

Thanks in advance

**Comment by kirchet** [comment]
Currently there is no way to do it, but you can change `base` value

https://github.com/tradingview/lightweight-charts/blob/master/docs/histogram-series.md#examples

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
