### ISSUE TITLE
Need more numbers after coma

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#199]
Hi!

Price rounds to 2 decimal places after comma, how to fix it? need 6
``0.016257`` => ``0.02`` need => ``0.016257`` 

![333](https://user-images.githubusercontent.com/10992863/64440175-34439800-d0d4-11e9-95e1-12d5a2352ab4.PNG)

**Comment by kirchet** [comment]
Just change `precision`
https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format

**Comment by nikitamarcius** [comment]
@kirchet tnx a lot!

Or like this:
```javascript
const seriesOptions = {
		priceFormat: {
			type: 'custom',
			formatter: (price) => parseFloat(price).toFixed(4)
		}
}
```

**Comment by timocov** [comment]
@tghilardi can you please create jsfiddle example with your problem?

**Comment by nikitamarcius** [comment]
@kirchet ``return '$' + price.toFixed(5);`` => ``return '$' + parseFloat(price).toFixed(5);``
Need conver ``String`` to ``Number``

**Comment by tghilardi** [comment]
> @tghilardi can you please create jsfiddle example with your problem?

Hi @timocov,

Here is the fiddle to look at:

https://jsfiddle.net/tghilardi/ecuw7sv0/1/

Price is 4 decimals, but I can only see two.

Thank you.

**Comment by timocov** [comment]
@tghilardi to change format on the whole price scale you need to pass `localization.priceFormatter` function - see https://github.com/tradingview/lightweight-charts/blob/93a4953e0b9cf3e61cc0dbbeb6b52533d215552e/src/model/localization-options.ts#L15-L18. We need to add it to docs...

**Comment by tghilardi** [comment]
Hi @timocov ,

Could you update the fiddle or send me the code? I was not able to get it to work.

**Comment by timocov** [comment]
Sure https://jsfiddle.net/txyLgwuv/

**Comment by tghilardi** [comment]
> Sure https://jsfiddle.net/txyLgwuv/

Thank you. Works great.

**Comment by rgitarov** [comment]
If we move the scale in a wider range there are some values appear with huge precision like 1.4000000000000001 or even 1.450000000000000002
How to avoid this precision?
![image](https://user-images.githubusercontent.com/26439528/114264730-7189ad80-9a0e-11eb-9b33-a962b042759e.png)

**Comment by rgitarov** [comment]
just made it work as follow:
`priceFormat: {
type: 'custom',
minMove: '0.000001',
formatter: (price) => {
if (price < 0.000001) return parseFloat(price).toPrecision(8)
else if (price >= 0.000001 && price < 1) return parseFloat(price).toPrecision(6)
else return parseFloat(price).toPrecision(6)
}
}, priceScale: {
autoScale: true
},
localization: {
locale: 'en-US',
priceFormatter: (price) => {
if (price < 0.000001) return parseFloat(price).toPrecision(8)
else if (price >= 0.000001 && price < 1) return parseFloat(price).toPrecision(6)
else return parseFloat(price).toPrecision(6)
}
},`
![image](https://user-images.githubusercontent.com/26439528/114264777-aeee3b00-9a0e-11eb-9d19-d8c91b6bee79.png)

**Comment by Baracoj** [comment]
Hello everybody. I nee a little help.
I need change thousands to letter k, somebody can help me?

**Comment by romfrancois** [comment]
@Baracoj take example of this [example](https://github.com/tradingview/lightweight-charts/issues/199#issuecomment-817105159). You'll have to change what's returned by `priceFormatter`.
