### ISSUE TITLE
Intraday charts, show data passed in seconds in one minute candle

### ISSUE THREAD

**Issue by pushand** [tradingview/lightweight-charts#201]
I have data in seconds. so for one minute candle I have 60 data.

I want to show minute candle such that if I pass data in seconds, chart should auto merge the data for that minute and show only one candle.

Attached is the output I get but but I want to show it as single minute instead. how should I do that?

I know I can do by passing minute hata which I don't want because I want to calculate SMA and other indicators based on seconds data

<img width="798" alt="Screenshot 2019-09-08 at 2 39 46 PM" src="https://user-images.githubusercontent.com/12893140/64486137-e13e2200-d246-11e9-9dd6-5604b084a835.png">

**Comment by kirchet** [comment]
> chart should auto merge the data for that minute and show only one candle

The library cannot merge bars to other resolutions, so you're need to do it yourself before passing the data to the library

**Comment by pushand** [comment]
Does full trading view library have this ability., Like to view data in 1min, 5min, 10min so on.. by supplying single data source in seconds?

**Comment by kirchet** [comment]
As I know, the full library can do this
