### ISSUE TITLE
Disabling scrolling does not work on a mobile device

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#202]
**Lightweight Charts Version:** 1.1.0

Disabled scrolling for the chart. When reopen a mobile window in the browser, starts scrolling  again.

https://jsfiddle.net/6kwcx23a/

**Comment by kirchet** [comment]
See `horzTouchDrag` and `vertTouchDrag` [here](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#scrolling-and-scaling-options)
