### ISSUE TITLE
Add option to show the "global" last value of the series instead of the last visible

### ISSUE THREAD

**Issue by AoDev** [tradingview/lightweight-charts#203]
**Is your feature request related to a problem? Please describe.**

When a user scrolls the chart, the price tag on the price axis, is updated with the last visible candle price.  We would like the price tag to be always of the last candle and not the last "visible" candle, regardless of the visible range.

We want the user to be able to know the current price, that is being updated in real time.
There is already an "horizontal line" that marks de current price and updates correctly when new ohlc data comes in, we just want the label to keep in sync with it. 

**Describe the solution you'd like**

I'd like an option to be able to force the price label to always show the last candle price instead of the last "visible" candle price.

**Additional context**

![Screen-Shot-2019-09-08-at-22 03 07](https://user-images.githubusercontent.com/1526150/64494007-b1fbd500-d287-11e9-9a05-6521023d7984.png)

In the screenshot: the horizontal line marks the last candle price, but the price tag on the vertical axis is showing the last visible candle price.

**Comment by timocov** [comment]
I hope we need to have option for that, which should be passed [here](https://github.com/tradingview/lightweight-charts/blob/4c6ae356f203a88ce2a352c439bbe418efed9255/src/views/price-axis/series-price-axis-view.ts#L47) instead of `false` (`false` there means "global last value").

If someone would like to add this - feel free to make PR with fixes.

**Comment by AoDev** [comment]
@timocov Thanks, right now I can not do it but I'll have a look at it when I have time (and if it was not solved by then)
