### ISSUE TITLE
Display value more densely on price axis

### ISSUE THREAD

**Issue by dekaj96** [tradingview/lightweight-charts#204]
Thanks for your awesome lib. 
I'm using it with such small numbers as eight digits after the comma. Now trying to adjust display of values on price axis in my candle chart. 

`        priceFormat: {
          type: 'price',
          minMove: 0.0000001,
          precision: 8
        }`

![priceaxisresult](https://user-images.githubusercontent.com/18724243/64515894-be1a7d80-d2ed-11e9-9cc2-b8099c3eee59.png)

Is there posibility to display price values more densely on the axis?

**Comment by timocov** [comment]
> Is there posibility to display price values more densely on the axis?

Did you try to set `precision` value more than 8?

**Comment by dekaj96** [comment]
Yeah I did, guess the current situation is the best I could get there.
Although it looks good just wasn't sure if there was not any other options to adjust the price axis :)

**Comment by Kmax4ever** [comment]
> Thanks for your awesome lib.
> I'm using it with such small numbers as eight digits after the comma. Now trying to adjust display of values on price axis in my candle chart.
> 
> ` priceFormat: { type: 'price', minMove: 0.0000001, precision: 8 }`
> 
> ![priceaxisresult](https://user-images.githubusercontent.com/18724243/64515894-be1a7d80-d2ed-11e9-9cc2-b8099c3eee59.png)
> 
> Is there posibility to display price values more densely on the axis?

Dear @dekaj96 , how can you set the value 
![image](https://user-images.githubusercontent.com/38153452/83322142-74a8fe80-a27f-11ea-8089-9168c704a226.png)

i can't set value for small numer in componentDIdmount reajctjs
![image](https://user-images.githubusercontent.com/38153452/83322158-9609ea80-a27f-11ea-8337-5ee133cc3755.png)

**Comment by Kmax4ever** [comment]
my code 
![image](https://user-images.githubusercontent.com/38153452/83322180-b043c880-a27f-11ea-8ca9-d2d412d306ea.png)
