### ISSUE TITLE
Adding marker to existing chart in time

### ISSUE THREAD

**Issue by ErcinDedeoglu** [tradingview/lightweight-charts#205]
Series-based markers #24

How can I add extra markers to chart? 
candlestickSeries.setMarkers([{ time: data[i].unixTime, position: position, color: color, shape: shape }]);
This method is replacing existing markers with new one. But I want to protect olds and add news.
Thanks

**Comment by kirchet** [comment]
```js
var markers = [];
...
markers.push(newMarker);
candlestickSeries.setMarkers(markers);
...
markers.push(newMarker);
candlestickSeries.setMarkers(markers);
```

**Comment by ErcinDedeoglu** [comment]
@kirchet is it forcing re-render? or only changed data rendering again?
For example how can I change the latest candle stick's values each 500ms? Is it same as your mention? Or is there any best practice?

**Comment by kirchet** [comment]
> is it forcing re-render?

Yes, it does.

Currently we don't have a method like we have for updating series bars. We have `setData` and `update` for series data, but only one method `setMarkers` for series markers.

When you call `setMarkers` it removes all the previous markers and adds the new ones.

> For example how can I change the latest candle stick's values each 500ms?

You need to update the last marker in the array and call `setMarkers`. However if you have a lot of markers and update them too often it can affect the performance. So, maybe it makes sense to implement a method like `updateMarker`

**Comment by ErcinDedeoglu** [comment]
@kirchet thanks for your detailed response. please can you give me an example that how to implement update for series?

**Comment by ErcinDedeoglu** [comment]
ok found it ty.

**Comment by jlzbd** [comment]
> ok found it ty.

Can you share code sample or gist?
