### ISSUE TITLE
Chart loading way outside div area

### ISSUE THREAD

**Issue by tghilardi** [tradingview/lightweight-charts#206]
**Lightweight Charts Version:** 

1.0.0

**Steps/code to reproduce:**

I want to place tv's charts within my div below my headings "daily chart" and "5m chart", but it's loading outside of it. Perhaps tv's css is conflicting with mine and if so, is there anything I can do about it?

I tried to set my main div and all other inner divs to overflow: hidden, but no success. Has anyone had this issue? See below screenshot.

**Screenshots**

![image](https://user-images.githubusercontent.com/2612420/64574932-be476700-d347-11e9-8174-8699329608bc.png)

**Comment by nikitamarcius** [comment]
@tghilardi make wrap chart around ``position: relative`` parent block. Let chart be ``position: absolute`` and setting the width and height through .js  https://github.com/tradingview/lightweight-charts/issues/71#issuecomment-528246568

https://jsfiddle.net/tfjo39y5/

**Comment by tghilardi** [comment]
Works great! Thank you @nikitamarcius
