### ISSUE TITLE
Hard to see markers

### ISSUE THREAD

**Issue by tghilardi** [tradingview/lightweight-charts#207]
The new markers feature is working really nice, however the markers are too small and hard to see. Would be nice if we could add a label on top/bottom of the arrow to make it easier to view. Or perhaps increase the size of the markers.

{ time: ..., label: 'bought 100 shares'...}

![image](https://user-images.githubusercontent.com/2612420/64721206-59545400-d4a2-11e9-8466-57d83558e8e2.png)

**Comment by tghilardi** [comment]
Hi @nikitamarcius , contrasting is one viable option.

@timocov, I don't have the means to create a screenshot, but to take care of these edge cases, label positions could be set as well as stick size where the stick is the length from the label to the marker.

label: position:left,stick size:10
label: position:right,stick size:10
label: position:top...,stick size:10
or even
label:position x,y...stick size:10

![image](https://user-images.githubusercontent.com/2612420/65050064-2ea04a80-d93d-11e9-9ec8-5b6fa76313d4.png)

**Comment by timocov** [comment]
@tghilardi it looks like new type of the markers (callout, balloon, note, or something like that) 🙂

**Comment by tghilardi** [comment]
yes, pretty useful to display what actually happened instead of just a marker.

**Comment by timocov** [comment]
If someone would like to suggest any kind of additional improvements except what @scrwdrv did in #349 - feel free to create the issue with the suggestions.

**Comment by Tereus-77** [comment]
> Hi @nikitamarcius , contrasting is one viable option.
> 
> @timocov, I don't have the means to create a screenshot, but to take care of these edge cases, label positions could be set as well as stick size where the stick is the length from the label to the marker.
> 
> label: position:left,stick size:10 label: position:right,stick size:10 label: position:top...,stick size:10 or even label:position x,y...stick size:10
> 
> ![image](https://user-images.githubusercontent.com/2612420/65050064-2ea04a80-d93d-11e9-9ec8-5b6fa76313d4.png)

How did you do that? Can you share example through fiddle link?
