### ISSUE TITLE
Omit value in candlestick chart

### ISSUE THREAD

**Issue by primozv** [tradingview/lightweight-charts#209]
**Lightweight Charts Version:** 
1.2.0 

**Steps/code to reproduce:**

To leave a value empty for a line or a histogram while you set the data with series.setData you can simply omit the value. 
ie. series.setData({ time: '2019-04-11' });

When you set data by omiting the value (high,low,close,open)  for candlestick series it fails due to value being undefined in the following code:
    function ensureDefined(value) {
        if (value === undefined) {
            throw new Error('Value is undefined');
        }
        return value;
    }

Can I do that differently? Is it even possible to omit a value for candlesticks? Is there a workaround?

**Comment by timocov** [comment]
Can you please describe a little why do you need this and what do you want to achieve by doing this?

**Comment by primozv** [comment]
Sometimes data is missing or is not available but we still want to assure that one bar is 1 minute (if one bar represents 1 minute) not 2 miuntes , or 5, or 10. The visualization in case of missing bars is deceiving and doesn't show time, it shows data entries.
It already works correctly for series with simple/single value per bar. Candlesticks on the other hand fail due to value being undefined.
I hope this helps.

**Comment by timocov** [comment]
I got it, sounds reasonable.

**Comment by sysopsnw18** [comment]
I tired sending empty data part for area series and below is the output. Is this empty data part possible in area series?
![image](https://user-images.githubusercontent.com/61038438/80703425-6345c880-8b00-11ea-99b4-b9da485cec36.png)

**Comment by sysopsnw18** [comment]
> I tired sending empty data part for area series and below is the output. Is this empty data part possible in area series?
> ![image](https://user-images.githubusercontent.com/61038438/80703425-6345c880-8b00-11ea-99b4-b9da485cec36.png)

Hey any update on this? When this feature will be available?

**Comment by timocov** [comment]
> I tired sending empty data part for area series and below is the output. Is this empty data part possible in area series?

@sysopsnw18 Yes, we'll handle it in the fix for this issue. cc @kirchet 

> Hey any update on this? When this feature will be available?

We don't have any ETA, but it'll be fixed in 3.0 (assigned milestone).

**Comment by timocov** [comment]
Needs to be sure that https://github.com/tradingview/lightweight-charts/issues/152#issuecomment-637107459 will be covered.
