### ISSUE TITLE
Can the original circle in the middle of the cross be customized?

### ISSUE THREAD

**Issue by lishuailibertine** [tradingview/lightweight-charts#210]
hello, Can the original circle in the middle of the cross be customized?
For example, the color outside the circle, and the color inside; The outer radius of the circle and the inner radius。

![1568707791717](https://user-images.githubusercontent.com/7145192/65023556-a4201100-d965-11e9-96fc-ac36bac123a7.jpg)

**Comment by timocov** [comment]
Currently the colors of this circle comes from series/chart - color is inside color of the series and outside color is background color of the chart. I believe it was done to improve visibility of that circles.

To customize radius of the circle you can use [`crosshairMarkerRadius`](https://github.com/tradingview/lightweight-charts/blob/v1.1.0/docs/line-series.md#customization) option.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
