### ISSUE TITLE
How to switch the type of chart in the chart

### ISSUE THREAD

**Issue by gebilaofan** [tradingview/lightweight-charts#216]
**Is your feature request related to a problem? Please describe.**

My chart needs to display two types, an `addCandlestickSeries` and an `addAreaSeries`.
![image](https://user-images.githubusercontent.com/46524158/65221509-baf26f00-daef-11e9-90bc-b8bb59ad3e5a.png)
When I click K to switch the `addCandlestickSeries` type chart, click A to switch the `addAreaSeries` chart.Is there such an example?

**Describe the solution you'd like**

**Additional context**

**Comment by timocov** [comment]
You can't easily switch type for one series, because different series' types has different data types (for instance for candlestick it's OHLC, but for like it's just value). So, in this case you need to create another series and set new data to it, and then remove the first series.

**Comment by gebilaofan** [comment]
> You can't easily switch type for one series, because different series' types has different data types (for instance for candlestick it's OHLC, but for like it's just value). So, in this case you need to create another series and set new data to it, and then remove the first series.

Is there a demo?

**Comment by timocov** [comment]
Currently no, but I believe we need to add it.

**Comment by gebilaofan** [comment]
> Currently no, but I believe we need to add it.

I am writing this recently, and it is nearing completion, I am very happy to provide you with a reference.

**Comment by timocov** [comment]
@gebilaofan you can post your example to jsfiddle (or any other similar tool) and post the link here. I believe it might be useful for someone who faced the same problem and find this issue.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
