### ISSUE TITLE
How i can do the `leftOffset`, the same of `rightOffset` for `timescale`?

### ISSUE THREAD

**Issue by Paqura** [tradingview/lightweight-charts#217]
I want to have displacement so that the data isn't blocked by the left bar
![FireShot Capture 008 - Benzinga Pro_ The Best Stock Market News Feed Tool - localhost](https://user-images.githubusercontent.com/22657076/65234406-8da0c380-dae5-11e9-94b4-3b27ef88a27e.png)

**Comment by timocov** [comment]
> the data isn't blocked by the left bar

What do you mean?

**Comment by Paqura** [comment]
the time panel overlaps with a price panel

**Comment by timocov** [comment]
I'm not sure that opposite prop for `rightOffset` helps there. If you want to prevent cutting time scale marks, we can try to fix it, but cannot tell you for sure, because there is edge cases when marks might overlap each other.

**Comment by timocov** [comment]
Hey @Paqura, any updates here?

**Comment by Paqura** [comment]
@timocov, eventually, we thought we could keep it that way.
