### ISSUE TITLE
Add option to fix right edge

### ISSUE THREAD

**Issue by primozv** [tradingview/lightweight-charts#218]
Is there a way to fix the right edge? Similar to what you achieve with fixLeftEdge but on the right side.
Or even better, fix both edges?!?

**Comment by timocov** [comment]
That's a good suggestion, thank you!

**Comment by deantheiceman** [comment]
Is there a way we can do this now? I have a chart with lots of initial data but it just shows a flat line since it's so zoomed out

(I'm using fix left edge)

**Comment by timocov** [comment]
@deantheiceman you can provide proposal of API here, and once it's approved, I hope, you (or anyone else) could make a PR for that, if you wish.

**Comment by ws420** [comment]
is there still no solution for this?

we need a fixRightEdge parameter!

**Comment by timocov** [comment]
@ws420 see https://github.com/tradingview/lightweight-charts/issues/218#issuecomment-542574810. It's applicable for everyone needs this feature actually 🙂.
