### ISSUE TITLE
not all prices visible in chart area

### ISSUE THREAD

**Issue by tghilardi** [tradingview/lightweight-charts#219]
Here is an issue I've been dealing with. Tried all options with no success. Price goes all the way to 14, but the chart stops displaying data after price reaches ~11

https://jsfiddle.net/tghilardi/6f5xah3b/1/

![image](https://user-images.githubusercontent.com/2612420/65436320-5a697780-ddf8-11e9-842e-404ba6d635b7.png)

**Comment by timocov** [comment]
Why prices are strings instead of numbers?

**Comment by tghilardi** [comment]
No clue why, but that solved. Thanks @timocov
