### ISSUE TITLE
`lineType` option does not work for area/line series

### ISSUE THREAD

**Issue by atanasbozhkov** [tradingview/lightweight-charts#220]
Does the project currently support step line charts? 
I noticed in the documentation that there is a [LineType ](https://github.com/tradingview/lightweight-charts/blob/master/docs/constants.md#linetype) enum which has an option named `WithSteps` but I cannot seem to use it in an example. Is anyone able to shed some light on this? 

Example of a line chart below.
![image](https://user-images.githubusercontent.com/1144752/65437270-20dd4000-dde9-11e9-8b8f-54c5f0cd9de7.png)

**Comment by timocov** [comment]
Looks like a bug.

We need to pass value from options [here](https://github.com/tradingview/lightweight-charts/blob/d863263cddc611f4de987d5b7c15c2054f1ca9bf/src/views/pane/line-pane-view.ts#L26) and [here](https://github.com/tradingview/lightweight-charts/blob/d863263cddc611f4de987d5b7c15c2054f1ca9bf/src/views/pane/area-pane-view.ts#L30).
