### ISSUE TITLE
Api to add resistance / support lines 

### ISSUE THREAD

**Issue by kimgysen** [tradingview/lightweight-charts#222]
I really dig these charts and would really love to use it to test my bot.  
In order to do so I would need to be able to add custom support / resistance lines to the graph that my bot will calculate and that I want to test visually.  

The feature that I would like to request is the ability to add these custom lines: 

- Connect custom price points 
- Define the length of the line (not from point to point necessarily)

**Comment by timocov** [comment]
Hey @kimgysen,

I'm sorry for long delay, I just missed this issue 🙁.

> Connect custom price points

You can do it via creating line series with 2 points, does it work?

> Define the length of the line (not from point to point necessarily)

In which units it should be defined?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
