### ISSUE TITLE
Double clicking on time scale will reset fix left edge

### ISSUE THREAD

**Issue by deantheiceman** [tradingview/lightweight-charts#224]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

When using fix left edge, if I double click on the "time scale" even with disabling scroll and scale it will reset the zoom level

```
  priceScale: {
    position: 'right',
    borderVisible: false,
    scaleMargins: {
      top: 0.2,
      bottom: 0.125
    }
  },
  timeScale: {
    borderVisible: false,
    fixLeftEdge: true,
    lockVisibleTimeRangeOnResize: true,
    rightBarStaysOnScroll: true,
    secondsVisible: false
  },
  layout: {
    backgroundColor: '#ffffff',
    textColor: '#333'
  },
  grid: {
    horzLines: {
      color: '#eee'
    },
    vertLines: {
      color: '#ffffff'
    }
  },
  crosshair: {
    vertLine: {
      labelVisible: true
    }
  },
  handleScroll: {
    mouseWheel: false,
    pressedMouseMove: false
  },
  handleScale: {
    axisPressedMouseMove: false,
    mouseWheel: false,
    pinch: false
  },
```

Expected, it should not change the time scale

**Comment by deantheiceman** [comment]
Is there also a way to fix the time scale from showing random data points? 
![image](https://user-images.githubusercontent.com/54087837/65903970-a9f70700-e3e7-11e9-9f61-f67b7823fc2e.png)

How can we set it to show intervals of 30 minutes etc instead of the random points

**Comment by eugene-korobko** [comment]
Hello!

I can approve bug with double-click, it will be fixed in the nearest releases

**Comment by deantheiceman** [comment]
@eugene-korobko thanks!

Do you have any ideas about how to format the time?

**Comment by timocov** [comment]
Hey @deantheiceman,

currently we trying to show uniformly time scale (and grid as well) so I hope it depends on the data you provided. Quite possible that in case of generating time scale marks by just some time (e.g. by 30 minutes) it could be look strange and uniform.
