### ISSUE TITLE
SyntaxError: Unexpected token export while importing

### ISSUE THREAD

**Issue by afsanefda** [tradingview/lightweight-charts#225]
Hi 
I am trying to use the lightweight chart on my **Nextjs - React** application but it keeps returning this error! Do you have any idea what is wrong with my component?

I thought maybe it's because of server-side rendering but I get the error as soon as I import it in my component! 

<a href="https://codesandbox.io/s/hello-world-2nqdy?fontsize=14">
  <img alt="Edit lightweightcharts" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

```
import React, { useRef } from 'react';
import { createChart } from 'lightweight-charts';

const Index = () => {
  const chartRef = useRef(null);
  const chart = createChart(chartRef.current, { width: 400, height: 300 });
  const lineSeries = chart.addLineSeries();
  lineSeries.setData([
    { time: '2019-04-11', value: 80.01 },
    { time: '2019-04-12', value: 96.63 },
    { time: '2019-04-13', value: 76.64 },
    { time: '2019-04-14', value: 81.89 },
    { time: '2019-04-15', value: 74.43 },
    { time: '2019-04-16', value: 80.01 },
    { time: '2019-04-17', value: 96.63 },
    { time: '2019-04-18', value: 76.64 },
    { time: '2019-04-19', value: 81.89 },
    { time: '2019-04-20', value: 74.43 },
  ]);

  return (
    <>
      <div ref={chartRef}></div>
    </>
  );
};

export default Index;

```

Error:
```


export { CrosshairMode, LineStyle, LineType, PriceScaleMode, createChart, isBusinessDay, isUTCTimestamp, version };
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/front-next/node_modules/lightweight-charts/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.lightweight-charts (/front-next/_next/server/static/development/pages/index.js:197:18)
    at __webpack_require__ (/front-next/_next/server/static/development/pages/index.js:23:31)
    at Module../pages/home/index.js (/front-next/_next/server/static/development/pages/index.js:109:76)
/front-next/node_modules/lightweight-charts/dist/lightweight-charts.esm.development.js:10998
export { CrosshairMode, LineStyle, LineType, PriceScaleMode, createChart, isBusinessDay, isUTCTimestamp, version };
^^^^^^

```

More info about error :
```
/front-next/node_modules/lightweight-charts/dist/typings.d.ts
Error:(92, 3) TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
Error:(516, 16) TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
```

**Comment by afsanefda** [comment]
> Hi
> I am trying to use the lightweight chart on my **Nextjs - React** application but it keeps returning this error! Do you have any idea what is wrong with my component?
> 
> I thought maybe it's because of server-side rendering but I get the error as soon as I import it in my component!
> 
> [ ![Edit lightweightcharts](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667) ](https://codesandbox.io/s/hello-world-2nqdy?fontsize=14)
> ```
> import React, { useRef } from 'react';
> import { createChart } from 'lightweight-charts';
> 
> const Index = () => {
>   const chartRef = useRef(null);
>   const chart = createChart(chartRef.current, { width: 400, height: 300 });
>   const lineSeries = chart.addLineSeries();
>   lineSeries.setData([
>     { time: '2019-04-11', value: 80.01 },
>     { time: '2019-04-12', value: 96.63 },
>     { time: '2019-04-13', value: 76.64 },
>     { time: '2019-04-14', value: 81.89 },
>     { time: '2019-04-15', value: 74.43 },
>     { time: '2019-04-16', value: 80.01 },
>     { time: '2019-04-17', value: 96.63 },
>     { time: '2019-04-18', value: 76.64 },
>     { time: '2019-04-19', value: 81.89 },
>     { time: '2019-04-20', value: 74.43 },
>   ]);
> 
>   return (
>     <>
>       <div ref={chartRef}></div>
>     </>
>   );
> };
> 
> export default Index;
> ```
> 
> Error:
> 
> ```
> 
> 
> export { CrosshairMode, LineStyle, LineType, PriceScaleMode, createChart, isBusinessDay, isUTCTimestamp, version };
> ^^^^^^
> 
> SyntaxError: Unexpected token export
>     at Module._compile (internal/modules/cjs/loader.js:720:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:683:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/front-next/node_modules/lightweight-charts/index.js:6:19)
>     at Module._compile (internal/modules/cjs/loader.js:777:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:683:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.lightweight-charts (/front-next/_next/server/static/development/pages/index.js:197:18)
>     at __webpack_require__ (/front-next/_next/server/static/development/pages/index.js:23:31)
>     at Module../pages/home/index.js (/front-next/_next/server/static/development/pages/index.js:109:76)
> /front-next/node_modules/lightweight-charts/dist/lightweight-charts.esm.development.js:10998
> export { CrosshairMode, LineStyle, LineType, PriceScaleMode, createChart, isBusinessDay, isUTCTimestamp, version };
> ^^^^^^
> ```
> 
> More info about error :
> 
> ```
> /front-next/node_modules/lightweight-charts/dist/typings.d.ts
> Error:(92, 3) TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
> Error:(516, 16) TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
> ```

**When I import it in didMount it seems correct but why is that?** 

```
import React, { useRef, useEffect } from 'react';

const Index = () => {
  const chartRef = useRef(null);
  let lightweightCharts;

  useEffect(() => {
    // eslint-disable-next-line global-require
    lightweightCharts = require('lightweight-charts');
    const { createChart } = lightweightCharts;
    const chart = createChart(chartRef.current, { width: 400, height: 300 });
    const lineSeries = chart.addLineSeries();
    lineSeries.setData([
      { time: '2019-04-11', value: 80.01 },
      { time: '2019-04-12', value: 96.63 },
      { time: '2019-04-13', value: 76.64 },
      { time: '2019-04-14', value: 81.89 },
      { time: '2019-04-15', value: 74.43 },
      { time: '2019-04-16', value: 80.01 },
      { time: '2019-04-17', value: 96.63 },
      { time: '2019-04-18', value: 76.64 },
      { time: '2019-04-19', value: 81.89 },
      { time: '2019-04-20', value: 74.43 },
    ]);
  }, []);

  return (
    <>
      <div ref={chartRef}></div>
    </>
  );
};

export default Index;
```

**Comment by eugene-korobko** [comment]
Hello!

Error says
`Try changing the `lib` compiler option to es2015 or later.`

Have you tried it?

**Comment by afsanefda** [comment]
> Hello!
> 
> Error says
> `Try changing the `lib` compiler option to es2015 or later.`
> 
> Have you tried it?

The problem is the way it should be imported! We have to import it when the component is rendered. Thanks by the wat

**Comment by timocov** [comment]
@afsanefda so your problem is fixed or still persist?

**Comment by afsanefda** [comment]
> @afsanefda so your problem is fixed or still persist?

The problem is solved - I had to import the charts on component did mount- the code above is updated
