### ISSUE TITLE
Logarithmic scaling is applied to volume

### ISSUE THREAD

**Issue by patrickdobler** [tradingview/lightweight-charts#227]
**Lightweight Charts Version:** 1.1.0

**Steps/code to reproduce:**

Add Logarithmic scale at to the chart: 

```
priceScale: {
    	mode: LightweightCharts.PriceScaleMode.Logarithmic,
},
```

i.e. in the official template https://jsfiddle.net/TradingView/cnbamtuh/

**Actual behavior:**

The volume scales also to logarithmic

**Expected behavior:**

An option to disable price scaling for histogram series or disable it completely.

**Screenshots**

![image](https://user-images.githubusercontent.com/16536946/66221066-80cbc480-e6ce-11e9-85ea-fdc990f99d74.png)

Thank you very much for this great library!

**Comment by kirchet** [comment]
Yes, seems like a bug, we should not apply logarithmic option for overlay series
