### ISSUE TITLE
Volume scaling issue in larger timeframes

### ISSUE THREAD

**Issue by patrickdobler** [tradingview/lightweight-charts#228]
**Lightweight Charts Version:** 1.1.0

**Steps/code to reproduce:**

When I try to use larger timeframes such as weekly or monthly, I often get a strange scaling behavior. I haven't found an option that would control this behavior. Even "scaleMargins" doesn't work correctly. In this example, it's even worse because "scaleMargins" doesn't work correctly on the bars either. If I left the values on default (0.1, 0.2), then the price range would not even be on the chart anymore. See the following figure.

![image](https://user-images.githubusercontent.com/16536946/66327848-cd600b80-e92b-11e9-8754-4490fa763ce1.png)

**Screenshots**

![07-10-_2019_17-45-34](https://user-images.githubusercontent.com/16536946/66327017-5bd38d80-e92a-11e9-91f9-2f8c34cb88e0.gif)

Sorry for the poor quality, but I think you can see it. Otherwise, I posted an example in jsfiddle.
The stock ticker is ADAP [weekly]

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/2hdkpz13/1/

**Comment by kirchet** [comment]
![image](https://user-images.githubusercontent.com/1572087/66330886-ff786a00-e939-11e9-81e3-b0b485ff681c.png)

Probably it's because `open`, `high`, `low` and `close` should be numbers
