### ISSUE TITLE
disable all kinds of scrolls and touch with one option

### ISSUE THREAD

**Issue by krtschmr** [tradingview/lightweight-charts#230]
```
      handleScroll: {
        mouseWheel: false,
        pressedMouseMove: false,
        horzTouchDrag: false,
        vertTouchDrag: false
      },
      handleScale: {
          axisPressedMouseMove: false,
          mouseWheel: false,
          pinch: false,
      },
```

this should be shortcutted to

```
{
  disableInteraction: true
}
```

**Comment by timocov** [comment]
@krtschmr I don't think that having the same thing in multiple variations is a good thing and we need to put it in the API. I'm not sure that it's a good idea, but it is possible that we can allow use `handleScroll: false` and `handleScale: false` for that to disallow some kind of interactions.

@kirchet any thoughts?

**Comment by krtschmr** [comment]
yes that would also be a good idea to call `false` on it

**Comment by kirchet** [comment]
>it is possible that we can allow use `handleScroll: false` and `handleScale: false` for that to disallow some kind of interactions.

Yes, sounds good

**Comment by timocov** [comment]
@krtschmr would you like to make PR for that?

**Comment by krtschmr** [comment]
@timocov i have no idea since i never did TS, but it can't be so difficult. i just need to override the settings in case it's set to `false`. i might have time for that tomorrow.

**Comment by timocov** [comment]
Ok, no problem at all.
