### ISSUE TITLE
Chart data cannot be displayed on ios

### ISSUE THREAD

**Issue by gebilaofan** [tradingview/lightweight-charts#231]
**Lightweight Charts Version:1.1.0** 

**Steps/code to reproduce:**

**Actual behavior:**
Charts can't render charts on iOS, but they can be viewed completely on the chrome Apple emulator and on Android. I didn't see the chart when I switched to the iphone. I have a debug test, setdata has data, and it seems that there is a problem during rendering.

**Expected behavior:**

**Screenshots**

**Comment by timocov** [comment]
Hey @gebilaofan, can you please provide a bit more info regard your devices: what iOS version you have? What Safari version? Can you reproduce the same problem on your devices on https://www.tradingview.com/lightweight-charts/ page?

**Comment by gebilaofan** [comment]
@timocov 
You can see the chart on the official website.
I am a web project, and I have an app shell outside, which is equivalent to a webview.
ios:12.4.2

![image](https://user-images.githubusercontent.com/46524158/68849179-8e805b00-070c-11ea-9f87-ef3e0c9f5304.png)

**Comment by timocov** [comment]
> You can see the chart on the official website.

So, you can see charts on www.tradingview.com, but unable on your page, right? In this case I guess you need to add polyfills on your page.

**Comment by timocov** [comment]
@gebilaofan did you play with polyfills?

**Comment by gebilaofan** [comment]
> @gebilaofan did you play with polyfills?

what is polyfills ???

**Comment by gebilaofan** [comment]
**This is iphone 6s**
![image](https://user-images.githubusercontent.com/46524158/69523957-09186880-0fa0-11ea-98b1-544b25a95653.png)


**This is Android**
![image](https://user-images.githubusercontent.com/46524158/69524140-5e547a00-0fa0-11ea-8f52-23ca33c5fe75.png)

**Comment by timocov** [comment]
> what is polyfills ???

See https://github.com/tradingview/lightweight-charts/issues/101#issuecomment-517117573

> This is iphone 6s

Can you provide jsfiddle-like example which we can open and debug locally?

**Comment by gebilaofan** [comment]
> Can you provide jsfiddle-like example which we can open and debug locally?

Thank you very much，I think I have solved the problem。

**Comment by gebilaofan** [comment]
> Can you provide jsfiddle-like example which we can open and debug locally?

Thank you very much，I think I have solved the problem。

**Comment by SardarShahzeb** [comment]
> > Can you provide jsfiddle-like example which we can open and debug locally?
> 
> Thank you very much，I think I have solved the problem。

HI, can you please tell me how you fixed this issue because i am also facing this issue and after so many tries and research  couldn't find the solution yet. shall be very thankful to you if you help me in this matter
