### ISSUE TITLE
Accept functions as value of options for more customization

### ISSUE THREAD

**Issue by srv91** [tradingview/lightweight-charts#237]
`PriceScaleMode` has 4 options to select from.
This feature request is not just for `PriceScaleMode` but several other options in chart customization that accept only specific set values to chose from. Would be great if it can accept a function for further customization.

**Comment by timocov** [comment]
When these functions should be called? What's the problem with preparing options and then apply them?

**Comment by srv91** [comment]
@timocov 
Let's assume my priceScale ranges in billions, so instead of showing a number like `2000000000`, is it possible to format it like `2bn` or `2m` for million?

> When these functions should be called?
So if there's an option for `PriceScaleMode` called `custom` that can be a function with PriceScale "values" as arguments and it can return a formatted value that can be used to display on the chart.

**Comment by srv91** [comment]
**Update**

Found this https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format
Exactly what I was referring to. Thanks!
