### ISSUE TITLE
Draw a line

### ISSUE THREAD

**Issue by cardimajs** [tradingview/lightweight-charts#238]
Hi,

Is possible to draw a line using javascript?

Thank You.

**Comment by timocov** [comment]
You can try to draw line series with 2 points. Did you try it before?

**Comment by cardimajs** [comment]
no, you have some example?

**Comment by timocov** [comment]
> is possible to use 2 datasets? 1 for prices and another to "draw a line?"

Yes, you can create 2 series and set data for each series separately.

> you have some example?

It's pretty the same as you create other line series, but only with 2 points in `setData` method.

**Comment by ProgrammingLife** [comment]
@timocov sounds interesting. But what if we need to draw 100 separate lines on one plot (for instance, vertical and horizontal lines). Then we need 100 separate series for each line or we can draw it with one serie?

**Comment by ProgrammingLife** [comment]
@timocov what if we need to draw a bunch of price channels: horizontal, diagonal? Then we need to create line series for each of those channels?

**Comment by timocov** [comment]
@ProgrammingLife Yes.

**Comment by cardimajs** [comment]
and about a draggable line? 
is possible?

**Comment by timocov** [comment]
@cardimajs no, it's impossible right now. Afaik we don't a plan to add such things (like drawings) because it's out of our goal for this library.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by douglascvas** [comment]
@timocov Is it possible to draw a line series over a candlestick series? When I add a line series to a candlestick chart it intercalates the candle with the line. So a line that should start on top of a candle at 11:00AM is rendered beside it, not over it.

**Comment by timocov** [comment]
> it intercalates the candle with the line

@douglascvas what do you mean?

> So a line that should start on top of a candle at 11:00AM is rendered beside it, not over it.

Try to change the order of creating series. Also see #136

**Comment by douglascvas** [comment]
@timocov this is what I mean:

![trade-1](https://user-images.githubusercontent.com/4059943/90303913-ce6fab00-def5-11ea-973c-852b85868b57.png)

![trade-2](https://user-images.githubusercontent.com/4059943/90303921-d4658c00-def5-11ea-84d4-f918d50fff31.png)

The line is a line series of two points, starting at 11:00 and ending at 12:00.
Instead of drawing the line over the candle, it draws the candle at 11:00 then opens another space on the right and draws the start of the line.

**Comment by timocov** [comment]
@douglascvas  I think that points of line series for 11 and 12 time and points of candlestick series for the same time has different time part, check it.
