### ISSUE TITLE
[bug] line series with candlestick don`t scale together

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#240]
**Lightweight Charts Version:** 1.1.0 

Hi.  line series with candlestick don`t scale together. Line created from OHLC data as SM with period 2. Rendered correctly but not scaled.

![1](https://user-images.githubusercontent.com/10992863/67773934-8fa75c00-fa6d-11e9-9250-3dee349d9135.png)

**Comment by timocov** [comment]
Could you please provide repro? I guess that you've created that series as overlay one.

**Comment by nikitamarcius** [comment]
@timocov yep. 

Code: https://stackblitz.com/edit/js-wjzamb
Demo: https://js-wjzamb.stackblitz.io/

**Comment by timocov** [comment]
So, as I've said - that's because you create series as `overlay` one. You need to remove `overlay: true` from options of line series.

**Comment by nikitamarcius** [comment]
it`s works. i add `overlay`, because candlestick is over then line. how to draw a line forward?

**Comment by timocov** [comment]
I think it depends on order of creating the lines. What order you have?

**Comment by nikitamarcius** [comment]
Its right. First chart (candle) then line, because chart it`s main component, in which mixed others (volume, lines etc.) . I want to force the order(ex. SMA 20, 50, 100, 200 over main chart). If there is no such option, then it must be added. 😊

**Comment by timocov** [comment]
@nikitamarcius yeah, maybe we need to think about API to reorder the series. Could you please another issue for that to avoid confusing with this issue and to have clear another one with different aim? :)

**Comment by nikitamarcius** [comment]
continued discussion: https://github.com/tradingview/lightweight-charts/issues/247
