### ISSUE TITLE
How do I get Crosshair when I click?

### ISSUE THREAD

**Issue by liubin595338764** [tradingview/lightweight-charts#244]
Now the chart needs a long press to appear Crosshair. How do I get Crosshair when I click? Long press will display the browser's menu.

**Comment by liubin595338764** [comment]
![image](https://user-images.githubusercontent.com/5274428/68066880-0dbf7780-fd7a-11e9-9581-0766f967f386.png)

**Comment by timocov** [comment]
Currently it's impossible.

> Long press will display the browser's menu.

What browser do you use? You can try to disable context menu on the chart element to prevent it.

**Comment by liubin595338764** [comment]
QQ browser, UC browser, HUAWEI Phone browser.
>Currently it's impossible.

Try disabling the context menu on the chart element to prevent this from happening. Effective on chrome

**Comment by liubin595338764** [comment]
Https://cn.tradingview.com/lightweight-charts/
This problem also exists on the website.

![image](https://user-images.githubusercontent.com/5274428/68363955-6ff7ee00-0167-11ea-8f52-05a28f020382.png)

**Comment by timocov** [comment]
> This problem also exists on the website.

Can you please describe what this context menu stands for? I don't know Chinese.

> QQ browser, UC browser, HUAWEI Phone browser.
> Effective on chrome

Can you please check in other browsers (e.g. Firefox, Safari)? I guess that it might be that "QQ browser, UC browser, HUAWEI" browsers doesn't respect HTML spec.
