### ISSUE TITLE
How do I delete a LineSeries  ?

### ISSUE THREAD

**Issue by saeidtf** [tradingview/lightweight-charts#245]
Hello
I automatically add a LineSeries  to the chart,
  How do I remove them?

![image](https://user-images.githubusercontent.com/6494364/68113591-64a78700-ff09-11e9-8111-4048b1169d4d.png)

**Comment by timocov** [comment]
> How do I remove them?

See https://github.com/tradingview/lightweight-charts/blob/b093a3e5df1fbad633c846da119afcd1ecf137b6/src/api/ichart-api.ts#L85-L88. We need to add it to the docs.

**Comment by saeidtf** [comment]
Thank you, great

**Comment by timocov** [comment]
Let's leave it open until we fix the docs. Thanks.
