### ISSUE TITLE
hours:minutes:seconds in graphs

### ISSUE THREAD

**Issue by gavin99587** [tradingview/lightweight-charts#246]
Hi:
I am having trouble making my graph display actual hour, minute, second data. the format 12:00 12:01 12:02 is what i want, but how can i define the Time in typescript? my trouble please see screenshot
![Snip20191106_8](https://user-images.githubusercontent.com/11565497/68314756-abf06c00-00f1-11ea-8483-7a1e8715ebea.png)

**Comment by timocov** [comment]
The first you need to divide time value by 1000, because the time [should be UNIX timestamp](https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp). The second, from the https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp:

> Note that to prevent errors, you should cast the numeric type of the time to UTCTimestamp (it's a nominal type) type from the package (value as UTCTimestamp) in TypeScript code.

**Comment by gavin99587** [comment]
> Hi:
> I am having trouble making my graph display actual hour, minute, second data. the format 12:00 12:01 12:02 is what i want, but how can i define the Time in typescript? my trouble please see screenshot
> ![Snip20191106_8](https://user-images.githubusercontent.com/11565497/68314756-abf06c00-00f1-11ea-8483-7a1e8715ebea.png)

thanks,i solve the problem according to your tips,

**Comment by gavin99587** [comment]
> The first you need to divide time value by 1000, because the time [should be UNIX timestamp](https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp). The second, from the https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp:
> 
> > Note that to prevent errors, you should cast the numeric type of the time to UTCTimestamp (it's a nominal type) type from the package (value as UTCTimestamp) in TypeScript code.

thanks,i solve the problem according to your tips,

**Comment by timocov** [comment]
You're welcome.
