### ISSUE TITLE
[Feature request] reorder charts

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#247]
Hi. I think, its will be great, if i can reorder charts. 

Ex: 

```
1. Line chart
2. Chart - candlestick
3. Volume chart
```

related from https://github.com/tradingview/lightweight-charts/issues/240#issuecomment-548773440

**Comment by bmatusiak** [comment]
would be cool if z-index would link charts when setting to the same index level
https://github.com/tradingview/lightweight-charts/issues/136

**Comment by timocov** [comment]
Ah, this is actually duplicate of #136. Thanks @bmatusiak!
