### ISSUE TITLE
timeScale().fitContent() problem

### ISSUE THREAD

**Issue by mrak1990** [tradingview/lightweight-charts#251]
**Lightweight Charts Version:** latest from unpkg

**Problem:** fitContent() and setVisibleRange() functions do not work as expected 

**CodeSandbox/JSFiddle/etc link:** https://jsfiddle.net/wheasqzf/2/

**Comment by timocov** [comment]
I don't think that it's bug - [we have a limitation](https://github.com/tradingview/lightweight-charts/blob/16b357bc63cc98fcab52ce14d8f3bc677445af10/src/model/time-scale.ts#L21-L22) of min/max bar spacing value. In case of bar spacing less than 1 we need to approximate values somehow (merge multiple bars into one?) to display the data correct. But it looks like feature (even like kind of big feature).

**Comment by mrak1990** [comment]
Got it. thanks. The approximation rule of data should be set by users, I suppose.
