### ISSUE TITLE
fitContent Doesn't work as expected

### ISSUE THREAD

**Issue by Rishabhai** [tradingview/lightweight-charts#252]
**Lightweight Charts Version:**  1.1.0

**Steps/code to reproduce:**
https://jsfiddle.net/emdqwfxt/22/

**Actual behavior:** 

timeScale().fitContent() is not able to plot all data points in visible range and when i scroll i see more data.
also tried using **setVisibleRange** but that also didn't help.

**Expected behavior:**
timeScale().fitContent() should plot whole data points in the visible range of chart

**Screenshots**

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/emdqwfxt/22/

**Comment by timocov** [comment]
Duplicate of #229
