### ISSUE TITLE
Animation on changes

### ISSUE THREAD

**Issue by deantheiceman** [tradingview/lightweight-charts#254]
Is it possible to add a transition animation on the charts?

d3 allows us to set a css animation transition which means adding new symbols or changing the canvas will do so smoothly rather than a jaggeder change

**Comment by timocov** [comment]
Hey @deantheiceman,

> Is it possible to add a transition animation on the charts?

No, it's impossible right now.

> d3 allows us to set a css animation transition 

Afaik D3 uses SVGs, right? We draw charts on canvas and it's hard to apply any animation just via CSS. Do you have any specific request for animations? It's possible that we'll add some to the lightweight-charts...

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by ttrasn** [comment]
Is it possible to update chart with animation ?  I want to add new point and update chart very smooth.

And is possible to control and style live price on y scale ?

**Comment by timocov** [comment]
> Is it possible to update chart with animation ? I want to add new point and update chart very smooth.

No, it's impossible right now.

> And is possible to control and style live price on y scale ?

What do you mean?

Also, you ask your questions on [StackOverflow](https://stackoverflow.com/questions/tagged/lightweight-charts) or in our [discord chat](https://github.com/tradingview/lightweight-charts/issues/241).

**Comment by fullgream** [comment]
Is it possible now with last update?

**Comment by sywyyhykkk** [comment]
Is it possible now with last update?

**Comment by carvinlo** [comment]
Is it possible now with last update?
