### ISSUE TITLE
Is this charting library support running my custom indicator?

### ISSUE THREAD

**Issue by luatnd** [tradingview/lightweight-charts#257]
I think this is a question more than a feature request.
I have some custom indicator on TradingView.com, can I view it in this charting library.
If no - is the non-open source version support custom indicator?
..
The final method that I would try is using another chart instance to show another data series that mirror my indicator, but I don't know how to sync 2 charts together when I scroll / scale 1 chart
..
Many thanks.

**Comment by timocov** [comment]
> can I view it in this charting library.

No, this library doesn't calculate anything under hood. If you want to calculate something - you need to do this yourself and provide data to the library.

> If no - is the non-open source version support custom indicator?

What do you mean?

> The final method that I would try is using another chart instance to show another data series that mirror my indicator, but I don't know how to sync 2 charts together when I scroll / scale 1 chart

Can you please describe your issue a bit more?

**Comment by luatnd** [comment]
> > can I view it in this charting library.
> 
> No, this library doesn't calculate anything under hood. If you want to calculate something - you need to do this yourself and provide data to the library.
Ah, Exactly, I forgot that I can add a new series to the chart :)

> > If no - is the non-open source version support custom indicator?
> 
> What do you mean?
> 
I mean 3 versions: Lightweight Charts / Technical Analysis Charts / Charting & Trading Platform

> > The final method that I would try is using another chart instance to show another data series that mirror my indicator, but I don't know how to sync 2 charts together when I scroll / scale 1 chart
> 
> Can you please describe your issue a bit more?
I thought I need to create a new chart to add Indicator data series.
Therefore I'll have 2 charts, when I scale chart 1, chart 2 need to scale identically following the chart 1.

**Comment by timocov** [comment]
> Therefore I'll have 2 charts, when I scale chart 1, chart 2 need to scale identically following the chart 1.

@luatnd You can add second series instead of chart.

**Comment by fmoQuant** [comment]
Hi,
If the custom indicator is an overlay of the main chart, yes we can add time series/histograms to the chart. But how to sync if I have a MACD-type indicator. We have to create another chart and synchronise the time axis with the main chart. How this can be done? Thank you for your help.
