### ISSUE TITLE
Can I similar to the magnet function?

### ISSUE THREAD

**Issue by suddenlocate** [tradingview/lightweight-charts#266]
This is more like a question!

I want to get the element closest to the cursor from open high low close when clicking on the chart

`chart.subscribeClick(function(param) { myfunction });`

Please let me know if there are other similar methods

**Comment by timocov** [comment]
Do you want to get that bar at `subscribeClick` callback, right?

In that callback you can already get series' price(s), see https://github.com/tradingview/lightweight-charts/blob/2c78462e4190dee0fd59ba0708cb6311572c3897/docs/events.md#mouseeventhandler (`seriesPrices` Map).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
