### ISSUE TITLE
Zooming by mousewheel with saving rightmost bar position

### ISSUE THREAD

**Issue by ws420** [tradingview/lightweight-charts#268]
We have some technical issues with the chart and I am wondering if maybe you could help us?

When zooming out on the chart, it looks like this:
![image](https://user-images.githubusercontent.com/48076840/69673008-5a3f5f80-1067-11ea-8fc9-8c65b72f6114.png)
There is a parameter called fixLeftEdge, which prevents scrolling to the left of the first historical bar. Is there a way to reproduce the same behavior, but for the right edge?

The charts on tradingview.com have this by default - zooming out looks like this:
![image](https://user-images.githubusercontent.com/48076840/69673025-62979a80-1067-11ea-8842-82145b8c2c18.png)
Thanks!

**Comment by timocov** [comment]
Did you search the similar issues before? 🙂 https://github.com/tradingview/lightweight-charts/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+fixRightEdge - see #218.

Also, on www.tradingview.com we have different kind of zooming - it zooms around rightmost point (but we're trying to add other way to zoom), in lightweight-charts we zoom around point under the cursor.

**Comment by ws420** [comment]
The thread you linked doesn't provide a solution to fix the issue... it says to make a proposal?

**Comment by timocov** [comment]
> The thread you linked doesn't provide a solution to fix the issue

That issue is pretty similar to what you've requested here, so this issue is duplicate actually.

> it says to make a proposal?

Yeah, it means that implementation might be unclear and we need to make design of the changes first.

> So there is no way to get charts with zooming like on tradingview.com?

Currently no and we didn't have a plan to make it here. Let's re-open it and wait for more feedback.

**Comment by SlicedSilver** [comment]
I believe that this issue is resolved with these API options:
- https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/TimeScaleOptions#fixrightedge
- https://tradingview.github.io/lightweight-charts/docs/next/api/interfaces/TimeScaleOptions#rightbarstaysonscroll
