### ISSUE TITLE
How do you call getBar to from and to after initialization, like tradingView, in order to initiate historyApi?

### ISSUE THREAD

**Issue by DemoHu** [tradingview/lightweight-charts#271]
**How do you call getBar to from and to after initialization, like tradingView, in order to initiate historyApi?**

I want to get the time of from and to after createchart, so as to request historical data to call SetData method,

And request more historical data when pulling the chart to the left

**Comment by timocov** [comment]
It's all up to you. You should decide how many bars you want to display at initial loading. `lightweight-charts` doesn't have a way to request data from you (unlike charting_library and its datafeed and JS-API).

**Comment by DemoHu** [comment]
> It's all up to you. You should decide how many bars you want to display at initial loading. `lightweight-charts` doesn't have a way to request data from you (unlike charting_library and its datafeed and JS-API).

When initializing the load, is there no callback function like getbar to get the initial from and to time to calculate the number of pieces needed by the current viewport?

I think the getbar function of tradingview is very well designed. It returns from and to, which can calculate how many pieces of data are needed during initialization according to from and to and resolution. However, tradingview is too large on the mobile side

It is hoped that lightweight charts can learn from the design of tradingview, and provide a callback function to return from and to during initialization, so that developers can calculate time range and request historical data according to their own resolution

And I hope that when I pull the chart to the far left, I can request more historical data.

I noticed that there was a subscribevisibletimerangechange method in the document, but it was triggered when the chart was pulled.

But I think when the chart is pulled to the far left and the data is not enough, the chart can tell me to ask for more historical data

**Comment by DemoHu** [comment]
> > It's all up to you. You should decide how many bars you want to display at initial loading. `lightweight-charts` doesn't have a way to request data from you (unlike charting_library and its datafeed and JS-API).
> 
> When initializing the load, is there no callback function like getbar to get the initial from and to time to calculate the number of pieces needed by the current viewport?
> 
> I think the getbar function of tradingview is very well designed. It returns from and to, which can calculate how many pieces of data are needed during initialization according to from and to and resolution. However, tradingview is too large on the mobile side
> 
> It is hoped that lightweight charts can learn from the design of tradingview, and provide a callback function to return from and to during initialization, so that developers can calculate time range and request historical data according to their own resolution
> 
> And I hope that when I pull the chart to the far left, I can request more historical data.
> 
> I noticed that there was a subscribevisibletimerangechange method in the document, but it was triggered when the chart was pulled.
> 
> But I think when the chart is pulled to the far left and the data is not enough, the chart can tell me to ask for more historical data

**This is the biggest obstacle to my current migration from tradingview to lightweight charts**

**Comment by timocov** [comment]
> When initializing the load, is there no callback function like getbar to get the initial from and to time to calculate the number of pieces needed by the current viewport?

`lightweight-charts` has different way to provide data. `charting_library` has "pull" approach, it means that the library will call your datafeed every time it decided to load/update/change/etc data, because it control all flow of the data, cache it and so on. `lightweight-charts`'s approach is opposite, it's "push" one. Thus, you should call APIs methods every time _you_ decided to update/modify data. So, as I said, it's up to you how many bars you want to show, which bar spacing you want to see on the chart.

> And I hope that when I pull the chart to the far left, I can request more historical data.

You need to implement it yourself. If we'll add all features from `charting_library` to `lightweight-charts` it becomes `charting_library` soon :)

> I noticed that there was a subscribevisibletimerangechange method in the document, but it was triggered when the chart was pulled.

What do you mean? If you think that there's bug, please provide examples (with jsfiddle-like links to repro).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by Gauthamastro** [comment]
I am also facing the same issue, as **getBars** method is not going to be called after initialisation. Only **onReady** and **resolveSymbol** are going to be called.

**Comment by timocov** [comment]
@Gauthamastro your issue isn't related to the lightweight-charts, charting_library and lightweight-charts are completely different products.
