### ISSUE TITLE
[bug] Price line didn`t hightlight price

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#273]
**Lightweight Charts Version: 1.2.1**

https://jsfiddle.net/ovpk2w07/1/

![Untitled](https://user-images.githubusercontent.com/10992863/69861908-66672f00-12aa-11ea-8a8f-d258ee7b764b.png)

**Comment by karunkrishna** [comment]
Possible to also add a custom alert string?
![image](https://user-images.githubusercontent.com/2157606/70378966-254bcc00-18f5-11ea-8fd0-4ebd5b667f7c.png)


```
const priceLine = emaSeries.createPriceLine({
    price: 2700,
    color: 'green',
    lineWidth: 1,
    lineStyle: LineStyle.Solid,
    priceVisible: true,
    alertString: 'Entry'

});
```

**Comment by nikitamarcius** [comment]
@karunkrishna hi. For what? make a separate function and set default parameters, name it `createAlertLine`

**Comment by karunkrishna** [comment]
When creating a createPriceLine, there should be a flag "priceVisible" that allows users to enable/disable the highlighted price (like your issue implies). Likewise, it would be a nice enhancement to be able to give a string label for the PriceLine. In the example above, the price line has a right-justified string _"Entry"_

**Comment by nikitamarcius** [comment]
> string label for the PriceLine

> @nikitamarcius please note that the first version will not support drawing text for price lines (on, above or even below).

https://github.com/tradingview/lightweight-charts/issues/183#issuecomment-557514399

> enable/disable the highlighted price

I don’t see the point, I think that the price should always be highlighted. You either add a line or not

**Comment by timocov** [comment]
> Likewise, it would be a nice enhancement to be able to give a string label for the PriceLine. In the example above, the price line has a right-justified string "Entry"

@karunkrishna please fill another issue for that.
