### ISSUE TITLE
Data submission form

### ISSUE THREAD

**Issue by EffMining** [tradingview/lightweight-charts#280]
From php to the page, ajax, the data from the database table are loaded
```
while ($row = $query->fetch_assoc()) {
            $orders_history['Amount'][]     = $row['Amount']/100000000;
            $orders_history['dttm_close_order'][]      = $row['TimeCloseOrder'];
        }
```
And sent to the page:
```
$out = array(
'orders_history' => $orders_history,
);
        echo json_encode($out);

```

There is a js script script in which data is presented as:
```
lineSeries.setData([
    { time:1575949947, value: 80.01 },
    { time: 1575949945, value: 96.63 },
]);
```

The question is how to bring the data to the form that comes from the database suitable for the schedule and how to integrate it there correctly? Thank you in advance

**Comment by timocov** [comment]
> There is a js script script in which data is presented as:

What's the problem with this code? It looks pretty suitable for lightweight-charts. Can you please describe a bit more info?

**Comment by EffMining** [comment]
I don’t understand how to create several lineSeries using a loop

**Comment by timocov** [comment]
Something like this:

```js
for (let i = 0; i < 10; ++i) {
	const series = chart.createLineSeries({ /* options here*/ });
	series.setData([/* data here */]);
}
```

**Comment by EffMining** [comment]
I try to do this:
```
for(var i = 0; i <result.orders_history1['Total'].length; i++){
            lineSeries.setData([
                  {time: parseInt(result.orders_history1['dttm_close_order'][i]),value: result.orders_history1['Price'][i]},
       
            ]);
        }
```
But only 1 dot appears on the chart

**Comment by EffMining** [comment]
There is my array of time and values in console:
```
{"orders_history1":"Price":["0.020175","0.020175","0.020176","0.020175","0.020176","0.020176","0.020173","0.4981319","0.020176","0.53198616"],
                    "dttm_close_order":["1576043833","1576043833","1576043833","1576043833","1576043833","1576043466","1576043466","1576043466","1576043466","1576043466"]}}

```

So I upload the data to the page and to the graph:
function chartdata() {
    $.ajax({
        url: "graph.php",
        type: "POST",
        data: {
            refresh: true
        }, 
        dataType: "json",
        success: function(result) {
            const lineSeries = chart.addLineSeries();
            for (var i = 0; i < result.orders_history1['Price'].length; i++) {
            lineSeries.setData([
                     {time: parseInt(result.orders_history1['dttm_close_order'][i]),value: 
                     result.orders_history1['Price'][i]},
}
But only 1 point is displayed on the chart

**Comment by timocov** [comment]
> But only 1 dot appears on the chart

Because you set only 1 point via calling setData method.

Try something like this:

```js
function chartdata() {
	$.ajax({
		url: "graph.php",
		type: "POST",
		data: {
			refresh: true
		},
		dataType: "json",
		success: function(result) {
			const lineSeries = chart.addLineSeries();
			const data = [];
			for (var i = 0; i < result.orders_history1['Price'].length; i++) {
				data.push({
					time: parseInt(result.orders_history1['dttm_close_order'][i]),
					value: result.orders_history1['Price'][i],
				});
			}

			lineSeries.setData(data);
		},
	});
}
```
