### ISSUE TITLE
Custom metric / indicators

### ISSUE THREAD

**Issue by pleaseshutup** [tradingview/lightweight-charts#281]
I have my own API/data source hooked up to the tradingview charting library. I have a metric, lets call it "sentiment" that I want to plot along with the price. Is this possible? How do I even get started? At this point I don't think I can even do this.

Alternative: how can I include non-ohlcv data on the charts? I have data that can't be calculated just from ohlcv data. It has to be queried and plotted

**Comment by timocov** [comment]
> I want to plot along with the price.

> how can I include non-ohlcv data on the charts?

What is it? Text, line, something else? Is it similar to #24?

**Comment by pleaseshutup** [comment]
Lets say I have a data source like:
[
{time: 12312332432, num_positive_tweets: 453},
{time: 12312335534, num_positive_tweets: 234},
{time: 12312334343, num_positive_tweets: 343},
{time: 12312367766, num_positive_tweets: 634},
{time: 12312374545, num_positive_tweets: 112},
]
That data is already available along with my OHLCV data in my API. I want to put it on the chart.
I want to plot it as a line either over the OHLCV candles OR its own line below.

What are my options? Is this possible? How?

**Comment by nikitamarcius** [comment]
@pleaseshutup 

To create indicators, need create separate array from OHLC (hight, close etc.), Then use [indicators lib](https://www.npmjs.com/package/tulind).

```javascript
const ohlc = [. . .]
const close = ohlc.map(i=> i.close)

tulind.indicators.sma.indicator([close], [3], function(err, results) {
  console.log("Result of sma is:");
  console.log(results[0]); // here is ur result [25, 33, 55, ...]
});

// From result by indicator (result[0]) need create new arr of objects [{price: 25, time: '10-10-12'}]
// NOTE: for SMA ind. first index 0-3 disabled 3 = [period]. [null, null, null, 25, 33, 55, ...]
```

**Comment by timocov** [comment]
@pleaseshutup you can creat another line series for your tweets.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
