### ISSUE TITLE
Clean data chart

### ISSUE THREAD

**Issue by EffMining** [tradingview/lightweight-charts#282]
There is a function by which a chart is built for a certain pair of currencies, and when switching this pair, in theory I need to clear the chart and load new data into it. If I add the line `chart.removeSeries (lineSeries);` then the chart is always empty, what's the problem?
```
function cd(){
    const lineSeries = chart.addLineSeries();
    let data_chart = [];
  //  chart.removeSeries(lineSeries);
    if (typeof(Data_for_chart[CoinVal]) != "undefined"){
        if (typeof(Data_for_chart[CoinVal][CoinProd]) != "undefined"){
            if ((typeof(Data_for_chart[CoinVal][CoinProd]['Price']) != "undefined")&&(typeof(Data_for_chart[CoinVal][CoinProd]['Time']) != "undefined")){
                console.log(Data_for_chart[CoinVal][CoinProd]['Price'])
                for(var i = 0; i < Data_for_chart[CoinVal][CoinProd]['Price'].length; i++){
                    data_chart.push({time:Data_for_chart[CoinVal][CoinProd]['Time'][i], value:Data_for_chart[CoinVal][CoinProd]['Price'][i]});
                }
                lineSeries.setData(data_chart);
            }
        }
    }
}
```

**Comment by kirchet** [comment]
You don't need to remove a series if you just want to update its data, `setData` replaces all the data of the series

**Comment by nikitamarcius** [comment]
@EffMining 

```javascript
	reCreateChart() {
			this.chart.removeSeries(this.series)
			this.chart = null
			this.createChart() // create chart again
		},
```

**Comment by timocov** [comment]
@nikitamarcius recreating the whole chart might cause performance issues. I'm sure you know what you're doing, it's just a note :) If you want to replace series, it's better to remove that series and create another one.

**Comment by nikitamarcius** [comment]
@timocov sure. While I have such a solution. When a trading pair changes, the OHLC data is rebuilt, while the chart remains in the same coordinates along X and Y. 
It is possible to align the graph only horizontally `chart.timeScale().resetTimeScale()`, but not vertically, I do not know this possibility.

**Comment by timocov** [comment]
@nikitamarcius it looks like an feature request for API to get/set price range...

**Comment by nikitamarcius** [comment]
@timocov 😉

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by johnworthley** [comment]
What is the solution for pushing marginal new data rather than rerendering the whole chart every 2 seconds? @timocov

**Comment by timocov** [comment]
> for pushing marginal new data 

@johnworthley what do you mean?

**Comment by PandaSobao** [comment]
Believe @johnworthley is looking for [update](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#update)()

**Comment by Christophe06410** [comment]
What works perfectly for me is this:
chart.remove();
Then you can call createChart again.
