### ISSUE TITLE
[bug] createPriceLine not removed

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#285]
**Version 1.2.1**

Hi. I need to dynamically add and remove an array of lines. When removed, they stay on the chart. Disappear if you scale the chart itself.

i think its caching. If so, how to remove this?

https://codepen.io/nikitamarcius/pen/dyPpwZM

**Comment by timocov** [comment]
We need to refresh the chart after that, thanks!

**Comment by Unstoppable-DeFi** [comment]
This regressed or was never fixed. Original codepen example still showing the bug.
