### ISSUE TITLE
[Feature request] Function to reset view to init X and Y position

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#287]
https://github.com/tradingview/lightweight-charts/issues/282#issuecomment-566140337

Need to set X and Y to initial range. 

Example `chart.resetScale() `

**Comment by timocov** [comment]
Just to clarify. Time scale could be reset by calling https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#resettimescale. But looks like we don't have an API to reset price scale.

**Comment by timocov** [comment]
Hm, looks like for price scale you can get price scale with https://github.com/tradingview/lightweight-charts/blob/v2.0.0/src/api/ichart-api.ts#L130 and then set `autoScale` option enabled. Does it work for now?

**Comment by timocov** [comment]
I'm going to close the issue since it seems that it already might be achieved (see my comments above). If you'll have any question or updates - feel free to re-open it.
