### ISSUE TITLE
jsfiddle.net cannot open

### ISSUE THREAD

**Issue by LeeeKevin** [tradingview/lightweight-charts#288]
On December 17th, the jsfiddle.net URL in China could not be opened. Please fix it.

**Comment by LeeeKevin** [comment]
You can choose to host a code tool accessible in China

**Comment by timocov** [comment]
Hey @LeeeKevin,

1. What tool can you suggest for that?
1. What if that "backup tool" will be blocked in China in the near future?

**Comment by timocov** [comment]
Related to #14

**Comment by LeeeKevin** [comment]
@timocov Thank you very much for taking the time to reply to me. I have now resolved the issue of inaccessibility, but there is one that bothers me. I set timeScale: {timeVisible: true, secondsVisible: false,} in createChart, but I still can't display the daily line. What is the reason?

**Comment by LeeeKevin** [comment]
@timocov Thanks for your help, i have solved

**Comment by timocov** [comment]
Great!
