### ISSUE TITLE
Export/render chart as img

### ISSUE THREAD

**Issue by epezon** [tradingview/lightweight-charts#295]
Hi,
I would like to render the lightweight chart as an image that could be used in a modal or a hovering object on top of the web-page. I tried to search the documentation and forums for it and it seems it is not supported by default. Any recommendations on how this type of action could be achieved? 
There is a good example of it at www.finviz.com site. When you move your mouse on top of the instrument/symbol link it opens a chart.

Thanks.

**Comment by timocov** [comment]
Can you please describe why do you need this? As one possible solution you can export image from lightweight-charts every time you want to update image, but it even can't understand why you need to do it instead of just using lightweight-charts there.

**Comment by timocov** [comment]
Ah, you're about "tooltip with chart image", right? If so, then you can render it in the background and then export image via [takeScreenshot](https://github.com/tradingview/lightweight-charts/blob/3a1908d8ad68b4609d9dc91a7187b59c10138e99/src/api/ichart-api.ts#L150-L154) method. Also, you can render lightweight-charts there without extracting image.

**Comment by epezon** [comment]
Thanks. Is there any example code for this?

**Comment by timocov** [comment]
For what? Taking the screenshot? You can look into our test case for `takeScreenshot` method https://github.com/tradingview/lightweight-charts/blob/3a1908d8ad68b4609d9dc91a7187b59c10138e99/tests/e2e/graphics/test-cases/take-screenshot.js#L43-L48

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
