### ISSUE TITLE
getVisibleRange() returns invalid range when chart is scrolled to the left of the first historical bar

### ISSUE THREAD

**Issue by mrak1990** [tradingview/lightweight-charts#297]
**Lightweight Charts Version:** 1.2.1
**Steps/code to reproduce:**

```javascript
// scroll to the left of the first historical bar
const range = chart.timeScale().getVisibleRange();
```

**Actual behavior:**

Key `from` of variable `range` contains timestamp of the first historical bar.

**Expected behavior:**

Key `from` of variable `range` contains timestamp before timestamp of the first historical bar.

**Comment by timocov** [comment]
> Key from of variable range contains timestamp before timestamp of the first historical bar.

Which one? The only we have here is bars you provided before, we don't approximate anything in the lightweight charts, so we can't predict the date. I guess we can return count of bars from left/right as well.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
