### ISSUE TITLE
Implementing a market depth chart

### ISSUE THREAD

**Issue by jesusgp22** [tradingview/lightweight-charts#298]
Looking at the API and use case examples every single chart uses the x axis as time and y axis as price, is there a way to have arbitrary abstractions for each axis? for example I am trying to implement a market depth chart where x is price and y is aggregated bid/ask volume at the price level, as seen here:

![image](https://user-images.githubusercontent.com/2547899/71909043-24e56180-313d-11ea-990b-1073806ef2af.png)

**Comment by timocov** [comment]
I think that market depth should different component, because there might be edge cases we can't implement in this library.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by abnerrizzi** [comment]
i love this king of chart

**Comment by indigoram89** [comment]
@jesusgp22 how did you solve the question?

**Comment by jesusgp22** [comment]
no, I don't think this library is able to support this use case

**Comment by indigoram89** [comment]
I think the same, thanks

**Comment by indigoram89** [comment]
I done it with chartjs =)

**Comment by compunect** [comment]
histogram can display the volume just instead of time we'd need a price scale horizontally.

**Comment by compunect** [comment]
> I done it with chartjs =)

chartjs does not seem to be really suitable for that ?
How did you do it ?

**Comment by duylinhdang1998** [comment]
> I done it with chartjs =)

Can you share example with chartjs? thanks

**Comment by Bitnasdaq** [comment]
how can we implement this?
