### ISSUE TITLE
Trendline does not draw correctly when out-of-view

### ISSUE THREAD

**Issue by karunkrishna** [tradingview/lightweight-charts#299]
**Lightweight Charts Version:** 
    "lightweight-charts": "^1.2.1"

**Steps/code to reproduce:**
Not sure if this is considered a bug as this is a workaround for drawing trend-lines by overlaying two charts together. 

When either the start or end point pans out of view, the overlay addLineSeries behaves rather ugly 

```
const trade_overlay = tradeReportChartOverlay(pnl_line_color)
trade_overlay.setData([
    {value: entry_price, time: epoch_entry_time},
    {value: exit_price, time: epoch_exit_time}
])
```

**Actual behavior:**
Please see image below on the resulting behaviour

**Expected behavior:**

Ideally it should be able to draw the trend line accurately 
On a side note, is it possible to remove the overlay addLineSeries data in the event the either the start or end "time" is "out-of-view"

**Screenshots**

![image](https://user-images.githubusercontent.com/2157606/72010525-ff805280-3225-11ea-8d8d-1f2335aa86ec.png)

**Comment by eugene-korobko** [comment]
Hello!

Could you please clarify why do you set line series an overlay? I belive it should be bound to the same price scale as candles.

**Comment by timocov** [comment]
Also, it would be very helpful to have jsfiddle-like repro.

**Comment by karunkrishna** [comment]
> Could you please clarify why do you set line series an overlay? I belive it should be bound to the same price scale as candles.

```
import {createChart, CrosshairMode, LineStyle} from "lightweight-charts";
const chart = createChart(elements.candlestickChart, {...})

const barSeries = chart.addCandlestickSeries({...})
const tradeDetailLineSeries= chart.addLineSeries({ overlay: true })
```
the barSeries has the full OHLC data, where as the tradeDetailLineSeries is limited to two points (which is the start- and end-point of the trendline) 



> Also, it would be very helpful to have jsfiddle-like repro.

Sure, I'll try to port over an example this afternoon

**Comment by timocov** [comment]
> where as the tradeDetailLineSeries is limited to two points (which is the start- and end-point of the trendline)

If `tradeDetailLineSeries` is referred to `barSeries` (has the same units and calculated from `barSeries` for instance) then, I guess, it shouldn't be overlay, because it should change it's range along with `barSeries` (and when `barSeries` change its price range).

**Comment by karunkrishna** [comment]
Closing.  
This was an bug on my side; It looked like the underlying ohlc was drawn with UTC, while the Trendline was draw with EST... so the trendline sort of fell-off when out of viewpoint
