### ISSUE TITLE
Candlestick series does not update properly when resetting data

### ISSUE THREAD

**Issue by AoDev** [tradingview/lightweight-charts#300]
**Lightweight Charts Version:** 
1.2.1

Note: I saw this issue when updating from 1.1.0 to 1.2.1. I have reverted back to 1.1.0 to verify and could confirm it does not happen. I think that it's a possible bug introduced in 1.2.1.

**Steps/code to reproduce:**
**Context**: I have a button that lets the user switch timeframe for a given market. 

Programmatically, the only thing I do is to call the `candlestickSeries.setData(selectedTimeframeData)`.

The issue happens after I set the data.

**Actual behavior:**
The chart looks fine when I set the data for the first time:

### First set of data for candlestick series
<img width="594" alt="Screen Shot 2020-01-10 at 12 35 28" src="https://user-images.githubusercontent.com/1526150/72150561-0afa8780-33a6-11ea-8458-75f4d8ff4dab.png">

### After setting new data in the serie (another timeframe)
I can scroll the chart horizontally and I have wrong candles painted in the "future".

You can see on the half right of the chart, all these "weird candles" that should not be there.
Note that also there is no date / time on the time axis for these. 

<img width="592" alt="Screen Shot 2020-01-10 at 12 35 48" src="https://user-images.githubusercontent.com/1526150/72150571-10f06880-33a6-11ea-9d4a-b1893034788f.png">

**Expected behavior:**

These unexpected candles, on the right, should not be there.

**Comment by timocov** [comment]
Can you please make a repro for this bug?

**Comment by AoDev** [comment]
Will do as soon as I can.

**Comment by timocov** [comment]
Any updates here?)

**Comment by AoDev** [comment]
Hello @timocov . Sorry, had been completely absorbed by my work. I'll do something this week-end.

**Comment by AoDev** [comment]
@timocov I have been unable to reproduce the issue I had. Not too sure what happened. I'll close it now and will reopen it, if happens again.
