### ISSUE TITLE
Crosshair line not visible when priceScale position set to none

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#302]
**Lightweight Charts Version:** 1.2.1

**Steps/code to reproduce:**

```javascript
var chart = LightweightCharts.createChart(document.body, {
    priceScale: {
        position: "none"
    }
};
```

**Actual behavior:**

Crosshair should be still visible, or at least vertical crosshair line

**Expected behavior:**

Crosshair not visible at all

**CodeSandbox/JSFiddle/etc link:**

Pricescale position none
https://jsfiddle.net/SuperPenguin/dxh012qb/3/

Compared to same code but Pricescale position right
https://jsfiddle.net/SuperPenguin/j24508sr/

**Comment by timocov** [comment]
> or at least vertical crosshair line

Agree.

**Comment by timocov** [comment]
Quite possible that the issue is somewhere [here](https://github.com/tradingview/lightweight-charts/blob/f26067981853bc28e42f5defb1cbac5db837f64f/src/model/crosshair.ts#L268-L279) (I'm not sure about exactly that place, but at least it should be `crosshair.ts`).
