### ISSUE TITLE
Android Setup Error (Invalid LinK)

### ISSUE THREAD

**Issue by Xy-joe** [tradingview/lightweight-charts#306]
the link https://github.com/tradingview/charting_library provided for the android library setup does not exist, returns the 404 error not found.

Where do I download the library from and how exactly are we to add it to the assets folder like the documentation states

**Comment by timocov** [comment]
> the link tradingview/charting_library provided for the android library setup does not exist, returns the 404 error not found.

1. Where you found that link in this repo?
1. Where said that it's "android library"?
1. This is private repo, you need to get access first on https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/.
