### ISSUE TITLE
candlestickSeries Time 

### ISSUE THREAD

**Issue by walterX12** [tradingview/lightweight-charts#307]
Hi,
 I would like to ask for help. I am trying to use the candlestickSeries for one hourly candles (new candle each hour). 

I am able to use candlestickSeries with Daily candles (OHLC), but I am not able to pass hours to time.     I have tried to tweak the sample, but no success.

   candlestickSeries.setData([
        { time: "2019-01-01T00:00:00.000Z", open: 141.77, high: 170.39, low: 120.25, close: 145.72 },
        { time: "2019-01-01T01:00:00.000Z", open: 145.72, high: 147.99, low: 100.11, close: 108.19 },
        { time: "2019-01-01T02:00:00.000Z", open: 108.19, high: 118.43, low: 74.22, close: 75.16 },
    ]);    

Does candlestickSeries support Hours ot minutes ? Or does it work only for Days ?

Thanks

Petr

**Comment by walterX12** [comment]
I have figured out. I need to pass UNIX.  I have used following syntax

time =  Date.parse( datetime  / 1000;

            chart.applyOptions({
                priceScale: {
                    autoScale: true,
                },
            });

**Comment by Masoud-garazhian** [comment]
can u describe more how u did it ?!

**Comment by walterX12** [comment]
Hi, I have abandoned this my project, so I do not remember details.

I have converted to Unix format.
 ` time =  Date.parse( datetime)  / 1000;`


Looking to my source code backup of the very first "draft" I found the function below, where I am converting

```
            function ParseDate(inDate)
            {
                var result; 
                var date = String(inDate);
                result = Date.parse(date) / 1000;
                //console.log('Date = ' + result);
                return result;
            }
```

Charts initialisation

```
      // Chart
            var chart = LightweightCharts.createChart(document.body, { width: 1600, height: 600 });

            chart.applyOptions({
                priceScale: {
                    autoScale: true,
                },
            });

            chart.applyOptions({
                timeScale: {
                    secondsVisible: false,
                    timeVisible:true,
                },
            });                   

```

I am sorry I cannot provide more details as I do not remember this project at all.
