### ISSUE TITLE
Reference line in overlay

### ISSUE THREAD

**Issue by walterX12** [tradingview/lightweight-charts#308]
I would like to ask for adding reference line(s) in overlay series. For example for RSI technical Indicator (0-100 - red line) are for reference usually displayed 2 lines: 30 and 70.

Refer to the picture.
![RSI](https://user-images.githubusercontent.com/26149953/72683501-28330280-3ad8-11ea-93f6-570c2e4d1d42.JPG)

I have tried to use overlay line series (addLineSeries) with values 0,70,70,..... but this line does not stick to RSI indicator itself and I am not able to anchor it.

Thank you for considering this feature.

**Comment by timocov** [comment]
> I have tried to use overlay line series (addLineSeries) with values 0,70,70,..... but this line does not stick to RSI indicator itself and I am not able to anchor it.

Currently they (all three lines) shouldn't be overlay. We'll add ability to merge several series to the same price scale in #129.
