### ISSUE TITLE
Candlestick chart does not handle intervals of less than 1 day

### ISSUE THREAD

**Issue by DominicTobias-b1** [tradingview/lightweight-charts#312]
Hi, I'm using lightweight charts because it's so much nicer than the higher tier offerings which have no NPM module, much larger bundles, and a horrible interface for datafeeds, but it seems that it has been purposefully limited perhaps to push users to a higher tier? Unless I'm missing how to configure the intervals.

**Lightweight Charts Version:** 1.2.1

**Steps/code to reproduce:**

Pass in OHCL data for a single day

**Actual behavior:**

Chart MUTATES the array (bad) into this format: `{day: 16, month: 1, year: 2020}` ignoring any time resolution less than a day, and bunches all the data together in one candle.

**Expected behavior:**

Should be able to view candles at lower intervals than a day, otherwise it's next to useless for traders

![Screenshot 2020-01-29 at 4 31 46 PM](https://user-images.githubusercontent.com/58683337/73340047-f4649380-42b4-11ea-9f1e-04ea257dc65b.png)

**Comment by timocov** [comment]
Can you provide what data you passed to the `setData` method? Also, did you read https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp?

**Comment by DominicTobias-b1** [comment]
Thanks for your super fast reply I skim read that oops, works great now 👌
