### ISSUE TITLE
Set markers disappear

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#313]
Hello! 
I display the candles for the day. I also display markers in certain candles. But
When I move the graph to the left or right the set markers disappear. In addition, markers disappear when you approach the graph.

Help, please.

**Comment by timocov** [comment]
Hi! Any repro? jsfiddle example? link to website with the problem?

**Comment by timocov** [comment]
> the set markers disappear. In addition, markers disappear when you approach the graph.

Please correct me if I'm wrong - out-of-view markers disappeared? Or random ones?

**Comment by Altyair** [comment]
Later I will provide a link to the website.

**Comment by Altyair** [comment]
here are two screenshots to get started. there are marks on the first one. I move the graph slightly to the left, and they disappear. This is the second screenshot.
![Снимок экрана от 2020-02-04 15-18-05](https://user-images.githubusercontent.com/18750140/73744468-44869e80-476a-11ea-9fe8-ee239610a45d.png)
![Снимок экрана от 2020-02-04 15-18-12](https://user-images.githubusercontent.com/18750140/73744470-44869e80-476a-11ea-913b-deb19ad8d3ad.png)

**Comment by timocov** [comment]
I see. Please provide steps to reproduce the problem: jsfiddle example, link to your chart and steps to reproduce.

**Comment by Altyair** [comment]
Website: https://dev.charts.vobla.tech/figure-charts/extremums

**Comment by Altyair** [comment]
Click: View chart

**Comment by timocov** [comment]
Is it dev server, right? Is it possible to deploy development version of the library to debug purposes?

**Comment by timocov** [comment]
Also, what's steps to reproduce?

**Comment by Altyair** [comment]
where can I get this version for development?

**Comment by timocov** [comment]
It depends on how you bundle your code, but every version of the library has "development" version inside the package https://unpkg.com/browse/lightweight-charts@1.2.1/dist/. Quite possible you just need to disable minification for `vendor` bundle and/or set `NODE_ENV` to `"'development'"` (I'm not sure what bundler you use and what config you have so can't provide exactly configuration).

**Comment by timocov** [comment]
The reason is that markers sorted in reverse order:

![image](https://user-images.githubusercontent.com/3112183/73746723-e4dac400-4766-11ea-96bc-7596ca590da2.png)

Just sort them in asc order by time and they should work fine.

**Comment by timocov** [comment]
I just created #315 to add data validation in development mode to avoid such issues.

**Comment by Altyair** [comment]
wow. I'm happy. thank you very much. you are the best ;)

**Comment by timocov** [comment]
You're welcome! 🙂

**Comment by jesusgp22** [comment]
I also noticed this issue randomly happen to me, is it required that markers are sorted asc?

**Comment by timocov** [comment]
@jesusgp22 Yes, they should be sorted asc by time. Just added it to the docs https://github.com/tradingview/lightweight-charts/commit/d5bbe97c486b9d0e92f01fae96c99fde5eaab317.
