### ISSUE TITLE
The vertical scale is not marked

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#316]
Hello)
There are no horizontal lines corresponding to each price level on the chart (the price scale on the right). please tell me if there is a way to add these lines. thus, it is not clear what price range the chart shows.
![Снимок экрана от 2020-02-04 15-18-05](https://user-images.githubusercontent.com/18750140/73748996-eced3080-4773-11ea-99c3-62c30fc693da.png)

**Comment by kirchet** [comment]
Probably you need to use [price lines](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#createpriceline)

**Comment by Altyair** [comment]
I need lines for each price (label) from the price scale on the right. I doubt that price lines will work. moreover, the price values on the scale may change.

**Comment by Altyair** [comment]
here is an example from the exchange. dotted lines on against each price from the price scale.
![Снимок экрана от 2020-02-04 16-47-28](https://user-images.githubusercontent.com/18750140/73750383-83225600-4776-11ea-914c-595f138cdf23.png)

**Comment by kirchet** [comment]
Look at https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#grid

**Comment by Altyair** [comment]
thanks. 
sorry for the inattention. I should have seen it myself)

**Comment by timocov** [comment]
Looks like the issue is solved now?

**Comment by Altyair** [comment]
Yes. Thanks.
