### ISSUE TITLE
custom indicators

### ISSUE THREAD

**Issue by fmoQuant** [tradingview/lightweight-charts#318]
Hi,

This is a continuation of the discussion in issue #257 

If the custom indicator is an overlay of the main chart, yes we can add time series/histograms to the chart. But how to sync if I have a MACD-type indicator. We have to create another chart and synchronise the time axis with the main chart. How this can be done? Thank you for your help.

**Comment by timocov** [comment]
We'll add support to grouping multiple series on the same (for instance "overlay") price scale in #129 so you'll be able to add all "plots" of the one indicator to the same scale.

**Comment by fmoQuant** [comment]
Well, I understand that. But my question was in respect of having a second chart displaying an indicator (say user written RSI) and synchronise the time axis with the main chart (e.g candlestick chart) for zoom and displaying only the lower time axis. If not already done, I know it is a lot of work.

**Comment by timocov** [comment]
Are you talking about multiple panes #50?

**Comment by fmoQuant** [comment]
Thank you. Naming things help understanding better. I will have a look there. Thanks again.

**Comment by timocov** [comment]
You're welcome!
