### ISSUE TITLE
The set Price scale and grid disappear

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#319]
Website: https://dev.charts.vobla.tech/figure-charts/extremums
Steps:

click on View chart. The set Price scale and grid are visible.
choosing another pair. And the set price scale and grid disappear.
what is the reason?
please help.

**Comment by timocov** [comment]
Can I ask you don't re-create the same issues if no answer there for some time please? Thank you in advance. #317 

> And the set price scale and grid disappear.

Every symbol/ticker has its own parameters like priceScale, minmove, fractional, etc. I guess that you don't set it properly. For example, I think, that a lot of symbols you have should have minMove something like 10^-6 or even less. See https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format

**Comment by Altyair** [comment]
Ok. Sorry.
I will try to change the parameters and report the results later.

**Comment by Altyair** [comment]
Thanks
