### ISSUE TITLE
Displaying dies with headers.

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#320]
Hello.

Please tell me if I can select stamps with names that are on the right (colored) to display them on the left ?

website:
https://dev.charts.vobla.tech/g/tpslSignal?dark=true&dealPeriod=48&width=800&height=550&tsFrom=1580924913&tsTo=1581184113&symbol=XRPETH&type=short&timestamp=1580989113&TP=1.75&SL=2.5

![example](https://user-images.githubusercontent.com/18750140/73944274-bea25900-490b-11ea-9cc7-339bf21d8fa7.jpg)

**Comment by timocov** [comment]
> Please tell me if I can select stamps with names that are on the right (colored) to display them on the left ?

That label displayed on the price axis's side.

I really suggest you ask such questions in our discord instead of GitHub issues - see https://github.com/tradingview/lightweight-charts/issues/241. It's better place to ask such kind of question though.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
