### ISSUE TITLE
Bug while rendering few datasets with not equal timescale

### ISSUE THREAD

**Issue by Kharabet** [tradingview/lightweight-charts#321]
**Lightweight Charts Version:** 

**First case**

I have there 3 datasets 21 timepoints each. They are not equal in time: one datasets starts from point `{"value":0,"time":"2019-11-26"}` while others starts from `{"value":0,"time":"2019-04-14"}`. But after chart rendering you can see that this datasets (orange line) starts not from 26 Nov '19 but from 10 Sep '19.

![image](https://user-images.githubusercontent.com/14793248/74027007-febb1780-49af-11ea-8aa1-29b62ad6fb8f.png)

jsfiddle with first case: https://jsfiddle.net/pensioneer/98p0v57a/1/

**Second case**

I have modified my fiddle to be loop-based. With this approach, I expected to get more flexible configuration. I got the same unexpected behavior, but with another result. After rendering I could see that the orange line starts from 4 Apr '19. Neither from 10 Sep '19 (first case) nor from 26 Nov '19 (expected result).

![image](https://user-images.githubusercontent.com/14793248/74026982-f2cf5580-49af-11ea-8a24-0222a60522c7.png)

The datasets and configuration options are the same as in the first case. Only the initialization method was changed.

jsfiddle with second case: https://jsfiddle.net/pensioneer/ac1Le3bh/9/

**Tip**
If run my jsfiddles with Lightweight Charts Version 1.0.0 (https://unpkg.com/lightweight-charts@1.0.0/dist/lightweight-charts.standalone.production.js) orange line renders as expected (from 26 Nov '19)

**Comment by timocov** [comment]
Another examples of the repro (it might be different cases) - https://github.com/tradingview/lightweight-charts/issues/329#issuecomment-585369634.

cc @Altyair

**Comment by timocov** [comment]
We've decided to publish the fix to [1.2.2 version](https://www.npmjs.com/package/lightweight-charts/v/1.2.2) instead of coming release 2.0.
