### ISSUE TITLE
Candlesticks overlap lines with headers.

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#322]
Hello.
Candlesticks overlap lines with headers. how can this be fixed? That is, the rows and their headers should be above the candles.

Web site where you can see my problem: https://dev.charts.vobla.tech/g/tpslSignal?dark=true&dealPeriod=48&width=800&height=550&tsFrom=1581007663&tsTo=1581266863&symbol=VETUSDT&type=long&price=0.006791&timestamp=1581050863&TP=5&SL=1.75

![example](https://user-images.githubusercontent.com/18750140/74033910-97fa2600-49d0-11ea-852f-f4b636924702.jpg)

**Comment by timocov** [comment]
See #136
