### ISSUE TITLE
Some markers are not visible in range scale but all are visible when series is fit to size.

### ISSUE THREAD

**Issue by aadityatamrakar** [tradingview/lightweight-charts#323]
**Lightweight Charts Version:** 

I have used unpkg CDN link in my code.

**Steps/code to reproduce:**

[https://jsfiddle.net/6kq9jy7m/](https://jsfiddle.net/6kq9jy7m/)

**Actual behavior:**

Markers should be visible all the time. 

**Expected behavior:**

belowBar Markers are only visible when series data is fit to content.

**Screenshots**

![Screen Shot 2020-02-09 at 1 25 06 AM](https://user-images.githubusercontent.com/11058559/74091348-5bb3ec00-4adc-11ea-9813-48e483fc4b58.png)

![Screen Shot 2020-02-09 at 1 24 57 AM](https://user-images.githubusercontent.com/11058559/74091350-6078a000-4adc-11ea-82ae-6d31cf83c2e1.png)

**CodeSandbox/JSFiddle/etc link:**

[https://jsfiddle.net/6kq9jy7m/](https://jsfiddle.net/6kq9jy7m/)

**Comment by aadityatamrakar** [comment]
I checked the issue by changing color, placement but still one type of markers is showing but another type of markers is not showing. 

Please check, I have shared jsfiddle link also with this issue.

**Comment by aadityatamrakar** [comment]
I think there is some issue with the time of the marker.

I tried sorting markers with time ascending then called setMarkers function. 

Now all the markers are working fine.

**Comment by timocov** [comment]
We're planning to add run-time checks for such issues #315.

**Comment by davidrot** [comment]
@aadityatamrakar Thank you for telling the fix. I've found this issue also in my application and could fix the missing markers by sorting the array. 👍 :)
