### ISSUE TITLE
Displaying text above lines or in specific places.

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#325]
Good day.
Is it possible to display some text above the lines or in certain places on the chart or to make callouts with the text?

The example below:
![Снимок экрана от 2020-02-11 09-37-59](https://user-images.githubusercontent.com/18750140/74215887-164e1500-4cbc-11ea-81aa-74944074d3b5.png)

**Comment by timocov** [comment]
Is that related to #278?

**Comment by Altyair** [comment]
relative. but still, I did not find such an implementation as in my screenshot. is it possible?

**Comment by timocov** [comment]
You can send your suggestions to #278. As you can see it's closed for now so no, it's impossible right now :)

**Comment by ProgrammingLife** [comment]
This feature really would be useful!
