### ISSUE TITLE
Is there any chance to load plot with exactly scale by time? (auto scale by time)

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#327]
I want to load my line series with auto scale feature by time: from time1 (at the left side of the window) and to time2 (at the right side).
Something like timeframe (one month, one week) but I want to scale it to the whole window size automatically.
Is it possible?

**Comment by timocov** [comment]
You can use `setVisibleRange` method https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#setvisiblerange to change visible range.
