### ISSUE TITLE
Bug with lineSeries exists in 1.2.1 but not exists in 1.0.0. Or a feature?

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#332]
I draw two line series. The first one is shorter than the second. It works as expected in 1.0.0 but doesn't work in 1.2.1. When I use 1.2.1 I see my horizontal line starting from the start (left border) but I don't have such data there. Look:
1.0.0 works as expected (short horizontal line): https://jsfiddle.net/bw64j7p3/1/
1.2.1, bug (horizontal line starting from the start): https://jsfiddle.net/bw64j7p3/2/

But if you reorder line series and you will place my "short line" (in the code) after adding main line serie - that will work fine but I need exactly that line order. I need to have a short line on top of the main line series.

**Maybe this issue is related to:** https://github.com/tradingview/lightweight-charts/issues/329#issuecomment-585369634 ?

**Comment by timocov** [comment]
@ProgrammingLife can you please test it with fixes from #330?

**Comment by ProgrammingLife** [comment]
It doesn't work also. (works the same as 1.2.1 with a bug).
My steps were:
`
git clone "https://github.com/tradingview/lightweight-charts.git"
cd gits/lightweight-charts
npm i
npm run tsc && npm run rollup && npm run build
... built without any errors ...

...in html:
<script src="gits/lightweight-charts/dist/lightweight-charts.standalone.development.js"></script>
`

**Comment by kirchet** [comment]
@ProgrammingLife, you should first switch to the branch several_non_regular_series_fix

```
git clone "https://github.com/tradingview/lightweight-charts.git"
git fetch
git checkout several_non_regular_series_fix
```

**Comment by ProgrammingLife** [comment]
@kirchet oh sorry, I didn't know it :) Yeah, now it works as expected without any bugs!

**Comment by timocov** [comment]
@ProgrammingLife Great! I'm going to close this issue in favor to #321.
