### ISSUE TITLE
How to reset (or to fit) a priceScale?

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#333]
I didn't find any mention in docs on how to reset (or to fit) a priceScale. I found only: `chart.timeScale().fitContent();` but how to fit a plot by priceScale after resizing it?

**Comment by timocov** [comment]
Try to enable `autoScale` option https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#price-axis.
