### ISSUE TITLE
Visible time range should have bars count of the space from left/right

### ISSUE THREAD

**Issue by nilsenpaul** [tradingview/lightweight-charts#335]
What I tried to do, is display a 1 day chart (with only the data for one day), and then load more data if a user zooms out (or more specific data if a user zooms in, but that's not the problem here).

In order to do that, I'd need to know the timestamps for the new (after scroll) boundaries of the chart:

![Schermafbeelding 2020-02-17 om 08 55 22](https://user-images.githubusercontent.com/6794819/74634316-e42d2f00-5163-11ea-91a9-fd4082b1f260.png)

There may be a way to get that, but I didn't find it yet.

**Comment by timocov** [comment]
We can't provide timestamps for spaces from left and right (because we can't approximate them), but I think we can provide offsets _in bars_ from right and left.

**Comment by timocov** [comment]
Actually right bars count might be taken from https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#scrollposition - if the value is positive - it's exactly offset from the right :)

**Comment by timocov** [comment]
As one of possible solutions I'd suggest to add 2 fields to [`TimeRange`](https://github.com/tradingview/lightweight-charts/blob/e0e1e2c10d634745187179abf86a5288a14998e9/src/api/itime-scale-api.ts#L7-L10) interface with bars before and bars after count and fill them in every place (I can't tell you for sure the names of that properties, but it might be something like `barsCountBefore`/`barsCountAfter` or just `barsBefore`/`barsAfter`, @tradingview/lightweight-charts-ios-maintainers any thoughts?).

**Comment by gkaindl** [comment]
I don't want to hijack this issue, but since this functionality would be quite crucial for me as well, I'd like to implement it and file a pull request, but as per CONTRIBUTING.md, I wanted to make sure that this is welcome (the issue doesn't have the "help wanted" tag).

Adding `barsBefore / barsAfter` sounds like a viable approach to me, or is there a better proposal? The calculations are already available and used internally, so it's really more or less a matter of exporting them into the public API.

Additionally, I think it'd also make sense to introduce a method to query the chart object for the amount of bars it can currently display at most in the viewport (based off of `width` and `barSpacing`).

My use-case would be to determine the amount of data to load up-front in order to fill the chart viewport completely when displaying it, then subscribing to the timeScale change event to dynamically load additional chunks while the user scrolls or zooms the chart.

**Comment by timocov** [comment]
> Adding barsBefore / barsAfter sounds like a viable approach to me, or is there a better proposal?

@kirchet @eugene-korobko @ezhukovskiy any thoughts? Sounds good for me too.

> Additionally, I think it'd also make sense to introduce a method to query the chart object for the amount of bars it can currently display at most in the viewport (based off of width and barSpacing).

Possibly, but I think we need to separate that features and don't mix them into 1 PR. You can create another issue for that and we'll discuss it there 🙂.

**Comment by kirchet** [comment]
> any thoughts?

Looks good

**Comment by timocov** [comment]
Ok then, @gkaindl if you wish you can get this issue to implement it 🎉

**Comment by gkaindl** [comment]
Fantastic, thanks! I'll get to it this weekend then.

I'll also explore my second idea/need (how many bars to load to fill the viewport of a fresh chart) a bit more and open a separate issue for it, so it can be done in an independent pull request.

**Comment by timocov** [comment]
@gkaindl if you'll need any help with the fixes - feel free to ask here or in discord (or even in PR's draft...).

**Comment by gkaindl** [comment]
Okay, I've implemented the changes in this branch: https://github.com/gkaindl/lightweight-charts/tree/335-bars-before-after

Putting more thought into it, I opted to introduce a new type `TimeRangeWithBars` that extends `TimeRange` for the `getVisibleBars()` method, as well as the visible range change callback – My rationale is that `TimeRange` is also used in other places, most notably `setVisibleRange()`, which is a public API. If we add the new fields as optional fields on the `TimeRange` type, we would have to describe it in the docs that those fields would only be set in the callback and in the return value of `getVisibleRange()`, but don't play a role in `setVisibleRange()`. That might be confusing to users, and I think doing it this way communicates the behavior more clearly (e.g. the new fields are not used in `setVisibleRange()`, and in the return value of `getVisibleRange()`, they are always present). Also, extending `TimeRange` to `TimeRangeWithBars` should still make sure that current user code doesn't break.

Also, I noticed with `nyc` that `time-scale.ts` currently has no test coverage, so I haven't implemented a test for now.

Please let me know what you think!

**Comment by timocov** [comment]
Ooops, sorry for the delay @gkaindl. I've started to write reply but something happened and then weekend has been started unexpectedly 😂 

> My rationale is that TimeRange is also used in other places, most notably setVisibleRange(), which is a public API

I think this would be good improvement to allow to specify barsBefore/barsAfter in setVisibleRange (I guess it might be useful for someone).

> Also, I noticed with nyc that time-scale.ts currently has no test coverage, so I haven't implemented a test for now.

Yeah, we don't have unittests for it, but I hope we can try to test it with e2e tests.

I just noticed that you already created the PR, so let's continue there.

**Comment by timocov** [comment]
## Proposal of feature

1. Don't change nor `TimeScaleApi.getVisibleRange` or `TimeScaleApi.setVisibleRange` - they will still work with _time_ range (e.g. with "data", not indexes).

1. Move `subscribeVisibleTimeRangeChange` and `unsubscribeVisibleTimeRangeChange` to `TimeScaleApi` (to make it consistent - see below) (yeah, this is breaking change, but this PR will be in 3.0 release, so breaking change looks OK here).

1. Add 4 methods to the `TimeScaleApi`:

	- `getVisibleLogicalRange` - returns object with the new type `LogicalRange` with properties `from` and `to` of the new nominal type `Logical`
	- `setVisibleLogicalRange` - sets passed `LogicalRange` object as current visible range
	- `subscribeVisibleLogicalRangeChange` - allows you subscribe on visible range changed (similar to `subscribeVisibleTimeRangeChange`, but provides `LogicalRange`)
	- `unsubscribeVisibleLogicalRangeChange` - unsubscribe from indexes range updates (similar to `unsubscribeVisibleTimeRangeChange`)

	The advantages of this new API are that it 1) provides you symmetric API to get/set visible range 2) allows you set visible range with "empty spaces" from left/right.

1. Add the new method `barsInLogicalRange` into `SeriesApi`, which have the only one argument of type `LogicalRange` and return object with the following properties (I guess we can call it something like `BarsInfo`, but I assume that there might be more suitable name) filled for passed argument:

	- `from`, type `TimePoint`
	- `to`, type `TimePoint`
	- `barsBefore`, type `number`
	- `barsAfter`, type `number`

	This method is pretty similar to what we currently have in the PR in method `TimeScaleApi.getVisibleRange`, but for the only one series. This will allow you know how much bars before/after are for every series separately, and also "convert" indexes to series' times (series could have different sets of the data).

/cc @gkaindl I hope I don't miss anything 😂

**Comment by gkaindl** [comment]
Haha, yes, that seems exhaustive – I don't think anything is missing! 🙂
