### ISSUE TITLE
Get series data time range

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#336]
**Is your feature request related to a problem? Please describe.**

From paulverheul on discord

>Hi all! Just a quick question ... what I'm trying to do is load a chart with the data for a day, and then load more data when users zoom out. In order to do this, I need the date/time for the left most chart boundary. Is there a way to get this? I expected the VisibleTimeRangeChange event would be of help, but that only return the time range of the data in the chart, not the time range of the complete chart.

**Describe the solution you'd like**

Add method `series.getDataRange()` to get most left (past) and right (recent) time from series data,
and the return value should be similar to `chart.timeScale().getVisibleRange()`

**Additional context**

**Comment by timocov** [comment]
I guess it's #335, isn't it?

**Comment by SuperPenguin** [comment]
> I guess it's #335, isn't it?

Nope, this one is to get the actual timerange of the data from certain series regardless of what the viewport see.
For example if I have 2 year of daily data and set it to series, the viewport initially maybe only show about a month of data, the `series.getDataRange()` basically return the range of the data like
```js
var data = [];
data.push({ time: '2018-02-18', value: 1234 });
data.push({ time: '2018-02-19', value: 1234 });
// ...
// more data here~
// ...
data.push({ time: '2020-02-17', value: 1234 });
data.push({ time: '2020-02-18', value: 1234 });

series.setData(data);

console.log(series.getDataRange()); // output: { from: '2018-02-18', to: '2020-02-18' } the real series data range
console.log(chart.timeScale().getVisibleRange()); // output: { from: '2020-01-18', to: '2020-02-18' } only viewport see
```

**Comment by SuperPenguin** [comment]
![image](https://user-images.githubusercontent.com/1574722/74739732-1174fc80-528c-11ea-80e9-3b8e5dffda30.png)
