### ISSUE TITLE
time data format including HH:MM:SS

### ISSUE THREAD

**Issue by kozillla** [tradingview/lightweight-charts#34]
Thanks for a great library!

I'm trying to display last 24h market data, however I can't find any documentation how time should be formatted, have tried something like :

lineSeries.setData([
    { time: '2019-04-11 10:14:19', value: 80.01 },
    { time: '2019-04-11  11:16:20', value: 96.63 },
    { time: '2019-04-11  12:38:10', value: 192.63 },
]);

however it does not work,
How to format correctly time to display data set within the same day?

kozilla

**Comment by eugene-korobko** [comment]
You should use timestamp values
please refer
https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md

**Comment by eugene-korobko** [comment]
[Here](https://jsfiddle.net/TradingView/bmL0vont/) is a sample for such case

**Comment by kozillla** [comment]
@eugene-korobko, works Perfectly!
Thanks for going back to me!
