### ISSUE TITLE
Displaying annotation with text above lines or candlestick in specific places on button click

### ISSUE THREAD

**Issue by HighBreedTech** [tradingview/lightweight-charts#348]
Hello please i have tried so hard to come up with annotation in a point using time and value to position it
Example when a button is clicked i want eg: $2000 to be fixed at the exact point where the graph is before the button click in a graph  

Let me explain better using Screenshot

i have tried this with my realtime data and it shows on first initiation and disappear after first load

i was thinking of using this magic

$('.play').click(function(){
   lineSeries.setMarkers([
    {
        time: CurrentTime(),
                position: 'aboveBar',
                color: 'yellow',
        shape: 'arrowDown',
    }
]);
}); 

all my plans failed, i don't know how i could explain this please

check here for my code  example i just need help i have zero knowledge about this whole Library
https://codepen.io/highbreedtech/pen/xxGRrYx

![WhatsApp Image 2020-02-18 at 3 22 47 PM](https://user-images.githubusercontent.com/21047633/75077140-307cc400-5502-11ea-8a4f-970ac648b05e.jpeg)
![WhatsApp Image 2020-02-18 at 3 26 27 PM](https://user-images.githubusercontent.com/21047633/75077146-32df1e00-5502-11ea-85ca-c9a10295c750.jpeg)

**Comment by HighBreedTech** [comment]
I Want The Annotation Static on the spot without moving with the line and i should be able to have as much as possible annotations per my new button click if i could get the one exactly on my screenshot or any related one that wrk exactly and perfectly i will be glad.

thanks in advance.

**Comment by HighBreedTech** [comment]
@timocov
@nikitamarcius
@karunkrishna

or if something related to this is not possible what of you checking 
https://codepen.io/highbreedtech/pen/xxGRrYx

that page added arrow but can't allow multiple arrow and also the arrow moves to follow the line instead of the arrow to be static at the point in which it was before i added it on my button click?

please help me i have spent days on this i could not resolve this am just new totally to this Api please any help i will be glad.

Thanks.

**Comment by HighBreedTech** [comment]
if we can't archive that priceTag what about adding Up and Down arrow to Live/Real Time data moving in milliseconds?

i tried it via my code here https://codepen.io/highbreedtech/pen/xxGRrYx 
but it is not marking it static it is following the new data i want it to insert new arrow anytime i click on my button and make the arrow static at that point i am using Timestamp for my data please help me check on my pen, what i am expecting is attached now.
![Screenshot from 2020-02-22 07-57-16](https://user-images.githubusercontent.com/21047633/75088321-f0daca00-554b-11ea-9bc8-f2fdd02c9ef2.png)

**Comment by HighBreedTech** [comment]
@kirchet
@subzey
i need serious help, this is urgent

**Comment by HighBreedTech** [comment]
@eugene-korobko @ezhukovskiy @Nipheris

i need serious help please.

**Comment by nikitamarcius** [comment]
@HighBreedTech https://github.com/tradingview/lightweight-charts/issues/348#issue-569218615 

**I see a few questions.** 

1. price fixing when pressed by the appearance of annotation
2. https://user-images.githubusercontent.com/21047633/75077146-32df1e00-5502-11ea-85ca-c9a10295c750.jpeg getting prices for later use in create order module

**Decision:**

1. Appearance of annotation not implemented in the lib. Only receiving data when hovering or clicking on a schedule. Then display the data in some kind of `div` aka `.legend`

```javascript
chart.subscribeCrosshairMove(function(param) {
    console.log(param.hoveredMarkerId);
});

chart.subscribeClick(function(param) {
    console.log(param.hoveredMarkerId);
});
```

2. In JS frameworks there is a certain storage of component states. By clicking, put the data into this storage, then pull it out.
   * VueJS - https://vuex.vuejs.org/guide/
   * ReactJS - https://redux.js.org

**Comment by HighBreedTech** [comment]
@nikitamarcius 

Please take a look at 
https://codepen.io/highbreedtech/pen/xxGRrYx 

how do i do it to work whenever i make new click to add more Marker on real data, marker are not  adding more when i use real data, it only adds on static data if you check https://codepen.io/highbreedtech/pen/xxGRrYx you wil see what am saying.

check the screenshot to see what exactly i wanted as alternative
![Screenshot from 2020-02-22 07-57-16](https://user-images.githubusercontent.com/21047633/75112437-24991b00-5644-11ea-8a9b-d423503b6d54.png)

just for me to add marker to realtime Data and i should be able to add much more below is the code i used

**JS CODE**

function CurrentTime(){
   return Math.round(new Date().getTime()/1000); 
}

$('.playHigh').click(function(){

   lineSeries.setMarkers([
    {
        time: CurrentTime(),
                position: 'belowBar',
                color: 'green',
        shape: 'arrowUp',
    }

]);
  alert("Make Drawing for Higher at time "+ CurrentTime());
});
$('.playLow').click(function(){

   lineSeries.setMarkers([
    {
        time: CurrentTime(),
                position: 'aboveBar',
                color: 'red',
        shape: 'arrowDown',
    }

]);
  alert("Make Drawing for Lower at time "+ CurrentTime());
});

this code seems not working i wish if i could get a live help or any as well, i just want example of marker to realtime moving data i will be okey with it thanks very much to help me on this code.

Real is my live Realtime data graph that could not work properly i want it to add new marker anytime i click the button https://codepen.io/highbreedtech/pen/xxGRrYx

**Comment by nikitamarcius** [comment]
> how do i do it to work whenever i make new button click it should add more Marker on real data,

This is not a question of the library, but of the reactivity of your code. I don’t use jquery, I don’t understand it. 

Question by code - a question for you. The easiest way to achieve reactivity is to use the JS framework.

My advice, forget about jquery forever. It's a bad experience

**Comment by HighBreedTech** [comment]
@nikitamarcius  

oh thanks as much i will try that.

> @HighBreedTech
> 
> > how do i do it to work whenever i make new button click it should add more Marker on real data,
> 
> This is not a question of the library, but of the reactivity of your code. I don’t use jquery, I don’t understand it.
> 
> Question by code - a question for you. The easiest way to achieve reactivity is to use the JS framework.
> 
> My advice, forget about jquery forever. It's a bad experience
> 
> As part of your implementation, do the following:
> _When adding a new marker, delete all previous ones and redraw the marker's array_

**Comment by timocov** [comment]
Hi @HighBreedTech,

Sorry for delay. Do you have any question at the moment I may help you with? Looks like @nikitamarcius answer on all your questions? (thank you Nikita!)

_I want to just note that if nobody answering your question/issue doesn't mean that it's missed or ignored. It also doesn't mean that you need to ping everybody you seen in other issues to help you. There might be a lot of reasons, the simplest and more obvious one is holidays or even weekend 🙂. We're really want to help with any question about the library, but we just can't guarantee you, that we'll answer the issues in minutes or even hours (even if your questions is urgent for you or somebody else), but we'll our best to help everyone. Just wait some time, and if no help is found (maybe several days) - you can ping maintainers/contributors/some active person in issue tracker. Just respect other persons you've mention here (I'm sure some of them don't want to get any notifications from that thread and now they need unsubscribe from the thread somehow) 🙏._

**Comment by HighBreedTech** [comment]
ok @timocov  thanks for your Reply

I Have a real Data from Api i am trying to Add Either LineSeries or PriceLine + Label or Use Just setMarkers but when i use setMarkers with Real Time data and use Timestamp as time and set value Noting works, if i use Timestamp - 100 it adds new marker but if i try to add new it adds above the old one i don't know what am getting wrong,actually i am adding new Marker on Button click so at the exact time a button is click Add new marker and all markers Adds on top of each other and if i tried to Wait couple of seconds before clicking the button Marker stops Adding,

Also if i add new LineSeries to Real time data after button is clicked and use Title with it the title comes Like Many times 

hmm this gets me Frustrated and i deleted both LineSeries and Marker and tried adding PriceLine but yet priceLine does not support Title and all i tried was failure, i ended up using Just a Line of priceLine without Title which is not good for Trading Platform where high and low is needed, Indicator or Marker is always needed but i get no solution t my problem and had no choice.

I won't mind if i can get Helped at least just to Add an Indicator or PriceLine with a Label/Title at a specific time and this Label should set exactly at the time where the time is added this would have been a nice Function and people will love it,

Priceline with Label/Title map to price at Horizontal and Labeled to time at Vertical part thanks very much i will send more screenshots.

**Comment by timocov** [comment]
> use Timestamp as time and set value Noting works, if i use Timestamp - 100 it adds new marker but if i try to add new it adds above the old one i don't know what am getting wrong

> time: CurrentTime(),

Did you try to use the latest bar's time instead?

> Also if i add new LineSeries to Real time data after button is clicked and use Title with it the title comes Like Many times

Not sure that understand you. Can you provide jsfiddle-like example for that?

> but yet priceLine does not support Title 

Can you create a separate feature request for that please?

**Comment by HighBreedTech** [comment]
>> Did you try to use the latest bar's time instead?
> How do i use that latest bar time?

>> Can you create a separate feature request for that please?
> I just created that at https://github.com/tradingview/lightweight-charts/issues/357 now take a look to see Example and more.

**Comment by timocov** [comment]
> How do i use that latest bar time?

You passed bars to the library, so you can save the latest bar's time.

**Comment by HighBreedTech** [comment]
> > How do i use that latest bar time?
> 
> You passed bars to the library, so you can save the latest bar's time.

Can i have example code from like JsFiddle?
i don't have idea about this please any example code?

**Comment by timocov** [comment]
@HighBreedTech your code doesn't work because you pass string as series' value here `var randomNum = (Math.random() * 0.9).toFixed(8);`. `toFixed` return a string, not a number. If you wrap this in `Number` (var randomNum = Number((Math.random() * 0.9).toFixed(8));` it will work as you might expect.

**Comment by HighBreedTech** [comment]
> @HighBreedTech your code doesn't work because you pass string as series' value here `var randomNum = (Math.random() * 0.9).toFixed(8);`. `toFixed` returns a string, not a number. If you wrap this in `Number` (var randomNum = Number((Math.random() * 0.9).toFixed(8));` it will work as you might expect.

OMG thanks @timocov  it worked like magic now huh.

this Api is the Best huh, remaining title in PriceLine.

+100 to @timocov

**Comment by timocov** [comment]
> remaining title in PriceLine.

Ok, if you have something about that, just write it in #357.

**Comment by SankaraRJ** [comment]
what type of charting library is this
