### ISSUE TITLE
[Feature] Footprint data for candlesticks / cluster analysis

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#350]
Footprint data for candlesticks is really useful thing. It's an ability to draw stepped volume for each candlestick. That's what I'm talking about:
![](https://wp.fxssi.com/wp-content/uploads/2019/11/footprint-6.png)

**Comment by timocov** [comment]
Are you talking about horizontal histograms, right (like volume profile)?

**Comment by ProgrammingLife** [comment]
@timocov, yes!

**Comment by timocov** [comment]
@ProgrammingLife Where?) Can you provide some examples please?

**Comment by ProgrammingLife** [comment]
@timocov I'm talking exactly about those horizontal histograms as shown above...

**Comment by timocov** [comment]
Ah, sorry, I just confused the issues with #351...

I'm not sure, but I think that we didn't plan to add such stuff to the lightweight charts. @ezhukovskiy could you please help with that?

**Comment by ezhukovskiy** [comment]
Hi, it is not the use case of the Lightweight Charts (we really want it to stay lightweight). But we plan to add such kind of displaying to the Advanced Technical Analysis Library.
