### ISSUE TITLE
Remove series then scroll to right after not working.

### ISSUE THREAD

**Issue by nakcyber** [tradingview/lightweight-charts#355]
Hi, lightweight-charts team
I am facing an issue with lightweight-charts.

**Lightweight Charts Version:** 1.2.2

**Steps/code to reproduce:**

- AddLineSeries when click on button 2001 , 2002 ,2003   to add more series.
- Click a button following step on button 2003 and button 2002 to remove selected series.
- Scroll chart to the end of the right side after removing a series.

**Actual behavior:**
Show Uncaught Error: Value is null;

**Expected behavior:**
Don't show Uncaught Error: Value is null;

**Screenshots**
https://drive.google.com/file/d/1Ws0Q2y6md0ZxxpaRLrolUuBbBiZbYhup/view

**CodeSandbox/JSFiddle/etc link:**

https://stackblitz.com/edit/js-eivupz?file=index.js

**Comment by timocov** [comment]
> AddLineSeries when click on button 2001 , 2002 ,2003 to add more series.

Looks like nothing happened when I click on that buttons.

**Comment by timocov** [comment]
Ah ok I got it, just removed `window.addEventListener('load', function () {` wrapper.

**Comment by timocov** [comment]
Looks like this happened only in case of subscription on `subscribeVisibleTimeRangeChange`.

**Comment by timocov** [comment]
Related to #270
