### ISSUE TITLE
Add title option to createPriceLine

### ISSUE THREAD

**Issue by HighBreedTech** [tradingview/lightweight-charts#357]
Priceline to allow people to set Label/Text and set Text/Label alignment eg: Right, Left, Up, Down and allow color for the title/label if possible to set the length either 100% to fill graph or even 50% to start from center of graph just to look almost exactly like the attached image below, this will be great and can be compared to other Professional Graph Api.

@timocov
@nikitamarcius

![Screenshot from 2020-02-25 16-55-57](https://user-images.githubusercontent.com/21047633/75264583-ea6c7c80-57ef-11ea-9427-0d681bcdc3fc.png)

**Comment by HighBreedTech** [comment]
Priceline to allow people to set Label/Text and set Text/Label alignment eg: Right, Left, Up, Down and allow color for the title/label if possible to set the length either 100% to fill graph or even 50% to start from center of graph just to look almost exactly like the attached image below, this will be great and can be compared to other Professional Graph Api.

![Screenshot from 2020-02-25 16-55-57](https://user-images.githubusercontent.com/21047633/75264583-ea6c7c80-57ef-11ea-9427-0d681bcdc3fc.png)

**Comment by timocov** [comment]
@HighBreedTech may I ask you don't tag people in every message please? Thank you in advance!

**Comment by christose** [comment]
@timocov if this is not going to be ready soon, can you pretty please provide me with some guidance about which classes I should look into and try to implement this?
This could save me time as I am trying since yesterday to find a starting point but the project is huge and I haven't figured it out yet...

**Comment by timocov** [comment]
> provide me with some guidance about which classes I should look into and try to implement this?

@christose yes, of course!

1. First, you need to add the new property to types for price line's options https://github.com/tradingview/lightweight-charts/blob/master/src/model/price-line-options.ts and update docs https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#createpriceline
1. Then you need to add the default value for the new property https://github.com/tradingview/lightweight-charts/blob/master/src/api/options/price-line-options-defaults.ts, I guess it should be an empty string
1. Then you need to use that property in https://github.com/tradingview/lightweight-charts/blob/master/src/views/price-axis/custom-price-line-price-axis-view.ts#L22-L49 and update `paneRendererData` (at least you need to set `visible` to `true` and set `text` passed via options), as example you can see at https://github.com/tradingview/lightweight-charts/blob/master/src/views/price-axis/series-price-axis-view.ts#L18-L55, I think you should get something similar (don't forget to update `borderColor` property).
1. _(the following part could be a bit tricky)_ Now you've changed `PriceAxisView` (it's a view for price axis), but `title` should be rendered on a pane. To achieve rendering a text on pane, you need to create an instance of `PanePriceAxisView` in `CustomPriceLine` (you can see how it's created in `series.ts` - you need to do it in the same way) and return that instance from `paneView` method.
  Note that `this._priceLineView` should be returned as well, so I guess you need to rename `paneView` method to `paneViews` and change the returned type to `readonly IPaneView[]`.
1. Add graphics tests. It should be easy though - see https://github.com/tradingview/lightweight-charts/tree/master/tests/e2e/graphics#writing-new-test-case.

That's it! Tell me if you'll have any question.

**Comment by christose** [comment]
@timocov Thanks a lot for the detailed instructions. I appreciate it. I start right away and I will let you know for the progress.

**Comment by christose** [comment]
@timocov I have finished coding, I wrote the test case but it seems I am doing something wrong with the runner.js command. 
I', not sure what are the golden standalone and test standalone paths and that's why I get the following error I guess "Error: ReferenceError: LightweightCharts is not defined"

**Comment by timocov** [comment]
1. `git stash` (if you didn't commit changes yet) or `git switch master` (if you did)
1. `npm run build`
1. `mv dist/lightweight-charts.standalone.development.js dist/golden.js`
1. `git switch BRANCH_NAME` (if you have one with committed changes) or `git stash pop` (if you didn't have)
1. `npm run build`
1. `node /tests/e2e/graphics/runner.js dist/golden.js dist/lightweight-charts.standalone.development.js`

Something like that.

**Comment by christose** [comment]
Yes I created a branch with the ticket number. Thanks a lot, I'm doing it now!

**Comment by christose** [comment]
OK, it seems some other tests contain some errors. 115 Passing, 5 failings. My test has passed. But I don't see it's a folder inside gendata, I see the 5 folders of the failed tests, is that the expecting behavior ?

**Comment by timocov** [comment]
> OK, it seems some other tests contain some errors. 115 Passing, 5 failings. My test has passed. But I don't see it's a folder inside gendata, I see the 5 folders of the failed tests, is that the expecting behavior ?

Yeah, folders with screenshots/pages are generated only in case of fail. You can push your changes and make PR and we'll continue there, to avoid spamming this issue :)

**Comment by christose** [comment]
Ok sure :)
Permission denied tho, I need access to push I guess :)

**Comment by timocov** [comment]
@christose you need to fork the repo, change remotes, push it to your repo and create PR.

https://guides.github.com/activities/forking/
