### ISSUE TITLE
Negative values on Price Axis

### ISSUE THREAD

**Issue by sachetsingh77** [tradingview/lightweight-charts#360]
On our implementation we need to remove negative numbers on price axis (since price cannot be negative). looking at docs, the closest properties we could find is scalesProperties in overrides section. minmov/pricescale is also about formatting, rather than startingpoint/range. how do we specify starting value on price axis to be say Zero. thank you.

**Comment by timocov** [comment]
Can you please provide a bit examples/screenshots what do you mean? What chart's behavior you've expected when an user zoom out price axis?

**Comment by sachetsingh77** [comment]
[image: Screen_Shot_2020-02-19_at_3.50.32_PM.png]
Hi -- Pls see this screenshot. Also, the chart can be seen at
https://dev.leverj.io. This is seen when we maximize the window. we just
wanted to know if there's a way to specify the range or lower bound (where
we could specify zero)

**Comment by timocov** [comment]
> Pls see this screenshot

Looks like it didn't attached.

> Also, the chart can be seen at dev.leverj.io. 

There is charting library, not lightweight-charts.

**Comment by sachetsingh77** [comment]
[image: Screen_Shot_2020-02-19_at_3.50.32_PM.png]

Yes, we use JS API for chart widget. Attached again. thank you.

[image: Screen_Shot_2020-02-19_at_3.50.32_PM.png]

**Comment by timocov** [comment]
![image](https://user-images.githubusercontent.com/3112183/75337092-62dd4700-589d-11ea-8a91-eb5688f5ceed.png)

It still doesn't work.

> we use JS API for chart widget

Does it mean that you use charting_library, not lightweight-charts?

**Comment by timocov** [comment]
Hey @sachetsingh77, do you have updates?

**Comment by sachetsingh77** [comment]
Hi

We looked at other implementations also, and it looks like the screen is
"centered" around the data. On scrolling, we do see negative numbers.

Thanks

**Comment by timocov** [comment]
> We looked at other implementations also, and it looks like the screen is
"centered" around the data

Yes, exactly! That's how autoscaling works.

> On scrolling, we do see negative numbers.

Why for you it's a problem>

**Comment by sachetsingh77** [comment]
Since price can never be negative, we wanted to explore if a floor could be
put in place. Auto scaling is an internal algo of the tool, and as an end
user of the widget/api, our expectation was to find a way to customise the
price axis range.

Thanks

**Comment by timocov** [comment]
We can add a way to set price range to the price scale, but you'll need to disable ability to change the price range via options. But even in this case there might be a case when an user scrolls to the history and will see nothing because of fixed price range. If you have "static" charts, it might work for you. But I don't think that we'll plan to customize behavior of autoscaling for now.

**Comment by timocov** [comment]
Related #360

**Comment by timocov** [comment]
@sachetsingh77 Looks like we'll kind of fix the issue in #392. We'll add something like `autoscaleInfo` option to override default series' autoscale info getter so you are able to override it and just return values higher than 0. But it'll work in autoscale only. If an user change the price range manually, it'll be able to see negative values.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by anshul-kai** [comment]
`autoscaleInfoProvider` doesn't work well when margins are present. It still shows negative numbers on the price scale.

```
autoscaleInfoProvider: () => ({
        priceRange: {
          minValue: 0,
          maxValue: 200,
        },
      }),

scaleMargins: {
      top: 0.15,
      bottom: 0.2,
},
```
