### ISSUE TITLE
bad plot using other series apart from LineSeries with Real time live data

### ISSUE THREAD

**Issue by HighBreedTech** [tradingview/lightweight-charts#361]
I have tried LineSeries it worked fine with real time data, but me using Bar,Area,Histogram, CandleSticks i get weird output like below screenshots.

please can anyone suggest what am ding wrong here?
@timocov 

![Screenshot from 2020-02-27 11-33-40](https://user-images.githubusercontent.com/21047633/75436804-6af8bd80-5955-11ea-9565-7eba3a926e6d.png)
![Screenshot from 2020-02-27 11-36-46](https://user-images.githubusercontent.com/21047633/75436831-78ae4300-5955-11ea-8204-452f2f94e4f1.png)
![Screenshot from 2020-02-27 11-38-30](https://user-images.githubusercontent.com/21047633/75436968-c2972900-5955-11ea-8ea3-a9099d25ba04.png)
![Screenshot from 2020-02-27 11-40-03](https://user-images.githubusercontent.com/21047633/75437074-f4a88b00-5955-11ea-9214-f5ea502c4c18.png)

**Comment by timocov** [comment]
Please check your data, I guess the problem is there. Values must be numbers (not strings), open/high/low/close values should be filled according the bar's data, every bar should be different object (not the same ref).

**Comment by HighBreedTech** [comment]
> Please check your data, I guess the problem is there. Values must be numbers (not strings), open/high/low/close values should be filled according the bar's data, every bar should be different object (not the same ref).

Did you see candle Stick too? all are not going well i don't know see below i set TIME then OHLC and yet @timocov  check below

![Screenshot from 2020-02-27 12-58-16](https://user-images.githubusercontent.com/21047633/75443011-dac07580-5960-11ea-844d-5a5fd8de0392.png)

**Comment by timocov** [comment]
Yes, I've took a look at all your screenshots, but I can't tell you for sure what's going on here because I can't guess by screenshots. Can you show here the data you've provided to `setData` method? Do you have jsfiddle-like example with that problem? If you want to get help, you need to provide as much as possible information.

**Comment by HighBreedTech** [comment]
@timocov 
i guess it was just the way i handled my code, now i get it worked here https://codepen.io/highbreedtech/pen/qBdmRNy

thanks for your help
