### ISSUE TITLE
[Feature] Showing Renko charts?

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#364]
Is that possible to draw Renko charts?
At the first sight looks it's possible to draw just as usual candles but Renko chart almost has no time association. It's just one block placing after another. Looks like a custom time scale from that is used by LightweightChart for now.

UPD: Looks it's just ordered candles placing one by one without any time just sorted by its index.

![](https://www.investopedia.com/thmb/dTuTdcXRXngwj5O_rjLDHB2SM5c=/1529x899/filters:no_upscale():max_bytes(150000):strip_icc()/Renko-5c6597dec9e77c000175523b.png)

**Comment by timocov** [comment]
We don't plan to add custom chart style to display Renko charts. If you'll see at www.tradingview.com/chart or even charting-library.tradingview.com - we also have "time scale" for Renko charts, but I agree that it useless here. What's your suggestion for that? Hide timescale? Something else?

**Comment by NomNomCameron** [comment]
@ProgrammingLife can you share a snippet of how you were able to add candlestick data without a `time` param? I'm unable to find anything in the docs that shows how to go about this?

**Comment by galvesribeiro** [comment]
Hello folks!

I've stumbled into the same. I know that TradeView itself makes renkos using time ranges, which is totally useless. I was expecting this chart component to not do anything in aggregating data but instead, print the datapoint the exact same way we pass data to it. 

So, is there a way to pass the candlestick data which _we_ aggregated as renkos based on the price and make the chart to _not_ aggregate it on timestamp?

Thanks!

**Comment by NomNomCameron** [comment]
@galvesribeiro read the comment I left on my question here, that's how I got it to work:
https://stackoverflow.com/questions/72339735/renko-tick-charts-with-tradingviews-lightweight-chart
