### ISSUE TITLE
Refactoring resize the chart

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#367]
https://github.com/tradingview/lightweight-charts/blob/a1c8d55e710783766d1d55a56ff296e8d5ad5642/src/gui/chart-widget.ts#L80-L91

Here we have hidpi fixes for chart's size, but that size applies in constructor only. Thus, if we'll resize the chart, we don't apply that "magic" and can get smoothing.

**Comment by eugene-korobko** [comment]
Atually, this patch is applied in the case of placing the chart inside a containing element. If the sizes are defined directly, we do not touch it, so, there is no reason to affect resize method.
Probably we have to create ResizeObserver to catch container resizing

**Comment by timocov** [comment]
> Atually, this patch is applied in the case of placing the chart inside a containing element. If the sizes are defined directly, we do not touch it, so, there is no reason to affect resize method.

What's the difference? Even we can't handle 71px width, does it matter what's the source of the that value: container's size or user defined value?
