### ISSUE TITLE
subscribeCrosshairMove seriesPrices always empty

### ISSUE THREAD

**Issue by SimonHausdorf** [tradingview/lightweight-charts#369]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**

```javascript
chart.subscribeCrosshairMove(param => {
  console.log(JSON.stringify(param));
});
```

**Actual behavior:**

```
{"time":{"day":20,"month":3,"year":2019},"point":{"x":271,"y":257},"seriesPrices":{}}
```

**Expected behavior:**

seriesPrices should display a value

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/u9c0emb5/1/

**Comment by timocov** [comment]
Afaik `seriesPrices` is a `Map` object, not just `Object`. Is it true?

**Comment by SimonHausdorf** [comment]
Thanks, will close the issue. Fixed with

```
chart.subscribeCrosshairMove(param => {
  console.log(JSON.stringify(param.seriesPrices.get(lineSeries)));
});
```

updated example: https://jsfiddle.net/oyhj3fax/
