### ISSUE TITLE
series.setMarkers requires at least one data point (Error: value is null)

### ISSUE THREAD

**Issue by Jeronimotio** [tradingview/lightweight-charts#372]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**
Try to set markers on Line series without any data points. May be other types of series are also affected.

**Actual behavior:**
Throws "Error: value is null"

**Expected behavior:**
No throw

**CodeSandbox/JSFiddle/etc link:**
https://codesandbox.io/s/blue-hill-lpn26

**Comment by brendalways** [comment]
Is there a workaround to plot markers where we have no data yet? Like in the past or in the future?

**Comment by timocov** [comment]
@brendalways I don't think so, but you can check whether the series has data or not.
