### ISSUE TITLE
Multiple series: error while trying to scroll the chart

### ISSUE THREAD

**Issue by Jeronimotio** [tradingview/lightweight-charts#373]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**
Try to scroll example chart with multiple series to the past

**Actual behavior:**
Type Error: Cannot read property 'x' of undefined

**Expected behavior:**
No throw

**CodeSandbox/JSFiddle/etc link:**
https://codesandbox.io/s/tender-golick-lj8tb

**Comment by kuamatzin** [comment]
Hi! Any fix?

**Comment by timocov** [comment]
@kuamatzin We'll fix it soon (in 3.0).
