### ISSUE TITLE
Replace const enums with enums to let use them in projects with enabled isolatedModules option

### ISSUE THREAD

**Issue by Jeronimotio** [tradingview/lightweight-charts#375]
**Is your feature request related to a problem? Please describe.**

Project templates like create-react-app use tsconfig.json with `isolatedModules: true` option. There is no support for const enums in ambient contexts (`d.ts` files). 

```
Cannot access ambient const enums when the '--isolatedModules' flag is provided.ts(2748)
```

There is no way to use `LineStyle`, `CrosshairMode`, `LineType`, `PriceLineSource` and `PriceScaleMode` in such environments.

The workaround is to use literal values for example `1` instead of `PriceScaleMode.Logarithmic`.

**Describe the solution you'd like**

It would be nice to have this enums as normal enums, or other solution which can help.

**Comment by timocov** [comment]
Actually that `const enum`s have output in JS code so importing should works in both JS and TS envs, but it looks like TS doesn't understand it so far. I'll prepare an issue for TypeScript soon.

**Comment by timocov** [comment]
Here we go https://github.com/microsoft/TypeScript/issues/37774

**Comment by timocov** [comment]
Ok, looks like we can't wait for "feedbacks" in TypeScript repo. We'll fix it from our side: https://github.com/timocov/dts-bundle-generator/issues/110.
