### ISSUE TITLE
Display only months for seasonality chart

### ISSUE THREAD

**Issue by ezhukovskiy** [tradingview/lightweight-charts#377]
![image](https://user-images.githubusercontent.com/10953908/76513277-1d0cab00-6467-11ea-9990-c2f5de0be08e.png)

Please add a way to customize the time scale labels so the only months will be displayed.

**Comment by timocov** [comment]
It requires to provide a way to customize [this code](https://github.com/tradingview/lightweight-charts/blob/a1c8d55e710783766d1d55a56ff296e8d5ad5642/src/model/time-scale.ts#L663-L701) somehow.

**Comment by timocov** [comment]
Duplicate of #226
