### ISSUE TITLE
Remove tick mark from price label

### ISSUE THREAD

**Issue by ezhukovskiy** [tradingview/lightweight-charts#378]
Currently a price label has a line in front of the text:
![image](https://user-images.githubusercontent.com/10953908/76513687-b8058500-6467-11ea-8835-f4bb1d60fe0c.png)

Please add an option to remove this line. For someone it can look like a minus.

**Comment by timocov** [comment]
Should it be the only one option to hide all tick marks at all or for every case separately (time/price axis' tick marks, labels' tick marks, cross hair, etc)?

**Comment by ezhukovskiy** [comment]
one option for all price marks should work

**Comment by AoDev** [comment]
@timocov Hello, I just faced the same issue. I don't know if you have decided to hide them all with a single option or doing it for each serie. We definitely need to be able to set this on a serie basis. Like current price is fine, but we are adding moving averages and we don't want the lines for these.

**Comment by timocov** [comment]
Hey @AoDev, do you want to have them like this, right?

![image](https://user-images.githubusercontent.com/3112183/79767387-efeacc80-8331-11ea-961b-4473abd5fbc2.png)

**Comment by AoDev** [comment]
@timocov ow, I have misunderstood this issue. What I'd like to do, is to remove the horizontal line completely, the one that marks the price. Sorry for the misunderstanding.

![remove-ma-lines](https://user-images.githubusercontent.com/1526150/79775589-c67f7000-8334-11ea-9dd8-522fe0e8e197.png)

I haven't found a setting for it [in the customization section](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md) or [line series docs](https://github.com/tradingview/lightweight-charts/blob/master/docs/line-series.md). 

I guess this should be a separate issue?

**Comment by timocov** [comment]
@AoDev see https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-line
