### ISSUE TITLE
Is there a way to set the change interval default?  In my charts saved alyout 

### ISSUE THREAD

**Issue by RyKaj** [tradingview/lightweight-charts#379]
I assume this repo is https://www.tradingview.com/. 

Is there a way part of my save layout and profile can save the my default interval  in the charts? Everytime I load y save layout I always have to maually change the interval

**Comment by timocov** [comment]
> I assume this repo is tradingview.com.

No, it's not.

**Comment by RyKaj** [comment]
Can you tell me which one is the repo

**Comment by timocov** [comment]
We don't have a repo for tradingview.com. If you have any question related to the website - please contact support on the website.
