### ISSUE TITLE
Add id to Series

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#381]
Needs to add id to series, so user can find series by id and get API instance for it. Don't forget about events with map, where keys are ISeriesApi instances.

**Comment by TomKaltz** [comment]
Is there a way to access the array of series added to the chart so that they may be removed?  Is there a way to clear all series of a chart?

**Comment by edew** [comment]
@TomKaltz 

Currently you would need to keep track of the series when you create them, then you could use the `ISeriesApi` instances to remove them from the chart.

```javascript
const chart = createChart()

const series1 = chart.createLineSeries()

const series2 = chart.createLineSeries()

// some time later...

chart.removeSeries(series1)

// some time later...

chart.removeSeries(series2)

```
