### ISSUE TITLE
[dark theme] Don't work

### ISSUE THREAD

**Issue by fernando-pascoal** [tradingview/lightweight-charts#383]
I set theme dark and not work.
```
const chartProperties = {
          width: document.body.height,
          height: document.body.width,
          theme:"dark",
          timeScale: {
            timeVisible: true,
            secondsVisible: false
          },
}
```

**Comment by qy20092011** [comment]
which docs I can see the theme option and how to set it.

**Comment by qy20092011** [comment]
> I set theme dark and not work.
> 
> ```
> const chartProperties = {
>           width: document.body.height,
>           height: document.body.width,
>           theme:"dark",
>           timeScale: {
>             timeVisible: true,
>             secondsVisible: false
>           },
> }
> ```

**Comment by qy20092011** [comment]
> I set theme dark and not work.
> 
> ```
> const chartProperties = {
>           width: document.body.height,
>           height: document.body.width,
>           theme:"dark",
>           timeScale: {
>             timeVisible: true,
>             secondsVisible: false
>           },
> }
> ```

which docs I can see the theme option and how to set it.

**Comment by timocov** [comment]
Where you've find it? We don't support themes ouf-the-box, but you might apply any custom themes via options (colors, settings, etc).

**Comment by timocov** [comment]
See https://jsfiddle.net/TradingView/6yLzrbtd/
