### ISSUE TITLE
Resize the chart not correctly render line.

### ISSUE THREAD

**Issue by nakcyber** [tradingview/lightweight-charts#385]
Hi, lightweight-charts team
I am found an issue about resizing with lightweight-charts.

**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**
 - Create chart by config.
 - Resize windows on chart.

**Actual behavior:**
The line chart renders wrong. after resize.

**Expected behavior:**
The line chart renders correctly. after resize.

**Screenshots**
https://drive.google.com/file/d/1uNLE_Vhfpvd2h0rP1YfBYlELrJ5Js-1U/view

**CodeSandbox/JSFiddle/etc link:**
https://codepen.io/piriyapong-su/pen/VwYgWmq

**Comment by timocov** [comment]
I'm afraid that's intended behaviour. When the size is too small, we adopt some time scale params (like right offset or bar spacing) to current viewport (kind of correcting) to avoid incorrect state. See https://github.com/tradingview/lightweight-charts/blob/5e328f4982675c78d8a7599a240a7d108cc84034/src/model/time-scale.ts#L583-L614.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
