### ISSUE TITLE
hi ! how do i run lightweight charts on nodejs ?

### ISSUE THREAD

**Issue by astral64** [tradingview/lightweight-charts#391]
i have nodejs v4.2.6 on ubuntu linux....

i don't know how to start running the application....

your help is much appreciated !

tal

**Comment by astral64** [comment]
okay - i saw lightweight charts require nodejs version at least v10....

i have the files for linux - of nodejs v12...

but i don't know how to install it...

**Comment by astral64** [comment]
if i try to update or upgrade the nodejs version through the terminal
it gives me this towards the end:

Errors were encountered while processing:
 linux-firmware
 initramfs-tools
 linux-image-4.4.0-150-generic
 linux-image-4.4.0-154-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by timocov** [comment]
Hi, lightweight-charts is client-side library, it could be used in the browser. I don't know whether it's possible to use it in nodejs. nodejs version in package.json in min version you could build the library and run tests for it.

**Comment by timocov** [comment]
Why do you need to run it in nodejs? What is your aim?

**Comment by astral64** [comment]
well, how do i run it in the browser ?

if i try to 'throw' files into the browser (like index.js for example) - it just shows the code...

**Comment by timocov** [comment]
I think it's better to ask such question on stackoverflow - it's doen't related to the lightweight-charts itself, you can ask such question related to anything.

https://stackoverflow.com/questions/16333790/node-js-quick-file-server-static-files-over-http

**Comment by timocov** [comment]
If you build the library locally, you can use suggestion from https://github.com/tradingview/lightweight-charts/blob/master/BUILDING.md#tips:

> If you want to play with a locally built package, you can create a debug.html page: cp debug.html.example debug.html.
