### ISSUE TITLE
Add ability to modify price scale's price range

### ISSUE THREAD

**Issue by dawood95** [tradingview/lightweight-charts#392]
**Is your feature request related to a problem? Please describe.**

Yes, I want to be able to set the price scale's min and max value displayed.

**Describe the solution you'd like**

chart.setOption({ priceScale: { min: <value>, max: <value> } })

**Comment by timocov** [comment]
Related https://github.com/tradingview/lightweight-charts/issues/360#issuecomment-596995263.

**Comment by timocov** [comment]
> chart.setOption({ priceScale: { min: , max: } })

I think it'd better to have such API in price scale itself.

**Comment by timocov** [comment]
Also, applying price range would force to disable auto scaling. Also, it can't be applied in percentage mode and should throw an error in run-time.

The open question here is what to do with overlay scales - they are always autoscaled, an user can't enable autoscale for them somehow (for non-overlay it might dbl click on price axis for instance).

**Comment by dawood95** [comment]
I think it's fair to disable the auto-scaling option if one wants to use price max and min. Currently, I'm able to scroll on the price scale to keep it fixed. 

In the meantime, is there any workaround I can use?

**Comment by timocov** [comment]
> In the meantime, is there any workaround I can use?

No. If you wish, you can try to fix it and provide PR.
