### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tolotrasamuel** [tradingview/lightweight-charts#395]
**Lightweight Charts Version:** 2.1.0

**Steps/code to reproduce:** Download code, `run npm install` then Run command `npm run test`

**Actual behavior:**

```
import { expect } from 'chai';
^^^^^^

SyntaxError: Cannot use import statement outside a module

```

**Expected behavior:**

Module should be found.

I don't know what I am missing

**Screenshots**

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
What nodejs version you use? I just checked it with clean env and everything is built fine (also, our CI it looks like works fine too which also have clean env).

**Comment by timocov** [comment]
I guess it might happen for instance if ts-node isn't registered to load files in nodejs (it's done by mocha's `require` option).

**Comment by tolotrasamuel** [comment]
I use node 12.13.1. Should I use some other version ?

**Comment by timocov** [comment]
I use v13.10.1, but in CI we use [v10](https://github.com/tradingview/lightweight-charts/blob/0f01a2fcd8bdc7f3430212168082cd4ad5670fd3/.circleci/config.yml#L35) as min supported to build the library version.

Ok, what OS you have? Can you run node and execute the following `require('ts-node/register')`? Does it work without errors?

**Comment by tolotrasamuel** [comment]
I am using Windows 10
```
$ node
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> require('ts-node/register')
{}

```

**Comment by timocov** [comment]
Hm, I have no idea what could be wrong here. I'm using win10 too, just tried with cmd, wsl with bash and git bash - everything works fine. Maybe you have some files missed?

Do you have `mocha` installed globally? Can you try to run `./node_modules/.bin/mocha 'tests/unittests/**/*.spec.ts'`?

**Comment by tolotrasamuel** [comment]
Also, I noticed that it does not recognize some packages in node_module 

For example, when I run `npm run verify` it says that it cannot find  'npm-run-all' . Also, it did the same error with the module `ttsc` when I ran `npm run tsc`. I installed the module ttsc globally and I worked. 
I am not sure if this is related 

```
 npm run verify

  > lightweight-charts@2.1.0 verify C:\Users\Tolotra Samuel\PhpstormProjects\lightweight-charts
  > npm-run-all clean -p tsc-all lint check-markdown-links -s build:prod test codechecks

  'npm-run-all' is not recognized as an internal or external command,
  operable program or batch file.
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! lightweight-charts@2.1.0 verify: `npm-run-all clean -p tsc-all lint check-markdown-links -s build:prod test codechecks`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the lightweight-charts@2.1.0 verify script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by tolotrasamuel** [comment]
Yes I have mocha and ts-node installed globally 


```
$npm list -g --depth=0
...
+-- mocha@5.2.0
+-- npm@6.9.0
+-- npm-check-updates@3.1.20
+-- sass@1.22.4
+-- t@0.5.1
+-- ts-node@8.3.0
+-- tslint@5.18.0
```

**Comment by timocov** [comment]
I guess that the issue might be in global packages. Try to remove them and run commands again. At least we use higher version of tslint and mocha. It might be related.

**Comment by timocov** [comment]
After removing global packages (I'd don't recommend use global packages at all) run `npm install` again to verify that everything is installed properly.

**Comment by tolotrasamuel** [comment]
Okay. Everything is working fine now.

I did what you said.
1) remove tsc, ttsc, ts-node and mocha globally
2) delete node_module folder
3) run npm install again
4) npm run test now works fine

Thank you
