### ISSUE TITLE
not able to set 24 hr window on timescale

### ISSUE THREAD

**Issue by HirulkarRajesh** [tradingview/lightweight-charts#397]
we need to set start point of timescale 00:00 initial time of the day and set end point of timescale 23:59 end time of the day not able to haw can do the same

**Comment by timocov** [comment]
Excuse me, I'm not sure that understand what do you want to achieve. Can you provide some examples/screenshots?

**Comment by ProgrammingLife** [comment]
I suppose he needs to show only one day per current window :)

**Comment by timocov** [comment]
Ah, for that you need to

- use setVisibleRange of timescale if you already have that data
- wait for #370 and set visible logical range, but approximate range yourself if you don't have that data

**Comment by timocov** [comment]
Another thing you might need to do it use something like "empty spaces" - see #209 and #423

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
