### ISSUE TITLE
TimeScaleOptions has no property tickMarkFormatter

### ISSUE THREAD

**Issue by tolotrasamuel** [tradingview/lightweight-charts#398]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**
`npm i lightweight-charts`

**Actual behavior:**

TimeScaleOptions has no proprety tickMarkFormatter

```
export interface TimeScaleOptions {
	rightOffset: number;
	barSpacing: number;
	fixLeftEdge: boolean;
	lockVisibleTimeRangeOnResize: boolean;
	rightBarStaysOnScroll: boolean;
	borderVisible: boolean;
	borderColor: string;
	visible: boolean;
	timeVisible: boolean;
	secondsVisible: boolean;
}
```

**Expected behavior:**

When I do git clone, I get the property

```
export interface TimeScaleOptions {
	rightOffset: number;
	barSpacing: number;
	fixLeftEdge: boolean;
	lockVisibleTimeRangeOnResize: boolean;
	rightBarStaysOnScroll: boolean;
	borderVisible: boolean;
	borderColor: string;
	visible: boolean;
	timeVisible: boolean;
	secondsVisible: boolean;
	tickMarkFormatter: TickMarkFormatter; // Here you go
}

```

How to get tickMarkFormatter on the package using npm i ?

**Screenshots**

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
This feature was added in #226 which is assigned to 3.0 version milestone. So, this feature isn't released yet.
