### ISSUE TITLE
backgroundColor: 'transparent' / using transparency

### ISSUE THREAD

**Issue by Vultwo** [tradingview/lightweight-charts#40]
When setting the layout properties to transparent, the chart doesn't seem to be working correctly.
https://jsfiddle.net/70k4yuhL/2/

**Comment by timocov** [comment]
All I can say right now is that it was done for performance purposes - instead of clearing canvas, then fill it with color, we can just fill it with color without clearing and get the same result. Possible we need to handle a case when color has transparency...
