### ISSUE TITLE
Price in Y-Axis not getting loaded

### ISSUE THREAD

**Issue by sayin-demah** [tradingview/lightweight-charts#401]
Hi, 

**Lightweight Charts Version:** 2.0.0

**Actual behavior:**

The price data is not showing in the Y-axis

**Expected behavior:**
The price data should be shown in the Y-axis scale

**Screenshots**

![image](https://user-images.githubusercontent.com/61697311/79105982-46cf2f80-7d8f-11ea-87a9-ef8a00b81555.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/niyas2109/ak5pn1x6/3/

Please let me know if I am missing anything

**Comment by timocov** [comment]
The first question is why your data is strings instead of numbers? The second - you need to configure price format, see https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format.

**Comment by sayin-demah** [comment]
Thank you for the clarification. Its working fine now
