### ISSUE TITLE
Can multiple charts be synchronized by time-axis?

### ISSUE THREAD

**Issue by b4git** [tradingview/lightweight-charts#402]
If we add two charts to a page, is it possible that when one chart is scrolled to a specific time, another chart can also auto-scrolled so that both of them show the cross-hair at that specific time?

**Comment by timocov** [comment]
Yes, it's possible right now, but with some limitation. After https://github.com/tradingview/lightweight-charts/issues/335#issuecomment-611046430 you'll be able to make more "smoothy".

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
