### ISSUE TITLE
Getting last candlestick from loaded chart

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#403]
Is that possible to get an information about last candlestick (or last value of lineSeries) from already loaded chart? Or should I make my own copy of those values? I'm using **candleSeries.update()** so I don't have it at this time :)

That's what I'm insterested in:
- Getting the last time value
- Getting the last price value (if possible)

I need it to call **setVisibleRange()** properly. For instance, I want to have only 100 bars visible per one screen.

**Comment by timocov** [comment]
No, currently we don't have that API and actually, as soon you provided data to the charts and we don't do any modification with the data (e.g. generating higher resolution), I don't see any strong reason to do this. After https://github.com/tradingview/lightweight-charts/issues/335#issuecomment-611046430 you'll able to get latest time value, but not bar itself.

**Comment by memokaradas** [comment]
@ProgrammingLife 

This is not implemented as @timocov mentioned.
I understand your Question though as there may be reasons to access previous Series-Data. 

Don´t forget that lightweight-charts is not meant to replace Tradingview´s Main Product ;)

Change "Series" to the Series you are trying to access and keep in mind that this is a quick and dirty solution.

```
const iterator = Series._dataUpdatesConsumer.de.ee.values();
const entries = [];

for (const value of iterator) {
  for (const res of value.mapping.values() ) {
    entries.push(res);
  }
}

console.log(entries); //has all entries of the Series
const last = entries[entries.length - 1];
console.log(last); //has last element of the Series
```

**Comment by timocov** [comment]
@memokaradas keep it mind that this solution will not work after (and if) we merge #436 (I guess it should be in 3.0), because it will `_dataUpdatesConsumer` as well as other "private" props (like `de.ee` in your code).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
