### ISSUE TITLE
How to get something like Shift+click in Tradingview?

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#405]
I wanna calculate price chaning from one point to another. How to get it?
I noticed about subscribing to mouse click event and then I can get coordinates of clicked point but what's next? :) I can take only series values under the click. Seems like Tradingview gets min and max prices in visible range and remaps it to coordinates.

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#coordinates-and-prices-converting - you can convert any price to coordinate and vice versa.

> Seems like Tradingview gets min and max prices in visible range and remaps it to coordinates.

Are you talking about autoscale, right?
