### ISSUE TITLE
How to reset price scale after changing it manually?

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#407]
I suppose it's easy to get but I can't find any information about it. How to do it?

**Comment by timocov** [comment]
You need to enable `autoScale` https://github.com/tradingview/lightweight-charts/blob/v2.0.0/docs/customization.md#price-axis.

**Comment by CreativeWarlock** [comment]
@timocov A more detailed answer (not a point-to-documentation) would be more appreciated since there is not hint how to configure the options in order to reset a price scale (after manually scaling + panning it).

Simly setting autoScale to true doesn't make it work.

**Comment by qvinh0704** [comment]
In my case, I run applyOptions again when I need to reset the price scale. 

`chart.priceScale(priceScaleId).applyOptions({autoScale: true});`
