### ISSUE TITLE
Getting an access to canvas context

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#408]
Is it possible now to get an access to canvas context for drawing anything we want right on the canvas?
Thus we can draw any custom graphics on a plot such as lines, text labels, free hand notes, etc. What do you think guys?

**Comment by timocov** [comment]
> Is it possible now to get an access to canvas context for drawing anything we want right on the canvas?

It's impossible right now.

> What do you think guys?

It's tricky question. Right now we have some optimisations internally, which allows us make charts performant. For instance, we have 2 canvases for every pane/price axis/time axis instead of just 1 or even the only 1 for the whole chart. Which one we should provide you? When (before our own renderers or after, or maybe between)? What's about pixel perfect (who should scale context and what if you want to use "native" context instead of scaled one)? What if you'll renderer out of "draw cycle" (requestAnimationFrame)? I guess there are a ton other questions we need to answer before start doing this.

But anyway, we keep in mind that it'd be better to provide such kind of API so users will be able to draw their own data as they wish.

**Comment by mqklin** [comment]
Agree, lots of tricky questions. I found a workaround to solve my problem, so no need to get canvas context now.

**Comment by adsonvinicius** [comment]
@mqklin Do you know how can I read the candle's time text?

**Comment by jonas-db** [comment]
I think this a key feature to enable advanced developers to fully leverage this library. In particular, I'm thinking about free drawing (trend lines etc). Any plans to support this?

**Comment by jonas-db** [comment]
It might be a good idea to have callbacks like before/afterDrawTimeSeries. These are called by the library for every point that is drawn on the canvas and the canvas context. Then we could draw additional things at/around each point for each time serie.

**Comment by asedsami** [comment]
@mqklin what was your problem? Would you know how to draw a rectange on the canvas?

**Comment by mqklin** [comment]
@asedsami i'm using built-in figures instead https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#setmarkers

**Comment by asedsami** [comment]
> What's about pixel perfect (who should scale context and what if you want to use "native" context instead of scaled one)?
Does full access to the context have to be given? how about accessing the context without being able to scale?

**Comment by jonas-db** [comment]
Isn't there any third-party fork that supports this? Too bad it hasn't been supported yet after almost 2 years

**Comment by timocov** [comment]
@jonas-db well, do you have the understanding how it could be done from API prospective? Keep in mind that we have 2 canvases for each type of chart item (2 for each pane, 2 for time axis, 2 for each price axis).

**Comment by zeeshan-shabbir** [comment]
> > Is it possible now to get an access to canvas context for drawing anything we want right on the canvas?
> 
> It's impossible right now.
> 
> > What do you think guys?
> 
> It's tricky question. Right now we have some optimisations internally, which allows us make charts performant. For instance, we have 2 canvases for every pane/price axis/time axis instead of just 1 or even the only 1 for the whole chart. Which one we should provide you? When (before our own renderers or after, or maybe between)? What's about pixel perfect (who should scale context and what if you want to use "native" context instead of scaled one)? What if you'll renderer out of "draw cycle" (requestAnimationFrame)? I guess there are a ton other questions we need to answer before start doing this.
> 
> But anyway, we keep in mind that it'd be better to provide such kind of API so users will be able to draw their own data as they wish.

is it possible now ?
