### ISSUE TITLE
Format in Timescale

### ISSUE THREAD

**Issue by thanhnntq** [tradingview/lightweight-charts#409]
How to format time in Timescale into a custom format like 'DD/MM/YYYY HH:mm:ss'?
Thank you so much!

**Comment by timocov** [comment]
What kind of time do you want to format? Is it crosshair's time or tick mark?

See https://github.com/tradingview/lightweight-charts/blob/v2.0.0/docs/customization.md#date-format, https://github.com/tradingview/lightweight-charts/blob/v2.0.0/docs/customization.md#time-format, https://github.com/tradingview/lightweight-charts/issues/226 and https://github.com/tradingview/lightweight-charts/issues/368.
