### ISSUE TITLE
timescale problem on multiple dataset

### ISSUE THREAD

**Issue by Winthan** [tradingview/lightweight-charts#41]
getVisibleRange() is returning null when I am using mulitple data set on chart. fitContent() doesn't work too when using multiple lines and area data. Do I need to specify exactly as the time from the Data which I have?  

```
var range = {
  from: '2019-06-09',
  to: '2019-06-10'
};
          chart.timeScale().setVisibleRange(range);
          chart.timeScale().fitContent();
```

**Comment by Winthan** [comment]
I was loading dynamic data, that's why it didn't load data.

**Comment by timocov** [comment]
There might be a problem with getting some values, we'll describe it here and in the docs. Let's leave this issue opened until we do it.

/cc @eugene-korobko

**Comment by Winthan** [comment]
Ya, I found some of the error when having multiple datasets with the different timestamps.  let's say, Dataset B may not starts with the same timestamp than Dataset A, or having a missing timestamp on another dataset,  causes the chart problem at loading first with "Value not found" error.

**Comment by timocov** [comment]
Can you please share a little repro with that?

**Comment by timocov** [comment]
@Winthan ping 🙂

**Comment by timocov** [comment]
I'm going to close this issue for now. If you'll have any updates/issues with that - feel free to reopen it.
