### ISSUE TITLE
Add ability to remove part of the series' data

### ISSUE THREAD

**Issue by divinci** [tradingview/lightweight-charts#417]
Hi there, first off what a great library thank you very much for it!

As I am streaming a lot of data into my chart I need to remove old data items for performance reasons.

I am currently doing this by calling `setData` on each render pass.

I know that this process could be optimised so my feature suggestion is to add a `removeData` method to the `DataUpdatesConsumer` and series API.

I'll have a crack it myself when I have some time to learn how to debug TS :)

**Comment by timocov** [comment]
How many bars you have? I'm asking it because I just want to understand the case when it comes slow for you. We have tested it with several thousands and it was ok.

What do you use to update the data? `update` or `setData`?

**Comment by divinci** [comment]
Hi @timocov, I have 1min candle data spanning years.  I agree with you a couple of thousand bars is great when the chart is not rendering.

However I am streaming in bars so there are a couple of renders every second.  Meaning I call `setData` a couple of times each second.  When in reality there could just be 1 bar added at the latest time, and 1 bar removed from the tail.

**Comment by divinci** [comment]
I presume `update` is less intensive than `setData`.  So all I need is a `remove` :)

**Comment by timocov** [comment]
>  Meaning I call setData a couple of times each second

Can you use `update` instead? It's aim is in update the latest bar or append the new one from the right and make it faster.

> I presume update is less intensive than setData.

Yeah, it should.

> when the chart is not rendering.

It's possible to get reproduce of performance issues you faced so you need to worry about that? We like to improve the project to make it faster and performative.

As workaround or improving the perf you can strip bars only several times. I meant, for instance, 1 time per 100-1000 bars.

**Comment by Tucsky** [comment]
Ive encountered the same issue.... as chart can get quite heavy with time Im looking for a way to strip old data from the chart, like to free up memory if that makes sense? But no remove function...
I was thinking bout gettings points of dataUpdatesConsumer some way, remove the whole chart, recreate it and set data but surely there is a better way to do this right?

**Comment by divinci** [comment]
> As workaround or improving the perf you can strip bars only several times. I meant, for instance, 1 time per 100-1000 bars.

Thanks for the workaround @timocov .  I don't have a repro yet sorry but ill let you know when I do.

**Comment by timocov** [comment]
> But no remove function... I was thinking bout gettings points of dataUpdatesConsumer some way, remove the whole chart, recreate it and set data but surely there is a better way to do this right?

@Tucsky yes, you can set new data with small count of bars.

Removing "bars" is tricky. Remove specific bar? Remove bars before passed? Remove the the only 1 series? We need to have more consistent solution than just "remove some bars because we can't call setData". And, if you have any repro of issues drawing several thousands bars and call update there - it'd be helpful there. Right now I see at https://leeoniya.github.io/uPlot/bench/lightweight-charts.html (afaik it has 160k points) and it draw them perfectly.

**Comment by Tucsky** [comment]
> yes, you can set new data with small count of bars
ended up doing exactly that, and as you said it might not even be needed, chart itself is fast af. I have a module using lightweight charts which is adding new bar every second, I just sleep better knowing it wont have (604800*nb of series) bars after a week of having it open 😁

**Comment by divinci** [comment]
> > yes, you can set new data with small count of bars
> 
> ended up doing exactly that, and as you said it might not even be needed, chart itself is fast af. I have a module using lightweight charts which is adding new bar every second, I just sleep better knowing it wont have (604800*nb of series) bars after a week of having it open 😁

A bar a second works nicely - i'm replaying ticks as fast as I can which leads to multiple updates per second - where it starts to degrade.

**Comment by timocov** [comment]
Since this ticket was opened we improved updating the data (both setData and update) a lot so probably now you can use any of them to update the data or to implement a strategy of having only a few bars on the chart without performance issues. Let me know if you're still experiencing the issue or have anything to add here.
