### ISSUE TITLE
Optimize setting data to series

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#418]
See https://leeoniya.github.io/uPlot/bench/lightweight-charts.html.

It takes about 700ms to set data to 3 series. I guess we can use that to optimize our algorithms to set data faster.

[Chrome DevTools profile](https://github.com/tradingview/lightweight-charts/files/4538947/Profile-20200427T130622.zip)

![image](https://user-images.githubusercontent.com/3112183/80360507-1e176180-8888-11ea-925f-8e0c44ac86cf.png)

**Comment by leeoniya** [comment]
nice.

let's first figure out https://github.com/leeoniya/uPlot/issues/185 so we're comparing apples to apples.

**Comment by gkaindl** [comment]
Not related to the screenshot above, but maybe related to optimizations of setting data in general, is the fact that the library currently expects series data as an array of objects of a certain shape (depending on the series type), so you'll often see a pattern like this (or something similar to what `prepData()` does in the example here):

```
mySeries.setData(
   array_of_stuff_I_have_from_my_data_source.map(
      my_obj_type => ({ ... shape that the lib wants ...})
   )
```

So if you're loading a lot of data, you'll do a huge allocation (and subsequent GC pass later) just to get the data into the right shape, which is also quite visible in profiling.

The d3 visualization app uses "accessor" functions, as an example, so when you set data there, you pass in the array of data the way you already have it, and a set of functions that take your array and an index, and return whatever the library expects. That's a way to prevent the need to copy data to a new shape and retrieve values as needed instead, eschewing unnecessary allocations.

What I did in my app now is using an array proxy that takes an array of my own types and converts them into the shape the library expects, which is a bit better GC-wise, but still worse than an "accessor" approach.

Working with accessors is a bit more annoying, but could be worth a try for huge sets of data. So the above boilerplate could then be written like this:

```
mySeries.setDataWithAccessors({
   data: array_of_stuff_I_have_from_my_data_source,
   dateAccessor: (data, idx) => data[idx].retrieve_the_date_from_my_own_type(),
   valueAccessor: (data, idx) => data[idx].retrieve_the_value_from_my_own_type()
})
```

or with closures

```
const arr = array_of_stuff_I_have_from_my_data_source;

mySeries.setDataWithAccessors({
   length: arr.length,
   dateAccessor: (idx) => arr[idx].retrieve_the_date_from_my_own_type(),
   valueAccessor: (idx) => arr[idx].retrieve_the_value_from_my_own_type()
})
```

**Comment by leeoniya** [comment]
a more efficient input format would help, but is likely not the main speedup here.

Chart.js-next [1] has basically identical prep code and runs in the same amount of time (~50ms) on my machine.

[1] https://leeoniya.github.io/uPlot/bench/Chart.js-next.html

**Comment by timocov** [comment]
btw we've made some perf improvements in #486 and now setting a data should be a bit faster.

**Comment by timocov** [comment]
I just tested https://leeoniya.github.io/uPlot/bench/lightweight-charts.html page with v3.6.1 and it seems that it is twice faster than v3.0.0 (~400ms vs ~200ms). The upcoming v3.7.0 is even more faster than v3.6.1 up to 25% (~150ms), so total improvements since v3.0.0 are ~60% (from 400ms to 150ms). I think this is good enough for now so we can close this issue.
