### ISSUE TITLE
Change time interval to hourly instead of daily

### ISSUE THREAD

**Issue by frevanauseloos** [tradingview/lightweight-charts#420]
I'm using the candlestick chart example and I would like to change the time interval to the hourly chart, is this possible? My data is hourly.
https://jsfiddle.net/freva/y4xn8eta/2/

**Comment by timocov** [comment]
If you'd like you have "intraday", you need to use timestamps. See https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#time. String is used as business day and is for daily+ intervals. Also, string as time should have format `yyyy-mm-dd` without time part.
