### ISSUE TITLE
The label not alinged when set scaleMargins of bottom 0

### ISSUE THREAD

**Issue by qy20092011** [tradingview/lightweight-charts#422]
**Lightweight Charts Version:** 
1.2.2
**Steps/code to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Screenshots**
![image](https://user-images.githubusercontent.com/28330610/80560051-27ccd080-8a12-11ea-9cd2-894e440b93ca.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
As you can see the label should be placed above that it placed on you screenshot. Where is the problem here?
