### ISSUE TITLE
Time Scale Display

### ISSUE THREAD

**Issue by sysopsnw18** [tradingview/lightweight-charts#423]
I want to plot graph between 9.15AM to 3.30PM like attached images. Is there any option available to add empty data.

![chart1 (2)](https://user-images.githubusercontent.com/61038438/80679458-852c5480-8ada-11ea-8f87-0579b0bcecb4.png)
![chart2 (2)](https://user-images.githubusercontent.com/61038438/80679460-85c4eb00-8ada-11ea-8a0d-c19860bddd5b.png)

**Comment by timocov** [comment]
Try to don't pass value in line series' data - https://github.com/tradingview/lightweight-charts/issues/209, it should work for line and histogram series already, but don't work for candlestick and bars series yet.

**Comment by sysopsnw18** [comment]
Is this possible for area series? I tried same with area series. Check image for output
Any solution for the same.

![image](https://user-images.githubusercontent.com/61038438/80702074-1a8d1000-8afe-11ea-979f-2855d767532b.png)

**Comment by sysopsnw18** [comment]
> Try to don't pass value in line series' data - #209, it should work for line and histogram series already, but don't work for candlestick and bars series yet.

Tired same empty data part for area series and below is the output.  Is this empty data part possible in are series?

![image](https://user-images.githubusercontent.com/61038438/80702219-56c07080-8afe-11ea-8b34-945bb1b4b555.png)

**Comment by timocov** [comment]
@sysopsnw18 let's continue in #209 - we'll fix it there (please copy your comment to there).

**Comment by ChukwudiNebo** [comment]
@sysopsnw18 how did you set the time scale to 12 hours format @timocov
