### ISSUE TITLE
Option for setting different timezone offsets to timescale.

### ISSUE THREAD

**Issue by Dwyte** [tradingview/lightweight-charts#428]
The title pretty much sums it up, right now timescale is using UTC+00 would be nice if we could manually have an option to set other timezone offset.

**Comment by eugene-korobko** [comment]
Hello!

We have an option now to customize label formatting on time scale

https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md

**Comment by timocov** [comment]
We aren't going to implement support for timezones, because it requires a lot of work and including tzdata into the package.

#359 https://github.com/tradingview/lightweight-charts/issues/125#issuecomment-511307557

**Comment by timocov** [comment]
But you can still do it yourself by converting your time to timezone you want to have and overriding formatting functions to respect that timezone.
