### ISSUE TITLE
Marker text not showing, size not changing.

### ISSUE THREAD

**Issue by Dwyte** [tradingview/lightweight-charts#429]
[Marker Image](https://cdn.discordapp.com/attachments/641204533338308609/707043953844944927/unknown.png)

```javascript
candleS.setMarkers([
  {
    time: history[index][history[index].length - 1].time,
    position: "belowBar",
    color: "orange",
    shape: "circle",
    id: "id4",
    text: "example",
    size: 4,
  },
]);
```

The marker shows, but size seems doesn't work, I tried different values, the size of the marker stays the same. Then the text doesn't show as well, I was expecting the text would be displayed inside the marker, isn't that how it suppose to be?

I mostly copied the sample code from the documentation was testing the feature out and wasn't getting expected results, thought of it might be a bug or something, thanks.

**Comment by eugene-korobko** [comment]
Hello!

Well, I see that text does not appear too. So I suppose you use old version of the library

**Comment by timocov** [comment]
@Dwyte what version do you use? Can you provide link to jsfiddle-like sample?

**Comment by Dwyte** [comment]
@timocov, @eugene-korobko  I use the latest version, 2.0.0 available from npm. Oh is this feature yet to be released?

**Comment by Dwyte** [comment]
I use lightweight charts with react.js, but here https://jsfiddle.net/raybdmef/ trying in jsfiddle, the marker doesn't show anything. Not sure what I'm doing wrong here.

**Comment by timocov** [comment]
> but here jsfiddle.net/raybdmef trying in jsfiddle, the marker doesn't show anything. Not sure what I'm doing wrong here.

There is used 1.0.0-rc.3 version, it's far away from 2.0.0 :)

The issue #207 where was added support for text in markers is assigned to 3.0 milestone, which isn't released yet.
