### ISSUE TITLE
Putting Timestamp doesn't put price values for every minute

### ISSUE THREAD

**Issue by shubhamchinda-sc** [tradingview/lightweight-charts#430]
I want to **set data** for every minute in the graph.

I'm using `timestamp` to achieve that referring to [Link](https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp)
```
[{
close: 121.68
high: 121.82
low: 121.55
open: 121.55
time: 1588588200000
}]
```
> Sample set of values

Here's a screenshot of result :
> ![Screenshot from 2020-05-05 18-42-03](https://user-images.githubusercontent.com/63850492/81071186-f5374200-8f01-11ea-82bd-7f65146461a0.png)

You can see that the X-Axis still has the month and data values instead of time.

Could anybody help me out?

Thanks :)

**Comment by eugene-korobko** [comment]
Hello!

This floating bar is obviuosly not a part of the library. Could you please provide code how it gets the value?

**Comment by timocov** [comment]
Also, you can ask such questions on [stackoverflow](https://stackoverflow.com/questions/tagged/lightweight-charts). I guess it's the best place to ask such questions there.

**Comment by shubhamchinda-sc** [comment]
@eugene-korobko 
Here it is : https://jsfiddle.net/TradingView/p6f5svr4/

You can check more templates here : https://in.tradingview.com/lightweight-charts/

**Comment by shubhamchinda-sc** [comment]
@timocov 

Thank you! Someone helped me on `Discord` :100:
