### ISSUE TITLE
When I use SetMarkers on lineSeries, the time scale on the x-axis changes

### ISSUE THREAD

**Issue by brendalways** [tradingview/lightweight-charts#431]
When I add markers to my lineSeries using SetMarkers, the scale on the x-axis changes. 
I am calling .applyOptions(chartOptions) where in my chartOptions variable, I define {timescale: {timeVisible: true}. 

What is this happening and how do I make the x-axis scale uniform even if I add multiple lineSeries or markers on the chart?
![image](https://user-images.githubusercontent.com/29526694/81373554-d5468080-90b1-11ea-9cc9-40336e885a74.png)

**Comment by timocov** [comment]
How it's changed and can you provide a repro for that?

**Comment by brendalways** [comment]
I actually do not have a repo yet, but I am creating a second lineSeries for my markers since the markers I want are in the past where I do not have a value in my lineSeries. But regardless of markers, if I have multiple lineSeries on my chart, how can I make my x-axis uniform?

**Comment by timocov** [comment]
To answer I need to understand what's going on first. I don't need a repo, I need reproducing for the issue. It might be jsfiddle-like example.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
