### ISSUE TITLE
Custom font families for watermarks

### ISSUE THREAD

**Issue by meetmangukiya** [tradingview/lightweight-charts#437]
**Is your feature request related to a problem? Please describe.**

Just would like to be able to change the font

I think should be easier to implement, just adding another argument to the `makeFont` call from the brief look at it?

**Comment by timocov** [comment]
Yeah, it needs to add the new option `fontFamily` to [WatermarkOptions](https://github.com/tradingview/lightweight-charts/blob/a6c3e8134be68ee9e79f0382540eba054d1e35cb/src/model/watermark.ts#L9-L22 ) and use it [in pane view](https://github.com/tradingview/lightweight-charts/blob/a6c3e8134be68ee9e79f0382540eba054d1e35cb/src/views/pane/watermark-pane-view.ts#L59).

Feel free to make a PR.
