### ISSUE TITLE
Pricescale & autoscaleInfoProvider dont work as expected in Candlestick Series

### ISSUE THREAD

**Issue by christose** [tradingview/lightweight-charts#442]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
priceRange:
maxValue: 0.89440 
minValue: 0.89580 
Assuming these are the highest and lowest visible values of a visible range of data in candlesticks for e.g. Symbol EUR/GBP
What I need is to have candlesticks taller instead of so small like in the screenshot below. I understand in order to achieve that I need to override the autoscaleInfoProvider.
Also, autoScale is set to true in order for autoscaleInfoProvider to work.

**Actual behavior:**
It shows values from 0.89440 to 0.89580 in the price scale

**Expected behavior:**
It should show values from 0.89467 to 0.89524 only on the price scale which are the highest and lowest values.

**Screenshots**
![image](https://user-images.githubusercontent.com/8969889/82269732-31938500-997b-11ea-804b-7ee1504db8c1.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Can you provide a repro for that please?

**Comment by christose** [comment]
Yes, sorry for not providing more details, I can provide more pieces of the code but not the data, it's impossible, data are historical by a 1-minute interval and assume that I have the high low, open close.
e.g. 
1.09364 | 2020-05-19 14:14:00
1.093 | 2020-05-19 14:13:00
1.09309 | 2020-05-19 14:12:00
1.09307 | 2020-05-19 14:11:00
1.0931 | 2020-05-19 14:10:00
1.09347 | 2020-05-19 14:09:00
1.09396 | 2020-05-19 14:08:00


This is my configuration for the price scale
chartOptions.rightPriceScale = {
      mode: PriceScaleMode.Normal,
      autoScale: true,
      invertScale: false,
      alignLabels: true,
      borderVisible: true,
      scaleMargins: {
        top: 0.25,
        bottom: 0.25,
      }
    };


The configuration of price format it is based on symbol so e.g.
series.applyOptions({
    priceFormat: {
        type: 'price',
        precision: 5 or 3,
        minMove: 0.01 or 0.001,
    },
});

The logic of autoscaleInfoProvider:
1) The VisibleData is an array being updated every time the visible data changes and I use the following code to get the visible data:
var j = this.ChartSeries._series.J;
this.VisibleData = j._items.length == 0 || j._itemsVisibleRange == null ? j._items : CloneArray(j._items).splice(j._itemsVisibleRange.from, j._itemsVisibleRange.to);

It doesn't look the right way to get the visible data I don't really like it, but I couldn't find a better way to access the visible range at the moment because the subscribeVisibleTimeRangeChange from - to object is correct but again I don't have the real visible data which are based on the zoom/interval etc.
2) So based on this array I calculate my high and low with the GetHighLow function, inside the autoscaleInfoProvider.

3) The Low and High values are correct I can see them in the console and I can compare them with the price scale and the visible candles, so lets say my low, high are 4-8, the price scale is wider, it shows values from lets say 0-12 and I dont understand why.
this.ChartSeries.applyOptions({
      autoscaleInfoProvider: (original) => {
        var res = original();
        var visible = this.GetHighLow(this.VisibleData);
        if (res.priceRange !== null && visible != null) {
            res.priceRange.minValue = visible.Low;
            res.priceRange.maxValue = visible.High;
        }
        console.log(res.priceRange);
        return res;
      }
    });


Please let me know if I can provide you with anything else in order to help you to reproduce this.

**Comment by timocov** [comment]
Can you provide your sample on jsfiddle (or any similar service) please?

**Comment by christose** [comment]
@timocov after a deep investigation it seems that data were wrong. The data is calculated to server the intervals e.g. 1m, 5m, 15m, 30m were being calculated a bit wrong so there were more data in number than expected so high and low were covering a larger range than the one you could see on the screen and that's why the price scale was covering a larger price range.

Sorry for any inconvenience I might cause to you.

You are all doing a great job in this great library.

Thanks
