### ISSUE TITLE
How to get the ohlc value and color of respective candlestick in candlestick series.

### ISSUE THREAD

**Issue by AbhishekS98** [tradingview/lightweight-charts#444]
![ohlc](https://user-images.githubusercontent.com/54749544/82318724-f2524c00-99ed-11ea-83a8-9fac156dd797.png)

```
chart.subscribeCrosshairMove((param) => {
      if (param.time) {
        console.log(param.seriesPrices.get(candleStick));
      }
    });
```

i'm getting the value but not the color.

**Comment by timocov** [comment]
I think you can calculate it yourself - [it's easy](https://github.com/tradingview/lightweight-charts/blob/a6c3e8134be68ee9e79f0382540eba054d1e35cb/src/model/series-bar-colorer.ts#L94-L98). Currently I don't think that exposing color is valuable and we need to provide it in API.

**Comment by AbhishekS98** [comment]
It is the basic functionality of candlestick based charts

**Comment by timocov** [comment]
What do you mean? It's single-line function and I don't think that it'll be changed in any future.
