### ISSUE TITLE
Importing the library in server-side context caused `ReferenceError`

### ISSUE THREAD

**Issue by azhang** [tradingview/lightweight-charts#446]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**

webpack build

**Actual behavior:**

  WebpackError: ReferenceError: navigator is not defined
  
  - lightweight-charts.esm.production.js:7 Module../node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js
    node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:110791
  
  - index.js:1 Module../src/components/ChartWrapper/index.js
    src/components/ChartWrapper/index.js:1:1

**Expected behavior:**

No error

**Screenshots**

**CodeSandbox/JSFiddle/etc link:**

**Comment by azhang** [comment]
Solved it. Problem was that I included `lightweight-charts` in a server-side rendering project (gatsby) which doesn't have `navigator` defined.

**Comment by NekitCorp** [comment]
I also have this problem. 

**"lightweight-charts": "^3.0.1"**

My usage (charts are not used on the server-side, but an error occurs anyway):

```ts
import React from 'react';
import { createChart } from 'lightweight-charts';

const TestChart: React.FC = () => {
    React.useEffect(() => {
        const chart = createChart(document.body, { width: 400, height: 300 });
        const lineSeries = chart.addLineSeries();
        lineSeries.setData([
            { time: '2019-04-11', value: 80.01 },
            { time: '2019-04-12', value: 96.63 },
            { time: '2019-04-13', value: 76.64 },
            { time: '2019-04-14', value: 81.89 },
            { time: '2019-04-15', value: 74.43 },
            { time: '2019-04-16', value: 80.01 },
            { time: '2019-04-17', value: 96.63 },
            { time: '2019-04-18', value: 76.64 },
            { time: '2019-04-19', value: 81.89 },
            { time: '2019-04-20', value: 74.43 },
        ]);
    }, []);

    return <div id="test-chart" />;
};
```

Error on server-side rendering: _UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined_

@timocov Do you see this as a problem? If so, then I can create a PR with a few edits to use `navigator` on SSR in [these places](https://github.com/tradingview/lightweight-charts/search?q=navigator&unscoped_q=navigator).

**Comment by timocov** [comment]
> Do you see this as a problem? If so, then I can create a PR with a few edits to checks before use navigator on SSR in these places.

@NekitCorp I don't quite understand how the library might be used in SSR context. Almost all created DOM elements in lightweight-charts are canvases, which couldn't be reused (afaik) between SSR and code inside the browser. And, the library creates all elements it needed on createChart call, so even there is some SSR provided DOM elements, they won't be used.

If you have an idea on how it might work with SSR - feel free to share it here please. I don't think that just replacing `navigator` with `typeof navigator !== 'undefined' ? navigator.language : 'en'` (for instance) would help here, it just hide the issue of using the library in SSR.

**Comment by azhang** [comment]
The way I solved this was by using [loadable-components](https://loadable-components.com/docs/library-splitting/) to defer loading of the library to clientside.

**Comment by NekitCorp** [comment]
@timocov Many react libraries are also used only on the client side in the browser (for example, carousels) and their import on the server side does not cause errors, because their variables are not called on the server side using window or navigator ([example](https://github.com/akiran/react-slick/blob/38c1b51996e2e8ff25d9f6a2241ac3b3034cb86d/src/utils/innerSliderUtils.js#L819)). I want to say that I do not call `createChart` on the server side, but just import `import { createChart } from 'lightweight-charts';` on the server side leads to an error.
Yes, the idea is right.

@azhang Yes, that's exactly what I did, but it looks complicated when other similar libraries do not require it.

**Comment by timocov** [comment]
> but just import import { createChart } from 'lightweight-charts'; on the server side leads to an error.

Ah, I got it. Yeah, I guess it's better to replace it in that way (don't forget to leave a comment there why we need to check it please).

**Comment by ogremagi4** [comment]
> The way I solved this was by using [loadable-components](https://loadable-components.com/docs/library-splitting/) to defer loading of the library to clientside.

Could you please share some code regards this one?  @azhang 
I just encountered the same issue with kaktana-lightweight-charts and my experiments with loadable-components never had success.

**Comment by dan-cooke** [comment]
```tsx
import loadable from "@loadable/component";

const AreaChart = loadable.lib(async () => {
  if (typeof window !== `undefined`) {
    return import(`~/components/Charts/AreaChart`);
  }
});
```

**Comment by dan-cooke** [comment]
If anyone stumbles upon this - you don't need a library.

Just make sure you wrap any calls to `lightweight-charts` in a window check, with dynamic import.

**before**
```
import { createChart } from 'lightweight-charts'
createChart(...)
```

**after**

**Comment by mustaphaturhan** [comment]
For the people who use `nextjs`, if you don't want to use `ssr: false` -which is exclude lightweight-charts from `getStaticProps` build-, you may want to use [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) instead.

- Open your `next.config.js` file.
- Export your config with using `withTM` hoc. Example:

```js
/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {...};

const withTM = require('next-transpile-modules')(['lightweight-charts', 'fancy-canvas']);

module.exports = withTM(nextConfig);
```

**Comment by pezdel** [comment]
for astro you just need to do client:only="react" 
https://docs.astro.build/en/reference/directives-reference/#clientload
