### ISSUE TITLE
Feature Request : API to set custom candle colors

### ISSUE THREAD

**Issue by b4git** [tradingview/lightweight-charts#447]
This feature would enable customizing individual candles both before and after the chart has been rendered programmatically based upon user-defined conditions.

For example, this API feature would allow end-users to select the top-most or bottom-most candle and set a random color for the that particular candle to mark for some event.

![image](https://user-images.githubusercontent.com/63267629/82710324-3ccf0500-9c48-11ea-844b-6ea4e5be8a7f.png)

**Comment by timocov** [comment]
Duplicate of #195
