### ISSUE TITLE
Time scale spacing doesn't accurately represent time 

### ISSUE THREAD

**Issue by jesusgp22** [tradingview/lightweight-charts#457]
**Lightweight Charts Version:** 
2.0.0
**Steps/code to reproduce:**
Create a line chart with addLineChart and add data to it using timestamps instead of date strings

**Actual behavior:**
The charting library lays points in the chart equally distant to each other, in the image bellow the blue line represents 10 minutes of data, and the rest of the chart represents only 4 minutes of intense activity

 
**Expected behavior:**

Expect to see points X coordinate to accurately represent time

**Screenshots**
![image](https://user-images.githubusercontent.com/2547899/83185287-55c83200-a0f0-11ea-9355-f0d2ac11fa7b.png)

![image](https://user-images.githubusercontent.com/2547899/83185627-e30b8680-a0f0-11ea-941f-147dfad0b147.png)

**Comment by timocov** [comment]
This is by design. We don't approximate anything to make it "aligned". After #209 you'll be able to provide "empty" bars so you can fill the gaps and make it as you wish, but I'm afraid we're not going to do this internally.
