### ISSUE TITLE
Version 3.0 is not up in npm

### ISSUE THREAD

**Issue by MohamedLamineAllal** [tradingview/lightweight-charts#461]
npm is stuck at 2.0!
You must forget to publish !!

**Comment by timocov** [comment]
We didn't publish it because we didn't finish it yet. You can subscribe on github's released and you'll be notified about release (as soon we'll release it we add the new release on github).

**Comment by MohamedLamineAllal** [comment]
I see! I installed it through the repo directly! And built and installed just ok!
`yarn add git+https://github.com/tradingview/lightweight-charts.git --save`

Thank you a lot
 I'll make sure to check !
