### ISSUE TITLE
Series label (title) is not visible when priceScaleId is set

### ISSUE THREAD

**Issue by Tucsky** [tradingview/lightweight-charts#463]
**Lightweight Charts Version:** 3.0.0

**Steps/code to reproduce:**
Add a serie with title property and priceScaleId
```javascript
var lineSeries = chart.addLineSeries({
	priceScaleId: 'test',
	title: 'LINE LABEL' // not visible because priceScaleId
});
```

**Actual behavior:**
Title is not visible
![image](https://user-images.githubusercontent.com/5738336/83850914-dea72500-a711-11ea-8de1-2ce18b574ff9.png)

**Expected behavior:**
.title is visible
![image](https://user-images.githubusercontent.com/5738336/83850943-e9fa5080-a711-11ea-9f35-ab0a669fa5a6.png)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/qja2t8pw/

**Comment by jussirantala** [comment]
This is happening for me with the latest version.

You can also see it in your example. If you add priceScaleId property to the areaSeries configuration, the label disappears.

**Comment by timocov** [comment]
@jussirantala Looks like a bug, let's continue in #926
