### ISSUE TITLE
Hide gap on closed market

### ISSUE THREAD

**Issue by pedegie** [tradingview/lightweight-charts#468]
Hello I need to hide gap between timestamps when the market is close. Currently it looks like below. Is there any possibility to achive that?

![9PU6P](https://user-images.githubusercontent.com/10982244/83989011-4db88f80-a945-11ea-8f51-bf4b533d9a4e.png)

**Comment by timocov** [comment]
Closed in favor https://stackoverflow.com/questions/62234835/lightweight-charts-hide-gap-time-on-closed-market.
