### ISSUE TITLE
Example with remote JSON data

### ISSUE THREAD

**Issue by awunder** [tradingview/lightweight-charts#47]
Hello TV;

first of all i wanna say thank you for that library!

could you please add an example with data pulled out of a remote json api?

thanks so much!

best,
Andreas

**Comment by ezhukovskiy** [comment]
Hi!
Try this:
https://jsfiddle.net/TradingView/0xLb8mr9/

**Comment by awunder** [comment]
Hey Evgeniy,

thank you, though i just see a white chart frame with no candles..

could you pls take another look?

thanks,
Andreas

**Comment by ezhukovskiy** [comment]
the api key was expired, 
I changed it to poloniex, try again

**Comment by awunder** [comment]
awesome, thank you so much!

**Comment by ezhukovskiy** [comment]
you're welcome

**Comment by awunder** [comment]
Evgeniy,

i know, you proly have way more important things to do but i dont get this to work, actually..

i tried to do it with my own api but i am totally stuck for hours..

could you pls take a look at this? https://jsfiddle.net/L1d36g79/

i am trying to go along your sample with a timeframe switcher, js is very experimental..

thanks a ton!

Andreas

**Comment by timocov** [comment]
First of all it looks like your example doesn't have https://unpkg.com/lightweight-charts@1.0.0-rc.3/dist/lightweight-charts.standalone.production.js in resources.

Also, I have a lot of errors about CORS, for example: `Access to fetch at 'https://alphatrade.finance/api/chart-data/year/4000.json' from origin 'https://fiddle.jshell.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

After setting the data you _cannot_ just modify an array of the data. If you receive the data and want to modify it, you need to update data in the chart as well (via methods `setData` or `updateData`).

**Comment by awunder** [comment]
thank you for taking a look at it.. and sorry, i fixed the fiddle

https://jsfiddle.net/kxgo6c24/1/

the thing is, what i did is to replace this:

candleSeries.setData([
	{ time: '2018-10-19', open: 180.34, high: 180.99, low: 178.57, close: 179.85 },
	{ time: '2018-10-22', open: 180.82, high: 181.40, low: 177.56, close: 178.75 },
<..snip..>
])

with this:

fetch("https://alphatrade.finance/api/chart-data/day/4000.json")
  .then(function(response) {
    return response.json().then((data) => {
      instrument_15976_dayData = data;
    });
  });

so, shouldnt it just work out of the box?

**Comment by timocov** [comment]
Are you familiar with [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)? Why do you expect that `instrument_15976_weekData = data;` will change an object in the `instrument_15976_seriesesData` Map?

**Comment by awunder** [comment]
well, when i let it show me instrument_15976_seriesesData  in the console, it has an aray of hashes.. (?)

**Comment by awunder** [comment]
hmm.. at least it did locally, it doesnt in the jsfiddle..

**Comment by awunder** [comment]
fwiw, i made it work.. refactored a bit to load the data not upfront but when switching the interval..

```
function syncToInterval(instrument_15976_interval) {
                if (instrument_15976_candleSeries) {
                    instrument_15976_chart.removeSeries(instrument_15976_candleSeries);
                    instrument_15976_candleSeries = null;
                }
                instrument_15976_candleSeries = instrument_15976_chart.addCandleSeries({
                    topColor: 'rgba(76, 175, 80, 0.56)',
                    bottomColor: 'rgba(76, 175, 80, 0.04)',
                    lineColor: 'rgba(76, 175, 80, 1)',
                    lineWidth: 2,
                });
                fetch("/api/chart-data/" + time_lookup.get(instrument_15976_interval)+ "/15976")
                    .then(function(response) {
                        return response.json().then((data) => {
                            instrument_15976_candleSeries.setData(data.map(candle => {
                                return {
                                    time: candle.time,
                                    open: candle.open,
                                    high: candle.high,
                                    low: candle.low,
                                    close: candle.close,
                                };
                            }));
                        });
                    });
            }
```

thanks again for your help Evgeniy, appreciate that a lot!

**Comment by timocov** [comment]
Great! So, for now your issue is solved?

**Comment by awunder** [comment]
it certainly is, thank you.
