### ISSUE TITLE
integrate the lightweight-charts in asp.net website

### ISSUE THREAD

**Issue by transgraph** [tradingview/lightweight-charts#472]
Hai,
I want to integrate the lightweight-charts library and widgets in my asp.net application.

My website using charting library. and my website devoloped based on asp.net framework.
My web site url: http://host.transrisk.net/charting/
So please suggest the how to integrate the lightweight-charts library and widgets in my website.

**Comment by timocov** [comment]
I'm afraid it'd be better to ask such questions in [Discord chat](https://github.com/tradingview/lightweight-charts/issues/241) or on [stackoverflow.com](https://stackoverflow.com/questions/tagged/lightweight-charts) because it doesn't related to the lightweight-charts itself.
