### ISSUE TITLE
Correctly handle `overlay: true` in series options while create series to backward compat

### ISSUE THREAD

**Issue by AlexKnyazyuk** [tradingview/lightweight-charts#475]
Hi,
I use latest standalone js file from 
https://unpkg.com/lightweight-charts@3.0.0/dist/lightweight-charts.standalone.production.js
I wan't to have an ability to make subscription on scrolling event for load more data to chart.
I found such methods 
[subscribeVisibleTimeRangeChange](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#subscribeVisibleTimeRangeChange)
[subscribeVisibleLogicalRangeChange](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#subscribeVisibleLogicalRangeChange)
But when i try to call them, i have next error:
`Uncaught TypeError: chart.timeScale(...).subscribeVisibleTimeRangeChange is not a function`
Can you explain what's wrong?

**Comment by timocov** [comment]
Hi there,

are you sure that you use the latest version?

I just tried to reproduce it on https://jsfiddle.net/wa2t6zbx/1/ and it works fine.

**Comment by AlexKnyazyuk** [comment]
Hmm, it is very interesting, 
i found the link on version 3.0 in src of page witch you attached.
https://unpkg.com/lightweight-charts@3.0.0/dist/lightweight-charts.standalone.production.js
You distribute this version just yesterday. Thanks

**Comment by AlexKnyazyuk** [comment]
I try test it with 2 types of charts and it looks broken
https://jsfiddle.net/b31phf9e/1/

**Comment by AlexKnyazyuk** [comment]
I found solution, just add `priceScaleId` to second series

**Comment by timocov** [comment]
It looks like we didn't handle correctly passing `overlay: true` for backward compatibility while creating the series (https://github.com/tradingview/lightweight-charts/blob/master/docs/3.0-breaking-changes.md#creating-overlay), but handle it while applying an options to the series.
