### ISSUE TITLE
Lost ability to resize based on screensize (ver 3.0.0)

### ISSUE THREAD

**Issue by tghilardi** [tradingview/lightweight-charts#476]
Great work on the new 3.0.0 version!

**Lightweight Charts Version:** 

3.0.0

**Steps/code to reproduce:**

Prior to 3.0.0, I was able to resize my charts based on screensize using the code below. 3.0.0 doesn't allow it anymore. Any workarounds?

```
chart.resize(document.querySelector('.chartd').offsetHeight, document.querySelector('.chartd').offsetWidth);
```

Before:

![image](https://user-images.githubusercontent.com/2612420/84426223-3acde580-abf9-11ea-9043-8435d3e51214.png)

After 3.0.0 switch:

![image](https://user-images.githubusercontent.com/2612420/84426166-2689e880-abf9-11ea-948e-b06849c92f38.png)

**Comment by timocov** [comment]
What previous version you used? Is it <2.0, right?

**Comment by tghilardi** [comment]
Right.

**Comment by timocov** [comment]
See #157, it might be related. It was breaking change in 2.0 - we changed order of width and height parameters of resize method.

**Comment by tghilardi** [comment]
That was it. Thanks.
