### ISSUE TITLE
Allow setting bar series data in array format.

### ISSUE THREAD

**Issue by b4git** [tradingview/lightweight-charts#480]
**Is your feature request related to a problem? Please describe.**

Most of the times we are dealing with  the financial data which are stored in a plain numeric array format of OHLC (open, high, low, close) with timestamp at the beginning and volume (sometimes optional) at the end of the array.

`type CandleStickOHLCArray = [timestampInEpochMilliseconds: number, open: number, high: number, low: number, close: number, volume?: number] ;`

Example use:

```
let myCandle: CandleStickOHLCArray = [1592213302578, 200.10, 204.90, 198.70, 202.50, 1000];
```

**Describe the solution you'd like**

It would be ideal if the library API could directly support or accept that array data type when setting as it seems more natural or possibly (someone can verify) efficient than converting to object literals as the API currently requires.

**Additional context**

Current Library API use case:

```
barSeries.update({
    time: '2018-12-19',
    open: 141.77,
    high: 170.39,
    low: 120.25,
    close: 145.72,
});
```
After this feature request support, it would also be possible to directly send the OHLC array element:

```
barSeries.update([1592213302578, 200.10, 204.90, 198.70, 202.50, 1000]);
```

This might also align better with the spirit of this API of being "lightweight".

**Comment by timocov** [comment]
> It would be ideal if the library API could directly support or accept that array data type when setting as it seems more natural or possibly (someone can verify) efficient than converting to object literals as the API currently requires.

Can't use just re-map that array of arrays to array of object like `data.map(x=>({open: x[0], high: x[1], low: x[2], close: x[3]}))`? Is some issue here? I'm sure there is a lot of other data formats could be exist (including binary like protobuf), but we can't adopt the library to cover all of them. Instead, we support the only 1 format, which is pretty readable and understandable (it looks like so), in which you can convert any of formats you're using.

> This might also align better with the spirit of this API of being "lightweight".

I don't think that having a support of providing values as arrays is related to whether the library is "lightweight" or not. The topic is about API readability, and I don't think that having arrays instead/in additional to objects we have right now is good idea though. It's really good to transfer the data between server/client, but you can easily convert it the data format we require.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
