### ISSUE TITLE
Applying watermark in setTimeout doesn't make an effect

### ISSUE THREAD

**Issue by qy20092011** [tradingview/lightweight-charts#485]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
It is not effective when i use setTimeout to set applyOptions

**Actual behavior:**

**Expected behavior:**

**Screenshots**
![image](https://user-images.githubusercontent.com/28330610/84986300-ee425700-b170-11ea-9500-d9f9f1119c2e.png)
![image](https://user-images.githubusercontent.com/28330610/84986350-03b78100-b171-11ea-920d-8e2570e31896.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Yeah, looks like a bug. Meantime, may I ask to provide a repro code please?

**Comment by timocov** [comment]
Never mind, I reproduce it 😉

**Comment by qy20092011** [comment]
> Never mind, I've reproduced it 😉

Sorry for the delayed response, it may just be a minor bug!
