### ISSUE TITLE
Tighten the price axis

### ISSUE THREAD

**Issue by hypo-thesis** [tradingview/lightweight-charts#489]
I am not sure how to make the the numbers on the Y axis to shrink because the candles I have are way too long. How to make them shorter without touching the width of the chart?

**Comment by timocov** [comment]
Not sure that understand you issue. Can you elaborate a bit please?

**Comment by hypo-thesis** [comment]
> Not sure that understand you issue. Can you elaborate a bit please?

[Here](https://s7.gifyu.com/images/dsfsdfsdf.gif) as you can see the price axis needs to be shrunk down as the candles are too long. How can I make this squeeze by default so I don't have to use mouse ?

**Comment by timocov** [comment]
So you want to change price range somehow?

**Comment by hypo-thesis** [comment]
Did you see the GIF I posted ? The price axis varies by 1 unit of price for example initially it is 1000 and the next is 1001. I wish it to be 1000 to 1020 so 20 by 20 so that it squeezes the candles into smaller sizes. Is there a prop it to ?

**Comment by timocov** [comment]
> Did you see the GIF I posted ?

Yes I saw it and don't quite understand your issue and what you're trying to achieve.

Can you provide screenshots what you currently have and what you're trying to achieve with highlighting key parts please?

**Comment by hypo-thesis** [comment]
[Click on this link to see the picture ](https://i.ibb.co/Y7261KV/nmnmnm.jpg)

As you can see the price axis goes by 1 so 26280, 26281 and so on....

When I grab the price axis by mouse I can make it shorter and the numbers go by 10s or 20s so they look like 26280 , 26300 , 26320 which makes the candles shorter.

Is it possible to achieve this ?  [here is a GIF of me doing it](https://s7.gifyu.com/images/dsfsdfsdf.gif)

**Comment by timocov** [comment]
It's impossible to modify this in that way. The library uses internal algorithm to generate tick marks on the price scale (depending on height of the price axis, price range, text size, etc).

May I ask you why do you need this?

**Comment by hypo-thesis** [comment]
I can change it on Tradingview and it stays the same. I was wondering if this was possible on this library too. 

I just need it for visual purposes as you may know the changes could be erratic and having only 1 difference in some stocks can mean 1/3 of the screen is being filled by a second which looks odd. 

Is there a way to at least keep it at the numbers after mouse adjustment ?

**Comment by timocov** [comment]
> I can change it on Tradingview and it stays the same.

If I understand you correctly, you're talking about saving/restoring price range. lightweight-charts doesn't provide any saving/restoring feature out-of-the-box, so you need to implement it yourself.

Currently we don't have a feature to getting/setting price range to the price scale. If you'd like, we can create an issue for that (or just rename this one).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by BleileJustin** [comment]
Im not sure if this is where I do this but my data is in fractions of pennies. Such as 0.012532 and there is no way to get any ticks at all for numbers that small. Tick precision would be very beneficial if it could be set similarly to priceFormat.

![Screen Shot 2022-11-23 at 2 23 47 AM](https://user-images.githubusercontent.com/25036525/203511226-b9124df4-23ad-487e-af6e-1088ec7eda4a.png)
