### ISSUE TITLE
How can i get point coordinate on canvas (x, y)

### ISSUE THREAD

**Issue by denistol** [tradingview/lightweight-charts#490]
Hi.
I can get coordinates if use subscribe `subscribeCrosshairMove`
But, how get coordinates without subscribe ?

**Comment by denistol** [comment]
I found this way `const points = [...areaSeries._series.J._items]`
But not sure if this is the right approach

**Comment by timocov** [comment]
> But, how get coordinates without subscribe ?

Coordinates of what?

> But not sure if this is the right approach

This is completely non-documented, incorrect approach, which won't work in 3.0 and might be broker between updates (because since 3.0 we've started to minify all internal fields/methods).

**Comment by denistol** [comment]
> Coordinates of what?
last point coordinates for example

**Comment by timocov** [comment]
If you know the price, you can convert it to the coordinate by using https://github.com/tradingview/lightweight-charts/blob/master/src/api/iseries-api.ts#L42-L47.

**Comment by denistol** [comment]
But this method return only Y coordinate

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/v3.0.1/src/api/itime-scale-api.ts#L69-L74 to get X coordinate.
