### ISSUE TITLE
Plot price zones

### ISSUE THREAD

**Issue by RichieZFX** [tradingview/lightweight-charts#498]
Is there a way to draw a price zone between two price lines and color the zone with a parameterized alpha value? Such as the green zone in my screenshot, but I'd like to set the alpha value of the filled color. Thanks.

![lightweight](https://user-images.githubusercontent.com/66101586/85817354-552ec400-b7a0-11ea-8fea-c30709954a3b.png)

**Comment by timocov** [comment]
Do you want to emulate something like multi-pane support #50 ?

**Comment by RichieZFX** [comment]
> Do you want to emulate something like multi-pane support #50 ?

I've tried this. There are two main issues. First, correct color blending is required in the overlapping area from both areaseries, such that this area has same color as the background. This can be done. However, the second issue is a show stopper. Any other line series drawn within this overlapping area will be covered (refer to attachment). 
![lightweightchart](https://user-images.githubusercontent.com/66101586/86084281-04d0a280-bacf-11ea-98d6-db2e4a7328ff.PNG)

**Comment by timocov** [comment]
Sorry, but I don't quite understand what you want. What is this “price zone" for?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
