### ISSUE TITLE
Drawing extended lines passing through any two price (O, H, L, C) points.

### ISSUE THREAD

**Issue by b4git** [tradingview/lightweight-charts#501]
How to draw lines between any two price points (o, h, l, c) of the candlestick bars to make a trend line that can extend to left or right or both directions?

Currently, a line segment can be drawn by simply creating a new series and adding two data points.

Extending left or right by creating a custom series manually using y = mx + b formula seems plausible, but a direct straight-forward API method would be more appropriate.

Note: this concern was posted on Discord and Stackoverflow as well, but was informed to post it here as well.

**Comment by timocov** [comment]
Replied on stackoverflow https://stackoverflow.com/a/62635193/3893439.

> Note: this concern was posted on Discord and Stackoverflow as well, but was informed to post it here as well.

Please do not duplicate questions on all available platforms. We're monitoring them and will answer sooner or later.
