### ISSUE TITLE
Charts have stopped displaying any data 

### ISSUE THREAD

**Issue by JawBreaker66** [tradingview/lightweight-charts#502]
I've been using Lightweight Charts for months without issue, and suddenly they have stopped displaying any data at all. The charts are rendering the axes and grid lines, but not the actual series'.  
 
This is happening on several different pages in my website, and on my localhost and online versions of the site, and in different browsers. I have not changed the code at all and I don't know what is causing this problem.

**Comment by Lastly** [comment]
Same issue for me.  Also, charts were ignoring parameters like mouseWheel. I reverted back to version 3.0.0 for now.

**Comment by RichieZFX** [comment]
> Same issue for me. Also, charts were ignoring parameters like mouseWheel. I reverted back to version 3.0.0 for now.

Hi, same issue here. How do i revert back to 3.0.0? thanks.

**Comment by RichieZFX** [comment]
> > Same issue for me. Also, charts were ignoring parameters like mouseWheel. I reverted back to version 3.0.0 for now.
> 
> Hi, same issue here. How do i revert back to 3.0.0? thanks.

Ok, managed to build v3.0.0 using NPM.

**Comment by dubmarm** [comment]
Same issue here. General debugging in the browser makes me suspect of the .setData() method for a Series.

**Comment by dubmarm** [comment]
If you don't use npm, and use unpkg instead you can change your <script> to the following address for 3.0.0

`<script src="https://unpkg.com/lightweight-charts@3.0.0/dist/lightweight-charts.standalone.production.js"></script>`

**Comment by RichieZFX** [comment]
> If you don't use npm, and use unpkg instead you can change your <script> to the following address for 3.0.0
> 
> `<script src="https://unpkg.com/lightweight-charts@3.0.0/dist/lightweight-charts.standalone.production.js"></script>`

Didn't know that. Thank you!

**Comment by JawBreaker66** [comment]
Thanks for the tips! It's working for me too. Hopefully the bug in the updated version will be fixed soon. Is there any way to log this as an issue to be fixed, or is that already done by this chain?

**Comment by timocov** [comment]
Can anyone in the thread provide a repro for the issue? Yesterday we've published 3.1 version, maybe something is changed there.

**Comment by timocov** [comment]
It seems that the issue is related to production build only.

**Comment by timocov** [comment]
I found the issue. The new version will be published soon.

**Comment by JawBreaker66** [comment]
Great, thanks Evgeniy! I look forward to the update.

**Comment by timocov** [comment]
The version 3.1.1 is just published with the fix. Sorry for inconvenience.

**Comment by romfrancois** [comment]
Hi @nichita-pasecinic !
You would have to provide some details as to what's not working and if you already have tried a few things / checks so we could better assist.

**Comment by romfrancois** [comment]
For those stumbling upon and wondering a workaround has been suggested [here](https://github.com/tradingview/lightweight-charts/issues/1356#issuecomment-1543768856).
