### ISSUE TITLE
Update area series having whitespaces

### ISSUE THREAD

**Issue by sysopsnw18** [tradingview/lightweight-charts#504]
Thanks for adding whitespaces support for area chart. 
I need to plot chart from 9.15 to 3.30. I am able to do that because of whitespaces support. 
Now I need to update area series in certain intervals. I tried using series.update function for the same but its giving below error.

**Uncaught Error: Cannot update oldest data, last time=1593617460, new time=1593603000**

How to update existing whitespace data?

**Comment by timocov** [comment]
You need to use `setData` to update the past data.

**Comment by sysopsnw18** [comment]
> You need to use `setData` to update the past data.

Hi,
As per documentation setData **Allows to set/replace all existing data with new one.**
I don't want to replace the existing series. Just need to update specific past data. 
Is this possible?

**Comment by timocov** [comment]
> I don't want to replace the existing series.

Not series, data of the one specific series.

> Just need to update specific past data.

As I said, to update data in the past (not the last bar) you have to use `setData`.

**Comment by sysopsnw18** [comment]
> > I don't want to replace the existing series.
> 
> Not series, data of the one specific series.
> 
> > Just need to update specific past data.
> 
> As I said, to update data in the past (not the last bar) you have to use `setData`.

Hi,
Will you please help me with more details. Below are screenshots of chart
1 - On page load chart- We have data till 10.30
![image](https://user-images.githubusercontent.com/61038438/86345737-8c5a1500-bc79-11ea-963a-b83ff8f3b88e.png)

2 - After 10 seconds - when we get more data through ajax call and we use **setData** method on exiting areaseries, chart changes to 
![image](https://user-images.githubusercontent.com/61038438/86345955-dc38dc00-bc79-11ea-9edf-cac4068bebd2.png)

Let me know if we are missing anything here.

Thanks

**Comment by timocov** [comment]
In your case I can suggest you create another "empty" series, which will have whitespaces only (it could be any type of series actually). So, you'll be able to use `update` method to update the last bar/add the new one, and meantime extend time scale with "predictions":

```js
const whitespacesSeries = chart.addLineSeries();
const seriesWithData = chart.addAreaSeries();
whitespacesSeries.setData([/* place "whitespaces" here including all data you'd like to see on the chart */]);

seriesWithData.setData([/* set actual data here without whitespaces */]);
// ...

// when new bar/data update comes
seriesWithData.update(item);
```

**Comment by sysopsnw18** [comment]
> In your case I can suggest you create another "empty" series, which will have whitespaces only (it could be any type of series actually). So, you'll be able to use `update` method to update the last bar/add the new one, and meantime extend time scale with "predictions":
> 
> ```js
> const whitespacesSeries = chart.addLineSeries();
> const seriesWithData = chart.addAreaSeries();
> whitespacesSeries.setData([/* place "whitespaces" here including all data you'd like to see on the chart */]);
> 
> seriesWithData.setData([/* set actual data here without whitespaces */]);
> // ...
> 
> // when new bar/data update comes
> seriesWithData.update(item);
> ```

Hi,
I tried above solution. But still not working. Please find attached screenshot for errors

![image](https://user-images.githubusercontent.com/61038438/86434179-68024500-bd1a-11ea-968e-dd7b47663e11.png)

How to resolve this?

**Comment by timocov** [comment]
Hey @sysopsnw18,

if you try to update the past data in the series, it won't work either. _To update the past data you have to use `setData` method_.

The solution with another series for whitespaces could be good approach to provide your own "extrapolations" (in the future) on the time scale for all series at the time. If you still want to update the past data - you need to use `setData`.
