### ISSUE TITLE
Random uncaught exception from mouse event

### ISSUE THREAD

**Issue by RichieZFX** [tradingview/lightweight-charts#507]
I start receiving uncaught exceptions after plotting more series on the chart (attached). This happens when I click on the chart to plot something but doesn't always happen. It's hard to reproduce and from the call stack it's not from my code.

Anyone has experienced this before? thanks.

![lightweightchart](https://user-images.githubusercontent.com/66101586/86309140-9403c480-bc4d-11ea-8c0c-7e86c8a4a70b.PNG)

**Comment by timocov** [comment]
It's strange. It'd be really useful to have reproducing of the problem somehow.

**Comment by RichieZFX** [comment]
> It's strange. It'd be really useful to have reproducing of the problem somehow.

I suspect it's related with overlapping lines. However, I can't seem to reproduce it. Anyway, it doesn't seem to have any impact other than appearing in console log.

**Comment by timocov** [comment]
@RichieZFX do you have any updates here?

**Comment by timocov** [comment]
@RichieZFX I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
