### ISSUE TITLE
How to set the time axis labels to show in minutes or seconds label?

### ISSUE THREAD

**Issue by b4git** [tradingview/lightweight-charts#508]
Fiddle link: https://jsfiddle.net/t79wgz4u/3/

When plotting seconds level timeframe, the time scale label is simply showing only the day number irrespective of the zoom in/out level.  Which doesn't make  much sense for smaller timeframes. How to properly show or format the time-axis to show the time in minutes or seconds 
 -- something such as 08:30:15 in hh:mm:ss  format?

Also, is it possible to use timeframes smaller than seconds ? Can the UTCTimestamp be in milliseconds or nanoseconds? For example: plotting a real-time sensor sensor data which can be milliseconds or even smaller.

**Comment by timocov** [comment]
> -- something such as 08:30:15 in hh:mm:ss format?

See `timeVisible` and `secondsVisible` https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options.

> Also, is it possible to use timeframes smaller than seconds ? Can the UTCTimestamp be in milliseconds or nanoseconds? For example: plotting a real-time sensor sensor data which can be milliseconds or even smaller.

We don't have out-of-the-box, but you can try. It's possible that you have to implement `tickMarkFormatter` https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options. But I guess it won't work :(

**Comment by leeoniya** [comment]
@b4git 

> For example: plotting a real-time sensor sensor data which can be milliseconds or even smaller.

you can give [uPlot](https://github.com/leeoniya/uPlot) a try for cases like this, which can natively go down to `ms` since that's the max resolution supported by JavaScript's `Date` objects. going down to micro or nanoseconds basically means you need to create the chart with a numeric but non-temporal x-axis and just format the ticks as offsets from some known initial `ms` timestamp. it doesn't make much sense at these scales to show calendar-aware, DST & timezone-respecting year/month/day anyhow. see https://github.com/leeoniya/uPlot/issues/111 for previous discussion.

**Comment by b4git** [comment]
@leeoniya  Thanks. From first glance, uPlot seems to be the right choice for my task. I will certainly consider testing it.

**Comment by jazoom** [comment]
`timeVisible: true` really should be default. I thought I was dealing with a weird bug.

**Comment by stavalfi** [comment]
> `timeVisible: true` really should be default. I thought I was dealing with a weird bug. The day number just keeps repeating itself on intraday timeframes, which is useless, and `tickMarkType` never returned `TickMarkType.Time` or `TickMarkType.TimeWithSeconds`, only `TickMarkType.DayOfMonth`.

@jazoom  how did you make `tickMarkType` return `TickMarkType.Time `or `TickMarkType.TimeWithSeconds`?

**Comment by jazoom** [comment]
@stavalfi this was 2 years ago but I assume the answer is that I set `timeVisible: true`
