### ISSUE TITLE
Chart issue on windows safari browser

### ISSUE THREAD

**Issue by sysopsnw18** [tradingview/lightweight-charts#510]
Unable to load chart on windows safari browser(version 5.1.7)

Error:
TypeError: '[object HTMLMapElement]' is not a constructor (evaluating 'new Map')

**Comment by timocov** [comment]
Did you use polyfills? I guess it's very outdated and don't support some features (it looks even worse than ie11).

From https://support.apple.com/en-us/HT204416:

> Apple no longer offers Safari updates for Windows. Safari 5.1.7 for Windows was the last version made for Windows, and it is now outdated.
> Published Date: **September 24, 2018**

**Comment by timocov** [comment]
As soon this browser isn't supported by Apple since 2018 I'm strongly don't recommend you to use it (and even support). And we won't support it. But anyway, try to use polyfills (see https://github.com/tradingview/lightweight-charts/issues/101#issuecomment-517117573 as example).
