### ISSUE TITLE
Crosshair doesn't work on touch devices

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#511]
I have created a short example to show the issues. The chart works on desktop and ipad, but not on iphone:
https://florian-kittel.github.io/lightweightCharts-mobile-debug/

Setup is as basisc as possible. I used the public version from mentioned production build from the docs.

Repo link if intrested in the code:
https://github.com/florian-kittel/lightweightCharts-mobile-debug/tree/master

When changing the chart version back to 2.0.0 cross-hair on mobile will work in this example.

_Originally posted by @florian-kittel in https://github.com/tradingview/lightweight-charts/issues/434#issuecomment-653740598_

**Comment by timocov** [comment]
For me it looks like this:

![image](https://user-images.githubusercontent.com/3112183/86591762-de14df00-bf9a-11ea-96b6-1f1e6cf44016.png)

And I can't move the crosshair.

**Comment by timocov** [comment]
Found a bug. Will fix shortly.

**Comment by timocov** [comment]
Version 3.1.2 with the fix is just published.

**Comment by florian-kittel** [comment]
Thanks for fixing. Works fine.

**Comment by Rishabh-Streak** [comment]
@timocov  i am using version 3.1.2 i have disabled handleScroll and handleScale and crosshair touch is not working

**Comment by timocov** [comment]
@Rishabh-Streak that's about https://github.com/tradingview/lightweight-charts/issues/434#issuecomment-666924467?

**Comment by Rishabh-Streak** [comment]
> @Rishabh-Streak that's about [#434 (comment)](https://github.com/tradingview/lightweight-charts/issues/434#issuecomment-666924467)?

Yes
