### ISSUE TITLE
API to get color of the bar/candlestick item

### ISSUE THREAD

**Issue by nakcyber** [tradingview/lightweight-charts#518]
Hi, lightweight-charts team
Is it possible to get `barStyle()` via an index in the series chart in lightweight-charts v3.1.2 ?
I used to `barStyle()` for get color in lightweight-charts v2.0.0

```
var candleSeries = chart.addCandlestickSeries();
var color = candleSeries.series().barColorer().barStyle(index);
```

example Information obtained from the `barStyle()`
{
barBorderColor: "rgb(229, 68, 95)"
barColor: "rgb(229, 68, 95)"
barWickColor: "rgb(229, 68, 95)"
}

Now it doesn't work. Can I have another method to use instead?

I want to get `barStyle()` method because my app chart has a legend feature a color the same as the bar color.

![image](https://user-images.githubusercontent.com/20948117/86869036-066a1e00-c100-11ea-9920-a301deb97998.png)
![image](https://user-images.githubusercontent.com/20948117/86869087-1e41a200-c100-11ea-9e34-5c91c75f1b95.png)
![image](https://user-images.githubusercontent.com/20948117/86869118-2ef21800-c100-11ea-943d-5fcdf5b8cbf6.png)

**Lightweight Charts Version:** 3.1.2

**Comment by timocov** [comment]
The issue we need to pay attention here is custom colors per bar item (available for histogram atm, but could bew implemented in other series soon in #195). If you don't use custom colors - you can do it easily by getting color from options (for bars logic of choosing a color is pretty simple).

**Comment by emrahtunc14** [comment]
How can I get the candle color on mouseover from charts that are like candle type?

**Comment by emrahtunc14** [comment]
any body here?

**Comment by SlicedSilver** [comment]
At the moment, you can't get the colour directly from the API but you can work around this to get it working.

The colour of the candlestick is either based on whether the it is higher or lower than the previous value, or set by the data itself. 

The crosshair event (https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IChartApi#subscribecrosshairmove) contains a `time` property which you could use to either check the colour you've set in the data, or find the previous value and compare it's value to determine the expect colour.

**Comment by GanatraJay2000** [comment]
Hi! Has there been any new updates for this or do we still need to use the work-around??
