### ISSUE TITLE
Create candlestick series not working in v 3.1.2 

### ISSUE THREAD

**Issue by nakcyber** [tradingview/lightweight-charts#521]
Hi, lightweight-charts team
I try to create candlestick series in lightweight-charts v.3.1.2,
I found an error in console `Uncaught Error: Value is null`

![image](https://user-images.githubusercontent.com/20948117/87031973-14a66000-c20e-11ea-938d-54716e49fce5.png)

**Lightweight Charts Version:** 3.1.2

**Actual behavior:** Show Uncaught Error: Value is null;

**Expected behavior:**  Don't show Uncaught Error: Value is null;

**CodeSandbox/JSFiddle/etc link:** https://jsfiddle.net/cyberdev1992/2vadx735/12/

**Comment by timocov** [comment]
```
              { time: '2019-04-21', open: 131.33, high: 151.17, low: 77.68, close: 96.43 },
              { time: '2019-04-21', open: 106.33, high: 110.20, low: 90.39, close: 98.10 },
```

You have 2 points with the same time, that's the reason.

**Comment by timocov** [comment]
We'll improve our error handling in #315
