### ISSUE TITLE
Library not working on my angular 7 project

### ISSUE THREAD

**Issue by xxholyChalicexx** [tradingview/lightweight-charts#524]
- Have installed this package using "npm install lightweight-charts".

- Have added this line of import to the component that is using the chat.
import { createChart } from 'lightweight-charts';

But now i am getting this error while compiling:
`ERROR in node_modules/lightweight-charts/dist/typings.d.ts(87,87): error TS1005: '?' expected.
node_modules/lightweight-charts/dist/typings.d.ts(87,99): error TS1005: ':' expected.
node_modules/lightweight-charts/dist/typings.d.ts(87,110): error TS1005: ';' expected.
node_modules/lightweight-charts/dist/typings.d.ts(87,127): error TS1005: ';' expected.
node_modules/lightweight-charts/dist/typings.d.ts(87,146): error TS1005: '(' expected.
node_modules/lightweight-charts/dist/typings.d.ts(88,1): error TS1128: Declaration or statement expected.`

### package.json file

> {
  "name": "myproj",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "~7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@r3droger/windowref": "0.0.1",
    "@types/selectize": "^0.12.34",
    "angular-bootstrap-md": "^7.5.3",
    "angular-google-charts": "^1.1.4",
    "angular-plotly.js": "^2.0.0",
    "angularx-social-login": "^2.2.1",
    "bulma": "^0.8.0",
    "chart.js": "^2.9.2",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highcharts": "^8.1.2",
    "highcharts-angular": "^2.4.0",
    "lightweight-charts": "^3.1.2",
    "ng-selectize": "^1.1.3",
    "ng2-charts": "^2.3.0",
    "ng2-search-filter": "^0.5.1",
    "plotly.js": "^1.54.6",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.0.0",
    "sweetalert2": "^8.13.0",
    "tslib": "^1.9.0",
    "window": "^4.2.6",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.2.0",
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "brotli-webpack-plugin": "^1.1.0",
    "codelyzer": "~4.5.0",
    "compression-webpack-plugin": "^4.0.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.0"
  }
}

**Comment by timocov** [comment]
> "typescript": "~3.2.0"

I'm afraid this is the reason. It's outdated version of TypeScript (current version is 3.9, 4.0 will be released in a month or so). Can you update it and try again?

**Comment by xxholyChalicexx** [comment]
ok...i guess will do that.!
