### ISSUE TITLE
Reseting the price scale

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#525]
I set the initial data for the graph. Then set the time and price axis scaling using the left mouse button. Next, I set new data for the graph. And to display the chart, you need to reset the price axis by double-clicking the left mouse button. How to make an automatic reset of the price axis after installation of the new data for the graph?

Help, please )

**Comment by timocov** [comment]
> How to make an automatic reset of the price axis after installation of the new data for the graph?

You can enable `autoScale` option via `applyOptions` of price scale.

**Comment by onur-celik** [comment]
here is the code
`chart.priceScale().applyOptions({autoScale : true})`

**Comment by Discordia** [comment]
Just a helpful note.

Two things that I missed are:
1. It did not work without 'right'. So `chart.priceScale('right').applyOptions({autoScale : true})`.
2. I needed to do it before I called setData on the series.
