### ISSUE TITLE
Event when data is updated in the series

### ISSUE THREAD

**Issue by dtanp** [tradingview/lightweight-charts#530]
Hi Team,

I create my own legend and I want the legend automatically updated to the latest price when the new data is added or modified. Currently, the new data can be updated via `update()` or `setData()` in series object but I don't see in the documentation how to get notified so I can re-render my legend accordingly.

Any suggestion would be much appreciated.

Cheers!

**Comment by timocov** [comment]
> Currently, the new data can be updated via update() or setData() in series object but I don't see in the documentation how to get notified so I can re-render my legend accordingly.

But it's you who call `update` or `setData` methods, isn't it? 🤔 I mean, you can control all places where you call that methods and update the legend there?

**Comment by dtanp** [comment]
That's fair statement and I agree that generally it's true. My situation is that I wrap lightweight chart as a webcomponent and when developer updates the data, they access lightweight chart API directly but the legend is part of webcomponent. 

The component doesn't know when developer is going to update the data. Our solution right now is to listen to timescale range changed event but it's not quite correct because not all updates will trigger this event.

So the recommendation to our developers is to pass the whole config i.e. to render the whole chart when they want to update the data.

Another solution that we're thinking is to provide `updateLegend()` method so developers can use this method to refresh the legend. However, we can't find API in lightweight to get list of series and we need information to construct the legend.

**Comment by timocov** [comment]
Thanks! I agree with that.

There are several open questions:

1. What's the target for that event. Series? Chart? Timescale?
1. If it's a series, should an event be emitted when timescale is changed (but series data isn't)?
1. Should we generate any event for series markers?
1. Anything about an options?

**Comment by dtanp** [comment]
Hi @timocov !

Currently we're using `subscribeVisibleTimeRangeChange` in https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md.

Does it have other event that we can listen for data changes?

I tend to agree with you that developers should know when they update the data so in theory, they can call some sort of method in the component to update the legend. As I mention above, we can't find getter API for list of series that currently displaying in the chart.

If you agree that it'll be useful if chart exposes new API for getting the series, we can close this issue and open a new one with a better description.

**Comment by timocov** [comment]
> As I mention above, the deal breaker is that we can't find getter API for list of series that currently displaying in the chart.

Did you mean just all series we currently have on the chart, right? Or something else?

> If you agree that it'll be useful if chart exposes new API for getting the series, we can close this issue and open a new one with a better description.

Yes, your sample sounds reasonable for me 👍 

> Does it have other event that we can listen for data changes?

You can look at https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#subscribevisiblelogicalrangechange, but I don't think that it's more suitable for your case (it allows you handle every change of visible range, even floating changes like shifting for 0.5 of bar).

**Comment by dtanp** [comment]
@timocov Thanks for your support. I will close this issue as the event when data is updated in the series is no longer need for me. I'll open a new issue about new API to get series pointer that using in the chart later. :)

**Comment by timocov** [comment]
> I will close this issue as the event when data is updated in the series is no longer need for me

I think this is unnecessary, because it might be needed for someone else :) Let's leave it open for now and wait some feedback.
