### ISSUE TITLE
Markers doesn't show and disappears on Chrome/Chromium browsers.

### ISSUE THREAD

**Issue by Dwyte** [tradingview/lightweight-charts#534]
**Lightweight Charts Version:** 3.1.2

**Steps/code to reproduce:**
Set Markers on a chart using chrome/chromium browsers.

**Actual behavior:**
Some of markers are not showing on chrome/chromium, and some disappears depending on the zoom.

**Expected behavior:**
All markers should show normally like on Firefox.

**Screenshots:**

On Firefox:
![Screenshot from 2020-07-25 21-10-25](https://user-images.githubusercontent.com/30210654/88457926-a1167b00-cebc-11ea-9056-a56481f44da2.png)

On Chrome:
![Screenshot from 2020-07-25 21-09-53](https://user-images.githubusercontent.com/30210654/88457939-bc818600-cebc-11ea-842d-2dcb4015d51e.png)

On Chrome (Zoomed in a bit):
![Screenshot from 2020-07-25 21-09-44](https://user-images.githubusercontent.com/30210654/88458091-fd2dcf00-cebd-11ea-8c4e-d75b2f1badd4.png)

- Mango and Dalandan markers are missing.
- Fruit suddenly disappeared on zoom.
- Sometimes if there are 2 markers on the same candle instead of behaving like on firefox (one marker below, then the other one above it) it will plot the markers on the same y position so texts become unreadable. (Didn't got a screenshot on this one, but I swear I've seen one)

Browsers used:
Firefox, Brave Browser and Chrome

**Comment by timocov** [comment]
Do you a jsfiddle-repro for that? Meanwhile, please check that all your markers are sorted in asc order by time.

**Comment by Dwyte** [comment]
@timocov yep, they are sorted in ascending order by time. It's all good on firefox.

**Comment by timocov** [comment]
Can you try to do the following:
1. Build your app with development build (every lightweight-charts version has development version in it https://unpkg.com/browse/lightweight-charts@3.1.5/dist/) and check whether there is any error or warning?
1. What format of the date you're using for shapes?
1. Provide jsfiddle example of the repro? We have a bunch of graphics tests based on chromium (we use puppeteer) and didn't see similar issues there yet.

**Comment by Dwyte** [comment]
Okie, to answer #2 the format I use is just the epoch timestamp of the candle for the shapes.

**Comment by canselcik** [comment]
I'm having the same issue. Some markers disappear when zoomed in or panned to a certain area, despite still being in range and should/would be drawn.

**Comment by kovalu** [comment]
Yes, I ran into the same issue (both Chrome and Firefox) and sorting the array helped.
Then I noticed that even the documention mentions that it needs to be sorted...

> An array must be sorted ascending by _time_.

https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#setmarkers

**Comment by timocov** [comment]
> It could be a feature request for the library to sort it automatically internally, so it's not a user's responsibility.

@kovalu Sorting array might affect performance, and if you pass a huge _sorted_ array, it might take some time for no reason. A user must sort it before pass it to the library, because it's a requirement of the library (which is declared in the docs as well). We'll warn about that in #315 in debug mode only, so it won't affect your production build, but you have no difference in behaviour between debug and production builds.

**Comment by timocov** [comment]
It seems that all issues are related to order of the data, so I'm going to close the issue. Feel free to ping me or re-create the issue (or re-open this one) if you'll find something else.
