### ISSUE TITLE
Mouse click doesn't work on mobile platform

### ISSUE THREAD

**Issue by RichieZFX** [tradingview/lightweight-charts#539]
I'm using chart.subscribeClick to attach a function to mouse click. It works perfectly using desktop browser. However, it doesn't work on any mobile browsers. I've tried both chrome and ios browser. Anything I need to configure to make it work? Thanks.

**Comment by timocov** [comment]
I just tried 

```js
		chart.subscribeClick(function() {
			alert('hey');
		});
```

and it works fine. Can you please provide a repro for that?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by fhassis** [comment]
I am having this issue as well in v3.8.0. This does not happen in v3.2.0 (this is the version I last used the library, and tested against it). I tested the same code in the browser on PC (it works) and in android and browser PC with mobile device emulation (both did not work).

**Comment by adammoisa** [comment]
+1 no click event happening when chart is tapped on mobile. Works fine on desktop.

**Comment by romfrancois** [comment]
Would you guys have a small reproduction we could inspect that highlight the issue?

**Comment by amanpatodia1** [comment]
on lightWeight chart , in android native we are try to show crossHair on tap and when user release finger we are hiding it, but when user tap again on different position the crosshair is visible at last x,y position why ? 
please give solution.
