### ISSUE TITLE
points on area series chart

### ISSUE THREAD

**Issue by nihal9ns** [tradingview/lightweight-charts#541]
Hey, I have a use case where I want to display the points on an area series charts as highlighted. I could not find this option in the docs (please correct me if I am wrong). But it would be good to have this if it does not exist.
<img width="539" alt="example" src="https://user-images.githubusercontent.com/30690618/89280950-f72ab180-d666-11ea-8667-9e768ca57868.png">

In the image, we can see an area series, I want to show all the points on the area series as highlighted dots as we can see when we hover over the chart.

<img width="540" alt="example2" src="https://user-images.githubusercontent.com/30690618/89281150-47a20f00-d667-11ea-88d4-798326d90dd0.png">

Check the highlighted dot on the chart.

Please suggest!

**Comment by timocov** [comment]
You can try to use series markers for that, but they don't provide you ability to control hovering state though.

**Comment by Linganna** [comment]
Hey, I tried to search the docs for series markers, was not able to find them. Can you point it out to me?

I just want all the points to be highlighted even when I am not hovering. I hope series markers can solve?

**Comment by nihal9ns** [comment]
Hey, I searched the docs, but could not find series markers. Can you guide me through?

I just want to highlight all the points even when I am not hovering. I hope series markers can solve?

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#setmarkers

**Comment by nihal9ns** [comment]
Thanks!
