### ISSUE TITLE
TradingView add data dynamically at Android

### ISSUE THREAD

**Issue by ugar0ff** [tradingview/lightweight-charts#542]
Good day everyone!

I started work with TradingView.
How can I add and update bars from an Android app programmatically? What me need send in `webView.evaluateJavascript(...)` ?

**Comment by timocov** [comment]
Are you using "Technical Analysis Charts" https://github.com/tradingview/lightweight-charts-android/issues/1#issue-673602854? Even if you aren't, how android's wrapper is related to this repo?
