### ISSUE TITLE
Prevent bold font in time series

### ISSUE THREAD

**Issue by devduke** [tradingview/lightweight-charts#545]
How do I prevent the font in the time series from being automatically bolded (as shown below @ 08 20:01:00)? I'd like to have the time series show only "font-weight: normal" and not bold.

<img width="748" alt="time-series" src="https://user-images.githubusercontent.com/14028544/89732280-9b23ac80-da1b-11ea-8907-cd57900ff7e1.png">

**Comment by kirchet** [comment]
There is no way to do it for now

**Comment by timocov** [comment]
Currently there is no way to do it. We use bold font there to highlight some "big" changes on the timescale. Just wonder why here you have `08 20:01:00` highlighted instead of `09 02:01:00`. Maybe it's timezone issue? Do you have -4 offset?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
