### ISSUE TITLE
display the chart in expanded form to avoid whitespaces

### ISSUE THREAD

**Issue by nihal9ns** [tradingview/lightweight-charts#546]
Hey

I am trying to plot a chart and it looks like this :

![image](https://user-images.githubusercontent.com/30690618/90008387-dba05600-dcb9-11ea-9e74-c27d306cc1d6.png)

You see, there is a lot of white space around and the line is being plot at one side of the chart.

Is there a way where I can get rid of the white spaces around and show the line expanded throughout the chart so that it takes up all the white space. 

Something like this :
![image](https://user-images.githubusercontent.com/30690618/90008622-45b8fb00-dcba-11ea-8301-c8cc847b7079.png)

This is after the chart was expanded, can we plot it in this way by default to avoid the white space without zooming in manually?

**Comment by timocov** [comment]
> Is there a way where I can get rid of the white spaces around and show the line expanded throughout the chart so that it takes up all the white space.

See https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#fitcontent and `fixLeftEdge` https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options

**Comment by Linganna** [comment]
Thanks!

**Comment by nihal9ns** [comment]
Thanks!
