### ISSUE TITLE
Line series incorrect rendering in v 3.1.5

### ISSUE THREAD

**Issue by nakcyber** [tradingview/lightweight-charts#547]
Hi, lightweight-charts team
I create line series in lightweight-charts v.3.1.5,
I found incorrect rendering a line chart.

![image](https://user-images.githubusercontent.com/20948117/91009798-86ded280-e60b-11ea-83d0-224a53972842.png)

But I found that in version 3.0.1 it displayed correctly.

![image](https://user-images.githubusercontent.com/20948117/91009835-9bbb6600-e60b-11ea-82a1-09c942cf18a9.png)

**Lightweight Charts Version:** 3.1.5

**CodeSandbox/JSFiddle/etc link:**
v3.0.1 : https://jsfiddle.net/cyberdev1992/og92ajr1/4/
v3.1.5 : https://jsfiddle.net/cyberdev1992/rf4zmy50/1/

**Comment by timocov** [comment]
Did you see an error `Error: Invalid date string=2018-02-29, expected format=yyyy-mm-dd`? 2018 isn't leap year though, there is no 29th Feb.
