### ISSUE TITLE
How to plot multiple charts wit different colors using TradingView lightweight library?

### ISSUE THREAD

**Issue by hooshbartar** [tradingview/lightweight-charts#548]
I am trying to plot two different charts(with different lenghth) using following code, but don't know how to specify colors for my charts? Also not sure will following code plot two charts in same TradingView window or not?

    this.apiService.predictor(this.selectedStock ,this.startDay,this.endDay).subscribe((results) => {
      const lineSeries = this.chart.addLineSeries()

        for(let result of results[0]['prediction_value']) {
          console.log("the result1 is" , result);
          lineSeries.update({time : result.time , value : result.price})
        }
      const lineSeries2 = this.chart.addLineSeries()

        for(let result of results[0]['real_value']) {
          console.log("the result2 is" , result);

          lineSeries.update({time : result.time , value : result.price})
        }

The `result` arrays are something like below:

    the result1 is {price: 18, time: "2019-09-28"}
    the result1 is {price: 68, time: "2019-10-01"}
    the result1 is {price: 5, time: "2019-10-04"}
    the result1 is {price: 11, time: "2019-10-07"}
    the result1 is {price: 8, time: "2019-10-11"}
    the result1 is {price: 14, time: "2019-10-14"}

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/master/docs/line-series.md#customization

**Comment by hooshbartar** [comment]
> See https://github.com/tradingview/lightweight-charts/blob/master/docs/line-series.md#customization

What about multiple lines in one chart?

**Comment by timocov** [comment]
Did you try to create several series? See https://jsfiddle.net/TradingView/srwoh679/
