### ISSUE TITLE
timeScale() changes visible range on setData()

### ISSUE THREAD

**Issue by beholderrk** [tradingview/lightweight-charts#549]
Based on https://stackoverflow.com/questions/63557823/lightweight-charts-timescale-changes-visiblerange-on-setdata/63562298#63562298
 
**Lightweight Charts Version:** 3.1.5

**Actual behavior:**

`setData` move to right visible range of `timeScale`

**Expected behavior:**

`setData` shouldn't set visible range of `timeScale`

**Screenshots:**

![kOl3nMpiwY](https://user-images.githubusercontent.com/841755/91054753-86a2ff00-e62c-11ea-92b7-db409bcdf3d5.gif)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/beholderrk/916g3tcf/3/

**Comment by timocov** [comment]
Actually that's ok that data of visible range is changed (because it is based on series' data), but the issue is that the library moved visual visible range. Quite probably we need to introduce method `prepend` or so here...

**Comment by beholderrk** [comment]
I'm not sure I can properly edit the description of the issue, since I don't really understand how setData should work. Perhaps adding a new api like `prepend` would be a better solution.

**Comment by beholderrk** [comment]
Another small video which shows problem.
* if you change the scale of time axis, the graph behaves correctly
* if you move the visible range and then change scale, the graph goes into an endless additional load, because it can't detect state when it's visible area completelly full.

![IGIGs3LeIi](https://user-images.githubusercontent.com/841755/91064474-f79be400-e637-11ea-85c2-b14455033e0e.gif)

**Comment by f-dg** [comment]
to prevent scrolling forward when setData:
`chart.timeScale().applyOptions({
  shiftVisibleRangeOnNewBar: true
})`

more [here](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#shiftvisiblerangeonnewbar)
