### ISSUE TITLE
[bug] Price: Precision of 5 and MinMove: 0.00001 create error of unexpected base

### ISSUE THREAD

**Issue by nothingalike** [tradingview/lightweight-charts#55]
below is the candlestick options and error output. Please note that precision of 3, 4, and 6 work fine. 5 is the only issue im seeing. Trying to display Forex data

![image](https://user-images.githubusercontent.com/638507/59315685-c6303600-8c88-11e9-9a1d-a5d7c7e9d1f7.png)

![image](https://user-images.githubusercontent.com/638507/59315568-3e4a2c00-8c88-11e9-934e-1eb8a7564a6c.png)

**Comment by timocov** [comment]
https://0.30000000000000004.com/ 🙂

**Comment by timocov** [comment]
[1.0.0-rc.4](https://www.npmjs.com/package/lightweight-charts/v/1.0.0-rc.4) has been published with the fix.

**Comment by nothingalike** [comment]
awesome, thank you.
