### ISSUE TITLE
Memory leak error

### ISSUE THREAD

**Issue by ayumi-cloud** [tradingview/lightweight-charts#552]
![image](https://user-images.githubusercontent.com/57409060/91201259-22e60800-e6f8-11ea-9683-e15dda958404.png)

Code line:

https://www.tradingview.com/static/bundles/main_chart.9e3236750f775607a03d.js:195

Happens in Google Canary for last 4 days - errors increase every milliseconds.

Google Canary Version 87.0.4243.0 (Official Build) canary (64-bit)

This is on a desktop computer opening any trading chart on tradingview! With no templates, indicators or anything loaded - just a fresh new chart.

**Comment by timocov** [comment]
This repo isn't related to TradingView's website. If you have any issues there - please contact website's support.

**Comment by ayumi-cloud** [comment]
@timocov you got a link I can go to ? I cant find any official repo for it.

**Comment by timocov** [comment]
@ayumi-cloud https://www.tradingview.com/?support
