### ISSUE TITLE
Getting x and y coordinates of a line series

### ISSUE THREAD

**Issue by Ranjeet-Naidu** [tradingview/lightweight-charts#553]
Is there an API that returns (x, y) coordinates for a line series. For example `series.getCoordinates(time, price)` will return `{x: 'x', y: 'y'}`. Since `setData` takes a series of `{time, value}` and plots on the canvas. Is there anyway to access that data?

**Comment by timocov** [comment]
To get x coordinate see https://github.com/tradingview/lightweight-charts/blob/v3.1.5/docs/time-scale.md#timetocoordinate, to get price one see https://github.com/tradingview/lightweight-charts/blob/8251f53d60b65ed8d899ae7c7c9527654538ab72/src/api/iseries-api.ts#L44-L50

**Comment by timocov** [comment]
> Is there anyway to access that data?

See #530 and #414
