### ISSUE TITLE
descending time order data not show

### ISSUE THREAD

**Issue by Usey95** [tradingview/lightweight-charts#554]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
apply descending time order data to the series

**Actual behavior:**

series disappeared

**Expected behavior:**

display normally

**CodeSandbox/JSFiddle/etc link:**

any jsfiddle in https://www.tradingview.com/lightweight-charts/, just reverse the data you set.

**Comment by timocov** [comment]
This is by design and I don't think that we'll change this in the future. Lightweight charts are designed to display financial data, do you have any example where data in descending time order is useful?

**Comment by Usey95** [comment]
> This is by design and I don't think that we'll change this in the future. Lightweight charts are designed to display financial data, do you have any example where data in descending time order is useful?

Well, it works fine in previous version. Sometimes we can't decide what the data source is like, maybe giving a warning is  helpful.

**Comment by timocov** [comment]
> maybe giving a warning is helpful.

See #315

**Comment by Usey95** [comment]
> > maybe giving a warning is helpful.
> 
> See #315

Cool👍🏻
