### ISSUE TITLE
Run "sh -c npm run install-hooks" error, exit code 1

### ISSUE THREAD

**Issue by zhaokui525** [tradingview/lightweight-charts#559]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

Execute npm install after download

**Actual behavior:**

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zk/.npminstall_tarball/_logs/2020-09-02T07_06_19_652Z-debug.log
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c npm run install-hooks" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c npm run install-hooks" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

**Expected behavior:**

Successfully executed and run the project

**Comment by timocov** [comment]
Any reproduction or additional log?

**Comment by zhaokui525** [comment]
<img width="594" alt="截屏2020-09-02 16 04 30" src="https://user-images.githubusercontent.com/12828843/91955692-2ac82c80-ed36-11ea-8929-bc3fd4ce7b1e.png">
<img width="582" alt="截屏2020-09-02 16 04 51" src="https://user-images.githubusercontent.com/12828843/91955713-2f8ce080-ed36-11ea-943e-161cf21bbd55.png">
<img width="587" alt="截屏2020-09-02 16 05 18" src="https://user-images.githubusercontent.com/12828843/91955716-30257700-ed36-11ea-824e-52c2ce32d4b0.png">

**Comment by timocov** [comment]
It seems that you're outside of the repo (there is no `.git` folder) that why installing githooks is failed. Can you use `git clone` instead of downloading repo state from GitHub without git repo itself? Anyway, I think we can work about that instead of fail.

**Comment by timocov** [comment]
I hope https://github.com/tradingview/lightweight-charts/commit/a8c5c8fec85e548c9f1be665c3307093e282e63f should fix it.

**Comment by zhaokui525** [comment]
I'm trying your method. In fact, it doesn't matter whether it can run successfully. What's more, I want to see how the specific parameters are set. However, I haven't seen the corresponding documents so far.

In addition, I would like to ask whether the package price of the official website is only the price of chart, or the price of chart plus data source, thank you.

**Comment by timocov** [comment]
> In addition, I would like to ask whether the package price of the official website is only the price of chart, or the price of chart plus data source, thank you.

Not sure that got your question.

**Comment by zhaokui525** [comment]
I execute git clone https://github.com/tradingview/lightweight-charts.git And then execute NPM install, or the previous error.

What I want to ask is, does your company also provide data source services, or only provide charts, and if so, where is the price list.

**Comment by timocov** [comment]
Afaik we don't provide any data services at the moment.

**Comment by zhaokui525** [comment]
Really? That is to say, the above data are not available, right? So many categories are not available.

Do you have any specific documentation for the initial question? Thank you

**Comment by zhaokui525** [comment]
Is all this data unusable

<img width="987" alt="截屏2020-09-02 16 50 57" src="https://user-images.githubusercontent.com/12828843/91960451-81386980-ed3c-11ea-9c70-edd7ec61d29c.png">

**Comment by timocov** [comment]
If your questions are related to www.tradingview.com website, please ask questions there via contacting support. If you have any question related lightweight-charts (not bug or feature request), please ask on stackoverflow. Let's keep this issue tracker for bug and features only.

**Comment by zhaokui525** [comment]
well. This is still a mistake before the report. What should I do

**Comment by timocov** [comment]
Can you provide steps to reproduce your issue?

**Comment by zhaokui525** [comment]
1. Execution: git clone https://github.com/tradingview/lightweight-charts.git

2. Execution: NPM install

**Comment by timocov** [comment]
```
$ git clone https://github.com/tradingview/lightweight-charts.git
Cloning into 'lightweight-charts'...
remote: Enumerating objects: 198, done.
remote: Counting objects: 100% (198/198), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 7681 (delta 105), reused 106 (delta 42), pack-reused 7483
Receiving objects: 100% (7681/7681), 5.71 MiB | 906.00 KiB/s, done.
Resolving deltas: 100% (5741/5741), done.

$ cd lightweight-charts/

$ npm i
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

> puppeteer@5.0.0 install C:\projects\temp\lightweight-charts\node_modules\puppeteer
> node install.js

Downloading Chromium r756035 - 144.6 Mb [====================] 100% 0.0s
Chromium (756035) downloaded to C:\projects\temp\lightweight-charts\node_modules\puppeteer\.local-chromium\win64-756035

> lightweight-charts@3.2.0 postinstall C:\projects\temp\lightweight-charts
> npm run install-hooks


> lightweight-charts@3.2.0 install-hooks C:\projects\temp\lightweight-charts
> node scripts/githooks/install.js

Installing githooks...
Installed to C:/projects/temp/lightweight-charts
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN tslint-microsoft-contrib@6.2.0 requires a peer of tslint@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 611 packages from 423 contributors and audited 616 packages in 83.742s

68 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

$ echo $?
0
```

**Comment by zhaokui525** [comment]
There's only one reason. Maybe it's because I'm in China. Can you package and distribute your whole project, including dependency packages, to me. Thank you very much. zhaokui525@163.com Or zhaokui525@gmail.com

**Comment by timocov** [comment]
I'm not sure that I can help you with that at the moment, unfortunately. If it's the issue with puppeteer and downloading chromium, you can set env variable (see in your log that message).

**Comment by kirchet** [comment]
>Maybe it's because I'm in China.

You can use VPN in this case
