### ISSUE TITLE
subscribeCrosshairMove for Candleseries

### ISSUE THREAD

**Issue by nvoisin** [tradingview/lightweight-charts#56]
Hi,

I'm unable to retrieve open, high, low, close in subscribeCrosshairMove param object with CandleSeries. Is there a way to achieve this ?
The only thing I manage to retrieve is a single value which I assume is the close (I think) : 
`const price = param.seriesPrices.get(this.oCandleSeries);`

Thanks,

**Comment by timocov** [comment]
It's a bug, we need to have a structure instead of just value in `seriesPrices` values (with all current values).

As workaround you can search that data in the original data array (by time).

**Comment by nvoisin** [comment]
Ok will do thanks!

**Comment by timocov** [comment]
The [version 1.0.0](https://www.npmjs.com/package/lightweight-charts/v/1.0.0) is just published.
