### ISSUE TITLE
Pull drawn candles

### ISSUE THREAD

**Issue by mattou78400** [tradingview/lightweight-charts#561]
**Is your feature request related to a problem? Please describe.**

Its incredibly frustrating to pull the candles drawn on the chart instance

**Describe the solution you'd like**

The best would be to have a function returning displayedCandles(chartInstance) --> 
[
{timestamp: XXX,
open: XXX
high: XXX
low: XXX
close: XXX}
...]

**Additional context**

this is how I currently do it but it seems to be browser specific and not portable
`
for (let serie of chart.activeSeries) {
          if (serie.id == 'price'){
            for (const k of chart.getSerie(serie.id).api.G_.ed.V_.keys()) {
              if (k.ui == -1){
                for (let candle of k.G.ma){
                  if (candle.V.Ss >= (visibleRange.from-this.timeframe*31))
                  displayedCandles.push({
                    timestamp : candle.V.Ss,
                    open : candle.Z[0],
                    high : candle.Z[1],
                    low : candle.Z[2],
                    close : candle.Z[3],
                  })
                }
              }
              }
          }
        }
`

**Comment by timocov** [comment]
Please post your thoughts and suggestions in #414
