### ISSUE TITLE
Markers not showing as expected with 1-sec data

### ISSUE THREAD

**Issue by tschirmer** [tradingview/lightweight-charts#565]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

set Markers on line series:
```
        this.chartSeries = chart.addLineSeries(this.options);

        this.chartSeries.setData(this.data);
        this.chartSeries.setMarkers([
          {
            time: this.data[0].time,

            color: '#f68410',
            shape: 'square',
            text: 'D',
            size: 15
          },
          {
            time: this.data[parseInt(this.data.length/2)].time,
            position: "belowBar",
            color: '#f68410',
            shape: 'circle',
            text: 'D',
            size: 20
          },
          {
            time: this.data[this.data.length -1].time,
            position: "aboveBar",
            color: '#f68410',
            shape: 'square',
            text: 'D',
            size: 1
          }
        ]);
```

**Actual behavior:**

Markers are not shown "belowBar" and "aboveBar" as expected. The only orange marker that's visible where position is not defined.

**Expected behavior:**

Markers are should be shown "belowBar" and "aboveBar" as expected. 

**Screenshots:**

![lightwieghtChartsBug](https://user-images.githubusercontent.com/3872130/92317454-0923b980-f044-11ea-8a43-e066840d26d2.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by tschirmer** [comment]
Found the Problem - The data I was passing through (value) was a string (not a float). As a string, it was rendering the graph, but not able to add the marker. probably worth a quick parseFloat within the marker renderer.

**Comment by timocov** [comment]
> The data I was passing through (value) was a string (not a float). 

Which one? Is the issue solved now?

**Comment by tschirmer** [comment]
each marker now shows. But the graph shows with a string value in the datapoint` {time: unitTimestamp, value: "20.0"},` but the marker won't render.

after changing the datapoint to the format: ` {time: unitTimestamp, value: 20.0 },` it renders fine. 

Ideally, this would either fail to render on the string value (and force all users to put in the correct float value), or render the markers with the string value. for consistency.

**Comment by timocov** [comment]
> Ideally, this would either fail to render on the string value (and force all users to put in the correct float value), or render the markers with the string value. for consistency.

See #315
