### ISSUE TITLE
How to add buffer animation to price jump

### ISSUE THREAD

**Issue by liubin595338764** [tradingview/lightweight-charts#567]
How to add buffer animation when price jumps
`areaSeries.update`

![GIF1](https://user-images.githubusercontent.com/5274428/92709043-2e3c6300-f389-11ea-95c8-5f0d94822235.gif)

**Comment by timocov** [comment]
Related to #254.

It's currently impossible. I'm not sure how many users this features is needed though.

**Comment by timocov** [comment]
But anyway whether we decide it implement it, I don't think that it will be easy to do, because of making animations on a canvas inside the whole application might be hard (paining comes from one side, invalidating from another one, etc).

**Comment by liubin595338764** [comment]
> But anyway whether we decide it implement it, I don't think that it will be easy to do, because of making animations on a canvas inside the whole application might be hard (paining comes from one side, invalidating from another one, etc).

It's great. We're looking forward to it

Now users are not satisfied with the ordinary K-line chart, the interesting animation effect is more attractive

**Comment by hellogiex** [comment]
Its definitely a great feature,  looking forward to it as well

**Comment by hx6509** [comment]
ChartIQ offers the feature, but I don't think it is as simple to adopt as tradingview

https://jsfiddle.net/chartiq/6fqw652z/

**Comment by hiendv** [comment]
@timocov Thanks for taking up the feature. Can we have an update on the progress please? Thank you!

**Comment by Thimows** [comment]
@timocov Any updates on this? This is really a must have for a chart library

**Comment by Thimows** [comment]
@timocov Any updates on this? This is really a must have for a chart library. Thanks!

**Comment by timocov** [comment]
If you're interesting in this feature, you can put your 👍 to the topic message, please don't post messages like "any updates?" - we'll post updates if we have any.

As I said in https://github.com/tradingview/lightweight-charts/issues/567#issuecomment-690204172, it's quite complicated thing to implement, it's not just wrap animation in rAF though.

**Comment by habib3962** [comment]
👍
