### ISSUE TITLE
Incorrect PriceScale calculation leading to few values not visible in chart by default

### ISSUE THREAD

**Issue by Rishabh-Streak** [tradingview/lightweight-charts#570]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
https://jsfiddle.net/n53h21pe/  <- this is demo of the issue

**Actual behavior:**

Expected all values to be visible in chart
![Screenshot 2020-09-16 at 12 34 08 PM](https://user-images.githubusercontent.com/53012197/93303411-0c276280-f819-11ea-89ea-e2d3213d251f.png)

**Expected behavior:**

This is after i adjust the priceScale manually
![Screenshot 2020-09-16 at 12 34 30 PM](https://user-images.githubusercontent.com/53012197/93303461-1ba6ab80-f819-11ea-96c4-1c7e9f0ead8d.png)

**Comment by timocov** [comment]
That's because your values are strings, not numbers `"value": "0.00"`. Related to #315
