### ISSUE TITLE
Strange behaviour when adding data on the right and left

### ISSUE THREAD

**Issue by beholderrk** [tradingview/lightweight-charts#574]
**Lightweight Charts Version:** master 9f52e942

**Steps/code to reproduce:**
* Add 2 series
* Add whitespace between series
* Add data to right series and then to left

**Actual behavior:**
Points in right seria shift to left on data added to left seria
![Ikf1171EhC](https://user-images.githubusercontent.com/841755/93583349-67d62500-f9ac-11ea-9e54-d80d2eb0d080.gif)

**Expected behavior:**
Points in right seria doesn't shift

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/beholderrk/83juqxvL/3/

**Comment by timocov** [comment]
The reason of that is duplicated data. In `generateData` function you have to start from `from` date + 1 day (rather that just from `from` date), and while adding data to the left you have to add N (20 in your sample) bars since N+1 day back. We'll warn about duplicated data in #315

**Comment by beholderrk** [comment]
Got it thanks
