### ISSUE TITLE
Graph moves on render when lastValueVisible is true in combination with volume price formatter (or any string formatter I think)

### ISSUE THREAD

**Issue by matthewlilley** [tradingview/lightweight-charts#582]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

https://codesandbox.io/s/nifty-beaver-r0w90

**Actual behavior:**

Graph moves on render

**Expected behavior:**

It should no cause the graph to move on render

**Comment by timocov** [comment]
I'd say that there is "eventual consistency" of the view, because of lazy data invalidation and validate-on-demand approach we're using in the library, but I think it'd be better to investigate what's going on and whether it's possible to reduce unnecessary redraw with changing size.

**Comment by matthewlilley** [comment]
@timocov when the lastValueVisible is numeric, it seems to always draw correctly the first time. It's when the price formatter is switched to type: "volume" where the addition draw happens, or even just adding a "$" with the localisation formatting option.

**Comment by timocov** [comment]
@matthewlilley could you please add more details what is going on wrong (probably with video/gif)? I just opened the page and I didn't noticed any glitch there, so probably I missed/forgot about something (I tried to uncomment type of formatter as well).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.
