### ISSUE TITLE
Turn a logical index into time, or get the current viewport time range

### ISSUE THREAD

**Issue by benma** [tradingview/lightweight-charts#583]
Hi

I have some chart data that I show for the past three months.

I am trying to figure out a way how to get the actual date range of the timescale when the user drags or zooms the chart, so that data from different date/time ranges can be dynamically loaded and shown.

`temp1.timeScale().getVisibleRange()` only gives me the range of the current data shown, not the "viewport".

The closest I could see that could help was `timeScale().getVisibleLogicalRange()`, which gives me logical offsets. I don't see a way how I can convert those into a time however, which I want use to fetch and display the data starting at that time.

Is there a way?

Thanks

**Comment by timocov** [comment]
> the range of the current data shown, not the "viewport".

What's the difference? 🤔 

`lightweight-charts` doesn't know actual time range which _could be_ on the chart right now if there is no data prior or after data. You can get logical range to get logical visible indexes and then convert them to BarsInfo for a specific series by using https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#barsinlogicalrange method, it contains a time of left and right bars, and also, if applied, barsBefore and barsAfter values.

**Comment by benma** [comment]
For example:

![image](https://user-images.githubusercontent.com/1225267/94124527-68ac0280-fe55-11ea-95d2-99180b3cc2cf.png)

The data starts somewhere slightly before 2017. I scrolled to the left, now there is a lot of empty space, and the timescale is unlabeled left of 2017.

What I hoped to achieve was to be able to get the time of the viewport, which in the picture would be somewhere around 2014 or 2015, so I can fill up the whole visible viewport with chart data.

The logical offset at the first chart point is 0, and the leftmost visible point is in my current example -825 (which is the same as the `barsBefore` in `barsInLogicalRange()`), but I am not sure if there is a way to convert this into a time, so I know from which time to fetch chart data.

I hope that makes it clearer?

As a workaround, I will just load all the data I have, but with less granularity in the past, to not overwhelm the chart with too many points. Ideally though it could be dynamic depending on where the user scrolls and zooms to.

**Comment by timocov** [comment]
> What I hoped to achieve was to be able to get the time of the viewport, which in the picture would be somewhere around 2014 or 2015 to roughly July 2019, so I can fill up the whole visible viewport with chart data.

This is out of scope of this library and I'm not sure that we'll change that in the future. It requires us to predict somehow what resolution you have and so on (including weekends and holidays - I'm 100% sure that right after we added some kind of "prediction" users will request to handle them as well).

You have to do it yourself, if you'd like. Since we introduced support for whitespaces, it should be easy to provide empty "bars" prior your data so we'll display times on the time scale.

> The logical offset at the first chart point is 0, and the leftmost visible point is in my current example -825 (which is the same as the barsBefore in barsInLogicalRange()), but I am not sure if there is a way to convert this into a time, so I know from which time to fetch chart data.

This means that you need to load 825 additional bars in the history since `from` time to fulfil viewport by data.

**Comment by timocov** [comment]
I should say that loading additional bars count instead of loading for specific date range (with dates instead) is much better and allows you avoid unnecessary requests when the library mismatch the dates it thinks should be there or if your data has gaps for instance due weekends or holidays.

**Comment by benma** [comment]
I see, thanks. I thought the timescale was linear, so I did not think about predictions etc. at all.

> I should say that loading additional bars count instead of loading for specific date range (with dates instead) is much better

What does bar mean exactly? How much time is one bar? What does it depend on?

**Comment by timocov** [comment]
> What does bar mean exactly? How much time is one bar? What does it depend on?

Under "bar" I meant "one data item", an item in the data array.

**Comment by benma** [comment]
Thanks!
