### ISSUE TITLE
Add coordinateToLogical and logicalToCoordinate

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#587]
**Is your feature request related to a problem? Please describe.**

I want to draw overlay using normal html elements on certain index of my data, and I need the x coordinate of certain logical bars, like image. At the moment this is using `coordinateToTime` and `timeToCoordinate`, which make sense for time -> time overlay, but I want to draw index -> index overlay so I keep converting index <-> time back and forth. And sometimes I need to draw overlay beyond the current data time range so I kinda need the logical coordinate for that.

![image](https://user-images.githubusercontent.com/1574722/95306696-ee966780-08b1-11eb-8238-5f642f46fc51.png)

**Describe the solution you'd like**

Add `coordinateToLogical` like [`coordinateToTime`](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#coordinatetotime), and`logicalToCoordinate` like [`timeToCoordinate`](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#timetocoordinate).

**Comment by timocov** [comment]
Sure thing! Feel free to make a PR.
