### ISSUE TITLE
Error: Cannot update oldest data, last time=1602514800, new time=1602514740

### ISSUE THREAD

**Issue by Kuzmich100kM** [tradingview/lightweight-charts#592]
I get this error periodically when updating chart data.
I understand that the problem is that the new_time < last_time, but the data comes through the websocket and I cannot change it.
This error crashes the browser, сan this be fixed or ignored?

**Comment by timocov** [comment]
> This error crashes the browser, сan this be fixed or ignored?

You can ignore these updates yourself, it's unnecessary to chart lightweight-charts.

> but the data comes through the websocket and I cannot change it.

I don't think that transporting a data via websocket is a problem itself. Quite probable the issue is with the order of updates, it doesn't related to the websocket.

**Comment by JessseG** [comment]
@Kuzmich100kM ——> Hey were you able to solve this? It seems I'm having the same issue?

**Comment by Kuzmich100kM** [comment]
> 
> 
> @Kuzmich100kM ——> Hey were you able to solve this? It seems I'm having the same issue?

I used my hook, which first checks that the new time is >= than the previous one.

**Comment by HartS** [comment]
Can this be reopened? The documented behaviour is that `update` should update candles if the times are the same: https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#update

If that doc is wrong, I'd be happy to make a PR to change the wording

**Comment by timocov** [comment]
> The documented behaviour is that update should update candles if the times are the same: 

Yes, the same as the latest bar's time `or updates the latest item if times of the passed/latest items are equal`.

> I'd be happy to clarify that updates need to be newer than existing candles, or not the same as them, or whatever is expected.

@HartS Do you have any problem with updating the latest bar by using `update` method?

**Comment by HartS** [comment]
@timocov yes, I should have clarified that I was seeing this issue when trying to add new data to an existing chart, with the same timestamp listed for both `last time` and `new time` in this error (the timestamp of the latest bar before the update)

**Comment by timocov** [comment]
@HartS can you create a repro for that please?

**Comment by HartS** [comment]
@timocov I will have to do it when I'm working on that project/component again, may not be for another week or two, but I'll try to repro

**Comment by zeeshan-shabbir** [comment]
@timocov  i am getting same error due to i show future time  points using whitespace . when i update old point it give me error cant update old data . how can we update data when using whitespace(using for shows future time) ?

**Comment by timocov** [comment]
@zeeshan-shabbir I'd suggest you to create a separate "whitespace series" to work with whitespaces only so you will be able to update data for the series and don't touch whitespaces

**Comment by zeeshan-shabbir** [comment]
> 

sorry to bother but i didnt get it. should i create another series with just white space and update that series? OR there is a series called "whitespace series". Kindly guide me

**Comment by kandarpgautam** [comment]
I wonder why this issue was closed.

**Comment by godwynnn** [comment]
any solution on this please?

**Comment by 0x1af2aec8f957** [comment]
```ts
candlestickSeries.update(item, true)
```

**Comment by ulisesten** [comment]
You need to validate if the new data is older than the one yo try to update:

I'm testing this:

    export const safeUpdate = (series, newBar) => {
       if(!series) return;
       const lastBar = series.dataByIndex(series.data().length - 1); // último dato
       const newTime = newBar.time;

       // Si no hay datos todavía, agregamos directo
       if (!lastBar) {
            series.update(newBar);
            return;
        }

        // Validar que el nuevo tiempo sea mayor o igual al último
        if (typeof lastBar.time === 'object') {
            // Convertir { year, month, day } a timestamp para comparar
            const lastTimeStamp = new Date(
                lastBar.time.year,
                lastBar.time.month - 1,
                lastBar.time.day
            ).getTime() / 1000;

            if (newTime >= lastTimeStamp) {
                series.update(newBar);
            }
        } else if (newTime >= lastBar.time) {
            series.update(newBar);
        }
    }

Let me now if you have a better solution
