### ISSUE TITLE
The lowest and highest values are out of block

### ISSUE THREAD

**Issue by AndreyStepanchuk** [tradingview/lightweight-charts#593]
**Lightweight Charts Version:** 3.1.5

https://jsfiddle.net/6dv4z2wk/14/
data is [BTCUSDT](https://www.binance.com/en/futures/BTC_USDT) future with 1M kline from binance API

**Actual behavior:**

The lowest and highest values are out of block

**Expected behavior:**

All values must be visible

**Comment by timocov** [comment]
Don't use strings-like-numbers where numbers are expected, they aren't the same.
