### ISSUE TITLE
 How to make the price axis have more decimal places?

### ISSUE THREAD

**Issue by StrRoma** [tradingview/lightweight-charts#594]
Because price low I don't see right axis 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/62382321/96324251-8837e480-1029-11eb-8868-b9c1ad8f0807.png">
How I can add more decimals to right axis?

**Comment by StrRoma** [comment]
And how to make the height and width set automatically according to the parent container?

**Comment by RubberArchind** [comment]
@StrRoma you can use [price format](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format) to add more decimals to right axis

**Comment by StrRoma** [comment]
@RubberArchind thanks

**Comment by RubberArchind** [comment]
to make the height and width set automatically according to the parent container, simply don't set the width and the height when initializing the chart
