### ISSUE TITLE
One-point line series is invisible

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#597]
Hello.

If the data consists of a single value it is not displayed on the chart.

![Снимок экрана от 2020-10-21 16-54-17](https://user-images.githubusercontent.com/18750140/96730076-e3b9f780-13c6-11eb-843c-789fffe9eb02.png)

you need to search for this point with the mouse.

![Снимок экрана от 2020-10-21 16-54-20](https://user-images.githubusercontent.com/18750140/96730335-18c64a00-13c7-11eb-8168-21fbe2454a0f.png)

how do I make this one point visible?

Help please.
Thanks.

**Comment by RubberArchind** [comment]
can you show how you produce it, it will make it easier to help you

**Comment by timocov** [comment]
We'll show that "point" like a horizontal line for bar's width.
