### ISSUE TITLE
Chart draws second time on render() if I change state of a component. Using ReactJS

### ISSUE THREAD

**Issue by denbondd** [tradingview/lightweight-charts#602]
**Lightweight Charts Version**: 3.1.5

```javascript
import React from 'react'
import './Home.css'
import Graph from '../graph/Graph'
import MoreInfo from '../moreInfo/MoreInfo';

export default class Home extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            showMoreInfo: false
        };
    }

    changeState = () => {
        this.setState({
            showMoreInfo: !this.state.showMoreInfo
        });
    }

    render() {
        return (
            <div className='container'>
                <div className='more_info'>
                    {this.state.showMoreInfo && <MoreInfo />}
                </div>
                <div className='graphs'>
                    <Graph symbol='GOOGL' changeState={this.changeState} />
                </div>
            </div>
        )
    }
}
```

**Actual behavior:**

When i click on button to use method changeState, state changes, MoreInfo component shows, but chart is drawing again like this:
![Снимок экрана 2020-10-26 091953](https://user-images.githubusercontent.com/55474761/97144298-de650000-176c-11eb-9eb5-8ba5a1a6b228.png)
![Снимок экрана 2020-10-26 092013](https://user-images.githubusercontent.com/55474761/97144317-e58c0e00-176c-11eb-8f05-52e9382a1e56.png)

I've already checked even without MoreInfo component. If I just change state of parent Component, graph draws one more time. If I click again on button, it draws third time and so more. If I display a lot of charts, all of them draw one more time every button click.

Can you help me with it?
Thanks

**Comment by timocov** [comment]
> Can you help me with it?

So, what's the problem?

**Comment by denbondd** [comment]
That it draws again on every button click but shouldn't.

**Comment by timocov** [comment]
> That it draws again on every button click but shouldn't.

What do you mean? The chart makes re-render or what? How it's related to the issue's title? Can you create reproduction for that?

**Comment by denbondd** [comment]
If I didn't describe this problem well with project title, I'm sorry. Here's a video of the problem. Again, chart shouldn't draw second and third time, but it does after I change state of component
![proofs](https://user-images.githubusercontent.com/55474761/97209925-945c3880-17c5-11eb-86ec-6e43e9de490a.gif)

**Comment by timocov** [comment]
This issue isn't related to the lightweight-charts itself, it's related to react and how you wrap the library with react. I think that the issue is with `import Graph from '../graph/Graph'` component, which re-creates the widget every instead of using the previous one. But because it isn't related the library, please ask this question on stackoverflow https://stackoverflow.com/questions/tagged/lightweight-charts or in our discord chat https://discord.com/invite/E6UthXZ.

**Comment by denbondd** [comment]
As you said, the problem was with the code. Every time I getting new data from api, I used method createChart() and it made new chart. I fixed it by just passing data to an existed chart.

**Comment by MrSohaibAhmed** [comment]
How did u do that ? Please share  the code or explain
