### ISSUE TITLE
Update scales design

### ISSUE THREAD

**Issue by eugene-korobko** [tradingview/lightweight-charts#606]
Updates scales and its labels according to the attached design images

**Comment by eugene-korobko** [comment]
![cross-hair-label](https://user-images.githubusercontent.com/7079444/97542448-ca710680-19d7-11eb-9bea-f4e2716d39fb.png)

**Comment by eugene-korobko** [comment]
![series-labels](https://user-images.githubusercontent.com/7079444/97542467-d1981480-19d7-11eb-8d51-f7732c5e8780.png)

**Comment by eugene-korobko** [comment]
![time-scale](https://user-images.githubusercontent.com/7079444/97542506-e4aae480-19d7-11eb-9dcd-1f64f3aab01f.png)

**Comment by DTupalov** [comment]
@timocov @eugene-korobko, this issue only update actual price scale design or you give api to set custom design for labels?

Would I be able to make such design after closing this issue?
![image](https://user-images.githubusercontent.com/1331473/117111833-dbd50a00-ad90-11eb-8bbd-52e88999767c.png)

**Comment by timocov** [comment]
@DTupalov it's about updating the default design for price labels.

**Comment by thanhlmm** [comment]
Will it have `radius` settings @timocov ?

**Comment by timocov** [comment]
> Will it have radius settings @timocov ?

@thanhlmm Not in this change. Can you please create another issue for that so after this issue will be closed we can start to work on adding the new features/overrides.
