### ISSUE TITLE
Incorrect Selection seen on long press in ios webview on chart

### ISSUE THREAD

**Issue by jalpesh** [tradingview/lightweight-charts#609]
![Image from iOS](https://user-images.githubusercontent.com/204597/97773766-941ebd00-1b78-11eb-9f27-d5fac6d33bea.png)

On long press I get this odd blue selection seen in ios webview, any solutions for this?

**Comment by timocov** [comment]
Can you provide a repro for that? I thought we've disabled this in https://github.com/tradingview/lightweight-charts/blob/db0472d2c9b514a7523499c0a11f16cea0474756/src/gui/canvas-utils.ts#L68-L78, maybe you have overridden this props in your code?

**Comment by jalpesh** [comment]
No have not overridden the above.  I added the below CSS in my code to fix the issue. 

`<style type="text/css">
		*:not(input):not(textarea) {
		  -webkit-user-select: none; /* disable selection/Copy of UIWebView */
		  -webkit-touch-callout: none; /* disable the IOS popup when long-press on a link */
		}
		</style>`

It is only happening in ios in app webview when embedded from flutter and not in any other situation.

**Comment by timocov** [comment]
> It is only happening in ios in app webview when embedded from flutter and not in any other situation.

So if you use it in just webview without flutter it works? Can you create a repro for that please? Did you try to add the library by using https://github.com/tradingview/LightweightChartsIOS, does it have the same issue?

**Comment by jalpesh** [comment]
Yes I did add the lib, got the same issue. Will need to check in webview without flutter will ping here once I try to rep in that. For now I think we can close this issue since it is solved by adding the above mentioned css for me.

**Comment by timocov** [comment]
I'm able to reproduce it in just webview. ~Safari is new IE...~

We'll fix it.
