### ISSUE TITLE
lightweight chart sma indicator

### ISSUE THREAD

**Issue by elifaydemir** [tradingview/lightweight-charts#614]
**I'm trying to plot the sma indicator on the lightweight chart, but I don't know how to add it to the chart. I'm pulling the Sma data, but how do I add it to the chart?** By the way, I'm writing with javascript

**Comment by timocov** [comment]
You need to add line series with sma data.

As soon as this is a question and not related to the library's issues, I'm going to close the issue. If you have any question, please ask on stackoverflow or in discord chart.
