### ISSUE TITLE
Histogram changes scale on movement.

### ISSUE THREAD

**Issue by Kshitij-Banerjee** [tradingview/lightweight-charts#617]
When scrolling left and right. The volume series is jumping.

Normal view: 
![image](https://user-images.githubusercontent.com/1330389/99150150-7a7b8a80-26cd-11eb-91a8-7fe30598ce36.png)

On scrolling to the right. 
![image](https://user-images.githubusercontent.com/1330389/99150159-9121e180-26cd-11eb-90bc-f3ebb0b11b71.png)

I have the following options on. 

```
this.chart = createChart('price-chart', { width: 600,
      height: 400,
      rightPriceScale: {
      scaleMargins: {
        top: 0.1,
        bottom: 0.50,
      },
        borderVisible: false,
      },
      leftPriceScale: {
        visible: true,
        borderColor: 'rgba(197, 203, 206, 1)',
      },
    });


    const volumeSeries = this.chart.addHistogramSeries({
      title: 'volume',
      color: '#26a69a',
      priceFormat: {
        type: 'volume',
      },
      priceScaleId: '',
      scaleMargins: {
        top: 0.95,
        bottom: 0,
      },
    });
```

Is this expected ?How can i make the volume series not move around ?

**Comment by timocov** [comment]
What data you set to the series? Please check whether the data is numbers, not strings.

**Comment by timocov** [comment]
@Kshitij-Banerjee do you have any updates on this?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
