### ISSUE TITLE
Some dates are not showing on the time scale consistently

### ISSUE THREAD

**Issue by Dwyte** [tradingview/lightweight-charts#618]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**
1. Render a chart with some data and certain options, (JSFiddle Provided)

**Actual behavior:** Some dates are not showing on the timescale. See Image below, Nov 9 is not showing on the timescale. While it's consistent with others it's weird that 9 is no where to be seen. 4, 5, 6, no 7 since market is closed, 8, *then 12:00 of 9* instead of 9, then 10 and so on... Nov 9 has complete data. Screenshots below shows it on 30m and 1h candles.

**Expected behavior:** Show each date on the timescale consistently. 4,5,6,8,9,10, and so on...

**Screenshots:**

![2020-11-15_14-23](https://user-images.githubusercontent.com/30210654/99178639-4301f200-2750-11eb-8d01-5499be768ee3.png)
![2020-11-15_14-23_1](https://user-images.githubusercontent.com/30210654/99178641-45644c00-2750-11eb-9429-195536aa3181.png)

JSFIDDLE SCREENSHOT:
![2020-11-15_15-15](https://user-images.githubusercontent.com/30210654/99179136-798e3b80-2755-11eb-9641-e080fd0d6ba1.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/3b7kojxz/1/

Tested on Firefox and Chrome, same behavior.

**Comment by timocov** [comment]
> 8, then 12:00 of 9 instead of 9, then 10 and so on... Nov 9 has complete data.

What's about Nov 8? I see the only 2 points for Nov 8, when Nov 9 has about 20+ points. 

![chart](https://user-images.githubusercontent.com/3112183/99223774-32a45280-27f6-11eb-83e5-054d1a4e7b39.gif)

Is that ok that after Nov 6 21:00 there is **Nov 8** 22:00? Shouldn't it be Nov 6 22:00 instead? What's trading session of the data?

Another thing is that the library knows nothing about your trading session, it operates by dates only and try to make time scale consistent. If you know that there is some gaps in the data you can add them manually (via whitespaces for instance, or by just repeating bar).

**Comment by Dwyte** [comment]
Nov 6 21:00 Fri market closes, then Nov 8 22:00 Sun it opens again.

Ahhh like empty candles. On the main tradingview charts timescale shows fine even with these gaps, I assume they use more advance libs for that one. Anyway thanks, sorry for the late response.

**Comment by timocov** [comment]
> On the main tradingview charts timescale shows fine even with these gaps, I assume they use more advance libs for that one. Anyway thanks, sorry for the late response.

@Dwyte Afaik the algo for generating tick marks is pretty the same and I'm not sure that there is difference between them. Can you provide example where www.tradingview.com's chart show different picture for the same data?

**Comment by Dwyte** [comment]
@timocov here's a sample clip from the www.tradingview.com.

https://imgur.com/a/ETHci9R

Used the same timeframe, timerange, and instrument symbol as the example I have given before. Timescale worked perfectly fine here even with the gaps.

**Comment by timocov** [comment]
We'll investigate this. Perhaps tradingview.com uses trading session as well to generate time scale marks...

**Comment by timocov** [comment]
> Used the same timeframe, timerange, and instrument symbol as the example I have given before. Timescale worked perfectly fine here even with the gaps.

@Dwyte I just looked at GIF one more time and it looks like tradingview.com just shifts the start point? Thus instead of showing odd day numbers it shows even ones right? Is this the main difference? The code is pretty the same but then main difference that on tradingview.com we use displayed time to generate tick marks (with possible timezone offset), not UTC one.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
