### ISSUE TITLE
High and Lows disappearing when CandleStick chart is zoomed out

### ISSUE THREAD

**Issue by Dwyte** [tradingview/lightweight-charts#619]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

1.  Zoom out a CandleStick chart

**Actual behavior:** At a certain point the highs and the lows will just disappear.

**Expected behavior:** Highs and Lows shouldn't disappear.

**Screenshots:**
![2020-11-15_14-24](https://user-images.githubusercontent.com/30210654/99179259-ea822300-2756-11eb-8795-3610a7da7ee9.png)
![2020-11-15_14-24_1](https://user-images.githubusercontent.com/30210654/99179260-ec4be680-2756-11eb-8e77-11660ddbda62.png)

**CodeSandbox/JSFiddle/etc link:**
The issue also appears on the demo provided for CandleStick chart
https://www.tradingview.com/lightweight-charts/

**Comment by timocov** [comment]
> the highs and the lows will just disappear.

What do you mean? Can you please provide screenshot and highlight there what's going wrong?

**Comment by Dwyte** [comment]
Sorry for the late reply, the wicks are disappearing.
![image](https://user-images.githubusercontent.com/30210654/100330917-7ffc9d00-300a-11eb-9bf1-9461cc67668c.png)

**Comment by timocov** [comment]
@eugene-korobko can you please take a look?

**Comment by eugene-korobko** [comment]
Hello!

Could you please check your browser zoom settings? Is it 100%? Does the problem reproduce with 100% browser zoom?

**Comment by Dwyte** [comment]
Yes, the zoom is 100%

**Comment by timocov** [comment]
I just tried to reproduce the issue on https://jsfiddle.net/TradingView/eaod9Lq8/ and no luck. @Dwyte can you please record a video of the issue? Also, what `devicePixelRatio` you have?

**Comment by Dwyte** [comment]
devicePixelRatio is 1, here are some clips:

https://imgur.com/a/PwZG4ij

https://imgur.com/a/98HAQKC

Same behaviour on chromium based browsers.

**Comment by timocov** [comment]
Thanks! I can see the issue right now.

**Comment by timocov** [comment]
Actually it seems that the issue is already fixed in 3.2 version (see https://jsfiddle.net/uxp9Lkfs/). Unfortunately, examples on https://www.tradingview.com/lightweight-charts/ aren't updates to the latest version yet.

@Dwyte can you check the issue with the latest 3.2 version please?

**Comment by Dwyte** [comment]
Yep @timocov it's fixed now just checked on 3.2.
