### ISSUE TITLE
Apply localization to specific series

### ISSUE THREAD

**Issue by nvoisin** [tradingview/lightweight-charts#62]
Hi,

I have a basic OHLC chart with volume data. I'd like to apply a custom price formatter for the candles only and not the volume. If I follow this [demo](https://jsfiddle.net/TradingView/gvqh8rx7) the price is formatted both for volume and OHLC candles. How can I just format the CandleSeries ?

Thanks,

**Comment by ezhukovskiy** [comment]
Hi!
it seems that we need to have a separate formatter for each data series.

**Comment by timocov** [comment]
See [custom price format](https://github.com/tradingview/lightweight-charts/blob/a460384e6df6f24d12ae52e01eddd709120b4e9e/docs/series-basics.md#price-format) or [associated test case](https://github.com/tradingview/lightweight-charts/blob/a460384e6df6f24d12ae52e01eddd709120b4e9e/tests/e2e/graphics/test-cases/initial-options/custom-price-format.js#L19-L27).

**Comment by nvoisin** [comment]
I don't seem to be able to get it to work with a CandleStickSeries.

**Comment by timocov** [comment]
It'll be available in 1.1 version.
