### ISSUE TITLE
Option to disable current price line

### ISSUE THREAD

**Issue by thisconnect** [tradingview/lightweight-charts#622]
**Is your feature request related to a problem? Please describe.**

There is still the current price line, even if price scale and crosshair is disabled.

![Screen Shot 2020-11-17 at 12 05 29 PM](https://user-images.githubusercontent.com/546900/99383074-ac5b3f80-28cd-11eb-8a80-5217b4e3b93b.png)

**Describe the solution you'd like**

It would be nice to have an option to disable rendering the current price line

**Additional context**

- here is a very minimal chart https://jsfiddle.net/1ov0chp8/ , but the current price is still visible, 🤞  I hope I dind't overlook the obvious.

**Comment by timocov** [comment]
See [`priceLineVisible`](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-line).

**Comment by thisconnect** [comment]
thank you 👍
