### ISSUE TITLE
`to` date of getVisibleRange contains partially visible data item and it's impossible to hover it

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#624]
**Lightweight Charts Version:** 3.2.0

**Steps/code to reproduce:**

1. Open https://jsfiddle.net/uwzkty5p/
1. Hover at rightmost data point

**Actual behavior:**

Crosshair shows it's 19 Nov 2020, but timeScale.getVisibleRange().to returns 20 Nov 2020.

**Expected behavior:**

It should be possible to hover the rightmost visible point, or visible range should not include "invisible" (or partially visible) points

**Comment by qinglong-zeng** [comment]
I find the reason that cause this problem. because time need to transfer to utc time.

**Comment by qinglong-zeng** [comment]
@timocov ,  This issue can be closed. Thanks

**Comment by timocov** [comment]
@qinglong-zeng excuse me? I'm not sure that this issue is related to time format/tz thought
