### ISSUE TITLE
Volume Field

### ISSUE THREAD

**Issue by dextersiah** [tradingview/lightweight-charts#628]
Hi I have a simple question that I couldn't find anyone mentioning about this. Does Lighweight-charts has support for Volume data aside from OHLC?

**Comment by timocov** [comment]
Did you look at our demos https://www.tradingview.com/lightweight-charts/? There is example named "Volume Study", I guess this is what you want.

If you'd like to show volume as histogram, you need to add another histogram series with volume data (along with main data series).

**Comment by dextersiah** [comment]
Yes! That was exactly what I was looking for, perhaps would need to have a clearer documentations as it isn't available in the docs. Thanks @timocov

**Comment by timocov** [comment]
@dextersiah lightweight-charts doesn't provide such kind of things like "studies" - main series, studies, etc - all of that are "series" for the library and it knows nothing about what you're trying to show with it. That's why we have demo page :)
