### ISSUE TITLE
Add layout.fontFeatureSettings option

### ISSUE THREAD

**Issue by sergeysolovev** [tradingview/lightweight-charts#635]
I’m currently using a font for the chart which has proportional figures enabled by default. I would like to be able to use tabular figures (monospaced numbers) in the chart so they are perfectly aligned at the Y axis.

In CSS it is possible to achieve this by settings `font-feature-settings: 'tnum' 1;`. This doesn’t apply to the chart canvas though. I suggest to add this as an option to the `layout`.

Some fonts have useful features like slashed zeros (`'zero' 1`) which is sometimes not enabled by default but is nice to see in the numeric data. The solution would have covered this case as well.

**Comment by timocov** [comment]
I'm not sure that this property might be applied to canvas' via its properties.

It seems that the only possible way to achieve that is to define the new font-face and use that font-face in `layout.fontFamily` option. Does it work?

**Comment by sergeysolovev** [comment]
@timocov Thank you for your feedback. I’ve tried to set tabular numbers for the whole page (on the body tag). Though it applies to last price label (the black rect on the screenshot), it somehow doesn’t apply to the rest of the prices on Y axis.

To notice the difference, see the numbers `18000` and `17000`, they are clearly proportional. Please also notice how the `1` looks in the price label and outside of it.

My guess is that if it’s possible to use tabular figures in the price label, it might be possible to apply this to the rest of the numbers at the Y Axis. Any chance?

<img width="169" alt="Screenshot 2020-12-08 at 15 04 38" src="https://user-images.githubusercontent.com/5831301/101451332-f1234500-3966-11eb-9d69-bc2ddccd7d70.png">

**Comment by sergeysolovev** [comment]
@timocov I’ll try to find a free font with the same features for the repro. I can’t use my exact font directly as it has a limited license.

**Comment by timocov** [comment]
Hi @sergeysolovev, do you have any updates here?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
