### ISSUE TITLE
Markers doesnt point to the correct level of buy/sell on the y axis (with positioning inBar) 

### ISSUE THREAD

**Issue by lotusjohn** [tradingview/lightweight-charts#636]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**
Having this issue with all my buy/sell markers but it is also the case in the jsFiddle of tradingView.
https://jsfiddle.net/TradingView/nd80cx1a/

**Actual behavior:**
Markers are shown with the arrow pointing at about 73.50 when the sell was at 75 for ex. Removing the text and/or changing to position "inBar" doesnt help either. 
The arrow doesnt point to the correct pricelevel no matter what positioning is used, isBar makes the marker even more off from the actual sell/buy price. 
For day/swing trades, this makes it very unusable since all the arrows are completely off, and just looking at the chart could give the impression that the trade was for ex a loss, but reading the markers text, or checking trade details one sees it actually was a profitable trade. 

**Expected behavior:**
Arrows should point correctly at the pricelevel of buy/sell. The down-tip of the arrowDown should be placed at the price-level of the sell. The upwards tip of the arrowUp should be placed at the pricelevel of the buy. 

I expect the arrow to point to the correct price level if positioning is "inBar", or expect that there would be another positioning option that would make the marker handle this case. 

**Screenshots:**
inBar: 
![image](https://user-images.githubusercontent.com/33894408/101281040-31e75680-37cd-11eb-8592-119425474487.png)

aboveBar (makes sense for this positioning option)
![image](https://user-images.githubusercontent.com/33894408/101281062-56dbc980-37cd-11eb-8829-178cae7fcad2.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/TradingView/nd80cx1a/

**Comment by timocov** [comment]
> The arrow doesnt point to the correct pricelevel no matter what positioning is used, isBar makes the marker even more off from the actual sell/buy price.

Series' markers aren't made to highlight a specific price level, [they even don't have `price` property in their options](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#setmarkers). They are pointing _a bar_ where something was happened and sometimes _a side_ where this happened (it might be used in several conditions, e.g. for trades it might show whether it's buy or sell trade).

> Arrows should point correctly at the pricelevel of buy/sell. The down-tip of the arrowDown should be placed at the price-level of the sell. The upwards tip of the arrowUp should be placed at the pricelevel of the buy.

See https://github.com/tradingview/lightweight-charts/issues/127

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Comment by fillky** [comment]
The nice workaround **to achieve having `markers` on exact price level** would be to create a line series with full transparent color and then setting `markers` on the "invisible line series" instead of candlesticks series.

**Comment by fillky** [comment]
[Code snippet](https://jsfiddle.net/fillky/mnu9ckvL/59) of workaround mentioned.

**Comment by maximbelyayev** [comment]
I really think introducing a marker with a price level or y-coordinate is of utmost importance. A lot of charting use-cases would be solved with lightweight-charts as a result.
