### ISSUE TITLE
plotcandle() shows candles as specks of dust when viewer zooms out

### ISSUE THREAD

**Issue by sanikolov** [tradingview/lightweight-charts#637]
**Is your feature request related to a problem? Please describe.**

Yes. This may or may not be a pinescript issue since plotcandle lacks a width or thickness parameter.
It might be an issue in the charting library.
When you zoom out candles look so tiny, they are barely visible.

**Describe the solution you'd like**

Make synthetic candles behave like regular candles. When you zoom out regular candles don't become nearly invisible. They still look as good and clear as when you zoom in.

**Additional context**

![image](https://user-images.githubusercontent.com/19896827/101398542-3fb7dd00-389c-11eb-81f6-46b0beea9df4.png)

**Comment by timocov** [comment]
> Yes. This may or may not be a pinescript issue since plotcandle lacks a width or thickness parameter.

This repo has nothing with pinescript.

> It might be an issue in the charting library.

This repo has nothing with charting library either.

This repo is about lightweight-charts library.

**Comment by timocov** [comment]
See similar issue #619

**Comment by timocov** [comment]
If you experience this issue with lightweight-charts, please re-open the issue and provide steps to reproduce the problem.
