### ISSUE TITLE
Candles drawn partially out of chart range

### ISSUE THREAD

**Issue by epezon** [tradingview/lightweight-charts#653]
Hi,
I am creating candlestick charts for 6 months of data and sometimes the candles are partially or fully above or below of the chart area. Seems like the price range scaling does not work correctly.  I am using `autoscale`
```
priceScale: {
        position: 'right',
        // mode: 2,
        autoScale: true,
    },
```
Here are three examples:
![image](http://www.tobaia.com/images/tv-lg-chart-error-01.png)

![image](http://www.tobaia.com/images/tv-lg-chart-error-02.png)

![image](http://www.tobaia.com/images/tv-lg-chart-error-03.png)

Here are my other configurations:
```
 chart.applyOptions({
      handleScroll: {
        mouseWheel: false,
        pressedMouseMove: false,
        horzTouchDrag: false,
        vertTouchDrag: false,
      },
      handleScale: {
        axisPressedMouseMove: false,
        mouseWheel: false,
        pinch: false,
      },
    });

    let candleSeries = chart.addCandlestickSeries({
      upColor: up,
      borderUpColor: up,
      wickUpColor: up,
      downColor: down,
      borderDownColor: down,
      wickDownColor: down,
    });

    var volumeSeries = chart.addHistogramSeries({
      color: 'rgba(150, 150, 150, 0.3)',
      priceFormat: {
        type: 'volume',
      },
      priceLineVisible: false,
        
    overlay: true,
    scaleMargins: {
      top: 0.8,
      bottom: 0,
    },
  });
```
How could I prevent this?

**Comment by timocov** [comment]
Can you share the data you've passed to the library? Quite probably you passed strings instead of numbers in bar's data.

**Comment by epezon** [comment]
That is not the case as you can see from the data:
![image](https://user-images.githubusercontent.com/54973181/103619669-d2e73f80-4f3a-11eb-8ecc-0454d8a62a2c.png)

**Comment by timocov** [comment]
@epezon so can you please create a repro for that please? I'm afraid that without that we're unable to help with that.

**Comment by epezon** [comment]
> @epezon so can you please create a repro for that please? I'm afraid that without that we're unable to help with that.

![image](https://user-images.githubusercontent.com/54973181/105731643-47a90a80-5f38-11eb-88d7-e4051c27a0b8.png)

And the data:
![image](https://user-images.githubusercontent.com/54973181/105731762-68716000-5f38-11eb-80fa-0b76edca74c4.png)

**Comment by epezon** [comment]
I can send you a link privately to the api which is called to populate the charts.
