### ISSUE TITLE
[NUXT, Vue] => export 'default' (imported as 'LightweightCharts') was not found in 'lightweight-charts'

### ISSUE THREAD

**Issue by p3t3r67x0** [tradingview/lightweight-charts#654]
**Lightweight Charts Version:**  3.2.0

**Introduction**
Thank  you at first for the great library, it seems I found probably a tiny bug using it in combination with VueJS and Nuxt in server side rendering context. I already saw the other issue but I could not solve the using it in combination with VueJS and Nuxt.

**Steps/code to reproduce:**
I installed the library using npm with this command `npm install --save lightweight-charts`
Then I created plugin file for Nuxt which might be the way to go

```js
import Vue from 'vue'
import LightweightCharts from 'lightweight-charts'

Vue.use(LightweightCharts)
```

**Reproduction**

```js
npm run dev
```

**Steps to do**
When I save and run this, I got the following error. It seems it has sth. to do with the window object...
But to be honest I have no glue I'm trying this already now for two days and I cant figure it out.
The expected behavior would be that I can use the methods without any import error obviously.

Any help with is highly appreciated, thanks in advance.

**Comment by timocov** [comment]
> I got the following error. It seems it has sth. to do with the window object...

What error?

Can you please create repro for this issue? Also, isn't it related to #543?

**Comment by p3t3r67x0** [comment]
Hi @timocov,

exactly this relates #543 

will close this issue.
