### ISSUE TITLE
Uncaught Error: Value is null

### ISSUE THREAD

**Issue by miladganjali** [tradingview/lightweight-charts#658]
**Lightweight Charts Version:** 3.1.3

I am using your chart for the cryptocurrency trade application in Vue project
but no matter what I get this error below is a sample code 

**There is no duplicated or null data.**

```
import {createChart} from "lightweight-charts";
export default {
data() {
return {
                chartProperties: {
                  width: 700,
                  height: 300,
                  timeScale: {
                     timeVisible: true,
                     secondsVisible: false
                },
                layout: {
                    //backgroundColor: '#262C49', //Dark Theme
                    //textColor: '#80859E',
                    fontSize: 12,
                    fontFamily: 'irsans ,Calibri'
                }
            },
            chartData: [],
            candleSeries: null,
}
}
mounted() {

let cdata = [
{
close: 22750.76
high: 22759.53
low: 22750.25
open: 22752.8
time: 1608635340
},
....
];

this.chartElement = document.getElementById('chart');
this.chartProperties.width = this.chartElement.offsetWidth;
this.chart = createChart(this.chartElement, this.chartProperties);
this.candleSeries = this.chart.addCandlestickSeries();

this.candleSeries.setData(cdata);

```

**Actual behavior:**

The chart is drawn with no candlestick

![chart1](https://user-images.githubusercontent.com/8298544/102883286-05863800-4465-11eb-90f0-c2438b0e6c53.png)

and repeated error of   **Uncaught Error: Value is null**

![chart2](https://user-images.githubusercontent.com/8298544/102883165-c952d780-4464-11eb-97b0-1798a07aa11c.png)

**Comment by timocov** [comment]
1. Can you try with the latest version?
2. Can you provide jsfiddle repro?

**Comment by miladganjali** [comment]
Update to latest version nothing change 

jsfiddle : https://jsfiddle.net/miladganjali/cmu5htpb/8/

**Comment by timocov** [comment]
https://api.huobi.pro/market/history/kline?period=1min&symbol=btcusdt

data should be ordered by time in asc order, not in desc.

**Comment by miladganjali** [comment]
Thank u 
I am closing the issue 
I never see that in one million years it cost me 4  days thanks again.

**Comment by inji-kim** [comment]
> https://api.huobi.pro/market/history/kline?period=1min&symbol=btcusdt
> 
> data should be ordered by time in asc order, not in desc.

I use this data but too the error has been occred.

**Comment by miladganjali** [comment]
> > https://api.huobi.pro/market/history/kline?period=1min&symbol=btcusdt
> > data should be ordered by time in asc order, not in desc.
> 
> I use this data but too the error has been occurred.

that was an error u should make data  ASC order in time

**Comment by inji-kim** [comment]
@miladganjali thanks, I have solve it. 

` const sortedData = data.sort((a, b) => a.time - b.time); `

**Comment by rapidtrader** [comment]
Even if my data is sorted it is giving me error

**Comment by miladganjali** [comment]
> Even if my data is sorted it is giving me error

maybe this [link](https://stackoverflow.com/questions/65408588/lightweight-charts-uncaught-error-value-is-null) and comments in answer can help you
