### ISSUE TITLE
Angular Change Detection

### ISSUE THREAD

**Issue by kevinsherman** [tradingview/lightweight-charts#668]
Per my question on StackOverflow (https://stackoverflow.com/questions/65544921/angular-httpinterceptor-cache-not-triggering-change-detection)

When the chart is NOT using caching, it renders correctly. When it IS using caching, it does not re-render properly even though the cache is returning the correct data. 

Any insight/direction would be appreciated.

**Comment by timocov** [comment]
@kevinsherman It seems that your question is already solved https://stackoverflow.com/a/65581481/3893439, is this issue still valid?

**Comment by kevinsherman** [comment]
Problem solved. Closing.... thanks @timocov.
