### ISSUE TITLE
Lock pane sizes

### ISSUE THREAD

**Issue by i3v** [tradingview/lightweight-charts#669]
**Is your feature request related to a problem? Please describe.**

I regularly accidentally move the horizontal line, separating two panes (when drawing something or scrolling). 

**Describe the solution you'd like**

It would be a good idea to add "Lock pane sizes" option next to the "Lock price to bar ratio" option. Or maybe next to the "Maximize pane" button.

**Additional context**
Just in case, this line: 
![line](https://user-images.githubusercontent.com/920364/103888571-00c4b380-50f6-11eb-91b6-ad78546b9271.png)

**Comment by timocov** [comment]
As I see your screenshot is for charting_library, not for `lightweight-charts` library? lightweight-charts doesn't have panes support so far.

**Comment by i3v** [comment]
@timocov , thanks for explaining the difference. 
Could you please transfer this suggestion to that repo?
