### ISSUE TITLE
Support React Native 

### ISSUE THREAD

**Issue by kentdev92** [tradingview/lightweight-charts#671]
The first thing i want to say thank you so much to you tradingview/lightweight-charts team for create an awesome open source for us.

I'm currently using this lib as well for my business.
I hope that you guys can start to create a new version for mobile, react native. Because i know that for now, don't have to much chart lib support for mobile as well, like the way you did with this lib.

Best regards

**Comment by timocov** [comment]
> I hope that you guys can start to create a new version for mobile, react native

Did you try to integrate the library with react native yourself?

Also, I think it'd be better to create [a discussion](https://github.com/tradingview/lightweight-charts/discussions/categories/ideas) for that instead of the issue.

**Comment by Rishabh-Streak** [comment]
@kentdev92 you can try self-hosting library implementation in a website and use it as a webview in react-native. I have Implemented it this way currently.
You can communicate using post messages between react-native and website.

**Comment by timocov** [comment]
Let's continue in #733

**Comment by yasaswiniGadde** [comment]
> The first thing i want to say thank you so much to you tradingview/lightweight-charts team for create an awesome open source for us.
> 
> I'm currently using this lib as well for my business. I hope that you guys can start to create a new version for mobile, react native. Because i know that for now, don't have to much chart lib support for mobile as well, like the way you did with this lib.
> 
> Best regards

Can you please give me the exact tradingView  package name for react native
