### ISSUE TITLE
Support mobile, react native

### ISSUE THREAD

**Issue by kentdev92** [tradingview/lightweight-charts#672]
The first thing i want to say thank you so much to you tradingview/lightweight-charts team for create an awesome open source for us.

I'm currently using this lib as well for my business.
I hope that you guys can start to create a new version for mobile, react native. Because i know that for now, don't have to much chart lib support for mobile as well, like the way you did with this lib.

Best regards

**Comment by dotku** [comment]
Any update here?

**Comment by timocov** [comment]
@dotku any update on what? lightweight-charts is web-based library which does work on mobile devices and handles touch devices properly

**Comment by salman-ar-sar** [comment]
@timocov How do you use the createChart API with react native? There is no HTML element there.
Is this the only way to do? [example](https://github.com/tradingview/charting-library-examples/tree/master/react-native)
