### ISSUE TITLE
Chart LineSeries type with additional characteristics

### ISSUE THREAD

**Issue by Kuzmich100kM** [tradingview/lightweight-charts#674]
I'm always frustrated when can't remove the line and draw only dots, squares, crosses, arrowUp, arrowLeft, ect, . 
I would also like to be able, if necessary, to set the color and size for each point. 

Possible Solution. You can add values ​​to the current chart type lineSeries

```js
lineSeries.setData([
    { time: '2018-12-01', value: 32.51, type: 'cross', color: 'default', size: 1.5 },
    { time: '2018-12-02', value: 31.11, type: 'circle', color: 'red', size: 0.75 },
    { time: '2018-12-03', value: 27.02, type: 'rect', color: '#777777', size: 0.75 },
]);
```
Size is a ratio to the default size.
If the type, color and size are not specified in the Data, then the default values ​​are applied.

```js
// Removes the line
lineSeries.applyOptions({
    lineWidth: 0,
});
```

If you allow, I will write a link to a site with an example

![изображение](https://user-images.githubusercontent.com/46998842/104130123-b7839680-5377-11eb-8e0a-61d19d836024.png)

**Comment by timocov** [comment]
> Possible Solution. You can add values ​​to the current chart type lineSeries

This is exactly what #127 is for. Please post your suggestion there.

**Comment by Kuzmich100kM** [comment]
1

**Comment by timocov** [comment]
> Now I was able to create a tick chart using CandlestickSeries, but this is using a hack and it looks like this:

If you'd like to use tick-based charts, I think that you might use candlestick series, but you need to set high=low in this case.

But I'm not still quite sure what you're actually want to. If you'd like to create series with some markers (crosses, circles, squares, etc), you need #127.

**Comment by Kuzmich100kM** [comment]
I need a tick chart. 
> If you'd like to use tick-based charts, I think that you might use candlestick series, but you need to set high=low in this case.

That's what I do, use candlestick series. But I cannot change the shape and size of the point. The first GIF shows that the red and green moving dots are of different sizes. I set their size as price * 0.9999. In this case, when I change the scale, the size of the point (candle height) also changes

```js
let data = {
     open:  res.price * 0.9999,
     close: res.price,
     high: res.price,
     low: res.price,
}
```
The Marker series is not suitable. For a tick chart, a Line series is suitable (GIF 2 with a blue moving line). But it will not be possible to indicate buy and sell points (red / green). And the blue line is sometimes unnecessary.

**Comment by timocov** [comment]
> I set their size as price * 0.9999. In this case, when I change the scale, the size of the point (candle height) also changes, it is not right.

What if you remove that multiplying by 0.9999, so you bar will be just `res.price` for all values?

> But it will not be possible to indicate buy and sell points (red / green).

I think for this case something like #195 will be useful.

**Comment by Kuzmich100kM** [comment]
> What if you remove that multiplying by 0.9999, so you bar will be just `res.price` for all values?
When I removed the multiplication, only a very thin line remained.

![bandicam 2021-01-11 14-30-31-819](https://user-images.githubusercontent.com/46998842/104183210-49dc7680-541a-11eb-8cf2-f47bdb2bcbfd.gif)
There is a similar implementation in some terminals. Like this

![bandicam 2021-01-11 14-38-44-975](https://user-images.githubusercontent.com/46998842/104184026-7e9cfd80-541b-11eb-9dca-ce027696513c.gif)


And this
![bandicam 2021-01-11 14-39-15-771](https://user-images.githubusercontent.com/46998842/104184079-95dbeb00-541b-11eb-9d9c-8daad2fa02ed.gif)

**Comment by timocov** [comment]
> There is a similar implementation in some terminals. Like this

Thus, as I said, you need #127 for that.

**Comment by Kuzmich100kM** [comment]
We did it! 

![bandicam 2021-01-11 16-51-23-114](https://user-images.githubusercontent.com/46998842/104197800-1d325a00-542e-11eb-9a46-62f01c443a4c.gif)
But after a 1 minute the browser renders slower and slower and soon dies. This is most likely due to the many push operations. When I use only a Candlestick series without Markers, everything works very quickly and does not lag

But now I understand that all the current types of charts can only draw one shape at a one time :-(

![изображение](https://user-images.githubusercontent.com/46998842/104200154-fc1f3880-5430-11eb-89a7-3971ffecb579.png)

**Comment by Kuzmich100kM** [comment]
> This is most likely due to the many push operations.

Oh no, the problem isn't pushing. After each push we completely redraw all markers. And there are more and more of them in the array.


```js
const markers = []
    function(data) {
        markers.push({
           time: data.time,
           position: "inBar",
           color:  "green",
           shape: "circle",
       })
  series.setMarkers(markers)
  }
})
```

If we added only one element as when updating the chart, it would be easier
