### ISSUE TITLE
Feature request: Horizontal histograms

### ISSUE THREAD

**Issue by davidtgq** [tradingview/lightweight-charts#676]
Static version where each time interval/session gets its own histogram:

![image](https://user-images.githubusercontent.com/14155110/104644939-71327e00-567c-11eb-911f-9b2b7d75fae6.png)

Dynamic version where histogram is being updating as user scrolls left and right:

![image](https://user-images.githubusercontent.com/14155110/104644766-36c8e100-567c-11eb-83a9-ffad77c88917.png)

Personally more interested in static version.

**Comment by timocov** [comment]
I'm afraid we're not going to implement this in the future in lightweight-charts. Probably in the future when and if we add an ability to draw anything directly on the canvas it'll be possible, but I can't tell you any additional information about that though.
