### ISSUE TITLE
Crosshair Marker Border Bug

### ISSUE THREAD

**Issue by hgwak** [tradingview/lightweight-charts#677]
My code so far: 

    this.chart = createChart(this.chartContainer.nativeElement, {
      width: this.chartContainer.nativeElement.offsetWidth,
      height: this.chartContainer.nativeElement.offsetHeight
    });
    const areaGraph = this.chart.addAreaSeries({
      topColor: 'rgba(33, 150, 243, 0.56)',
      bottomColor: 'rgba(33, 150, 243, 0.04)',
      lineColor: 'rgba(33, 150, 243, 1)',
      lineWidth: 2,
      crosshairMarkerVisible: true,
      crosshairMarkerRadius: 6,
    })
    const themeOptions = {
      chart: {
        layout: {
          backgroundColor: 'transparent',
          lineColor: '#2B2B43',
          textColor: '#D9D9D9',
        },
        watermark: {
          color: 'rgba(0, 0, 0, 0)',
        },
        crosshair: {
          color: 'white',
          vertLine: {
            color: '#6C6E88',
            width: 0.5,
            style: 0,
            visible: true,
            labelVisible: false,
          },
          horzLine: {
              visible: false,
              labelVisible: false
          },
          mode: 1,
        },
        grid: {
          vertLines: {
            visible: false,
          },
          horzLines: {
            visible: false,
          },
        },
      },
      series: {
        topColor: '#4D2CA3',
        bottomColor: '#25264A',
        lineColor: '#6D40E2',
        priceLineVisible: false,
        lastValueVisible: false,
      },
    }
    this.chart.applyOptions(themeOptions.chart);
    areaGraph.applyOptions(themeOptions.series);

![image](https://user-images.githubusercontent.com/45578343/104727820-d91fad80-56ea-11eb-8997-9c49964e87fc.png)

**Actual behavior:**

There is no border around the crosshair marker. 
The docs also indicate there are two properties that are able to adjust the crosshair marker properties. 
![image](https://user-images.githubusercontent.com/45578343/104728084-3f0c3500-56eb-11eb-9a79-c54e09aebfd2.png)
Yet when I looked at the typing those options seem to be missing 
![image](https://user-images.githubusercontent.com/45578343/104728163-564b2280-56eb-11eb-8405-821491db1043.png)

Looking at the examples it looks like most if not all of the crosshairs have a default white border but I can't seem to get any border showing on my dot. 

**Expected behavior:**

There should be a border around the crosshair marker.

**Screenshots:**

**Comment by timocov** [comment]
This feature isn't released yet #310. It is assigned to 3.3 version, but the latest one on npm is 3.2.
