### ISSUE TITLE
Changing time scale into incremental numbers

### ISSUE THREAD

**Issue by dextersiah** [tradingview/lightweight-charts#683]
Is it possible to not display the date in the x-axis instead to display example Day 1, 2, ... And change the date indicator when hovering on the charts.

![image](https://user-images.githubusercontent.com/46256927/105330922-cd157d80-5c0d-11eb-8f4a-7069a858a98c.png)

**Comment by timocov** [comment]
It looks pretty similar to https://github.com/tradingview/lightweight-charts/discussions/649 (I'll post an answer there soon).

Long story short - it is possible. You need to override [`tickMarkFormatter`](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options).
