### ISSUE TITLE
The time label is not match crosshair's time? How to fix it?

### ISSUE THREAD

**Issue by qinglong-zeng** [tradingview/lightweight-charts#685]
![image](https://user-images.githubusercontent.com/25050827/105807584-3f58da00-5fe1-11eb-8aba-8be9b7036b65.png)
![image](https://user-images.githubusercontent.com/25050827/105807593-45e75180-5fe1-11eb-872d-a078a6fc3f40.png)

The label day is not match crosshair date?  There is a api to change the label date?

**Comment by timocov** [comment]
Can you please provide steps to reproduce the issue? Can you provide a code to reproduce it as well?

**Comment by qinglong-zeng** [comment]
@timocov
It is found that there is a problem with the time transmitted from the background, which is transmitted in UTC time, which conflicts with the local time.

**Comment by timocov** [comment]
> which conflicts with the local time.

What do you mean?
