### ISSUE TITLE
Disabling autoScale for non-visible series

### ISSUE THREAD

**Issue by Bryanoxx** [tradingview/lightweight-charts#687]
Hello, 

Firstly thank you this great open-source chart library, really a pleasure working with it.

I have a problem that I think can be resolve easily, but need some context.
Basically I have two main series in my chart : "Backtest" and "Témoin" (I'm french!)
![https://puu.sh/HcgTZ/edfd48aaeb.png](https://puu.sh/HcgTZ/edfd48aaeb.png)

Thoses lines series are calculate using others lines series that i dont show by default, like this for example :
![https://puu.sh/HcgUs/9828dd5704.png](https://puu.sh/HcgUs/9828dd5704.png)
![https://puu.sh/HcgUe/5a426e54c3.png](https://puu.sh/HcgUe/5a426e54c3.png)

The problem is : thoses "others lines series" are not visible but they are taking into account for the scale of the chart, so my most important line series ("Backtest" and "Témoin") are really little for some of thoses "others lines series" :
![https://puu.sh/HcgUH/11e9ec55ae.png](https://puu.sh/HcgUH/11e9ec55ae.png)
![https://puu.sh/HcgUO/a254c13f9a.png](https://puu.sh/HcgUO/a254c13f9a.png)

The solution would be to have the possibility to disable autoScale for non-visible series, because :
- I already tried to use `autoScale: false` when `visible` is `false` too, but it don't work (maybe i misunderstood the scope of that property)
- I know I can remove and add series, but I still want the performance that allow `visible: false` (because there is a lot of points)

That's all !
Thank you and have a great day.

**Comment by timocov** [comment]
Yeah, I think it's a bug.

Would you like to provide a PR with fixes? I think it should be pretty easy to do, it just needed to add `if` statement to check `visible` option from series options (similar to [this one](https://github.com/tradingview/lightweight-charts/blob/3a4ce2fbc587eca3a668a38f678981745bc1ee23/src/views/pane/line-pane-view.ts#L19-L22)) [somewhere here](https://github.com/tradingview/lightweight-charts/blob/3a4ce2fbc587eca3a668a38f678981745bc1ee23/src/model/price-scale.ts#L804-L807) (and add an e2e test case for that as well).

**Comment by Bryanoxx** [comment]
Thanks for the quick answer !

I don't know how to code with TS, but I still forked the project and watch what i could, the fact that the `source` object of type `IPriceDataSource` don't have the `options` configuration of a serie block me real quick...

I'm sorry I don't think I have the skill to do this PR :/

**Comment by timocov** [comment]
The fix is just published in [3.3.0 version](https://github.com/tradingview/lightweight-charts/releases/tag/3.3.0).
