### ISSUE TITLE
How is it possible to extract data from a TradingView chart?

### ISSUE THREAD

**Issue by rezaee** [tradingview/lightweight-charts#69]
Is there anyway to get data from a TradingView chart? I mean I see a website that uses TradingView chart to show it's data like stock data for example. I like to grad that data and do some data analyzes on them. How is it possible?

**Comment by timocov** [comment]
If it's TradingView's widget, then we don't provide a way to export our data from charts. If it's TradingView's charting library or even `lightweight-charts` - then please contact the website's owner.

But anyway, this issue isn't related to the `lightweight-charts` itself.
