### ISSUE TITLE
Slow candlestick loading . Is there a way to check when the data has been fully loaded on the chart? ( Loading... ) animation?

### ISSUE THREAD

**Issue by JessseG** [tradingview/lightweight-charts#690]
The candlestick chart takes a while to load candlestick data (20+ seconds when loading 20K candlesticks for example). It can even take more than a minute and a half if I want to load 40K candles. If there's no way to load this faster like trading view charts or others do quickly, then I want to see if there is a way to check when the data has been fully loaded on the chart so that I can add an overlaying ( Loading... ) animation while the chart data loads.

**Comment by timocov** [comment]
> The candlestick chart takes a while to load candlestick data (20+ seconds when loading 20K candlesticks for example). It can even take more than a minute and a half if I want to load 40K candles

To be honest I don't believe that it's real. Do you have any example of reproduction so I can look into it? I just tried to reproduce it locally and it takes max 250ms for 50k line items.

**Comment by JessseG** [comment]
Nevermind it was the Python socket where the chart data was being sourced from that was taking so long
