### ISSUE TITLE
Chart candlesticks look broken when Zooming out

### ISSUE THREAD

**Issue by JessseG** [tradingview/lightweight-charts#691]
I've noticed that when I zoom out on the candlestick chart the candles begin to look broken and glitchy. Here are 2 screenshots. Why might this be happening? 

![brittled-graph-bug](https://user-images.githubusercontent.com/61717513/106732568-d673f200-65de-11eb-9cc0-b13b41858640.PNG)
![brittled-graph-bugg](https://user-images.githubusercontent.com/61717513/106732581-db38a600-65de-11eb-8f75-01ebf48bbd31.PNG)

**Comment by timocov** [comment]
What version of lightweight-charts you use?

**Comment by JessseG** [comment]
I didn't use npm to install. I just added the cdn to my html head like this. 

<script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>

**Comment by timocov** [comment]
You can execute `LightweightCharts.version()`. Also, you can specify a version via URL - use <https://unpkg.com/lightweight-charts@3.3.0/dist/lightweight-charts.standalone.production.js> to use the latest version.

Anyway, please provide a repro and steps how to reproduce the issue (jsfiddle or so is fine).

**Comment by JessseG** [comment]
Thanks it works I just needed to change the HTML head script from ```https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js``` to ```https://unpkg.com/lightweight-charts@3.3.0/dist/lightweight-charts.standalone.production.js```
