### ISSUE TITLE
Allow to change just one option via JS

### ISSUE THREAD

**Issue by lbphp** [tradingview/lightweight-charts#692]
**Is your feature request related to a problem? Please describe.**

I am happy with using this example as-is: https://jsfiddle.net/TradingView/gvqh8rx7/

Except i would want to be able to change the font size of the scale on mobile via JS, just the font size. 
That would be handy: copy-paste a ready-to-use example where you can change just one option like a color, font etc.

This page https://www.cssscript.com/financial-chart/ says you can call applyOptions method `mySeries.applyOptions({ ... })`  of the lineSeries, which requires me to pass **all** the options, and there are dozens of them, and i don't know all the values i need to pass to have the same result as the code example i am using. 
So it's not very user friendly having to know all the options without being able even to read the current options.

**Describe the solution you'd like**

I would like a "getOptions" method to get the current option values, to be used like this

```
var opt = lineSeries.getOptions();
opt.layout.fontSize = 50;
lineSeries.applyOptions(opt);
```

Or if something similar can be already achieved in other ways, let me know please

**Comment by SuperPenguin** [comment]
Both chart and series instances has method `options` to get current options
Example usage: 
```js
const chart = createChart(chartContainer, {
    width: chartContainer.clientWidth,
    height: chartContainer.clientHeight,
    layout: {
        fontFamily: "sans-serif",
        fontSize: 16
    }
});

const chartOptions = chart.options();
chartOptions.layout.fontSize = 20;
chart.applyOptions(chartOptions);
```

Also `applyOptions` doesn't require you to pass all the options, only options that you want to change. So this also valid usage
```js
chart.applyOptions({
    layout: {
        fontSize: 20
    }
});
```

**Comment by timocov** [comment]
> `chartOptions.layout.fontSize = 20;`

This might be tricky though, because we _might_ return an options object itself (not a copy) and the following `applyOptions` could be no-op in some cases.

But yeah, as fairly noted @SuperPenguin - you don't need to pass all other options to override one single thing - every `applyOptions` method (or even constructor with options in it) are designed to take partial of all options.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
