### ISSUE TITLE
How to add vertical line?

### ISSUE THREAD

**Issue by Hyung-Kim** [tradingview/lightweight-charts#693]

**Comment by pavitrakumar78** [comment]
@Hyung-Kim Hi, did you solve this? I tried adding a line series using this:
```
			var lineSeries_ind = chart.addLineSeries({
				lineWidth: 2,
			});
			lineSeries_ind.setData([
				{ time: <date_1>, value: 9999 },
				{ time: <date_1>, value: -9999 }
			]);
```
But it didn't work properly - the line extended all the way to the volume graph and the line was also not straight when zoomed.

**Comment by githubhwen** [comment]
i need help

**Comment by edew** [comment]
Duplicate of https://github.com/tradingview/lightweight-charts/issues/128, https://github.com/tradingview/lightweight-charts/issues/127, https://github.com/tradingview/lightweight-charts/issues/965, https://github.com/tradingview/lightweight-charts/issues/1049
