### ISSUE TITLE
tradingview in npm

### ISSUE THREAD

**Issue by Yousef-Maktabi** [tradingview/lightweight-charts#695]
hi
i wanna ask a qusetion about tradingview professional library.
if i send a request for access this library and be accepted, can i use it with npm command?
how this is possible that i use with npm?

**Comment by timocov** [comment]
This issue tracker is not about charting library or any other TradingView's product (except lightweight-charts library of course). Please contact platforms@tradingview.com to get help.

![screenshot](https://user-images.githubusercontent.com/3112183/107195103-f7cf4680-6a01-11eb-9d05-29bd6f7d1775.png)

**Comment by satthucon99** [comment]
vietnamese pls

Vào Th 2, 8 thg 2, 2021 vào lúc 15:37 Evgeniy Timokhov <
notifications@github.com> đã viết:
