### ISSUE TITLE
Whitespace on line series isn't showing the gaps

### ISSUE THREAD

**Issue by xqpoo9** [tradingview/lightweight-charts#700]
When adding whitespace entries to a line series with the following code, the whitespace gaps don't appear. This code is from the [line series](https://github.com/tradingview/lightweight-charts/blob/efcd313b0336d50a4782320337a59d9f57b40629/docs/line-series.md#data-format) and [whitespace](https://github.com/tradingview/lightweight-charts/blob/master/docs/whitespace-data.md) docs:

    var chart = LightweightCharts.createChart(document.body, { width: 400, height: 300 });
    var lineSeries = chart.addLineSeries();
    lineSeries.setData([
        { time: '2018-12-01', value: 32.51 },
        { time: '2018-12-02', value: 31.11 },
        { time: '2018-12-03', value: 27.02 },
        { time: '2018-12-04' }, // whitespace
        { time: '2018-12-05' }, // whitespace
        { time: '2018-12-06' }, // whitespace
        { time: '2018-12-07' }, // whitespace
        { time: '2018-12-08', value: 23.92 },
        { time: '2018-12-09', value: 22.68 },
        { time: '2018-12-10', value: 22.67 },
        { time: '2018-12-11', value: 27.57 },
        { time: '2018-12-12', value: 24.11 },
        { time: '2018-12-13', value: 30.74 },
    ]);
    chart.timeScale().fitContent();

<img width="412" alt="Screen Shot 2021-02-11 at 11 03 03 PM" src="https://user-images.githubusercontent.com/63019253/107728904-5542ec00-6cbd-11eb-85f2-719f4d7fa835.png">

**Comment by timocov** [comment]
Whitespace doesn't mean gap actually right now. It means that there is no value for a series.

If you hover values, you'll see that a series doesn't have values for times where you set no value (whitespace).

Ability to display gaps will be added in #699
