### ISSUE TITLE
Is it possible to subscribeCrosshairMove Like the graph in the photo ? 

### ISSUE THREAD

**Issue by IbrahimSam96** [tradingview/lightweight-charts#701]
![Picture1](https://user-images.githubusercontent.com/72482204/108139829-e683db00-708e-11eb-8539-f097531349d8.png)

Please let me know if this can be done (Selecting area of the graph to be measured)?

**Comment by timocov** [comment]
You can create an area series with data of that selected period only so you'll get highlighting, but we aren't going to implement with feature in-house though.

**Comment by IbrahimSam96** [comment]
any hints to how I can use the highlighting feature?

**Comment by IbrahimSam96** [comment]
create a custom highlighting feature more so **
