### ISSUE TITLE
Add an option to not render price labels outside defined scaleMargins

### ISSUE THREAD

**Issue by agrinei** [tradingview/lightweight-charts#702]
When axes have scaleMargins, it would be nice to have an option to not render labels and crosshair values outside defined margins. Let's say we have a chart with two price scales and they have scaleMargins defined so we can simulate panels.

Currently we have:

![image](https://user-images.githubusercontent.com/10330654/108383096-3b873480-71e8-11eb-9367-d4e538eeb05d.png)

Top serie (rightPriceScale) has scaleMargins: { top: 0.02, bottom: 0.33 }
Bottom series (leftPriceScale) have scaleMargins: { top: 0.75, bottom: 0 }

I think it should not render labels outside defined margins:

![image](https://user-images.githubusercontent.com/10330654/108383142-45109c80-71e8-11eb-945b-f30b8e813442.png)

**Comment by timocov** [comment]
I understand your point, but it looks like attempt to emulate multiple panes, but it seems this "feature" can't be used for anything else, that's why I'd prefer to look at and track #50 instead.
