### ISSUE TITLE
Drawing a rectangle

### ISSUE THREAD

**Issue by parliament718** [tradingview/lightweight-charts#706]
I'm trying to find a solution to replace my custom charts.  Ive tried both lightweight-charts and the full trading view charts with technical analysis. 

Lightweight-charts almost fits my needs with just one exception: I cant draw a simple rectangle on the chart

This is an important requirement for me, so I decided to give the full TA charts a try... Unfortunately those have their own limitation. It seems the **series.setData()** method is not available there, and you must provide a "datafeed" instead. This doesnt work for me as I need to be able to update the data synchronously based on user-actions outside of the chart.

A simple rectangle can hardly be considered "Technical Analysis". I dont need all the additional tools in TA package.

Can this please be added to Lightweight-charts?

**Comment by parliament718** [comment]
By the way, I dont even need this rectangle to be interactive (resizing, moving, etc). It's just going to be used to highlight an area on the chart.

**Comment by hp8wvvvgnj6asjm7** [comment]
i'm looking for the same, but I don't think it's supported here.

**Comment by parliament718** [comment]
Id be willing to give it a try implementing myself if the maintainers could give some pointers about the desired design.

**Comment by timocov** [comment]
> Can this please be added to Lightweight-charts?

We do not plan to add any type of drawings into lightweight-charts. We might add a feature to allow you to get access to canvas so you can draw anything you want, but there is no specifics for that.

**Comment by asedsami** [comment]
@timocov I'm wondering if you have added the feature to allow access to canvas?

**Comment by timocov** [comment]
@asedsami see #408

**Comment by jussirantala** [comment]
I need it too

**Comment by christaylor98** [comment]
I have a very inelegant workaround for this.

You can add a series on a different scale, and have it fill in a certain time period on a chart.  Note its going to be the whole height of the chart as it seems to auto scale no matter what value you set it to, unless you add values with differing heights on the chart.   

Works ok if you want to highlight a certain time period, and you can you transparent colors to overlay different items on the same area.

**Comment by nuevofilipo** [comment]
https://github.com/tpunt/lightweight-charts/tree/boxes


https://github.com/tradingview/lightweight-charts/pull/1064?utm_source=pocket_saves

guys check this out, you can create different shaped in the lightweight charts. Just have to follow the installation guide in the discussions.

**Comment by nuevofilipo** [comment]
guys he literally integrated it above, tpunt!!!!!

https://github.com/tradingview/lightweight-charts/pull/1064?utm_source=pocket_saves
