### ISSUE TITLE
autoScale returns true after manual rescaling

### ISSUE THREAD

**Issue by kristiamo** [tradingview/lightweight-charts#707]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**

chart.applyOptions({ priceScale: { autoScale: true } });

* manually rescale the chart
* then get:

chart.options().priceScale.autoScale

**Actual behavior:**

options member returns true, but I assume internally it's been set to false?

**Expected behavior:**

returned options members should be updated to match internal state

OR is there another method to find out about such internal changes?

**Comment by timocov** [comment]
`priceScale` is option to apply to both left and right price scales. If you'd like to get current state you need to get options from price scale. Try to call `chart.priceScale('left').options().autoScale` instead (or `'right'` for right visible price).

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
