### ISSUE TITLE
Histogram series doesn't respect priceFormat option.

### ISSUE THREAD

**Issue by DakotaLarson** [tradingview/lightweight-charts#708]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**

`chart.addHistogramSeries({
  priceFormat: {
    type: "volume",
  },
})`

**Actual behavior:**

I continue to see only large numbers on the price scale despite selecting a volume price format. No other series exist on the chart.
![image](https://user-images.githubusercontent.com/6530255/109809742-4a111b00-7bee-11eb-8a69-4cec1456bb67.png)

Additionally, using price format type "custom" with a callback doesn't seem to work at all. The callback is never run, no matter what `minMove` value I set.

If I set `priceScaleId` to '', the price scale isn't visible, but the price line is correct. When querying `chart.timescale().options()` , property `visible` is false, but using `applyOptions` doesn't change anything.
![image](https://user-images.githubusercontent.com/6530255/109809980-92303d80-7bee-11eb-9c8e-d03c680f9977.png)

**Expected behavior:**

I would expect to see truncated numbers. "12M", etc. 

Please let me know if I can provide any more information.

**Comment by timocov** [comment]
Can you create a repro on jsfiddle or om any similar resource please?

**Comment by DakotaLarson** [comment]
@timocov https://jsfiddle.net/t931c740/6/ Does this help?

**Comment by timocov** [comment]
@DakotaLarson thanks!

So, I just opened your JSFiddle and see that a callback is called so I can see your custom formatter.

![image](https://user-images.githubusercontent.com/3112183/111987941-dee9a300-8b20-11eb-9b28-2e8fd87b37f9.png)

What problem do you have right now?

**Comment by DakotaLarson** [comment]
@timocov I may have been a touch vague. The price scale doesn't display anything, in contrast to the first image on the issue where the price scale has numbers.
![image](https://user-images.githubusercontent.com/6530255/111992617-9d86d280-8ae3-11eb-807c-ed7cf861d4b7.png)

**Comment by timocov** [comment]
@DakotaLarson Is this https://jsfiddle.net/Lh4kysen/ what you'd like to achieve?

**Comment by DakotaLarson** [comment]
Hmm, well I removed the priceScaleId attribute in the fiddle and it's working as expected. I will run this later today and see if my issue is resolved. Otherwise, yes, that is generally what I am trying to solve.

**Comment by timocov** [comment]
Let me know if your issue still exists.
