### ISSUE TITLE
Problem with percent when i use mode 2

### ISSUE THREAD

**Issue by npismenkov** [tradingview/lightweight-charts#715]
Hi. I have doing charts with lightweight-charts. And i have bug and i don't know how i can fix it. Bug: I push data like {time: "2021-03-23", value: "32.20"}. But if i use "mode: 2" in options(i need it), i have troubles with percents on chart. If i push value "32.30", on chart it will be 3220%. But it should be 32.20%, and it was write in documentation. If i don't use "mode: 2", it works right. What i should do, to fix this? I need your help, please.

**Comment by timocov** [comment]
Values must be numbers.

**Comment by npismenkov** [comment]
> Values must be numbers.

i did that, but it's not fix something.

**Comment by npismenkov** [comment]
> Values must be numbers.

I kept code of my React component.
