### ISSUE TITLE
rendering problems when zooming out

### ISSUE THREAD

**Issue by paulcarouge** [tradingview/lightweight-charts#717]
![chrome_2021-03-26_09-00-35](https://user-images.githubusercontent.com/77453866/112600627-bd830280-8e11-11eb-8b1e-d967fbb56a08.png)

when zoomed in the chart renders very well but when zooming out it becomes unreadable.
Is this behavior normal? if not what would be the fix?

thank you!

**Comment by paulcarouge** [comment]
![chrome_2021-03-26_09-00-35](https://user-images.githubusercontent.com/77453866/112600627-bd830280-8e11-11eb-8b1e-d967fbb56a08.png)

**Comment by timocov** [comment]
0. Why did you ignore the template for a bug report?
1. What version of the library you use?
2. What dpr you have (`devicePixelRatio`)?
3. Can you create a repro for your case? jsfiddle is fine
