### ISSUE TITLE
Time is not displayed in user locale time

### ISSUE THREAD

**Issue by kamilkazmierczak** [tradingview/lightweight-charts#720]
**Lightweight Charts Version:** 3.3.0

**Steps to reproduce:**
Go to demo provided by TradingView
https://jsfiddle.net/TradingView/bmL0vont/

**Actual behavior:**
Time is displayed in UTC timezone.

**Expected behavior:**
Time should be displayed in user locale time.

**Screenshots:**
![obraz](https://user-images.githubusercontent.com/13839309/112804859-2fa75180-9075-11eb-8101-db64f16f9a03.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/ypmvszdu/

**Comment by timocov** [comment]
This is by design. If you'd like to show dates in user local TZ, please implement your own date/time and tick marks formatter.

**Comment by gajus** [comment]
Times are formatted using `timeFormatter`, but what about tick marks?

**Comment by rafaelfaria** [comment]
> This is by design. If you'd like to show dates in the user's local TZ, please implement your own date/time and tick marks formatter.

This actually doesn't answer the question.
Is there any example of how to implement our own date/time and tick markers formatted? I also have issues with this.
