### ISSUE TITLE
Customize background color (as a vertical space) for each time from X axis

### ISSUE THREAD

**Issue by mxmihai** [tradingview/lightweight-charts#721]
**Is your feature request related to a problem? Please describe.**
No

I need to emphasize some moments/times when I am long or short by changing the background color of the whole vertical space of each candle (from bottom to top of the chart.

**Describe the solution you'd like**
Would like to be able to specify (when needed) the backgroiund color for each time/moment from the X axis.

It would be easy to mark the time intervals when some action happens (position open, etc)

Thank you

**Comment by timocov** [comment]
I don't think that we'll implement something like this in lightweight-charts because it looks like something quite niche.

But as workaround you can try to use histogram/area series on overlay its own price scale and without margins, something like that https://jsfiddle.net/7a93swd6/.

**Comment by mxmihai** [comment]
thanks, it looks very good.

**Comment by justin-pierce** [comment]
> I don't think that we'll implement something like this in lightweight-charts because it looks like something quite niche.
> 
> But as workaround you can try to use histogram/area series on overlay its own price scale and without margins, something like that https://jsfiddle.net/7a93swd6/.

Looks like this might work ok as a workaround, but it'd be nice to be able to shade certain areas of the background to indicate pre-market/after-market bars, for example.
