### ISSUE TITLE
Can I draw a dateline in the chart？

### ISSUE THREAD

**Issue by yuzhiyuan** [tradingview/lightweight-charts#724]
I have 2 questions:
1.Can I draw a dateline in the chart？
2.Can I draw some marks, their height is based on some prices？ and Custom shapes such as triangle

like this
![20210405171930](https://user-images.githubusercontent.com/2228066/113558965-27ca4d00-9633-11eb-8f94-57b84f4ef550.jpg)

**Comment by timocov** [comment]
> Can I draw a dateline in the chart？

What is this?

> Can I draw some marks, their height is based on some prices？ and Custom shapes such as triangle

Is #127 what you need to?

**Comment by yuzhiyuan** [comment]
@timocov yes! thanks very much！

**Comment by obaidaalam** [comment]
how can i draw line

**Comment by edew** [comment]
@obaidaalam it's not currently possible to draw a date/vertical line.
