### ISSUE TITLE
How to update lineSeries with UNIX timestamp

### ISSUE THREAD

**Issue by tupx333** [tradingview/lightweight-charts#730]
I try
`lineSeries.update({
    time: '1619055902',
    value: 24.11,
});`

but it not work . 
Uncaught Error: Invalid date string=1618827153, expected format=yyyy-mm-dd

**Comment by timocov** [comment]
So, the error stated that you provide a time as a string which we interpret as a business day string, not unix timestamp. So to use unix timestamp a time must be a NUMBER, not a string.

**Comment by aktan24** [comment]
i have the same issue, but time is Number, it shows normal in Chrome, but in Safari it shows Invalid date.

**Comment by edew** [comment]
Hi @aktan24 

Can you create a codesandbox/jsfiddle that reproduces your issue?

**Comment by Diogomartf** [comment]
Hi. I also have the same issue with a number. My version:    ` "lightweight-charts": "^3.8.0",`

**Comment by SerjioValentes** [comment]
> Hi. I also have the same issue when Time is a number.
> 
> My version: ` "lightweight-charts": "^3.8.0",`

Same problem

**Comment by pdonaire1** [comment]
I fixed with the next approach:
```
const chartOptions = {
  localization: {
    timeFormatter: (timestamp: any) => moment(timestamp).format('YYYY-MM-DD HH:mm'),
  },
...
}
```

And dataframe set is:
```
const dataParsed = dataFrame.map((df) => ({
      time: df.date, // timestamp, Ex: 1698361200000
      open: df.open,
      high: df.high,
      low: df.low,
      close: df.close,
    }));
```
