### ISSUE TITLE
Candlestick series not respecting `priceFormat` options

### ISSUE THREAD

**Issue by cryptofish7** [tradingview/lightweight-charts#735]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**

```js
      priceFormat: {
      type: 'custom',
      minMove: 0.000001,
      formatter: (price: any) => {
        if (price < 0.000001) return parseFloat(price).toFixed(8)
        else if (price >= 0.000001 && price < 1) return parseFloat(price).toFixed(6)
        else return parseFloat(price).toFixed(4)
      }
    }
```

**Actual behavior:** Shows price to 2 decimal places and a min move of 0.01 (default).

**Expected behavior:** Expecting it to show price to 4 decimal places.

**Screenshots:**

![Screen Shot 2021-05-04 at 1 50 03 AM](https://user-images.githubusercontent.com/80465877/116965185-32502480-ac7b-11eb-9887-00a09924f1e4.png)

**Comment by timocov** [comment]
Can you create jsfiddle snippet to reproduce the issue please? Because I cannot reproduce it here https://jsfiddle.net/jo8gk572/

**Comment by cryptofish7** [comment]
I'm closing this cos it was actually an issue with [kaktana-react-lightweight-charts](https://github.com/Kaktana/kaktana-react-lightweight-charts)
