### ISSUE TITLE
Can the time be formatted as HH: mm on the time axis 

### ISSUE THREAD

**Issue by jinhuatai** [tradingview/lightweight-charts#74]
Hi,
Can the time be formatted as HH: mm? For example, 12:20, 12:21,...
I did not find a similar configuration in the document。

**Comment by sailsweep** [comment]
`function generateCandle(i, target) {
	var step = (i % 20) / 5000;
	var base = i / 5;
	target.open = base * (1 - step);
	target.high = base * (1 + 2 * step);
	target.low = base * (1 - 2 * step);
	target.close = base * (1 + step);
}

function generateData() {
	var res = [];
	var time = new Date(Date.UTC(2018, 0, 1, 0, 0, 0, 0));
	for (var i = 0; i < 500; ++i) {
		var item = {
			time: time.getTime() / 1000,
		};
		time.setUTCDate(time.getUTCDate() + 1);

		generateCandle(i, item);
		res.push(item);
	}
	return res;
}

// eslint-disable-next-line no-unused-vars
function runTestCase(container) {
	var chart = LightweightCharts.createChart(container);

	var mainSeries = chart.addCandlestickSeries();

	mainSeries.setData(generateData());
}
`

**Comment by eugene-korobko** [comment]
Hello!
You can define time formatter of your own, with option `localization.timeFormatter`

**Comment by ezhukovskiy** [comment]
![image](https://user-images.githubusercontent.com/10953908/60168096-06f18880-980d-11e9-8fae-217efe1ac82e.png)

**Comment by timocov** [comment]
> Can the time be formatted as HH: mm? For example, 12:20, 12:21,...

You can disable [secondsVisible](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#time-axis) option.

**Comment by timocov** [comment]
@jinhuatai does something from https://github.com/tradingview/lightweight-charts/issues/74#issuecomment-503184950 or https://github.com/tradingview/lightweight-charts/issues/74#issuecomment-507166502 help you? Or you still have an issue?

**Comment by timocov** [comment]
I'm going to close this issue for now. If you'll have any updates/issues with that - feel free to reopen it.
