### ISSUE TITLE
Append Historical Data for Line Series when scroll

### ISSUE THREAD

**Issue by AsimCanALKAN** [tradingview/lightweight-charts#740]
**Is your feature request related to a problem? Please describe.**

If I scroll horizontally to the historical data, the chart can return a time range to me, but I cannot get the historical data from my own API system according to that range because I have 2 problems.
        1- When I slide to the left, there are a lot of time ranges suddenly. Here I want to get the ranges when I press the mouse and when I up it.
        2- How do I add historical data to the Chart? Update method does not work. it just wants new data.

** Solution Advice **
        1- New mouse event which is called when I press mouse and up it. 
        2- New update method which can append new historical data on the chart

**Comment by timocov** [comment]
1. See https://github.com/tradingview/lightweight-charts/blob/master/docs/events.md. Also you can use something like debounce to load all your data.
2. See example https://jsfiddle.net/TradingView/fg7yez2s/

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
