### ISSUE TITLE
Directionally shaded graphs

### ISSUE THREAD

**Issue by jonluca** [tradingview/lightweight-charts#744]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a chart with directionally shaded graphs - anything above 0 is green and below is red, for instance

**Describe the solution you'd like**

Shading that is different based on the line value set at a certain amount

**Additional context**

Many other financial charts support this

**Comment by timocov** [comment]
It seems that https://github.com/tradingview/lightweight-charts/issues/151 is what you're looking for?

**Comment by jonluca** [comment]
Yes it is! Looks like it wasn't merged in though
