### ISSUE TITLE
Add an option to disable crosshair

### ISSUE THREAD

**Issue by makedonsky94** [tradingview/lightweight-charts#749]
We need a flag or a method to hide the crosshair. Moreover this feature should disable long tap on canvas.

The case: 
- Make the crosshair invisible
- Start the chart
- Make a long tap on canvas
- The chart looks like freezed

**Comment by alexiuz24** [comment]
Any news on this? Even though I am hiding crosshair (visually) on mobile, the chart script seems to think it exists, disabling panning around on the chart until i double touch the chart.
