### ISSUE TITLE
Candlestick upColor and downColor is not changed on applyOptions

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#750]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**

```ts
import { BarData, createChart } from "lightweight-charts";

const chartRoot = document.getElementById("main-chart") as HTMLDivElement;
const chart = createChart(chartRoot, {
  width: 800,
  height: 600
});

const candlestick = chart.addCandlestickSeries({
  upColor: "rgb(0,255,0)",
  downColor: "rgb(255,0,0)"
});

const data: BarData[] = [
  {
    time: "2021-06-04",
    open: 1000,
    high: 1200,
    low: 800,
    close: 900
  },
  {
    time: "2021-06-05",
    open: 1000,
    high: 1200,
    low: 800,
    close: 1100
  }
];

candlestick.setData(data);

setTimeout(() => {
  candlestick.applyOptions({
    upColor: "rgb(0,0,255)",
    downColor: "rgb(0,255,0)"
  });
}, 2000);

setTimeout(() => {
  candlestick.applyOptions({
    upColor: "rgb(0,255,255)",
    downColor: "rgb(255,255,0)"
  });
}, 4000);
```

**Actual behavior:**

Candlestick color doesn't change at all

**Expected behavior:**

Candlestick color should change after applyOptions

**Screenshots:**

![image](https://user-images.githubusercontent.com/1574722/120891108-e6edb500-c630-11eb-860b-99390153938b.png)
After last applyOptions, candlestick color still not changed, it should be yellow down and light blue up

**CodeSandbox/JSFiddle/etc link:**

**Comment by Tucsky** [comment]
[Here a jsfiddle to reproduce the issue](https://jsfiddle.net/xeyj4u3g/2/)
This does not seem to be a recent issue at all / regression. I get the same behavior on 1.x versions of Lightweight Charts

**Comment by SuperPenguin** [comment]
It seems this function called on setData but not applyOptions, hence the _items PaneView still use old style
https://github.com/tradingview/lightweight-charts/blob/cb973d2b460aa187b0b8b5bc8bc327ee072796e5/src/model/series-bar-colorer.ts#L82-L101

**Comment by timocov** [comment]
Looks like a bug. Probably we don't update colors when the only options are applied
