### ISSUE TITLE
Using chart.timeScale().setVisibleRange() before data is added is causing "Error: Value is null"

### ISSUE THREAD

**Issue by gajus** [tradingview/lightweight-charts#751]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

Simply call `chart.timeScale().setVisibleRange()` before adding data to either of the series.

**Actual behavior:**

Produces "Error: Value is null"

**Expected behavior:**

Triggers "subscribeVisibleTimeRangeChange" event.

The reason this behavior is desired is because it would allow a single mechanism to fetch data.

**Comment by gajus** [comment]
Currently, I work around this using:

```js
const startTime = new Date();

startTime.setMinutes(0, 0, 0);

candlestickSeries.setData([
  {
    time: Math.round(startTime.getTime() / 1_000),
  },
]);

chart.timeScale().setVisibleRange({
  from: Math.round(Date.now() / 1_000) - 24 * 3_600,
  to: Math.round(Date.now() / 1_000) + 60,
});
```

Though it is not clear why such limitation exists in the first place.

**Comment by gajus** [comment]
I just realized that `subscribeVisibleTimeRangeChange` values does not change as I scroll.

How do I get "time range that is currently visible regardless of whether there is data"?

**Comment by gajus** [comment]
Looks like I need to do something along the lines of:

```js
timeScale.subscribeVisibleLogicalRangeChange((logicalRange) => {
  const bars = candlestickSeries.barsInLogicalRange(logicalRange);

  if (bars === null) {
    return;
  }

  const from = Math.min(bars.from, Math.round(bars.from - timeBucketWidth * 60 * Math.abs(bars.barsBefore)));
  const to = Math.max(bars.to, Math.round(bars.to + timeBucketWidth * 60 * Math.abs(bars.barsAfter)));

  console.log({
    from,
    to,
  });
});
```

**Comment by gajus** [comment]
I remain confused how to calculate the visible range. The above answers are not right.

<img width="1139" alt="Screen Shot 2021-06-06 at 10 14 14 AM" src="https://user-images.githubusercontent.com/973543/120929816-24ddee00-c6b0-11eb-8a95-532047cde808.png">

As an example, in this chart, only data from 10:00 to 7:00 is loaded.

But the chart allows for a lot more data. What's the correct way to calculate how much data could fit?

**Comment by gajus** [comment]
I think what I am missing is a method "barsInViewport".

If I had that, then I could calculate how much data to load.

**Comment by timocov** [comment]
@gajus is here anything I can help with? Or it's solved now?
