### ISSUE TITLE
Removing data for the last series doesn't actually remove the data

### ISSUE THREAD

**Issue by Tucsky** [tradingview/lightweight-charts#752]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**
Take 2 lines series : serie 1 and serie 2 both line type series of a couple hundred points.

1. Draw serie 1 `serie1.setData([... data points serie 1 ...])`
2. Draw serie 2 `serie2.setData([... data points serie 2 ...])`
3. Clear serie 1 `serie1.setData([])`
4. Clear serie 2 `serie2.setData([])`
5. Draw serie 1 `serie1.setData([... data points serie 1 ...])`

**Actual behavior:**

Serie 1 appear on chart as expected but serie 2 is rendered too (although I _deleted_ the data using setData([]))

**Expected behavior:**

Only serie 1 is drawn as a result of the serie1.setData([... points ...])

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/kjg1zvnx/

![2021-06-06 03 57 41](https://user-images.githubusercontent.com/5738336/120910011-6e601600-c67b-11eb-8019-36bc2b6c91c6.gif)

Maybe setData([]) isn't made for deleting the data? 

This works :
Instead of calling setData([]) draw a fake point
```
serie1.setData([
"time": 1622933040, // first time from other series, avoid 'invalid date' error on time axis...
"value": undefined
}])
```

**Comment by Tucsky** [comment]
![2021-06-06 04 16 52](https://user-images.githubusercontent.com/5738336/120910325-3d351500-c67e-11eb-8ed5-da75164563d9.gif)
Another workaround is to call setData([]) twice

**Comment by timocov** [comment]
@Tucsky https://beta.aggr.trade/series.json says 404 for me

**Comment by timocov** [comment]
> Maybe setData([]) isn't made for deleting the data?

You can use it to delete the data. Also, you can completely remove the series by calling `series.remove()` and then add it again as a workaround.

**Comment by Tucsky** [comment]
> @Tucsky https://beta.aggr.trade/series.json says 404 for me

Ah shit. sorry it's back now

> You can use it to delete the data

That's what I thought in the first place, but sometime it doesn't !

> Also, you can completely remove the series by calling series.remove() and then add it again as a workaround.

Of course. Thought it would be easier on the perf just use setData on existing series instances instead of creating new instances of SeriesApi AND setData all the time, I haven't compared tho

**Comment by timocov** [comment]
Thanks! It's a definitely a bug and we'll fix it.

**Comment by timocov** [comment]
The issue is somewhere here https://github.com/tradingview/lightweight-charts/blob/cb973d2b460aa187b0b8b5bc8bc327ee072796e5/src/api/data-layer.ts#L415-L428
