### ISSUE TITLE
How to calculate bars in viewport?

### ISSUE THREAD

**Issue by gajus** [tradingview/lightweight-charts#753]
The original [issue](https://github.com/tradingview/lightweight-charts/issues/751) got messy as I was trying to figure out how `lightweight-charts` work.

However, it boils down to a single question: How to calculate bars in viewport?

I am able to use `candlestickSeries.barsInLogicalRange(logicalRange)` to get bars missing in the viewport (where there is not enough data) or how many there are outside of the viewport. However, there does not seem to be a method to tell me how many bars fit in the current viewport.

The use case is that I want to ensure that there is always at least 10% of the available viewport's width-worth of data loaded for historical data.

**Comment by gajus** [comment]
so you can get it like this:

```js
const subscribeVisibleLogicalRangeChange = throttle(250, (logicalRange) => {
  const bars = candlestickSeries.barsInLogicalRange(logicalRange);

  if (bars === null) {
    return;
  }

  const barsBefore = Math.round(bars.barsBefore);
  const barsAfter = Math.round(bars.barsAfter);

  const totalBarCount = loadedBarCount - barsAfter - barsBefore;
});

timeScale.subscribeVisibleLogicalRangeChange(subscribeVisibleLogicalRangeChange);
```

for `loadedBarCount`, you will need to track how many data points you've added using `setData`, e.g.

```js
bucketFiller.subscribe((tradeBuckets) => {
  candlestickSeries.setData(tradeBuckets);

  setLoadedBarCount(tradeBuckets.length);
});
```

**Comment by timocov** [comment]
@gajus is here anything I can help with? Or it's solved now?

**Comment by gajus** [comment]
The amount of effort that's currently needed just to calculate what is the width of candlestick bars is pretty insane, including tracking all data that is loaded and workarounds such as [this one](https://github.com/tradingview/lightweight-charts/issues/764#issuecomment-861621082). It would be really nice to just have a method that returns a calculated value.

**Comment by gajus** [comment]
The amount of effort that's currently needed just to calculate what is the width of candlestick bars is pretty insane, including tracking all data that is loaded and workarounds such as [this one](https://github.com/tradingview/lightweight-charts/issues/764#issuecomment-861621082). @timocov It would be really nice to just have a method that returns a calculated value.
