### ISSUE TITLE
Add the ability to have stacked bar charts

### ISSUE THREAD

**Issue by jonluca** [tradingview/lightweight-charts#761]
It would be nice if we could support stacked bar charts. This is a fairly common charting pattern in the financial world, especially when you want to know the cumulative sum of a set of series.

[Info](https://chartio.com/learn/charts/stacked-bar-chart-complete-guide/)

![Image](https://user-images.githubusercontent.com/13029040/121722920-eaab8c80-cab3-11eb-89d1-301a913f6048.jpg)

**Comment by timocov** [comment]
The link to the image doesn't work, it says "AccessDenied".

I'm not sure that we're going to cover all possible "common charting pattern in the financial world" in lightweight-charts. We want to keep it fast, simple and small. Probably #408 might be an option for that so you can implement them yourselves. Probably in the future we'll change our minds.

@ezhukovskiy if you think that we need to implement and this feature might be in lightweight-charts - please re-open the issue.
