### ISSUE TITLE
barsInLogicalRange does not include bars null data

### ISSUE THREAD

**Issue by gajus** [tradingview/lightweight-charts#764]
**Lightweight Charts Version:** 

3.3.0

**Steps/code to reproduce:**

1. set data where some of the data are NULLs, e.g. `candlestickSeries.setData([{time: Date.now()}, {time: Date.now(), open: 1, high: 1, low: 1, close: 1}])`
2. use `candlestickSeries.barsInLogicalRange()`

**Actual behavior:**

* `barsInLogicalRange` does not report NULL data points that are outside of the viewport.
* `barsInLogicalRange` does not report NULL data points that are inside of the viewport.

**Expected behavior:**

* `barsInLogicalRange` reports all data points loaded to series.

**Screenshots:**

N/A

**CodeSandbox/JSFiddle/etc link:**

N/A

**Comment by timocov** [comment]
This is by design and expected. whitespaces are just empty points on the timescale and aren't affected series' data itself, they are removed from series' data before the data is passed to the series.

You can use https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#getvisiblerange for getting visible time range according the data of all series in the chart.

**Comment by gajus** [comment]
I needed this specific requirement in order to accurately [calculate the bar width](https://github.com/tradingview/lightweight-charts/issues/753).

I ended up achieving this by creating a "shadow" series that duplicates all data from the main series, but fills it with filler data that is not NULL.

```js
localChart.addCandlestickSeries({
  priceScaleId: 'shadow',
  visible: false,
})
```

**Comment by timocov** [comment]
> I needed this specific requirement in order to accurately calculate the bar width.

@gajus Why do you need the bar width? Can you explain your case please?

**Comment by gajus** [comment]
* to calculate `vertLine` width (see screenshot)
* to calculate how much data to load (I am loading 20% of the current viewport worth of historic data)

**Comment by timocov** [comment]
> to calculate how much data to load (I am loading 20% of the current viewport worth of historic data)

You don't need to know bar width for that, you can you logical range of time scale for that. See "Infinite history" example here https://jsfiddle.net/TradingView/fg7yez2s/.

> to calculate vertLine width (see screenshot)

I think you can use https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#logicaltocoordinate for that - logical index is the index of bar, thus if you get coordinates for 2 neighbour indexes (1 and 2 for instance) you will get the bar width.

Also, I think we should sync barSpacing/rightOffset values back to the options thus you can get options anytime to retrieve current barSpacing for instance. Can you please check it and if it doesn't work create an issue to fix it?
