### ISSUE TITLE
Chart with a lot of markers lags when chart.update of a single candle is called

### ISSUE THREAD

**Issue by h0wXD** [tradingview/lightweight-charts#767]
**Lightweight Charts Version:** 3.3 

**Steps/code to reproduce:**

Create a chart with a LOT of markers / chart data, the chart I am viewing has a total of 5747 markers, example image can be seen below.

Everything runs incredibly smooth when I don't call following method (once a second or let's say every 5 seconds), but when I do call update on the final candle to repaint, cursor, scrolling and dragging all hangs and it becomes very choppy.

**Actual behavior:**

It repaints every single marker, which takes around 300ms and the chart becomes unusable.

**Expected behavior:**

I would assume that it shouldn't touch any of the existing markers, unless there is a marker on the candle that was updated, then maybe it should update the marker position?

**Screenshots:**

chart with a lot of markers:
![image](https://user-images.githubusercontent.com/10574115/122422970-2668b980-cfc0-11eb-949f-661ab645fa41.png)

Devtools output when calling .update() with a single new candle:
![image](https://user-images.githubusercontent.com/10574115/122423218-56b05800-cfc0-11eb-9401-43905618581f.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Can you provide an example please which we can debug? Probably we can optimize it.

**Comment by h0wXD** [comment]
@timocov Please find the example attached: 
[sample.zip](https://github.com/tradingview/lightweight-charts/files/6678028/sample.zip)
