### ISSUE TITLE
Remove unused internal method from SeriesApi

### ISSUE THREAD

**Issue by creotiv** [tradingview/lightweight-charts#768]
https://github.com/tradingview/lightweight-charts/blob/b28e03c5a5748c9d478399388f3554a96328ba49/src/api/series-api.ts#L54

**Comment by timocov** [comment]
Oh nice catch thanks! We'll remove it since it is not used anywhere and is not part or public API.

**Comment by timocov** [comment]
Another proof that our minifier works very well 😂 Even the method is marked as "public" but since it is not part of public API is has been renamed along with other "internal" methods

**Comment by creotiv** [comment]
Guys, really you had very bad API, i was working for few days just to make it work normally inside electron with dynamic resizing and other things. I still dont know why it cant resize automatically and i should call it from my side, why data should be handled from my side and can't be just updated normally as every developer expect, why i can't access data that i just put into the series.. and many other things.

**Comment by timocov** [comment]
@creotiv if you have any suggestions how to improve our API - feel free to make a suggestion. I think every member of the community will thank you.

> i was working for few days just to make it work normally inside electron with dynamic resizing and other things. I still dont know why it cant resize automatically and i should call it from my side

Please read #71 for this where we already discussed it.

> why data should be handled from my side and can't be just updated normally as every developer expect

I'm sorry? Where you expect the data should be handled? What do you exactly mean under "handled"? How do you expect to "update" the data?

> why i can't access data that i just put into the series.. and many other things.

I think we've discussed it in #414, you can write a note there if you wish.
