### ISSUE TITLE
How to remove price in volumeSeries HistogramSeries

### ISSUE THREAD

**Issue by phongjimmy** [tradingview/lightweight-charts#770]
I need remove price in orange color in image, but not found any document
Thanks
<img width="602" alt="Screen Shot 2021-06-20 at 02 54 24" src="https://user-images.githubusercontent.com/71168450/122654125-5b693d80-d173-11eb-8c69-e091c7330305.png">

**Comment by timocov** [comment]
Duplicate of #623
