### ISSUE TITLE
Data overlaping on plot

### ISSUE THREAD

**Issue by creotiv** [tradingview/lightweight-charts#772]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**
Update with big amount of candles dynamically with time in unix timestamp 
(I dont have any data with different values for same timestamp)

**Video:**
https://youtu.be/HQwnPMwye_I

**Comment by timocov** [comment]
Can you please provide steps to reproduce which I can run locally?

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
