### ISSUE TITLE
Watermark icon

### ISSUE THREAD

**Issue by djaeger-inercomp** [tradingview/lightweight-charts#774]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice if it was possible to add an icon next to the watermark text (left or right). It would be generally nice to be able to add an image as watermark instead of just text.

**Additional context**

**Comment by thanhlmm** [comment]
Yeah, this should be great to have it because we need to add logo as trademark

**Comment by dubeychandan996** [comment]
Is there any alternate method to implement to use the image as background color?
Putting image via CSS I (in canvas) not working because it apply on both canvas and has no power (position: back/front) for z-index.

**Comment by SlicedSilver** [comment]
Example for how to add a logo as a watermark: https://tradingview.github.io/lightweight-charts/tutorials/how_to/watermark
