### ISSUE TITLE
How to work/add support with different time zones

### ISSUE THREAD

**Issue by kamilkazmierczak** [tradingview/lightweight-charts#781]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**
Visit https://jsfiddle.net/b5v8L9et/

**Actual behavior:**
Day TickMark is displayed at 2:00 instead of 0:00

**Expected behavior:**
Allow to configure chart to display tickmark in position valid for specific locale - at 0:00 for day, month, year

**Screenshots:**
![obraz](https://user-images.githubusercontent.com/13839309/124390106-6632df00-dcea-11eb-8bc1-45560c0b69fc.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/b5v8L9et/

I provided custom tickMarkFormatter (and timeFormatter for easier readability) but there is no way to customize where specific tickMark should be displayed

**Comment by timocov** [comment]
As workaround you can try to "fix" the dates you provide in the data by adding timezone offset.

**Comment by maxbethke** [comment]
I had the same problem. This is my workaround for it, incase anyone is feeling lazy:

```
chart.applyOptions({
                    timeScale: {
                        timeVisible: true,
                        tickMarkFormatter: (time, tickMarkType) => {
                            time = this.getTimezoneCorrectedTime(time)
                            [...]
                        }
                    }
                })
   
```



```

getTimezoneCorrectedTime(utcTime, returnAsUnixTimestamp = false) {
                if(utcTime instanceof Date) {
                    utcTime = utcTime.getTime()/1000
                }

                const timezoneOffsetMinutes = new Date().getTimezoneOffset()
                console.log(timezoneOffsetMinutes)

                const correctedTime = utcTime+(timezoneOffsetMinutes*60)

                if(returnAsUnixTimestamp) return correctedTime

                return new Date((utcTime+(timezoneOffsetMinutes*60))*1000)
            }
```

**Comment by timocov** [comment]
Please see https://github.com/tradingview/lightweight-charts/blob/7104e9a4fb399f18db7a2868a91b3246014c4324/docs/time-zones.md

**Comment by ChrisWphoto** [comment]
@timocov Is there a way to select timezone programmatically via chart Options? I see that there is a timezone selector that shows up by default on the bottom bar of the chart. But searching through the docs I don't see if there is a way to set timezone programatically. The time-zones.md seem to be saying no timezone selection is supported 🤔 

![image](https://user-images.githubusercontent.com/8596524/142683119-1ee829fc-97d3-406a-8976-10eaa809fd9e.png)

**Comment by timocov** [comment]
@ChrisWphoto this is not lightweight-charts (on your screenshot).

**Comment by ChrisWphoto** [comment]
Thank you @timocov you're right at poloniex we actually use both the `lightweight-charts` and the paid `tv_chart/charting_library`. I really wish TV's docs were public. Having to request access to see the docs it a perennial gotcha for me 😅
