### ISSUE TITLE
dist directory missing

### ISSUE THREAD

**Issue by victor-github** [tradingview/lightweight-charts#786]
The "dist" directory is not present in the package installed through "npm install".

Whereas these are required in index.js and are not being found:

if (process.env.NODE_ENV === 'production') {
	module.exports = require('./dist/lightweight-charts.esm.production.js');
} else {
	module.exports = require('./dist/lightweight-charts.esm.development.js');
}

**Comment by victor-github** [comment]
Current list of directories inside the package installed through "npm install":

<img width="445" alt="Screen Shot 2021-07-12 at 1 48 25 PM" src="https://user-images.githubusercontent.com/99985/125242970-9cd6ae00-e317-11eb-8d95-519889864108.png">

**Comment by timocov** [comment]
Yes, it is https://unpkg.com/browse/lightweight-charts/dist/.

I don't think that it's a good idea to install this package directly from github as soon as you have to compile and bundle library before use it.

**Comment by victor-github** [comment]
I just installed it as per the instructions in the README, with "npm install". How else should I install it?

**Comment by timocov** [comment]
@victor-github Can you prepare steps to reproduce the issue and what versions of nodejs and npm you have?
