### ISSUE TITLE
Strange margins in the chart

### ISSUE THREAD

**Issue by Grayn** [tradingview/lightweight-charts#79]
I added this chart library unpkg to my pet project and I see strange margins, this is the screenshot https://postimg.cc/ykktdrJ1. What can cause this?

**Comment by Business223rx** [comment]
I don't know I think I got a virus

**Comment by eugene-korobko** [comment]
Hello!

Could you please try different browsers and try your browser in incognito mode, without plugins/extensions. It looks like some external app affects chart layout

**Comment by Grayn** [comment]
> Hello!
> 
> Could you please try different browsers and try your browser in incognito mode, without plugins/extensions. It looks like some external app affects chart layout

I understood that it can be because of the css collision, can I somewhere see classes used in this library?

**Comment by timocov** [comment]
> I somewhere see classes used in this library?

We don't use any CSS classes to style the library (we inline some styles right inside elements, but nothing else). I believe you can easy detect what's wrong by using devtools and see, what styles are applied to the elements with that margins.

**Comment by timocov** [comment]
@Grayn did you solve your issue or still have a problem>

**Comment by timocov** [comment]
I'm going to close this issue for now. If you'll have any updates/issues with that - feel free to reopen it.
