### ISSUE TITLE
series.priceFormatter().format(price) does not work

### ISSUE THREAD

**Issue by olegchernenko** [tradingview/lightweight-charts#790]
**Lightweight Charts Version:** 3.2.0

**Steps/code to reproduce:**

```js
const chart = LightweightCharts.createChart(document.body);
const lineSeries = chart.addLineSeries();
lineSeries.priceFormatter().format(123.4);
```

**Actual behavior:**

an error "Uncaught TypeError: chart.timeScale(...).formatDateTime is not a function" occurs

**Expected behavior:**

I will get the formatted price value

**Comment by timocov** [comment]
The minifier...
