### ISSUE TITLE
Overlapped line chart show wrong color order when hover

### ISSUE THREAD

**Issue by thanhlmm** [tradingview/lightweight-charts#794]
**Lightweight Charts Version:** 3.4.0

**Steps/code to reproduce:**

```js
var series = chart.addLineSeries({
  color: "green",
  lineWidth: 2
});

series.setData(data);

var series2 = chart.addLineSeries({
  color: "red",
  lineWidth: 2
});

series2.setData(data);
```

**Actual behavior:**

The crosshair when hover show as red but the line show in the chart is green.

**Expected behavior:**

The crosshair when hover should be in green since the green line is above the red line

**Screenshots:**

<img width="531" alt="Screen Shot 2021-07-26 at 16 48 44" src="https://user-images.githubusercontent.com/9281080/126969534-711fae95-5d76-4d9d-8b3c-301ed5e0eb34.png">

**CodeSandbox/JSFiddle/etc link:**

https://codesandbox.io/s/hardcore-frost-3pxjn?file=/src/index.js

**Comment by timocov** [comment]
> The crosshair when hover should be in green since the green line is above the red line

I think the opposite - the line should be red instead of green since the red line was created after the green one, so this looks like a bug I think.

**Comment by thanhlmm** [comment]
> > The crosshair when hover should be in green since the green line is above the red line
> 
> I think the opposite - the line should be red instead of green since the red line was created after the green one, so this looks like a bug I think.

Yeah whatever order but I think I should show the same like what the line is displayed, If it is green, the crosshair should show green

**Comment by timocov** [comment]
@thanhlmm if you'd like you can provide a fix for that.

**Comment by thanhlmm** [comment]
I'd like to. Do you have any suggest on where I can start to investigate on?

**Comment by timocov** [comment]
@thanhlmm Sure.

I'd start from the following places:
- [zOrder getter & setter](https://github.com/tradingview/lightweight-charts/blob/57cdf877ec87e6a32299c74615032c1175574a0b/src/model/data-source.ts#L14-L20) of DataSource - zOrder basically defines the order of data source through all other data sources
- [orderedSources](https://github.com/tradingview/lightweight-charts/blob/57cdf877ec87e6a32299c74615032c1175574a0b/src/model/pane.ts#L313-L319) which sorts sources in model
- [CrosshairMarksPaneView](https://github.com/tradingview/lightweight-charts/blob/57cdf877ec87e6a32299c74615032c1175574a0b/src/views/pane/crosshair-marks-pane-view.ts) pane view which is used to create renderers for small dots for every line-like series to draw them a top of all series
- [PaneWidget._drawSources](https://github.com/tradingview/lightweight-charts/blob/57cdf877ec87e6a32299c74615032c1175574a0b/src/gui/pane-widget.ts#L569-L580) method which is used to draw all sources.

Probably there is some differences between the order of sources for crosshair and for pane.
