### ISSUE TITLE
Price line label show on both axis

### ISSUE THREAD

**Issue by thanhlmm** [tradingview/lightweight-charts#795]
**Lightweight Charts Version:** 3.4.0

**Steps/code to reproduce:**

```js
var series = chart.addLineSeries({
  color: "green",
  lineWidth: 2,
  priceScaleId: "left"
});

series.setData(
  data.map((row) => ({
    time: row.time,
    value: row.value * 10
  }))
);

var series2 = chart.addLineSeries({
  color: "red",
  lineWidth: 2,
  priceScaleId: "right"
});

series2.setData(data);

series2.createPriceLine({
  price: 98,
  color: "blue"
});
```

**Actual behavior:**

Price line label show on both axis

**Expected behavior:**

Price line show only on its axis

**Screenshots:**

<img width="514" alt="Screen Shot 2021-07-26 at 17 20 35" src="https://user-images.githubusercontent.com/9281080/126973739-76325b92-961b-4731-baf7-d41ccde0df1c.png">

**CodeSandbox/JSFiddle/etc link:**

https://codesandbox.io/s/price-line-show-on-both-axis-wo98u?file=/src/index.js:16149-16520

**Comment by timocov** [comment]
The issues is [somewhere here](https://github.com/tradingview/lightweight-charts/blob/f26d7ce1592f8c8c4dec7c2736cf8b6bdee662fb/src/model/series.ts#L375-L378). @thanhlmm would you like to provide a fix for that?

**Comment by thanhlmm** [comment]
@timocov I will
