### ISSUE TITLE
Development with live update & example

### ISSUE THREAD

**Issue by thanhlmm** [tradingview/lightweight-charts#796]
**Is your feature request related to a problem? Please describe.** 
I'm trying to add a new feature to the lib, but the problem is that I don't know how to live development with testing example

**Describe the solution you'd like**

I see that we already have an e2e test folder, is there any way we can make it live to debug on the browser?

**Additional context**

I'm trying to contribute on this issue: https://github.com/tradingview/lightweight-charts/issues/699

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/master/BUILDING.md#tips.

Basically to work with the library locally you need to setup your `debug.html` page (see the doc above) and run `npm run build` every time you want to update the build. `debug.html` file could be opened in browser directly so you don't need to run webserver for that.

**Comment by thanhlmm** [comment]
Thanks @timocov . That really help

**Comment by timocov** [comment]
```html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
	<title>Debug page</title>

	<script type="text/javascript" src="./dist/lightweight-charts.standalone.development.js"></script>
</head>

<body style="padding: 0; margin: 0;width: 100%; height: 100%;">
	<div id="container" style="position: absolute; width: 100%; height: 100%;"></div>

	<script type="text/javascript">
		function runTestCase(container) {
		}

		runTestCase(document.getElementById('container'));
	</script>
</body>

</html>
```

Also, your `debug.html` file might be something like this, and if you want to run any e2e test case to see how it looks like you can just copy the content of a test file and then replace `runTestCase` function.

**Comment by timocov** [comment]
Let me know if you will have any issues.
