### ISSUE TITLE
Chart prevents vertical scroll on touch devices

### ISSUE THREAD

**Issue by vladmoroz** [tradingview/lightweight-charts#80]
I was unable to create a chart that would scroll horizontally on iOS, yet wouldn't prevent user from scrolling the page vertically. The chart captures touch events and doesn't let them through.

I expected that one of the following options would have worked for me, but neither did:
```
handleScroll: {
  pressedMouseMove: false
}

// Nope, disables all scroll on touch devices

OR

handleScale: {
  mouseWheel: false
}

// Nope, still captures vertical scroll on touch devices
```

**Comment by timocov** [comment]
We've added 2 new options for handle scroll of the chart: `horzTouchDrag` and `vertTouchDrag`.

For more information see #92 and https://github.com/tradingview/lightweight-charts/blob/76a3dc2ccb1b4932ade6ac3b5d3dd53b3781c479/docs/customization.md#scrolling-options for docs.

These fixes will be published to npm soon (I believe in couple of days).

**Comment by timocov** [comment]
The [version 1.0.0](https://www.npmjs.com/package/lightweight-charts/v/1.0.0) is just published.

**Comment by vladmoroz** [comment]
@timocov thank you so much 🙏

**Comment by onur-celik** [comment]
@vladmoroz this is an old case but is the solution worked for you?

**Comment by vladmoroz** [comment]
@onur-celik Sorry, this was a while ago and I don't remember. Not working on anything that uses this package currently.

**Comment by onur-celik** [comment]
oh ok @vladmoroz thanks anyway.

**Comment by timocov** [comment]
@Amiram1 what exact issue? This issue was marked as a bug and closed long time ago.

**Comment by emrahtunc14** [comment]
> Hey @timocov what I am trying to do is actually same with this page.
> If you open this url on a mobile device ( I've checked both iOs and Android devices ) https://tr.tradingview.com/symbols/BIST-GARAN/ you will see that user is available to scroll page down touching right over the chart. But I could not make the same thing. Even I set both handleScroll and handleScale to false, you can not scroll the page up or down if the chart cover all over the screen.

I have the same problem @timocov

**Comment by timocov** [comment]
> But I could not make the same thing. Even I set both handleScroll and handleScale to false, you can not scroll the page up or down if the chart cover all over the screen.

@emrahtunc14 @onur-celik can you please prepare a reproduction for your issue?

**Comment by mrtpain** [comment]
Is there anyone that still has this issue other than myself? Using `3.6.1` currently with charts can't seem to allow scrolling.
