### ISSUE TITLE
horizontals bars on graph

### ISSUE THREAD

**Issue by 8Link21** [tradingview/lightweight-charts#809]
Hi every one ^^

I have an issue with graph. Many horizontals bar appears. (on Safari & Gchrome last update)
I've check:
> data's array don't have troubles. (empy data or bad properties names) 
data = [{time: 1627399614, value: 19.2841}, ... ]

I've read on Docs:
Note that to prevent errors, you should cast the numeric type of the time to UTCTimestamp (it's a nominal type) type from the package (value as UTCTimestamp) in TypeScript code.

But I dont understand how and where to convert time data with UTCTimestamp (from ts script's package)
May be it's the solution...

if you need some infos or if someone already had this problem tell me

Thanks :)

<img width="579" alt="Capture d’écran 2021-08-02 à 20 06 41" src="https://user-images.githubusercontent.com/15885288/127905914-a6354bec-9dc8-41a0-a9fa-fdbc8d9cd091.png">
<img width="587" alt="Capture d’écran 2021-08-02 à 20 07 06" src="https://user-images.githubusercontent.com/15885288/127905924-2cbc4396-9f1d-4d8b-9a8b-cc828d9ae42a.png">

**Comment by edew** [comment]
Hi @8Link21. Can you tell us which version of the library you are using, and if possible provide an example that reproduces the issue (using CodeSandbox, jsFiddle, etc)?

**Comment by 8Link21** [comment]
Hi @edew, sure :)

I'm with latest lightweight-charts ^3.4.0
When I worked on reproducing issue, I found the error and solution too ^^

I had not checked the time values. An error occurs when 2 identical values ​​follow one another.
you can check the issue [here](https://jsfiddle.net/8link21/q8ou4rw1/)

I'm just make filter on data array like this:
`let lastTime = 0;
let dataFiltered = data.filter(el => el.time !== lastTime ? (lastTime = el.time, 1) : 0)`


another thing, about casting time to UTCTimestamp via package (view [here](https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md)
How do that ?

Thanks a lot ^^

**Comment by edew** [comment]
Hi @8Link21. Cool, glad you got it working.

Here's an example of casting a `number` to `UTCTimestamp` in TypeScript. If you're not using TypeScript in your application then you don't need to do this of course.

https://codesandbox.io/s/polished-cdn-fxzvk

**Comment by 8Link21** [comment]
Thanks @edew, 
for your time and explanations
thats clear now ^^
