### ISSUE TITLE
Issue with autoscale

### ISSUE THREAD

**Issue by cserb** [tradingview/lightweight-charts#811]
I assume it's an issue with autoscale...
I would expect that the area is automatically scaling to the width of the chart, but it leaves some space on the left side

![Screenshot 2021-08-04 at 15 13 27](https://user-images.githubusercontent.com/1147993/128239900-a9a955d0-03c1-4eee-90d5-d58bc652ae5b.png)

https://jsfiddle.net/bvjgp5z7/
I'm still trying it out, that's why the code is a bit messy. Sorry about that.

**Comment by thanhlmm** [comment]
I usually use `chart.timeScale().fitContent();` to make the chart fit with its container

More detail: https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md

**Comment by timocov** [comment]
Auto scale is only working for price scales and I think it works fine. The thing you want to achieve might be done by using fitContent as mentioned @thanhlmm in https://github.com/tradingview/lightweight-charts/issues/811#issuecomment-893289560. Also, you can use fixLeftEdge/fixRightEdge options to disallow scroll outside of the data, so you won't see any space from both sides.
