### ISSUE TITLE
Histogram Suddenly Not Respecting setData Ordering (as of Aug.4, 2021)

### ISSUE THREAD

**Issue by jonnyzwi** [tradingview/lightweight-charts#812]
It appears that as of today, the histogram no longer respects the layering/order of setData.

This problem has occurred in several unchanged scripts, so I know the change in functionality did not come from an inadvertent change on my part.

Is there a new way to specify the order in which series are rendered, or is this a bug?

**Histogram Respecting setData Ordering (yesterday, Aug.3,2021):**

![Histogram Respecting setData Ordering](https://user-images.githubusercontent.com/76882288/128263152-85eb7d50-984c-4285-a392-396d54880a1d.jpg)

**Histogram NOT Respecting setData Ordering (today, Aug.4,2021):**

![Histogram Not Respecting setData Ordering](https://user-images.githubusercontent.com/76882288/128263155-0fba6708-9fc6-44c5-964f-53b5ea7b4ecb.jpg)

Thank you

**Comment by thanhlmm** [comment]
Hey, it might due to this change https://github.com/tradingview/lightweight-charts/pull/800

So the order display in the chart will respect the order on your code. Eg;
```
chart.addSeries1;
chart.addSeries2;
```
=> `series2` is above `series1`

**Comment by timocov** [comment]
Yeah, this is intended and it was a bug actually.

**Comment by jonnyzwi** [comment]
Thank you
