### ISSUE TITLE
Incorrect initial barSpacing when both fixRightEdge and fixLeftEdge are enabled

### ISSUE THREAD

**Issue by kritsky** [tradingview/lightweight-charts#823]
Example is the first demo from the website:
https://jsfiddle.net/TradingView/v0p52anL/

just change this:
```
timeScale: {
		borderColor: 'rgba(197, 203, 206, 1)',
	},
```

to this:
```
timeScale: {
		borderColor: 'rgba(197, 203, 206, 1)',
		fixRightEdge: true,
		fixLeftEdge: true,
	},
```

It zooms in. How to fix it?

**Comment by edew** [comment]
Hi @kritsky, thanks for opening this issue.

Can you tell us what behaviour you expected in this case?

**Comment by kritsky** [comment]
The same view as by default.
And that users can't scroll to the future and the past from the first data.

**Comment by timocov** [comment]
Yeah, looks strange.
