### ISSUE TITLE
Price axis doesn't respect the width of crosshair label

### ISSUE THREAD

**Issue by thanhlmm** [tradingview/lightweight-charts#834]
**Lightweight Charts Version:** 3.5.0

**Steps/code to reproduce:**

```js
  priceFormat: {
    type: "custom",
    minMove: 0.00000001,
    formatter: (price) => {
      return window.numeral(price).format("0.[000]") + "USD";
    }
  }
```
`numeral` is a lib to format number

**Actual behavior:**

<img width="336" alt="Screen Shot 2021-09-06 at 20 25 31" src="https://user-images.githubusercontent.com/9281080/132224261-eb3e7715-15b9-4a49-91b8-ecd0054fafcc.png">

**Expected behavior:**

The axis will show enough space for the label

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**
https://codesandbox.io/s/axis-number-width-qve8d?file=/index.html
You will need `Open in New window` to check it

**Comment by thanhlmm** [comment]
Propose solution:

Currently, the chart width is determined by the length of Min and Max label. So I think it better to check width by all mark label visible + a medium point (min + max)/2

**Comment by timocov** [comment]
Hi there, it seems that we already fixed this on tradingview.com, I'll migrate a fix to lightweight-charts soon.

**Comment by thanhlmm** [comment]
Sound great
