### ISSUE TITLE
Improve performance of updating data

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#838]
We significantly have improved performance of setting/updating data of series. It needs to migrate these fixes to lightweight-charts as well.

**Comment by timocov** [comment]
Related to #418

**Comment by vritme** [comment]
Done some tests on the production project.
3.5.0 - setting data for 9.845s.
3.7.0 - setting data for 6.045s.
38.6% improvement. Fantastic!)
Also in my case I  have noticed, that 3.8.0 was a little bit slower than 3.7.0.
