### ISSUE TITLE
[bug] Plotted dates differ between different PC time zones

### ISSUE THREAD

**Issue by awunder** [tradingview/lightweight-charts#84]
**issue seems to be timezone related, please skip to https://github.com/tradingview/lightweight-charts/issues/84#issuecomment-504732465 and https://github.com/tradingview/lightweight-charts/issues/84#issuecomment-504732712**

**Lightweight Charts Version:** 
1.0.0 RC5
**Steps/code to reproduce:**

load data from json url and plot the chart

**Actual behavior:**

right now my json api delivers this data:

[
...snip...
{"time":"2019-06-13","open":31.69,"high":33.32,"low":31.41,"close":33.09},
{"time":"2019-06-14","open":32.97,"high":33.2,"low":32.22,"close":32.68},
{"time":"2019-06-17","open":32.1,"high":32.92,"low":32.1,"close":32.56},
{"time":"**2019-06-18**","open":32.78,"high":33.3,"low":32.42,"close":32.52}
]

the chart however, shows all the dates substracted by 1 day(?)

**Expected behavior:**

it should plot the chart dates like its input.
**Screenshots**

see screenshot of the actual chart to the data pasted above:

![image](https://user-images.githubusercontent.com/13486613/59870774-25b2d380-9364-11e9-927c-3e8dd38d560e.png)

thank you,
Andreas

**Comment by awunder** [comment]
there def is an issue and it seems to be a timezone related.. and it even affects monthly charts..(!?)

when i open load the page with my PC set to Eastern Standard Time (my default setting), i see the monthly candle for june presented as may (wrong):

![image](https://user-images.githubusercontent.com/13486613/59973779-3b95e380-9572-11e9-8ba7-4ea66cfabc2f.png)

when i set my PC clock to CEST and refresh the page it shows the same data but this time the candle is presented to me as the june candle (correct):

![image](https://user-images.githubusercontent.com/13486613/59973793-61bb8380-9572-11e9-987f-c3d9c8211dea.png)

please take a look at it as its pretty confusing.

thanks,
Andreas

**Comment by awunder** [comment]
fwiw and completeness sake, here are the daily charts as well:

CEST with correct dates:

![image](https://user-images.githubusercontent.com/13486613/59973865-00e07b00-9573-11e9-88eb-76026800c9b7.png)

EST with incorrect dates:

![image](https://user-images.githubusercontent.com/13486613/59973871-0dfd6a00-9573-11e9-915c-6013168f7a03.png)

**Comment by timocov** [comment]
The [version 1.0.0](https://www.npmjs.com/package/lightweight-charts/v/1.0.0) is just published.
