### ISSUE TITLE
Data set input issue

### ISSUE THREAD

**Issue by mcmichaelau** [tradingview/lightweight-charts#842]
I am trying to plot using the candlestick chart in javascript and am running in to an issue with the data input. Before I use my actual data, I have been testing with a mock dataset:

`var o = [1,2];`
`var h = [3,4];`
`var l = [0,1];`
`var c = [2,3];`
`var t = [1,2];`

These arrays are how I receive my data and are separated by open, high, low, close, and time. In order to arrange this data in the format needed for the chart input, I use a simple for loop and push function:

```js
var input_array = [];
for (let i = 0; i < o.length; i++){
	ohlc = [
		{
		open:o[i],
		high:h[i],
		low:l[i],
		close:c[i],
		time:t[i]
		}
	]
	input_array.push(ohlc);
}
```

This arranges each corresponding array element into an object called "ohlc" and then pushes these objects into an array called "input_array". I then log the result to console just to see that it is working and also use the setData function to insert the data into the graph:

`console.log(input_array);`
`candleSeries.setData(input_array);`

I have tested that all my other graphing code works if I manually input the data, however when I use this for loop method, I get a blank graph and an error:
![lightweighterror](https://user-images.githubusercontent.com/89956667/132802917-8fb4996d-93a0-4541-be0f-bdc388faf222.jpg)
I can see the array in the console and it seems to be in the correct format so I am not sure what's going wrong:
![arraylightweight](https://user-images.githubusercontent.com/89956667/132803036-7451a336-4156-4b01-863b-ef48c7e7a769.jpg)
I haven't found any documentation on this, any help would be greatly appreciated.

Thanks!

**Comment by timocov** [comment]
Can you create jsfiddle (or any other similar tool) reproduction please?

**Comment by mcmichaelau** [comment]
Here's the jsfiddle link: https://jsfiddle.net/4s2vg8na/14/#&togetherjs=a1NerA42qb

I am not sure if that is how the array should be input into the setData function, but I have tried it numerous ways without success.

Thanks for the response

**Comment by mcmichaelau** [comment]
I've been messing with the input a little bit to try and figure this out. I didn't find a solution but I did find something that might help. I tried placing the setData function inside the for loop with the ohlc object as an input and it worked fine. Of course, this will only plot the candlestick from the final run through of the for loop, but at least it shows that the arguments within the array are formatted properly.

Here is the jsfiddle link to what I just described: https://jsfiddle.net/scjhqop7/3/

The problem must be something to do with how the candlestick objects are formatted within the input array. Hope this helps.

Thanks

**Comment by timocov** [comment]
@mcmichaelau the issue is that `ohlc` object must be _an object_, not an array. So just replace 

```js
	ohlc = [
		{
		open:o[i],
		high:h[i],
		low:l[i],
		close:c[i],
		time:t[i]
		}
	]
```

with

```js
	ohlc = {
		open:o[i],
		high:h[i],
		low:l[i],
		close:c[i],
		time:t[i]
	}
```

and it will work as expected.
