### ISSUE TITLE
Doesn't work with candles with different intervals between

### ISSUE THREAD

**Issue by jussirantala** [tradingview/lightweight-charts#847]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
Add a candle dataset with candles with different timespans between. For example 1 min candle, 3min candle, 12min candle.
https://jsfiddle.net/n3ypu1am/

**Actual behavior:**
Empty chart.

**Expected behavior:**
Candles should be visible. I use this for volume intervals. New candle is printed after every new X million of new volume. That is the reason the time interval doesn't stay as the same.

**Comment by timocov** [comment]
Can you provide example please? The library doesn't count the resolution of your data so most likely something is wrong with your data or config.

**Comment by jussirantala** [comment]
> Can you provide example please? The library doesn't count the resolution of your data so most likely something is wrong with your data or config.

https://jsfiddle.net/n3ypu1am/

There's an example with the bug. The console is getting spammed with "Value is null" error.

**Comment by jussirantala** [comment]
Found the problem. Some candles had the same timestamp
