### ISSUE TITLE
rightOffset doesn't work with fixRightEdge

### ISSUE THREAD

**Issue by getmonyinfo** [tradingview/lightweight-charts#848]
`timeScale: {
                rightOffset: 3,
                fixRightEdge: true,
            },`

rightOffset has no effect!

so,what's the problem ?

**Comment by timocov** [comment]
The problem is that `rightOffset` and `fixRightEdge` are exclusive options - you cannot set positive right offset if `fixRightEdge` is enabled (due the nature if this option - it restricts to have positive right offset). So this is by design and expected.

**Comment by getmonyinfo** [comment]
thanks . and i want 2 bars space between right axis, and prevent scrolling too right, any idea?
