### ISSUE TITLE
Add scaleMargins to candlestickSeries

### ISSUE THREAD

**Issue by fabriziogiordano** [tradingview/lightweight-charts#852]
**Is your feature request related to a problem? Please describe.**
Candlestick Series currently do not fit the entire available space in a chart.

**Describe the solution you'd like**
I'd like to have the option (as it is on regular series) to determine how much bottom and top space a candlestick series can take.

**Comment by timocov** [comment]
> Candlestick Series currently do not fit the entire available space in a chart.

Any example? What do you mean?

**Comment by fabriziogiordano** [comment]
It seem that these options:

```
	scaleMargins: {
		bottom: 0.1,
		top: 0.2,
	},
```	
can't be configured for candlestick series.

https://github.com/tradingview/lightweight-charts/blob/c84b12e5f7a97576902d9129decb3e8acbaf8e72/src/api/options/price-scale-options-defaults.ts#L13

**Comment by fabriziogiordano** [comment]
Nevermind I should have read the doc more carefully. It can be applied to the whole chart.

**Comment by timocov** [comment]
[`scaleMargins` is an option](https://github.com/tradingview/lightweight-charts/blob/master/docs/customization.md#price-axis) for _price scale_, not for the chart itself. If you apply this option to one of your price scale it will work as you expect https://jsfiddle.net/Luojmd5h/.
