### ISSUE TITLE
Get time coordinate from any time, not just the present on the chart

### ISSUE THREAD

**Issue by maracaipe** [tradingview/lightweight-charts#855]
Hello! First of all congrats to the package maintainers on such good implementation.

I'm implementing one feature on top of the chart that requires me to get the x (time) coordinate from timestamps in the future, that doesn't contain data points for them.
The current implementation (`timeScale.timeToCoordinate(time)`) is kinda limited for me because it only returns coordinates for data points that are on the specific timestamp.

I tried to use whitespace data, but it didn't work for me because I have a live chart, and when I create a whitespace datapoint in the future, and my live data provider updates the chart, I get an error because the chart doesn't support receiving data that is in the past of the last data point.

I noticed that other chart solutions from trading view have the possibility to get the coordinate for timestamps that don't contain data on them, so I wonder if it's possible to port something from them to this solution. If it's not possible, then it's a feature request for here.

**Comment by timocov** [comment]
Hi there,

> I noticed that other chart solutions from trading view have the possibility to get the coordinate for timestamps that don't contain data on them, so I wonder if it's possible to port something from them to this solution. If it's not possible, then it's a feature request for here.

I'm afraid we don't have it and we're not going to implement this feature in lightweight-charts because this feature is quite complicated and I'd say it might be the same size (or even more) as this package. If you'd like to have "a prediction" of time points, please do it yourself by using whitespaces.

> when I create a whitespace datapoint in the future, and my live data provider updates the chart, I get an error because the chart doesn't support receiving data that is in the past of the last data point.

You can try to create another series for whitespaces only so updates of "the real series" will not generate such errors.

**Comment by maracaipe** [comment]
> You can try to create another series for whitespaces only so updates of "the real series" will not generate such errors.
That's a good idea! I can try that in the future.

In the meantime, I was able to get the precise location with this logic:

```ts
const getChartCoordinateFromTime = (time: Date, data: BarData[], chart: IChartApi): number | undefined => {
    if (data.length < 2) return;

    const baseDataPoint = data[data.length - 2];
    const compareDataPoint = data[data.length - 1];

    const x1 = chart.timeScale().timeToCoordinate(baseDataPoint.time);
    const x2 = chart.timeScale().timeToCoordinate(compareDataPoint.time);

    if (!x1 || !x2) return;

    const offset = x2 - x1;
    const secondsDifference = differenceInSeconds(time, new Date(baseDataPoint.timestamp)); // date-fns method

    return x1 + (offset * (secondsDifference / 60));
}
```

**Comment by timocov** [comment]
Glad to hear that. I'm going to close the issue then. If you'll have any question or updates - feel free to re-open it.
