### ISSUE TITLE
TypeError: performance.now is not a function when using lightweight chart

### ISSUE THREAD

**Issue by 106820026** [tradingview/lightweight-charts#856]
**Lightweight Charts Version: 3.7.0**

**Steps/code to reproduce:**
I import the script like this
```
<script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
```
I get the data set from Google cloud firestore as the input
```
<script type="text/javascript">
    $(document).ready(function() {
        db.collection('爬蟲歷史資料').doc("費半").collection("歷史價錢").get().then((documents) => {
            var histData = []
            documents.forEach(function(doc) {
                var json = {
                    'time': doc.id,
                    'value': parseFloat(doc.data().price.toString().replace(",", ""))
                }
                histData.push(json);
            })
            console.log(histData)
                // 建立技術分析圖
            var width = document.getElementById("stock-chart").getBoundingClientRect().width * 1.05;
            var height;
            if (screen.width <= 1920) {
                height = 500;
            } else if (screen.width <= 3840) {
                height = 1120;
            }

            var dest = document.getElementById("SOX");
            var chart = LightweightCharts.createChart(dest, {
                width: width,
                height: height,
                layout: {
                    textColor: '#d1d4dc',
                    backgroundColor: 'rgba(0, 0, 5, 0.9)',
                },
                rightPriceScale: {
                    scaleMargins: {
                        top: 0.3,
                        bottom: 0.25,
                    },
                },
                crosshair: {
                    vertLine: {
                        width: 5,
                        color: 'rgba(224, 227, 235, 0.1)',
                        style: 0,
                    },
                    horzLine: {
                        visible: false,
                        labelVisible: false,
                    },
                },
                grid: {
                    vertLines: {
                        color: 'rgba(42, 46, 57, 0.8)',
                    },
                    horzLines: {
                        color: 'rgba(42, 46, 57, 0.8)',
                    },
                },
            });

            var areaSeries = chart.addAreaSeries({
                topColor: 'rgba(38, 198, 218, 0)',
                bottomColor: 'rgba(38, 198, 218, 0)',
                lineColor: 'rgba(51, 51, 255, 1)',
                lineWidth: 2,
                crossHairMarkerVisible: false,
            });
            console.log("set data")
            areaSeries.setData(histData);

            dest.style.position = 'relative';

            var legend = document.createElement('div');
            legend.classList.add('legend');
            dest.appendChild(legend);

            var firstRow = document.createElement('div');
            firstRow.innerText = '費半';
            firstRow.style.color = 'white';
            firstRow.style.fontFamily = 'Microsoft JhengHei';
            legend.appendChild(firstRow);

            function pad(n) {
                var s = ('0' + n);
                return s.substr(s.length - 2);
            }

            chart.subscribeCrosshairMove((param) => {
                if (param.time) {
                    const price = param.seriesPrices.get(areaSeries);
                    const date = param.time['year'] + "/" + param.time['month'] + "/" + param.time['day']
                    firstRow.innerText = '費半' + '  ' + date + '  ' + parseFloat(price).toFixed(2);
                } else {
                    firstRow.innerText = '費半';
                }
            });
        });
    });
</script>
```

**Actual behavior:**

An error occur when calling ```var areaSeries = chart.addAreaSeries``` and the chart only shows background.

**Expected behavior:**

Originally, it will shows a chart with my own data on it.

**Screenshots:**
Error message

![image](https://user-images.githubusercontent.com/52745661/135192887-ef3eb8eb-a81e-4afc-8721-d99a6fbd1e3e.png)

Chart with only background

![image](https://user-images.githubusercontent.com/52745661/135193268-64e91c7f-d790-442c-a65b-10dc37d3f60c.png)

Console log of the data I got from firestore

![image](https://user-images.githubusercontent.com/52745661/135193419-7a559463-bf72-4f1a-aedd-744664110262.png)

**Comment by timocov** [comment]
What browser do you use?

**Comment by timocov** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#browser_compatibility it looks like it should be available almost everywhere in modern browsers.

**Comment by 106820026** [comment]
I am using Chrome.



It is weird that if I don’t use the data from firestore, and input the data from other resource, the chart will show data but it can’t be dragged on x axis.


寄件者: Evgeniy Timokhov
傳送時間: 2021年9月29日 下午 03:48
收件者: tradingview/lightweight-charts
副本: 106820026; Author
主旨: Re: [tradingview/lightweight-charts] TypeError: performance.now is not a function when using lightweight chart (#856)

https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#browser_compatibility it looks like it should be available almost everywhere in modern browsers.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by timocov** [comment]
I just tried the same in latest Chrome 94 on the page https://jsfiddle.net/L7eoasym/ and it works fine. Can you deploy your page somewhere where you can reproduce the issue so I can take a look?

**Comment by 106820026** [comment]
Here is the link - https://raspberrypi4-15cd1.web.app/invest.html
![image](https://user-images.githubusercontent.com/52745661/135232536-70dc5dad-fce7-486a-8177-015ef7fa8505.png)
Please click the red circle and the error chart will show up.

**Comment by 106820026** [comment]
By the way, I am using the free plan of firestore, sometimes it will hit the maximum read and write volume and the webpage will show nothing @@.

**Comment by timocov** [comment]
It seems that you declared a global variable with a name `performance` so that's why it doesn't work correctly.

![image](https://user-images.githubusercontent.com/3112183/135241421-bf0a21d9-dd2f-42de-8af0-a1f750c6be81.png)

Overriding browser's API is not a good idea so please try to fix it.

**Comment by 106820026** [comment]
Thanks a lot! I didn't notice that. How did you find out? You’re very professional!

**Comment by timocov** [comment]
I just stopped on the exception and look at the code caused it. You can enable this option in your devtools so you'll stop on every uncaught exception too so you'll see call stack, local and global variables at the time.

![image](https://user-images.githubusercontent.com/3112183/135243951-25f99c8f-8cf9-480f-a9cf-0fe5a3894477.png)

**Comment by hatgit** [comment]
my charts worked for months and now suddenly getting this error even though no changes to code: "....... Failed to fetch chart data: TypeError: chart.addAreaSeries is not a function
    at ......"

**Comment by vishnuc** [comment]
You have used cdn , use version 4 ..

**Comment by hatgit** [comment]
> You have used cdn , use version 4 ..

Thanks, I am changing to ""https://unpkg.com/lightweight-charts@4.0.0/dist/lightweight-charts.standalone.production.js" as we speak, I hope that should fix. Cheers!
