### ISSUE TITLE
Render the zero line in a darker color and wider width

### ISSUE THREAD

**Issue by jonluca** [tradingview/lightweight-charts#857]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

All x axis grid lines are the same color. It would be nice if we could have the zero line be a different color, and a different width, so it's clear when the values cross the 0 line.

**Additional context**

N/A

**Comment by timocov** [comment]
What's about something like this https://jsfiddle.net/cfn30ovL/ ?
