### ISSUE TITLE
Custom price line is hidden behind histogram

### ISSUE THREAD

**Issue by fatterpave** [tradingview/lightweight-charts#858]
**Lightweight Charts Version:** 3.3.0

**Steps/code to reproduce:**

Current code:

```js
            rsiSeries = chart.addHistogramSeries({
                priceScaleId: 'left',
                title: 'RSI',
                scaleMargins: {
                    top: 0.9,
                    bottom: 0,
                },
                priceFormat: {
                    type: 'volume',
                },
                priceLineVisible: false,
                overlay: true,
            });

            let maxPriceLine = {
                price: rsiEntryVal,
                lineColor: '#be1238',
                lineWidth: 1,
                lineStyle: LightweightCharts.LineStyle.Solid,
                axisLabelVisible: true,
                title: 'maximum price',
            }

            rsiSeries.setData(indicatorObj.Rsi);
            rsiSeries.createPriceLine(maxPriceLine);      
```

**Actual behavior:**

My hope was that my custom rsi line would be on top of the histogram, but it is mostly hidden behind the histogram

**Expected behavior:**

That the custom price line is on top/front of the histogram

**Screenshots:**

![image](https://user-images.githubusercontent.com/10440276/135725437-5d29be97-5a43-4141-8dd1-82f2e16f3eb0.png)

Is there any way of forcing the price line to be "on top" (like z-index)?

Great library, BTW :)
Best regards, Joakim

**Comment by timocov** [comment]
> Is there any way of forcing the price line to be "on top" (like z-index)?

Since the custom line is "attached" to the series to raise the line up you need to raise up the series. The zorder of series is based on their creating time, so if you want to have your candlestick atop of histogram, you need to create histogram series before candlestick one.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
