### ISSUE TITLE
Uncaught Error: value is null

### ISSUE THREAD

**Issue by cbusenbark** [tradingview/lightweight-charts#859]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

Render the attached 'broken.html' file to see no candle data displayed(https://htmledit.squarefree.com/)

**Actual behavior:**

No candles displayed and error displayed in console

**Expected behavior:**

Candles to be displayed

Note: can render the 'first_data_removed.html' to see issue fixed by just removing the first entry of the candle series data

**Screenshots:**

Attached

**CodeSandbo
<img width="1016" alt="value_is_null" src="https://user-images.githubusercontent.com/9123918/135739863-393d309e-2d45-442a-a856-d026a3a0b116.png">
x/JSFiddle/etc link:**

[html_files.zip](https://github.com/tradingview/lightweight-charts/files/7272707/html_files.zip)

**Comment by cbusenbark** [comment]
[html_files.zip](https://github.com/tradingview/lightweight-charts/files/7272712/html_files.zip)

**Comment by timocov** [comment]
You can use `development` build for debug purposes. For instance, if you switch from production build to development one by replacing `standalone.production` with `standalone.development` you'll see the following message in the console:

![image](https://user-images.githubusercontent.com/3112183/135837761-dca51a14-60a9-411c-93c6-1725fa41e52b.png)

which means that your data is not ordered or you might have duplicated data. If you look closer to your data you can see pairs of points with the same time, e.g. `{time:'2021-09-27',open:58.85,high:59.8,low:58.82,close:59.32},{time:'2021-09-27',open:58.85,high:59.8,low:58.82,close:59.3}`. Just remove all dupes and the chart will work as expected:

![image](https://user-images.githubusercontent.com/3112183/135837714-de06f0d7-e683-4e5c-aa0c-1f0f7fb00df5.png)
