### ISSUE TITLE
The value of zero on the price axis is displayed as negative

### ISSUE THREAD

**Issue by Vichkarichka** [tradingview/lightweight-charts#860]
I use the chart library the latest version to display charts with percentages on the price axis. I encountered such a problem that sometimes the value 0 is displayed as negative
<img width="426" alt="Снимок экрана 2021-10-04 в 10 19 56" src="https://user-images.githubusercontent.com/12201826/135809911-b5a954a3-f541-4530-916f-203848981d1d.png">
I use priceFormatter to change the display of values on the price axis, and the value of price in this function is not what I set in setData for some reason
<img width="446" alt="Снимок экрана 2021-10-04 в 10 20 01" src="https://user-images.githubusercontent.com/12201826/135810286-4d34ccfb-34c1-42c3-9613-e7bc6fe82107.png">
I would like the zero on the price axis to always be positive, can you explain why this happens and how to fix it

**Comment by timocov** [comment]
@Vichkarichka can you provide jsfiddle example of you issue please?

**Comment by Vichkarichka** [comment]
@timocov https://codesandbox.io/s/fast-sun-vc1n5?file=/src/App.js:544-554

**Comment by timocov** [comment]
So that's because your custom formatter, you need to fix it to handle this case.

**Comment by Vichkarichka** [comment]
<img width="1166" alt="Снимок экрана 2021-10-04 в 13 59 18" src="https://user-images.githubusercontent.com/12201826/135840641-775ddbd4-6e72-4ae4-a8d5-b2a6ba6081d7.png">
<img width="1188" alt="Снимок экрана 2021-10-04 в 13 59 01" src="https://user-images.githubusercontent.com/12201826/135840683-42902c24-e6af-472d-a526-bfc7d2deb7af.png">
@timocov Okay, I use rules like in yours documentation https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md what wrong? I want to formatted value in price axis

**Comment by timocov** [comment]
If you want to format your prices as percent you can use `percent` formatter rather than using custom one https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-format. But anyway, in the documentation we have just examples, you have to adapt them and make them work for your app. And also don't forget about https://0.30000000000000004.com/ 🙂
