### ISSUE TITLE
I want to show top toolbar in my lightweight chart

### ISSUE THREAD

**Issue by kkk210** [tradingview/lightweight-charts#862]
![Screen Shot 2021-10-07 at 6 38 03 PM](https://user-images.githubusercontent.com/48204519/136368910-dec733b5-d217-4898-af4d-1320a4eade91.png)

Hi everyone.
I hope you are doing well
I want some  help from tradingview lightweight chart expert.

I am using Infinite history chart and I don't have top toolbar.
I want same toolbar with the image I attached.
How can I get it?
Is there any option in createchart function?

I hope that I can get a good solution from you.

Best regards.
Thank you.

**Comment by edew** [comment]
Yes. All kinds of toolbars are out of scope for this library.
