### ISSUE TITLE
Log axis is not scaling on small number

### ISSUE THREAD

**Issue by thanhlmm** [tradingview/lightweight-charts#874]
**Lightweight Charts Version:** Latest

**Steps/code to reproduce:**
Use log axis in small number, About 0 - 0.0003

**Actual behavior:**

https://user-images.githubusercontent.com/9281080/137660059-4b51dd66-b564-4668-9555-7e8c02810fc8.mov

**Expected behavior:**

Highchart can scale on very small number like the video

**Screenshots:**

<img width="916" alt="Screen Shot 2021-10-18 at 9 27 30 AM" src="https://user-images.githubusercontent.com/9281080/137660181-bd7bab20-c7bc-4e81-891b-e72d1074ea68.png">

![image](https://user-images.githubusercontent.com/9281080/138048202-f44354bb-5a08-43be-901e-77476e254639.png)

Log chart on `lightweight-charts` vs `highchart`

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Probably the issue with [this constants](https://github.com/tradingview/lightweight-charts/blob/90b8724c335184a5e719a3514702fc0308bb7140/src/model/price-scale-conversions.ts#L6-L7), but needs to investigate.

**Comment by thanhlmm** [comment]
```
const enum Constants {
	LogicalOffset = 10,
	CoordOffset = 0.0000001,
}
```
<img width="925" alt="Screen Shot 2021-10-20 at 2 31 38 PM" src="https://user-images.githubusercontent.com/9281080/138047850-fb095e44-e3bd-4bf3-ad5d-6da6a8b96aad.png">
This is the result after I changed the Constants, which is work for me and does not affect other charts whose price is various.

@timocov is it worse to create MR which this config?
