### ISSUE TITLE
 Animation of the canvas and lines when adding data.

### ISSUE THREAD

**Issue by VladSturm** [tradingview/lightweight-charts#882]
Couldn't find a way to add animation to canvas and lines when updating data in real time. The display of new data is very intermittent.
Is it possible to set the animation speed along the x axis?
![constant](https://user-images.githubusercontent.com/37978572/140861470-07adb405-0ce4-4ef6-9f2d-8bb54651f703.gif)

**Comment by timocov** [comment]
> Is it possible to set the animation speed along the x axis?

No, it is not possible and to be honest I'm not sure that we're going to add it in the future.
