### ISSUE TITLE
Last price animation is active when no data added to the right (but to the left)

### ISSUE THREAD

**Issue by kirchet** [tradingview/lightweight-charts#886]
**Lightweight Charts Version:**  3.7.0

**Steps/code to reproduce:**

* Enable last price animation on data update
* Add more history bars via `setData`

**Actual behavior:**

Animation is active

**Expected behavior:**

No animation. Animation should start only if a series has data and we're adding new bars to the right side or updating the last bar

**Screenshots:**

![animation](https://user-images.githubusercontent.com/1572087/141298341-d4558205-2d00-42f9-b17c-e33535bb4042.gif)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/6hq2vopz/2/

**Comment by timocov** [comment]
Since we removed a knowledge of the first changed data index from series (we don't have merging algorithm any more in PlotList) it might be tricky. Probably we have to provide that information from DataLayer for every series (but actually only "currently updated" series will have it).
