### ISSUE TITLE
subscribeCrosshairMove callback is not called on mouseleave event

### ISSUE THREAD

**Issue by kirchet** [tradingview/lightweight-charts#887]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**

* add a subscription to crosshair move event
* disable chart scaling via mouse wheel
* scroll the page via mouse wheel

**Actual behavior:**

`subscribeCrosshairMove` callback is not called 

**Expected behavior:**

`subscribeCrosshairMove` callback should be called or there should be another subscription something line `subscribeLeave`

**Screenshots:**

![mousemove](https://user-images.githubusercontent.com/1572087/141301304-0671e01f-993c-4963-b98f-0b51c6f6bd57.gif)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/ge50La7d/2/

**Comment by timocov** [comment]
It seems that the browser doesn't send us an event about that. Not sure if we can handle it somehow internally without hacks:

![scroll-bug](https://user-images.githubusercontent.com/3112183/142197742-0a0dd5c0-e42e-4134-9390-5f4b54ceb91a.gif)

**Comment by timocov** [comment]
On the gif above I made a mistake and subscribed on `window` events, but we need to subscribe on container:

![scroll](https://user-images.githubusercontent.com/3112183/142200724-82abe9c9-e10c-43d3-8b6a-1bc1f48db6d0.gif)

So it seems that if a window is not active then we don't receive an event (the first part of gif above), but if a window is active we do receive that events (second part after clicking in the window). I'm unable to produce the issue with this information in FF either so most likely this is a bug of Chrome.

**Comment by timocov** [comment]
Just created an issue in Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1271119
