### ISSUE TITLE
DOcumentations

### ISSUE THREAD

**Issue by dayojohn19** [tradingview/lightweight-charts#895]
can someone tell us why the docs are remove??

**Comment by romfrancois** [comment]
Hey @dayojohn19,

Doc has not been removed believe me!
We've just made it better for the community and it's accessible [here](https://tradingview.github.io/lightweight-charts/).

Maybe the link hasn't been updated. We'll check that.

**Comment by timocov** [comment]
@dayojohn19 please use the latest tag to get documentation https://github.com/tradingview/lightweight-charts/tree/v3.7.0/docs. We're in preparing state now to deploy our docs as a website, so as soon it is ready we'll update links.
