### ISSUE TITLE
Scrollbar for horizontal scroll

### ISSUE THREAD

**Issue by Spader3** [tradingview/lightweight-charts#896]
I wonder if there any plans to add scrollbar for horizontal scrolling
(or maybe someone have already implemented it, will be very thankful if some code provided)

**Comment by timocov** [comment]
@Spader3 Like what?

**Comment by Spader3** [comment]
Do you mean you need example? If so, then i attach screenshot
There is a scrollbar at the bootom of the chart, that is what i need
![fin-chart-example](https://user-images.githubusercontent.com/58947235/141987078-e7ee59e8-6433-4945-9147-304372754981.png)

**Comment by timocov** [comment]
> Do you mean you need example? 

Yep, just to be on the same page.

I don't think that we're going to implement anything like that in the future. But you never know...
