### ISSUE TITLE
optimize candles

### ISSUE THREAD

**Issue by JackSonJson** [tradingview/lightweight-charts#897]
is there any option or idea for remove wrong candles? 
![Untitled](https://user-images.githubusercontent.com/94376760/141795812-4c836896-c718-404a-8225-06d405e5dc80.png)

sometime some of candles are wrong in close or open values, so how can detect them to avoid such scenes

**Comment by timocov** [comment]
```js
function isGoodCandle(candle) {
    // write your code here
}

// somewhere in the code

series.setData(data.filter(isGoodCandle));
```

Please use this snippet, I don't know why you decided you open this issue because it looks like related to your code and data. Have you check this so far?
