### ISSUE TITLE
When rendering multiple charts with baseline series, baseValue of the last element is used on all charts series.

### ISSUE THREAD

**Issue by deaglegame** [tradingview/lightweight-charts#898]
**Lightweight Charts 3.7.0**
**React 16.14.0** used in my project, **React 17.0.2** in codesandbox with same results
**Codesandbox example :** https://codesandbox.io/s/pensive-blackwell-cuz1j?file=/src/Baseline.jsx

Hello,

While trying to render multiple charts, each with a baseline series, setting the baseValue on each chart independently doesn't seem to work as expected, instead it applies the value of the last series to each element. 

In my example, the grey price line is to indicate where the baseValue price should be set for each chart series.

![image](https://user-images.githubusercontent.com/63978721/142021059-7d905973-158a-44e2-9959-8704d8ba90ce.png)

I have tried everything I could think of as far as React goes. To name a few, setting baseValue in either addBaselineSeries or applyOptions doesn't affect anything. Thinking it might be because each series is not unique, I tried keeping a list of refs of all my series in state, outside of my loop, and once the charts rendered, iterating through the list calling applyOptions on each series to set baseValue, without success.

If I play around with the data and put the first item at the end of my array, you notice that now it works for that particular chart, but only because it's now last. And the second to last (previously last) shows all red because its values are lower than the new baseValue price.

![image](https://user-images.githubusercontent.com/63978721/142023397-b5d5909b-720c-460c-b3f7-6ee1874dbb42.png)

I'm scratching my head over this because all other series options seem to work fine. I have read the docs without finding anything about this. I'm still thinking it could be user error, my apologies if so. That is the reason I did not file this under bugs, just in case.

Thank you for this great library!

**Comment by serpiko-git** [comment]
@deaglegame 

It was very helpful in implementing the baseline chart. TradingView and Lightweight charts are inconvenient and difficult to understand due to the lack of appropriate samples. deaglegame's example was very helpful. Thank you so much..

https://codesandbox.io/p/sandbox/lightweight-charts-addbaselineseries-test-r65r8k?file=%2Fsrc%2FApp.tsx%3A37%2C33  😀
