### ISSUE TITLE
Draw Cup Pattern

### ISSUE THREAD

**Issue by danielbavaryan** [tradingview/lightweight-charts#906]
drawing cup pattern and [curved line series](https://github.com/tradingview/lightweight-charts/issues/506) in this chart lib would be great. we have scenario that have multiple charts on page(Viewable all the same time) and we cant use Main Trading View chart.
is there any way we can draw curve lines and cup pattern?

[cup pattern ](https://www.lightweight.com/ideas/cupandhandle/)
![Capture4](https://user-images.githubusercontent.com/93032870/142722009-22d7c1ea-0821-4e47-b873-96a8374eed01.PNG)

**Comment by timocov** [comment]
I'm afraid we're not going to implement any kind of drawings in this library (at least for now). Probably after #506 it would be possible to draw a line like on your screenshot though.
