### ISSUE TITLE
removePriceLine not working

### ISSUE THREAD

**Issue by iwolford** [tradingview/lightweight-charts#911]
**Lightweight Charts Version:** Latest Prod

**Steps/code to reproduce:**

go to the tutorial fiddle:
https://jsfiddle.net/TradingView/fz4v5ouq/

At line 458 (right after "createPriceLine" statements) add:
`  series.removePriceLine(avgPriceLine);`

Then "Run" the fiddle.

**Actual behavior:**

The middle price line is not removed.
In console you get an error 
```
Uncaught TypeError: t.od is not a function
at t.removePriceLine (lightweight-charts.standalone.production.js:7)
```

**Expected behavior:**

The middle price line should be removed.

**Comment by timocov** [comment]
`series.removePriceLine(avgPriceLine);` this method expects to have a result of `createPriceLine` method as an argument, not options of a price line. So if you replace `series.createPriceLine(avgPriceLine)` with `const lineApi = series.createPriceLine(avgPriceLine)` and then call `series.removePriceLine(lineApi);` if would work as expected.
