### ISSUE TITLE
Smooth curves through time series points

### ISSUE THREAD

**Issue by club9822** [tradingview/lightweight-charts#914]
**Is your feature request related to a problem? Please describe.**

Would be nice to have option to draw smooth curves through points, with `cardinal-spline-js` or any lib for draw curve
the `LineType`  with `Curved` option would be nice.

**Describe the solution you'd like**

adding Curve in LineType for draw curved line
```
export const enum LineType {
	/**
	 * A line.
	 */
	Simple,
	/**
	 * A stepped line.
	 */
	WithSteps,
	/**
	 * A Smooth curved line between points.
	 */
	Curved,
}
```

**Additional context**

**Comment by timocov** [comment]
Duplicate of #506

**Comment by timocov** [comment]
@club9822 would you mind to search similar issues before creating a new one please?

**Comment by timocov** [comment]
That issue could be found by literally "curved" word in search https://github.com/tradingview/lightweight-charts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+curved, you don't need to even try different words.

**Comment by club9822** [comment]
thank u for your works and responses, sorry my mistake.
please close this and see [Curve line](https://github.com/tradingview/lightweight-charts/pull/915) if can be merged.
