### ISSUE TITLE
New user 

### ISSUE THREAD

**Issue by mariamlouis** [tradingview/lightweight-charts#920]
I am a new user for trading view , I am .net Developer

if you please help me how to use the source code and make an updates meet requirements

Thanks

**Comment by timocov** [comment]
Kindly reminder that if you'll spam across different issues/discussions with unrelated messages and asking for help, we could treat it as a spam. Please respect others in this repo and have patience.

This project is not for .Net technology itself, this is for a web and could be work only there. If you want to get to know how to make js and .net work together, please use stackoverflow.com/ or any other resource. Let's keep this repo for the library itself.
