### ISSUE TITLE
Overlay series title is not rendered when no series use right price scale

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#926]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**

```ts
import { createChart, LineData, UTCTimestamp } from "lightweight-charts";

const chartRoot = document.getElementById("main-chart") as HTMLDivElement;
const chart = createChart(chartRoot, {
  width: 800,
  height: 600,
});

const line1 = chart.addLineSeries({
  priceScaleId: "overlay",
  color: "rgb(255, 0, 0)",
  title: "SIN",
});
const line2 = chart.addLineSeries({
  priceScaleId: "overlay",
  color: "rgb(0, 255, 0)",
  title: "COS",
});

const data1: LineData[] = [];
const data2: LineData[] = [];

const now = new Date();
function dateToUTC(date: Date): UTCTimestamp {
  return Math.floor(date.getTime() / 1000) as UTCTimestamp;
}

for (let i = 0; i < 90; i++) {
  data1.push({
    time: dateToUTC(now),
    value: Math.sin(i * 4 * Math.PI / 180),
  });

  data2.push({
    time: dateToUTC(now),
    value: Math.cos(i * 4 * Math.PI / 180),
  });

  now.setDate(now.getDate() + 1);
}

line1.setData(data1);
line2.setData(data2);
```

**Actual behavior:**

Series title is not rendered

**Expected behavior:**

Series title should rendered

When another series is added that use right priceScale, even though it's not used, will fixed issue above. However if it used only left priceScale, it won't render title properly again
```ts
const line3 = chart.addLineSeries();
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/1574722/144573589-9b0710cb-47bc-4381-8e01-bf56e3e3ba62.png)

with line3 added
![image](https://user-images.githubusercontent.com/1574722/144573980-adca4be7-6d48-461d-871c-d9cf0c3089c4.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
@SuperPenguin what's the reason to use empty price scale? just to display values from overlay sources?
