### ISSUE TITLE
Hotfix for 'hoveredMarkerId' is undefined

### ISSUE THREAD

**Issue by CreativeSau** [tradingview/lightweight-charts#931]
**Lightweight Charts Version: v3.7.0*

I've been wanting to target markers on hover, but `hoveredMarkerId` always returns `undefined` .
Example use:
```js
const  myCrosshairMoveHandler = (param) => {
	console.log(param.hoveredMarkerId) //undefined
}
chart.subscribeCrosshairMove(myCrosshairMoveHandler)
```
I don't know Typescript and therefor won't create a pull request, but I've managed to hotfix the source code so it returns the marker's index in the series.

In the compiled version changing the following lines of code does the trick.
@line:10326, from:
```js
var  hoveredObject = hoveredSource !== null && hoveredSource._internal_object !== undefined
? hoveredSource._internal_object._internal_externalId
: undefined;
```
To:
```js
var  hoveredObject = hoveredSource !== null && hoveredSource._internal_object !== undefined
? hoveredSource._internal_object._internal_hitTestData
: undefined;
```
Result: `console.log(param.hoveredMarkerId) //123`

So I took a quick dive into the TS files and changed the following lines:

File: `chart-widget.ts`
@line32 – from: `hoveredObject?: string;` -> to: `hoveredObject?: any;`
@line611 – from `hoveredSource.object.externalId` -> to `hoveredSource.object.hitTestData`

I'm not sure what `_internal_externalId` is supposed to return initially, and I haven't thoroughly tested it, but it works for me.

**Comment by Ffloriel** [comment]
`param.hoveredMarkerId` will return undefined if you didn't defined the id when you set the markers.
Are you defining the markers with an id like below?
```js
setMarkers([
    { id: 'id1', time: '2017-04-10', position: 'inBar', color: 'orange', shape: 'circle' }
]);
// hoveredMarkerId will be 'id1'
```
Here is an example you can try to see the id being returned:
```js
const chart = LightweightCharts.createChart(container, {});
const line = chart.addLineSeries();
line.setData([
    { time: '2017-04-11', value: 80.01 },
    { time: '2017-04-12', value: 96.63 },
    { time: '2017-04-13', value: 76.64 },
    { time: '2017-04-14', value: 81.89 },
    { time: '2017-04-15', value: 74.43 },
    { time: '2017-04-19', value: 81.89 },
    { time: '2017-04-20', value: 81.89 },
    { time: '2017-04-21', value: 81.89 },
    { time: '2017-04-22', value: 81.89 },
    { time: '2017-04-23', value: 81.89 },
]);

line.setMarkers([
    { time: '2017-04-10', position: 'inBar', color: 'orange', shape: 'circle', id: 'id1' },
    { time: '2017-04-16', position: 'inBar', color: 'orange', shape: 'circle', id: 'id2' },
    { time: '2017-04-17', position: 'inBar', color: 'orange', shape: 'circle', id: 'id3' },
    { time: '2017-04-18', position: 'inBar', color: 'orange', shape: 'circle', id: 'id4' },
    { time: '2017-04-24', position: 'inBar', color: 'orange', shape: 'circle', id: 'id5' },
]);

chart.subscribeCrosshairMove(param => {
    console.log(param.hoveredMarkerId);
})
```

**Comment by timocov** [comment]
@CreativeSau ^^

**Comment by CreativeSau** [comment]
@Ffloriel No I didn't. That totally makes sense. Thanks for clarifying!
Maybe adding an 'id' key in the example in the docs could point others into the right direction in the future.
