### ISSUE TITLE
Zooming out from minutes to months

### ISSUE THREAD

**Issue by AnAlgoTrader** [tradingview/lightweight-charts#935]
Hi, I am plotting intra-day data (1 minute) of two symbols. 
I am using LineSeries for it. They align pretty well together as per screenshot below:

![image](https://user-images.githubusercontent.com/68376620/145663008-6d9d00ce-170e-42ac-a4e9-99714d41dd81.png)

Source code of the main definition:

```
<body style="padding: 0; margin: 0;">
    <div id="container" style="position: absolute; width: 100%; height: 100%;"></div>
    <script type="text/javascript">
        var chart = LightweightCharts.createChart(document.getElementById('container'),
            {
                layout: {
                    backgroundColor: '#000000',
                    textColor: 'rgba(255, 255, 255, 0.9)',
                },
                grid: {
                    vertLines: {
                        visible: false,
                    },
                    horzLines: {
                        color: 'rgba(42, 46, 57, 0.5)',
                    },
                },
                crosshair: {
                    mode: LightweightCharts.CrosshairMode.Normal,
                }
            });

        const symbol1 = 'DEU.IDXEUR';
        const lineSeries1 = chart.addLineSeries({
            color: "rgba(255, 211, 75, 1)",
            lineWidth: 1,
        });

        const symbol2 = 'PLN.IDXPLN';
        const lineSeries2 = chart.addLineSeries({
            color: "rgba(138, 171, 238, 1)",
            lineWidth: 1,
        });

        fetch(`./${symbol1}_lineSeries.json`)
            .then(response => response.text())
            .then(data => {
                var chartData = JSON.parse(data);
                lineSeries1.setData(chartData);
            });
        fetch(`./${symbol2}_lineSeries.json`)
            .then(response => response.text())
            .then(data => {
                var chartData = JSON.parse(data);
                lineSeries2.setData(chartData);
            });
        document.title = `Y:${symbol1} - B:${symbol2}`;

        chart.applyOptions({
            timeScale: {
                borderVisible: false,
                borderColor: '#fff000',
                visible: true,
                timeVisible: true,
            }
        });
    </script>
</body>

```
The input data, as requested,  is in the format:

```
[
    {
        "time": 1627776000.0,
        "value": 15566.611
    },
    {
        "time": 1627776060.0,
        "value": 15566.611
    },
    {
        "time": 1627776120.0,
        "value": 15566.611
    },
    {
        "time": 1627776180.0,
        "value": 15566.611
    }
]

```

**I don't seem to be able to zoom out to see the chart by days, weeks or months. The scrolling ends at the hour level.
Am I missing any settings that would allow me to do that?**

Amazing library, by the way. Thanks for your hard work.

**Comment by edew** [comment]
Hi @AnAlgoTrader.

I've not been able to reproduce the behaviour you describe. Are you able to create a CodeSandbox/JSFiddle/or similar that shows the issue?

**Comment by timocov** [comment]
> I don't seem to be able to zoom out to see the chart by days, weeks or months

@AnAlgoTrader What do you mean here? Can you record a video of the problem please?

**Comment by majh** [comment]
@AnAlgoTrader  I had a similar issue and found by setting the "timeScale.minBarSpacing : 0.0 option allowed zoom out.
ie

```
       chart.applyOptions({
            timeScale: {
                borderVisible: false,
                borderColor: '#fff000',
                visible: true,
                timeVisible: true,
                minBarSpacing: 0.0,
            }   
        }); 
```

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to ping me.

**Comment by AnAlgoTrader** [comment]
> @AnAlgoTrader I had a similar issue and found by setting the "timeScale.minBarSpacing : 0.0 option allowed further zoom out. ie
> 
> ```
>        chart.applyOptions({
>             timeScale: {
>                 borderVisible: false,
>                 borderColor: '#fff000',
>                 visible: true,
>                 timeVisible: true,
>                 minBarSpacing: 0.0,
>             }   
>         }); 
> ```

Thank you, I am glad that you came to the rescue. This is the actual solution.
