### ISSUE TITLE
Change a location of `Time` type from model to api

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#938]
In https://github.com/tradingview/lightweight-charts/pull/934 we moved the type `Time` to model layer since we need to use this type in 2 places in time scale ([one](https://github.com/tradingview/lightweight-charts/blob/f6e24e6637298194f22c63a768232d3243b6aeac/src/model/time-scale.ts#L729), [two](https://github.com/tradingview/lightweight-charts/blob/f6e24e6637298194f22c63a768232d3243b6aeac/src/model/time-scale.ts#L883)), i.e. on a model layer.

It looks like this type shouldn't be at model layer and should be declared at api layer, since a model layer doesn't use this type all and it doesn't even know that it is internally (for example, `string` from that type parsed in DataLayer and never used anywhere else).

But it seems that there is no straightforward solution for that without breaking the API or without making it hard to read/understand.

**Comment by SlicedSilver** [comment]
Closing this issue in favour of an internal investigation and refactor of the time scale.
