### ISSUE TITLE
There are no tick marks on the price axis

### ISSUE THREAD

**Issue by kirchet** [tradingview/lightweight-charts#939]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**

- Create series
- Set data items
- Set empty data items
- Apply series options with custom price formatter
- Set the same data items

```js
var chart = LightweightCharts.createChart(document.body, { width: 500, height: 300 });
var series = chart.addLineSeries();

series.setData([
  { time: '1990-04-24', value: 0 },
  { time: '1990-04-25', value: 1 },
  { time: '1990-04-26', value: 2 },
  { time: '1990-04-28' },
]);

setTimeout(
  () => {
    series.setData([]);

    setTimeout(    
      () => {
        series.applyOptions({
          priceFormat: {
            type: 'custom',
            formatter: priceValue => priceValue.toFixed(2),
            minMove: 0.01,
          },
        });
        
        setTimeout(
          () => {
            series.setData([
              { time: '1990-04-24', value: 0 },
              { time: '1990-04-25', value: 1 },
              { time: '1990-04-26', value: 2 },
              { time: '1990-04-28' },
            ]);	
          },
          500
        );
      },
      500
    );
  },
  500
);
```

**Actual behavior:**

There are no tick marks on the price axis

**Expected behavior:**

The axis should paint tick  marks

**Screenshots:**

![image](https://user-images.githubusercontent.com/1572087/146246187-b38dee09-1b14-46ec-b096-cad73bfd5528.png)

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/8m1nkjws/3/

**Comment by timocov** [comment]
@kirchet would you like to fix this issue? 😉 😁

**Comment by kirchet** [comment]
@timocov, yes, I'm going to do it today or tomorrow
