### ISSUE TITLE
A painting slows down after a while with tons of updates

### ISSUE THREAD

**Issue by Tucsky** [tradingview/lightweight-charts#946]
**Lightweight Charts Version:** 3.7.0 & 3.8.0

**Steps/code to reproduce:**

- Standard setup with candlestick and volume (don't matter)
- **And very very fast realtime update** 

**Actual behavior:**

CPU gradually increase (maybe more than it should?)
..then after like 20min **CPU shoots up to 100% for no apparent reason**

The whole update task takes about 250ms, 90% of it being dedicated to painting the time-axis-widget
![image](https://user-images.githubusercontent.com/5738336/146654151-0f794b77-f775-4149-a852-ed7297d3cd04.png)

This is what the same update looks like at the very beginning (takes about 15ms)
![image](https://user-images.githubusercontent.com/5738336/146654179-2f111c95-d02c-45e2-bb0d-7c4d075078e0.png)

Once cpu goes 100% it doesn't come back. However I have found that changing layout font size fixes it
![image](https://user-images.githubusercontent.com/5738336/146654605-9231091a-9ee9-434f-a4e5-e389fbde53dd.png)
It's only temporarily tho, the CPU start to increase again and eventually melt up

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/qktjy154/5/ - takes about 20min on my build (i7-9700 3.2ghz, 16gb ram), tab needs to remain active

Will update

**Comment by Tucsky** [comment]
Jsfiddle not good for perf monitoring so I uploaded this http://51.255.41.169/lcissue/test.html
same code as the jsfiddle + measure the execution time of TimeAxisWidget.prototype._internal_paint

![image](https://user-images.githubusercontent.com/5738336/146655421-f44a9b8e-eac0-4124-9748-bec84045d705.png)
![image](https://user-images.githubusercontent.com/5738336/146655582-9d8fd14c-2854-44b5-9243-9c73912a3af4.png)

**Comment by timocov** [comment]
Hi @Tucsky, thanks for your report! Have you tried to reproduce the same issue in different browsers? Also, is it a type that you stated that there is a possible memory leak but measure CPU usage instead? Quickly looking at your data I can see that for some reason a browser slows down the rendering of the text ([you can see](https://github.com/tradingview/lightweight-charts/blob/ea265534166af048366d0ec3fa52ed2714ffc18b/src/gui/time-axis-widget.ts#L345-L361) that in this code all the library does is call `ctx.fillText()`).

I just kept the page for several minutes and didn't see any heavy memory usage though, every time I click on "Collect garbage" button it goes down for the same value (around 5-6mb in my case).

**Comment by timocov** [comment]
@Tucsky are you able to reproduce it in different browsers/PCs?

**Comment by Tucsky** [comment]
Yes you are right, memory is not the issue it's the CPU, I was looking for an equivalent term but didn't find any 🙂 it's about the Time Axis canvas operations (fillrect, filltext etc) taking 100x longer than it should after some time. The time before it 'triggers' is relative to the amount of updates made per sec, and most likely the power of your own cpu. I have the full runtime performance snapshot of it if needed (about 20s before the heavy load starts to manifest and a few sec in). will try on other browsers asap

**Comment by Tucsky** [comment]
@timocov I can absolutely reproduce the issue on my 15" 2015 macbook pro
![image](https://user-images.githubusercontent.com/5738336/147962760-23dbc73d-cddb-428a-ba26-c0efa77ae15c.png)
takes about the same time to trigger

**Comment by Tucsky** [comment]
![Screenshot_20220103-190837](https://user-images.githubusercontent.com/5738336/147964472-c265df67-5b34-4587-80ae-e4395382ad4b.jpg)
 Oneplus 5

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/147977485-09c70c0a-9acb-4efa-828a-3e47b7cd8c99.png)

No issue on firefox 🥇

**Comment by timocov** [comment]
> No issue on firefox 🥇

What version of _Chrome_ do you use on your laptop and phone? It looks like the issue of the browser for now.

**Comment by Tucsky** [comment]
@timocov I'm using 96.0.4664.110 (last version)  on both

**Comment by timocov** [comment]
@Tucsky could report this to Chromium please? I just tried to reproduce it on `Version 88.0.4298.0 (Developer Build) (64-bit)` and it works fine (at least for 16 minutes). I'm able to reproduce it with the latest Chrome version so most likely it's Chromium's issue. Afaik they made some changes related to this recently so probably it's related.

Also, as soon as you're unable to reproduce it in FF it only confirms that it's issue in Chrome. You can also check in Safari, but I believe you won't be able to reproduce it.

**Comment by timocov** [comment]
Hey @Tucsky, did you file an issue in Chromium by any chance for this issue?

**Comment by Tucsky** [comment]
No I did not, I am unable to reproduce the issue outside of this library
It works just fine when I change the layout fontSize every couple minutes so I'm just doing that now

**Comment by timocov** [comment]
Got it, thanks! We'll report to Chromium this issue then. It seems that it might be caused by some other scenarios and your repro is simple enough. I'll post a link here once it will be created.

**Comment by timocov** [comment]
It seems that @kirchet found the cause of the issue. We'll provide a fix soon.
