### ISSUE TITLE
Labels might be cut off when disabling scale and scroll

### ISSUE THREAD

**Issue by maxbethke** [tradingview/lightweight-charts#947]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:** refer to this codesandbox https://codesandbox.io/s/unruffled-benz-z9f5p

**Actual behavior:** The last label on the time axis will be hidden behind a non-transparent canvas, if it happens to overflow the canvas for the time scale

**Expected behavior:** The time scale labels would be overflowing their canvas, so they would display their whole content

**Screenshots:**
![](https://user-images.githubusercontent.com/1520124/145370347-ded4ad02-3f11-41a0-9aec-6f38f51ff302.png)

**CodeSandbox/JSFiddle/etc link:** https://codesandbox.io/s/unruffled-benz-z9f5p

With reference to 
#226 and #835

**Comment by maxbethke** [comment]
This can happen on the left end of the time scale too btw 
![grafik](https://user-images.githubusercontent.com/1520124/146784248-57e36e8e-4cc5-46b7-b6b7-8f1f522842bd.png)

**Comment by timocov** [comment]
The fix should be somewhere [here](https://github.com/tradingview/lightweight-charts/blob/ea265534166af048366d0ec3fa52ed2714ffc18b/src/model/time-scale.ts#L505-L512) - we need to respect disabling scrolling/scaling as well, not just fixing an edge.

**Comment by rchvalbo** [comment]
Would a fix for this solve the issue with series markers being cutoff? This issue has been haunting us for quite some time. No work around for it at the moment. We just need the ability to shift these markers in. Maybe an ability to add left/right padding for any marker plotting? Let me know if there's something I can do to help. We really need this.
![image](https://user-images.githubusercontent.com/28923633/147715087-201c9bb7-7eb8-4b8f-8fe0-6856ba34831e.png)

**Comment by timocov** [comment]
@rchvalbo no, I don't think so. Please create another ticket for that.

**Comment by maxbethke** [comment]
> @maxbethke would you like to create a fix for this?

Sorry, gotcha too late. Would have loved to help.

**Comment by timocov** [comment]
@maxbethke no worries, we handled it.
