### ISSUE TITLE
How to create a box like pine script

### ISSUE THREAD

**Issue by youhu868** [tradingview/lightweight-charts#948]
hello,which api can create a box? like pine script "box.new(left, top, right, bottom, border_color, border_width, border_style, extend, xloc, bgcolor) → series box"

![图片](https://user-images.githubusercontent.com/18002879/146742977-31f5dbe7-3f3d-408f-b2d6-ec541ea7086b.png)

**Comment by timocov** [comment]
It is impossible to create such boxes in lightweight-charts and I don't think that we're going to implement anything like that in near future.

**Comment by youhu868** [comment]
OK, Thanks~
