### ISSUE TITLE
Price axis width

### ISSUE THREAD

**Issue by amiralitaheri** [tradingview/lightweight-charts#950]
**Lightweight Charts Version:** 3.6.0

**Steps/code to reproduce:**
Setting custom price format will cause miscalculation in price axis width. And I think it is related to this issue https://github.com/tradingview/lightweight-charts/issues/834

**Screenshots:**

![image](https://user-images.githubusercontent.com/45509862/146906926-c419d53b-ebbd-4f99-8b2c-192496ec34ce.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/stf9h451/2/

**Comment by timocov** [comment]
![image](https://user-images.githubusercontent.com/3112183/147666043-7fad3133-765b-422b-8ae9-d13af55de05a.png)

This is the answer. Custom formatter should respect series' parameters and limit number of decimals.

**Comment by zirlman** [comment]
@timocov Thank you for figuring this out 🙇‍♂️🙇‍♂️🙇‍♂️
