### ISSUE TITLE
Marker disappear after zoom in

### ISSUE THREAD

**Issue by filipemarques87** [tradingview/lightweight-charts#956]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**
I am using the example from https://www.tradingview.com/lightweight-charts/

**Actual behaviour:**
When I have a chart with markers and I zoom in until I get only one marker visible, that marker disappears

**Expected behaviour:**
The marker should not disappear

**Screenshots:**

![recording (1)](https://user-images.githubusercontent.com/32367633/147657824-e7c37f7d-7079-48aa-bf59-19ed4ffdb7cb.gif)

And thanks for this library, it is really great 👍

**Comment by timocov** [comment]
Interesting...

**Comment by timocov** [comment]
This is bug in the example - the order of data is opposite of what the library expects. We'll fix it.
