### ISSUE TITLE
timeScale.fitContent is not working correctly

### ISSUE THREAD

**Issue by iksent** [tradingview/lightweight-charts#966]
**Lightweight Charts Version:** 3.7.0 (but 3.5.0 is working OK)

**Code to reproduce:** https://jsfiddle.net/iksent/8akv3x59/

**Actual behavior:** executing `.timeScale().fitContent()` (after changing series data) sometimes not fitting the chart fully.

**Screen recording:**
https://user-images.githubusercontent.com/32956521/148347730-4f0dbccd-5e5a-4104-8db8-30fc4b64f5f3.mov

**Expected behavior:** `fitContent` must fit the content correctly.

**Comment by iksent** [comment]
Very annoying problem 😫 This is what it looks like on our project: 

https://user-images.githubusercontent.com/32956521/148349175-24e43beb-5bcc-4524-a682-5f488d98bed0.mov

Chart is not fitted **every time** on series-data change.

**Comment by timocov** [comment]
It seems that it is related and quite similar to #943. Is it possible to check #959 locally with your case?

**Comment by timocov** [comment]
It seems it doesn't help. We'll investigate the issue.
