### ISSUE TITLE
Remove horizontal dashed lines of prices from chart

### ISSUE THREAD

**Issue by saragholizadeh** [tradingview/lightweight-charts#968]
Hi , I can't find something in docs for remove horizontal line of prices , and price marks in prices axis.

is there a way for delete these dashed lines and prices from chart? 

![Chart](https://user-images.githubusercontent.com/78765024/148724472-4eda27ea-2ca9-4118-b3dd-8615027e6b73.png)

**Comment by timocov** [comment]
See https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#pricelinevisible
