### ISSUE TITLE
How to access the docs

### ISSUE THREAD

**Issue by maxbethke** [tradingview/lightweight-charts#980]
(This ticket is less meant as an actionpoint for the developers, but more as help for the users of this library)

Currently the project seems to be transsitioning from having the docs directly in the repo (/docs) with the root readme.md as entrypoint, to providing the docs as a github pages site.

**Problem**: Right now, the old docs are already removed but the new docs (https://tradingview.github.io/lightweight-charts/) are not fully populated yet. For me as a user of this library, it is very hard to use this without a full set of docs:

**temporary workaround solution**: When I usually do is that I saved link to the 3.6 release and just browse the 'old docs' from there: https://github.com/tradingview/lightweight-charts/tree/release/3.6/docs. They might not be up to date, but helped me tremendously

Is there another way the docs are availble right now? Did I miss something?

**Comment by edew** [comment]
Hi @maxbethke.

Is there something specific you think is missing from the new docs, or were you only looking for the docs for a specific version and couldn't find a link?

**Comment by timocov** [comment]
We just released the new version of lightweight-charts and now docs are available at https://tradingview.github.io/lightweight-charts/.
